google/nomulus

- README.md
This allows us to click on the build badge to visit kokoro and find out build status. The link is only accessible for Googlers.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/101)
> Add a link to kokoro

- java_common.gradle
This option causes Intellij build to fail if the
'Delegate IDE build/run actions to gradle' box is checked.
We do not know of anyway to change the Intellij behavior.
This change allows an IDE user to prevent -Werror to be passed
to javac by adding a Gradle VM option: -Dno_werror=true
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/115)
> Allow switching off the -Werror javac option

- package-lock.json
- package.json
I'm seeing odd errors in versions of Karma more recent than 3.0.0. While
I investiage, I'd like to see what Github has to say about these
dependencies (we got some vulnerability messages for earlier versions)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/119)
> Bump karma-related dependencies

- core/src/main/java/google/registry/tools/AuthModule.java
This provider is not used. Instead, depending on if the login is performed on
[a remote machine or not](https://github.com/google/nomulus/blob/8bdc77501fcbb4053bf7742ac112b3a0551b44e0/core/src/main/java/google/registry/tools/LoginCommand.java#L43),
the instance is created directly in the command.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/113)
> Remove unnecessary provider method

- core/src/test/java/google/registry/export/ExportPremiumTermsActionTest.java
- core/src/test/java/google/registry/testing/FakeHttpSession.java
- core/src/test/java/google/registry/webdriver/RegistrarConsoleWebTest.java
- core/src/test/java/google/registry/webdriver/WebDriverPlusScreenDifferRule.java
- proxy/src/test/java/google/registry/proxy/CertificateModuleTest.java
- proxy/src/test/java/google/registry/proxy/handler/SslInitializerTestUtils.java
Fix or suppress deprecation warnings except those about GoogleCredential,
which is being handled separately.
The @SuppressWarnings("deprecation") annotation does not cover imports
even when it is at the class level. We removed imports of deprecated
classes and use their fully qualified names in class body.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/121)
> Fix or suppress some deprecation warnings

- core/src/test/java/google/registry/model/EntityTestCase.java
- core/src/test/java/google/registry/model/ResourceCommandTestCase.java
- core/src/test/java/google/registry/model/host/HostCommandTest.java
- core/src/test/java/google/registry/model/registrar/RegistrarTest.java
- core/src/test/java/google/registry/rdap/RdapActionBaseTestCase.java
- core/src/test/java/google/registry/rdap/RdapHelpActionTest.java
- core/src/test/java/google/registry/rdap/RdapSearchActionTestCase.java
- core/src/test/java/google/registry/tmch/TmchActionTestCase.java
- core/src/test/java/google/registry/ui/server/registrar/RegistrarSettingsActionTestCase.java
IntelliJ is complaining when this annotation is used on a base class that has no
actual runnable tests itself.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/107)
> Don't use @RunWith JUnit annotations on classes with no @tests

- .travis.yml
- appengine_war.gradle
- build.gradle
- core/build.gradle
- gradle/wrapper/gradle-wrapper.properties
- package-lock.json
- proxy/build.gradle
Our CI (Travis & Kokoro) runs "gradle build", so we need to make
sure that all tasks used in the release process are called during
the build so that breakage can be caught earlier.
In order to stage the GAE folder we need gcloud to be present.
Therefore the Travis config is changed to install gcloud.
See: https://gist.github.com/mjackson/5887963e7d8b8fb0615416c510ae8857
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/108)
> Add tasks used in release as dependencies of the build task

- proxy/terraform/modules/gcs.tf
- proxy/terraform/modules/iam.tf
Per
https://cloud.google.com/container-registry/docs/access-control#granting_users_and_other_projects_access_to_a_registry,
for a service account to access GCR, it does not need reader access to *all*
buckets in a project, but just the specific one.
This is duped from cl/254092941.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/125)
> Update IAM binding to restrict proxy service account's access to GCS

- release/cloudbuild-beam.yaml
- release/cloudbuild-nomulus.yaml
- release/cloudbuild-release.yaml
Some of the texts are not really secerts because they are per-project.
Also changed the location of the credential file to `secerts` so that in
the future we may add more secerts in that folder.
The encrypted file is base64 encoded, consistent with how the proxy
certificates are encoded. Also made some changes to the other pipelines
to facilitate automation with Spinnaker
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/134)
> Update GCB beam deployment pipeline

- core/build.gradle
The API is deprecated and removed in Java 12. Do not build these
classes when using Java 12, till we migrate to the new API.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/135)
> Disable Javadoc and tests in Java 12

- core/src/main/java/google/registry/batch/DeleteLoadTestDataAction.java
- core/src/main/java/google/registry/batch/DeleteProberDataAction.java
- core/src/main/java/google/registry/config/RegistryConfig.java
- core/src/main/java/google/registry/dns/DnsMetrics.java
- core/src/main/java/google/registry/ui/server/registrar/ConsoleOteSetupAction.java
- core/src/main/java/google/registry/ui/server/registrar/ConsoleRegistrarCreatorAction.java
- core/src/main/java/google/registry/ui/server/registrar/ConsoleUiAction.java
- core/src/main/java/google/registry/ui/server/registrar/RegistrarSettingsAction.java
- core/src/test/java/google/registry/batch/DeleteProberDataActionTest.java
- core/src/test/java/google/registry/ui/server/registrar/ConsoleOteSetupActionTest.java
- core/src/test/java/google/registry/ui/server/registrar/ConsoleRegistrarCreatorActionTest.java
- core/src/test/java/google/registry/ui/server/registrar/ConsoleUiActionTest.java
- core/src/test/java/google/registry/ui/server/registrar/RegistrarSettingsActionTest.java
- core/src/test/java/google/registry/ui/server/registrar/RegistrarSettingsActionTestCase.java
We found that some webdriver tests failed because RegistryEnvironment
was set to 'production' by other test and was carried over to the
webdriver test, and it was nontrivial to fix them because the instance
of RegistryEnvironment was injected into the testing web server.
Also, to eliminate this problem from potential victims, we stopped
provisioning RegistryEnvironment from Dagger. Instead, we just use
RegistryEnvironment.get() function to get the instance, which indeed
retrives the value from system property every time. If any test case
needs to run the test with other environment, it can just simply use
the existing SystemPropertyRule and RegistryEnvironment.${ENV}.setup
to change it.
--- …
> Stop provisioning RegistryEnvironment from Dagger

- core/src/main/java/google/registry/flows/EppException.java
- core/src/main/java/google/registry/flows/picker/FlowPicker.java
- core/src/test/java/google/registry/flows/domain/DomainRestoreRequestFlowTest.java
- core/src/test/java/google/registry/flows/domain/testdata/domain_update_restore_report.xml
Per DomainRestoreRequestFlow's Javadoc, we automatically approve and instantly
enact all domain restore requests, thus we don't use or support restore
reports. This improves the registrar-visible error message to help make this
more clear.
BUG=b/136493385
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/145)
> Throw a more useful error message on attempted domain restore reports

- proxy/src/main/java/google/registry/proxy/EppProtocolModule.java
- proxy/src/main/resources/google/registry/proxy/hello.xml
- proxy/src/test/java/google/registry/proxy/resources/hello.xml
Apparently it was lost during the great refactoring.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/147)
> Re-add hello.xml file

- core/src/main/java/google/registry/beam/invoicing/InvoicingPipeline.java
We got non-serialization object error when deploying the invoicing
pipeline. It turns out that Beam requires every field in the pipeline
object is serializable. However, it is non-trivial to make
GoogleCredentialsBundle serializable because almost all of its
dependency are not serializable and not controlled by us. Also,
it is non-necessary to inject the credential as the spec11
pipeline also writes output to GCS without having injected
credential. So, removing the injected variable can solve the
problem.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/155)
> Remove injected credentials from invoice pipeline

- release/cloudbuild-release.yaml
This allows for easier testing.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/157)
> Set beam deployment environment in GCB trigger

- core/build.gradle
- core/src/test/java/google/registry/webdriver/RepeatableRunner.java
This PR prevents Gradle from copying the golden images
to build/resources/test, so the screenshot test would
read golden images from src/test/resources directly and
display the path in test log if the test fails. Because
the path pointing to the actual file in src/ folder,
the engineer can easily find it.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/159)
> Read golden images from src folder directly

- core/src/test/java/google/registry/webdriver/WebDriverTestCase.java
Sometimes, the webdriver tests get stuck forever for no reason. It could
be some issue in the test container but it is hard to root cause it. So,
adding a 30s timeout can either trigger the retry earlier or let the
test just fail.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/161)
> Add a 30s timeout for all webdriver tests

- build.gradle
- buildSrc/build.gradle
- config/dependency-license/allowed_licenses.json
- config/dependency-license/license_normalizer_bundle.json
- dependency_license.gradle
Use jk1/Gradle-License-Report to verify that all
dependencies have open-source licenses.
Note that the following dependencies are not checked:
Dependencies of official Gradle plugins
Dependencies declared in buildscript block
Dependencies of jk1/Gradle-License-Report itself
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/165)
> Check dependencies' open-source licenses

- core/src/main/java/google/registry/flows/EppMetrics.java
Assuming this all goes well, we can remove the by-tld and by-id metrics since they're taking up a significantly larger amount of space / cost.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/163)
> Add a metric for EPP processing time regardless of ID/TLD

- core/src/main/java/google/registry/beam/invoicing/InvoicingPipeline.java
- core/src/main/java/google/registry/beam/spec11/Spec11Pipeline.java
- core/src/main/java/google/registry/tools/AuthModule.java
- core/src/test/java/google/registry/beam/invoicing/InvoicingPipelineTest.java
- core/src/test/java/google/registry/beam/spec11/Spec11PipelineTest.java
This will fix #167.
TESTED=Deploy the pipelines successfully locally without seeing any warning(see https://paste.googleplex.com/4664621635993600). Deploy the pipelines from alpha's Cloud Build to crash's GCS successfully(see https://pantheon.corp.google.com/cloud-build/builds/c19daf88-8223-4a9c-9bb9-b9382db8afb7?project=domain-registry-alpha).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/170)
> Fix permission issue in Beam pipeline deployment

- LICENSE
- README.md
Also copy & pasted the license file from https://choosealicense.com/licenses/apache-2.0/. For some reason GitHub is not correctly detecting our license. Hopefully this should fix it.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/174)
> Fix a typo

- build.gradle
- gradle/wrapper/gradle-wrapper.properties
- gradlew
- gradlew.bat
Also make the default wrapper type "all" instead of "binary". This is
helpful for IDEs to understand the gradle script.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/178)
> Upgrade to Gradle 5.5.1

- core/src/main/java/google/registry/reporting/billing/CopyDetailReportsAction.java
- core/src/main/java/google/registry/storage/drive/DriveConnection.java
- core/src/test/java/google/registry/reporting/billing/CopyDetailReportsActionTest.java
When the detailed reports are copied from GCS to registrars' Drive
folders, do not fail the entire copy operation when a single registrar
fails. Instead, send an alert email about the failure, and continue to copy the
rest of the reports.
Also, instead of creating duplicates, overwrite the existing files on
Drive.
BUG=127690361
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/181)
> Fail gracefully when copying detailed reports

- .lgtm.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/191)
> Add customized .lgtm.yml

- appengine_war.gradle
appengineDeployAll requires appengine.deploy.version to be set
otherwiese the deployment would fail.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/198)
> Fix deploying to alpha from workstation

- core/src/main/java/google/registry/env/common/backend/WEB-INF/web.xml
The relevant action was deleted last year here: google@218c451
This removes the final hanging piece.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/184)
> Remove vestigial path for streaming EPP metrics

- gradle.properties
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/210)
> Use OpenJDK8 for Gradle build

- appengine_war.gradle
- build.gradle
- projects.gradle
- proxy/build.gradle
- proxy/deploy-proxy-for-env.sh
Also refactored some common code regarding the mapping between
environments and projects.
The script to update proxy deployments and kill all pods are lifted from
https://cs.corp.google.com/piper///depot/google3/domain/registry/tools/bashrc?l=163
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/214)
> Add a Gradle task to deploy the proxy

- build.gradle
- config/dependency-license/allowed_licenses.json
- java_common.gradle
Enable jacoco, the official Gradle code coverage plugin.
The 'build' task will write a code coverage report to
build/reports/jacoco for each subproject that has tests.
We should consider publish periodical reports to a well known
location.
This change also defines a minimum coverage verification task.
The task is for experiment only, and is not added to the build
process yet.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/216)
> Generate code coverage report

- proxy/src/main/java/google/registry/proxy/ProxyConfig.java
- proxy/src/main/java/google/registry/proxy/ProxyModule.java
- proxy/src/main/java/google/registry/proxy/config/default-config.yaml
https://github.com/google/nomulus/pull/129 migrated `GoogleCredential`
to `GoogleCredentialsBundle` and introduced a subtle bug. I don't fully
understand why but there are times when the access token is null but
`credentials.refresh()` is not called, resulting in NullPointerException
when `credentials.getAccessToken().getTokenValue()` is called.
Since the new GoogleCredentials class supports `shouldRefresh()`, we now
just rely on it to make sure that we always get a value access token.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/217)
> Fix expired access token bug in the proxy

- core/src/main/java/google/registry/request/RequestMetrics.java
Metric usage scales linearly with the number of paths (basically) so we should bucket these
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/220)
> Bucket RDAP metrics by type

- core/build.gradle
Labeling it 'compile' unnecessarily makes psql-dependency a
public contract.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/225)
> Make postgres dependency runtime

- build.gradle
- gradle.properties
- gradle/dependency-locks/buildscript-classpath.lockfile
- gradle/wrapper/gradle-wrapper.properties
- prober/gradle/dependency-locks/buildscript-classpath.lockfile
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/232)
> Update Gradle wrapper to 5.6

- proxy/deploy-proxy-for-env.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/245)
> Update proxy deployment script description

- core/build.gradle
- core/src/main/java/google/registry/config/RegistryConfig.java
- core/src/main/java/google/registry/config/RegistryConfigSettings.java
- core/src/main/java/google/registry/config/files/default-config.yaml
- core/src/main/java/google/registry/persistence/EntityManagerFactoryProvider.java
- core/src/main/resources/META-INF/persistence.xml
- core/src/test/java/google/registry/persistence/EntityManagerFactoryProviderTest.java
- dependencies.gradle
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/234)
> Set up database connection pool

- build.gradle
- core/build.gradle
It doesn't work very well and has been superseded by "verboseTestOutput",
which does the same thing and more.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/247)
> Remove the "showAllOutput" property from the build

- core/src/main/java/google/registry/batch/ExpandRecurringBillingEventsAction.java
- core/src/test/java/google/registry/batch/ExpandRecurringBillingEventsActionTest.java
When the project was originally being designed, we envisioned have a purely
point-in-time architecture that would allow the system to run indefinitely
without requiring any background batch jobs. That is, you could create a domain,
and 10 years later you could infer every autorenewal billing event that should
have happened during those 10 years, without ever having to run any code that
would go through and retroactively create those events as they happened.
This ended up being very complicated, especially when it came to generating
invoices, so we gave up on it and instead wrote the
ExpandRecurringBillingEventsAction mapreduce, which would run as a cronjob and
periodically expand the recurring billing information into actual one-time
billing events. This made the invoicing scripts MUCH …
> Don't write TX records for domains deleted in autorenew grace period

- core/build.gradle
- core/src/main/java/google/registry/tools/GenerateSqlSchemaCommand.java
- core/src/test/java/google/registry/tools/GenerateSqlSchemaCommandTest.java
Add a --start-postgresql option to the nomulus generate_sql_schema command so
that users don't have to start their own docker container to run it.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/249)
> Start postgresql container in generate_sql_schema

- core/build.gradle
This is another dockerized test and these are flakey in the CI runs.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/251)
> Move EntityManagerFactoryProviderTest to fragile

- core/src/main/java/google/registry/tools/GenerateSqlSchemaCommand.java
- core/src/test/java/google/registry/tools/GenerateSqlSchemaCommandTest.java
The rest of the nomulus commands use underscores for delimiting words in
parameter names, so this should too.
Also fixed capitalization of some proper nouns.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/250)
> Make parameter names in generate_sql_schema command consistent

- core/src/main/java/google/registry/model/domain/DesignatedContact.java
- core/src/main/java/google/registry/model/domain/DomainAuthInfo.java
- core/src/main/java/google/registry/model/domain/DomainBase.java
- core/src/main/java/google/registry/model/domain/GracePeriod.java
- core/src/main/java/google/registry/model/domain/Period.java
- core/src/main/java/google/registry/model/domain/launch/LaunchNotice.java
- core/src/main/java/google/registry/model/domain/secdns/DelegationSignerData.java
- core/src/main/java/google/registry/model/eppcommon/AuthInfo.java
- core/src/main/java/google/registry/model/eppcommon/Trid.java
- core/src/main/java/google/registry/model/transfer/BaseTransferObject.java
- core/src/main/java/google/registry/model/transfer/TransferData.java
- core/src/main/java/google/registry/tools/GenerateSqlSchemaCommand.java
- core/src/main/resources/META-INF/persistence.xml
- db/src/main/resources/sql/schema/db-schema.sql.generated
Generate a basic schema for DomainBase and everything that is part of it.
This still isn't complete, in particular it lacks:
- Correct conversions for problematic types (e.g. DateTime, Key...)
- Schema generation for history records.
- Name translation.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/246)
> Generate basic schema for all of DomainBase

- karma.conf.js
Not necessary for the tests but it gets rid of log lines
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/257)
> Serve up all the closure library files

- util/src/main/java/google/registry/util/DateTimeUtils.java
- util/src/test/java/google/registry/util/DateTimeUtilsTest.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/260)
> Add DateTimeUtils conversion methods

- core/src/test/java/google/registry/tools/CreateTldCommandTest.java
- core/src/test/java/google/registry/tools/UpdateTldCommandTest.java
CommandTestCase already wraps stdout stderr, just use the provided methods.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/258)
> Fix command tests that set stdout/stderr

- java_common.gradle
Guava is often specified by version only by other
dependencies. In such cases, Gradle usually resolves
it to the '-android' version, which lacks the collection
classes.
We use custom resolution strategy to force the selection
of the '-jre' version.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/271)
> Force Gradle to use jre version of Guava

- core/src/test/java/google/registry/tools/CommandTestCase.java
CommandTestCase currently consumes stdout & stderr for the command being
tested.  Unfortunately, this results in us not being able to see the command
output.  Add an output splitter so that output gets written to the original
stream in addition to being captured.
A simpler approach would be to print the captured data after command
completion.  However, this won't work for tests that become hung and also
won't display output in real-time.
Tested: Ran a command test with verboseTestOutput=true, verified that standard
output was visible.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/248)
> Output command test output as well as consuming it

- core/build.gradle
Tokens are delimited by pipes and can be escaped. If we use -args
directly, we will not be able to escape the delimiter, if both the
double and single quotes happen to be present in the arguments.
See:
https://docs.gradle.org/current/javadoc/org/gradle/api/tasks/JavaExec.html#setArgsString-java.lang.String-
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/273)
> Update registryTool task to better handle command line arguments

- db/src/main/resources/sql/user/create_table_readwrite_user.sql
- db/src/main/resources/sql/user/delete_user.sql
Added sql files to create and delete the Cloud SQL user for the nomulus app engine services.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/274)
> Add sql files to manage Cloud SQL user

- appengine_war.gradle
For some reason tools.jar (which we don't need in the runtime in the first
place) gets exploded readonly, causing subsequent builds to fail since they
can't overwrite it.  This hack makes it writable at the end of explodeWar.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/279)
> Add work-around for our "explode war" failure

- db/src/main/resources/sql/user/create_readwrite_user.sql
The regular read-write user should not have write permissions to
the flyway metadata table.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/297)
> Restrict nomulus user access to flyway table

- appengine_war.gradle
- core/src/main/java/google/registry/model/transaction/TransactionManagerFactory.java
This fixes the App Engine build.  The runtime now needs access to this.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/293)
> Add persistence.xml to the war files

- core/src/main/java/google/registry/model/transaction/TransactionManagerFactory.java
Add a more elaborate explanation of why actual JpaTransactionManager
initialization was removed from the factory.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/299)
> Add an explanation to dummied-out JPA init

- build.gradle
- projects.gradle
Move the project mapping into its own file so that it can be more easily
overriden.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/300)
> Refactor environment -> project map out of build

- core/src/main/java/google/registry/persistence/CreateAutoTimestampConverter.java
- core/src/main/java/google/registry/schema/tld/PremiumList.java
- core/src/main/java/google/registry/schema/tld/PremiumListDao.java
- core/src/main/java/google/registry/tools/CreateOrUpdatePremiumListCommand.java
- core/src/main/java/google/registry/tools/CreatePremiumListCommand.java
- core/src/main/java/google/registry/tools/server/CreateOrUpdatePremiumListAction.java
- core/src/main/java/google/registry/tools/server/CreatePremiumListAction.java
- core/src/main/java/google/registry/tools/server/ToolsServerModule.java
- core/src/main/java/google/registry/tools/server/UpdatePremiumListAction.java
- core/src/test/java/google/registry/schema/tld/PremiumListDaoTest.java
- core/src/test/java/google/registry/tools/CreatePremiumListCommandTest.java
- core/src/test/java/google/registry/tools/UpdatePremiumListCommandTest.java
- core/src/test/java/google/registry/tools/server/CreateOrUpdatePremiumListActionTest.java
- db/src/main/resources/sql/flyway/V5__update_premium_list.sql
- db/src/main/resources/sql/schema/db-schema.sql.generated
- db/src/main/resources/sql/schema/nomulus.golden.sql
This adds support to the `nomulus create_premium_list` command only; support for
`nomulus update_premium_list` will be in a subsequent PR.
The design goals for this PR were:
1. Do not change the existing codepaths for premium lists at all, especially not
on the read path.
2. Write premium lists to Cloud SQL only if requested (i.e. not by default), and
write to Datastore first so as to not be blocked by errors with Cloud SQL.
3. Reuse existing codepaths to the maximum possible extent (e.g. don't yet
re-implement premium list parsing; take advantage of the existing logic), but
also ...
4. Some duplication is OK, since the existing Datastore path will be deleted
once this migration is complete, leaving only the codepaths for Cloud SQL.
--- …
> Add initial support for persisting premium lists to Cloud SQL

- core/src/main/java/google/registry/persistence/PersistenceModule.java
- core/src/main/java/google/registry/persistence/ZonedDateTimeConverter.java
- core/src/main/java/google/registry/tools/GenerateSqlSchemaCommand.java
- core/src/main/resources/META-INF/persistence.xml
- core/src/test/java/google/registry/persistence/ZonedDateTimeConverterTest.java
- core/src/test/java/google/registry/rde/EscrowTaskRunnerTest.java
Hibernate provides a default converter for ZonedDateTime, but it converts timestamp to a non-normalized format, e.g., 2019-09-01T01:01:01Z will be converted to 2019-09-01T01:01:01Z[UTC]. This converter solves that problem by explicitly calling ZoneId.normalized() to normalize the zone id.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/287)
> Implement ZonedDateTimeConverter

- db/README.md
- db/src/main/resources/sql/user/create_readonly_user.sql
- db/src/main/resources/sql/user/create_readwrite_user.sql
- db/src/main/resources/sql/user/delete_user.sql
- db/src/main/resources/sql/user/initialize_roles.sql
- db/src/main/resources/sql/user/set_flyway_privileges.sql
Create readonly and readwrite roles that may be granted to users.
Also configured default privileges for tables created in the future.
Made sure arbitrary users may not create database or tables.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/302)
> Modify Cloud SQL user management scripts

- db/build.gradle
- db/src/main/resources/sql/user/initialize_roles.sql
Desktop schema push to production is needed in the short term.
Long-termly we need to decide if this should be kept for glass-breaking.
Sandbox and production pushes require interactive confirmation.
Also fixed a typo in initialize_roles.sql.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/309)
> Allow schema-push to all env with Flyway

- core/build.gradle
- gradle.properties
The segregated test targets in core break the --tests filter.  Fix this by
defining a "testFilter" property and creating the FilteringTest task type that
applies it to the property set by "--tests".
Tested:
Ran locally with and without the property set and with the property set to multiple test patterns.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/311)
> Enable filtering across all test tasks

- db/build.gradle
- gradle.properties
Encode Cloud SQL credential files on gcs with base64,
to be consistent with our Cloud Build practices.
Also renamed a property that specifies where to publish
the schema jar. New name is schema_publish_repo.
Manually tested relevant Flyway tasks.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/314)
> Use base64-encoded SQL credentials

- core/src/main/java/google/registry/ui/server/RegistrarFormFields.java
- core/src/main/java/google/registry/ui/server/registrar/RegistrarSettingsAction.java
- core/src/test/java/google/registry/ui/server/registrar/ContactSettingsTest.java
The existing code assumes that the "contacts" segment of the form
contains an exact representation of the registrar contacts. This breaks
when we have a contact with an existing registry lock password because
we don't want to keep passing around that password in plain text (we
never store it in plain text)
This PR changes the code so that instead of assuming the contact is
provided in its entirety, we load the contact from storage first
(matching by email address) if it exists. We then set the required
fields from the JSON object, and set the password optionally if it was
provided.
Alternatives:
- Create a separate RegistrarContactPassword object with a
RegistrarContact parent. This increases complexity significantly since
we'd be adding a parent-child relationship and adding more objects …
> Don't destroy existing registry lock passwords in contacts

- core/src/main/java/google/registry/model/transaction/TransactionManagerFactory.java
- core/src/main/java/google/registry/persistence/PersistenceModule.java
- core/src/main/java/google/registry/tools/UploadClaimsListCommand.java
This PR made the following changes:
1. Make `UploadClaimsListCommand` implement `CommandWithCloudSql` so that the command
can get Cloud SQL environment installed. See #303 for more details.
2. Change to use Cloud SQL JDBC Socket Factory library to connect to Cloud SQL for App Engine application. The previous setup was derived from the public Cloud SQL [doc](https://cloud.google.com/sql/docs/postgres/connect-app-engine) but it just didn't work.
The following tests have been done to verify the current setup:
1. Tested the connection from Nomulus tool by running the `upload_claims_list` command:
* `java -jar ./nomulus.jar -e alpha upload_claims_list --also_cloud_sql /tmp/test_cloud_sql/claims_list.txt`
2. Tested the connection from App Engine application by running the `create_premium_list` …
> Fix issues related to Cloud SQL connection

- config/dependency-license/README.md
- config/dependency-license/allowed_licenses.json
"Public Domain" license must be reviewed case by case.
Removed blanket acceptance and named accepted dependencies
individually.
Also added a README file to warn about this license and WTFPL.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/329)
> Restrict "Public Domain" license acceptance

- core/src/main/java/google/registry/persistence/CurrencyUnitConverter.java
- core/src/main/java/google/registry/persistence/ToStringConverterBase.java
- core/src/main/resources/META-INF/persistence.xml
- core/src/test/java/google/registry/persistence/CreateAutoTimestampConverterTest.java
- core/src/test/java/google/registry/persistence/CurrencyUnitConverterTest.java
- core/src/test/java/google/registry/persistence/UpdateAutoTimestampConverterTest.java
- core/src/test/java/google/registry/persistence/ZonedDateTimeConverterTest.java
- core/src/test/java/google/registry/schema/integration/SqlIntegrationMembershipTest.java
- core/src/test/java/google/registry/schema/integration/SqlIntegrationTestSuite.java
- db/src/main/resources/sql/flyway/V9__premium_list_currency_type.sql
- db/src/main/resources/sql/schema/db-schema.sql.generated
- db/src/main/resources/sql/schema/nomulus.golden.sql
- proxy/src/main/java/google/registry/proxy/metric/BaseMetrics.java
- proxy/src/test/java/google/registry/proxy/handler/FrontendMetricsHandlerTest.java
- util/src/main/java/google/registry/util/Retrier.java
This uses the well-known String representation for currency units. It also
provides a base class for other converters that will be persisting the
toString() representation.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/334)
> Add a converter for CurrencyUnits stored in the database

- core/src/main/java/google/registry/model/registry/RegistryLockDao.java
- core/src/main/java/google/registry/model/transaction/JpaTransactionManagerImpl.java
- core/src/test/java/google/registry/model/registry/RegistryLockDaoTest.java
- core/src/test/java/google/registry/model/tmch/ClaimsListDaoTest.java
- core/src/test/java/google/registry/persistence/CurrencyUnitConverterTest.java
- core/src/test/java/google/registry/schema/tld/PremiumListDaoTest.java
There's no reason to wrap them in PersistenceException, and it makes dealing
with thrown exceptions harder as seen in the diffs on test classes in this
commit.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/338)
> Don't wrap exceptions thrown inside Cloud SQL transactions

- java_common.gradle
- release/cloudbuild-nomulus.yaml
Tentatively release SQL schema at the same time as the server release.
Publish schema jar to gs://domain-registry-maven-repository/nomulus
and also upload it with server artifacts.
Also removed the Gradle 'version' variable which is not used.
Tested=On cloud-build with a simplified version of
cloudbuild-nomulus.yaml.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/341)
> Release SQL schema in Cloud Build

- core/src/main/java/google/registry/config/RegistryConfig.java
- core/src/main/java/google/registry/config/RegistryConfigSettings.java
- core/src/main/java/google/registry/config/files/default-config.yaml
This is because the nomulus tool has been changed to use the same JDBC url as the App Engine application in #321 .
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/330)
> Remove jdbcUrl config for nomulus tool

- core/src/main/java/google/registry/persistence/HibernateSchemaExporter.java
- core/src/test/java/google/registry/model/transaction/JpaTransactionManagerRule.java
- core/src/test/java/google/registry/model/transaction/JpaTransactionManagerRuleTest.java
- core/src/test/java/google/registry/persistence/BloomFilterConverterTest.java
- core/src/test/java/google/registry/persistence/CreateAutoTimestampConverterTest.java
- core/src/test/java/google/registry/persistence/CurrencyUnitConverterTest.java
- core/src/test/java/google/registry/persistence/HibernateSchemaExporterTest.java
- core/src/test/java/google/registry/persistence/UpdateAutoTimestampConverterTest.java
- core/src/test/java/google/registry/persistence/ZonedDateTimeConverterTest.java
When we add the extra test entity to the current `JpaTransactionManagerRule` by calling `jpaRule.withEntityClass(TestEntity.class)` and `jpaRule.withProperty(Environment.HBM2DDL_AUTO, "update")`, the rule would override the golden database scheme with the schema derived from the current entity class(This is an expected behavior by enabling `HBM2DDL_AUTO`). This behavior prevents us from detecting breaking changes in ORM classes.
This PR fixed the issue by adding `HibernateSchemaExporter` to export the DDL script for given extra entity class, and make `JpaTransactionManagerRule` execute the DDL script to create the corresponding table for the extra entity when initializing the database. This PR also simplified the code when adding extra entity class for testing. For now, you don't need …
> Prevent test from changing golden schema

- core/build.gradle
- Disable failOnMatchingTests so we don't fail if we filter out all of the
tests for any given task.
- Add excludeTestCases flag so that we can turn this behavior off for test
tasks that need to run TestCas/TestSuite classes.
- Add includeAllTests() function for test tasks where we don't explicitly
include our required tests.
This makes all test tasks in core FilteringTest, with the exception of the
default test task which now does nothing (it just depends on the other test
tasks).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/339)
> Improve FilteringTest so it works in all cases

- core/src/test/java/google/registry/schema/integration/SqlIntegrationTestSuite.java
This should have been there before but there was a semantic merge conflict (the branch didn't have this test running)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/347)
> Add RegistryLockGetActionTest to SQL testclasses

- core/karma.conf.js
soyutils_usegoog.js (the dependency) has been moved into core/src/main/javascript/ so it's covered by the other rules in the file -- this was a special-cased rule that we had before that is no longer necessary 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/345)
> Clean up Karma config file

- core/src/main/java/google/registry/model/common/Cursor.java
This PR only adds the new cursor types to Cursor.java. Once these are added, the nomulus update_cursor tool can be used to add the cursors for each tld with a cursorTime of the 1st of next month. This is a necessary first step before #343 can be deployed.
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/349)
> Add cursors for tracking ICANN report uploads to Cursor.java

- core/src/main/java/google/registry/flows/domain/DomainCreateFlow.java
- core/src/main/java/google/registry/flows/domain/DomainPricingLogic.java
- core/src/test/java/google/registry/flows/domain/DomainCreateFlowTest.java
- docs/flows.md
We should communicate to the users why this command failed, that they are not allowed to use discounted allocation tokens on premium domains. Currently it still fails, but we don't yet tell them why.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/351)
> Throw an EPP exception when using discount on premium domains

- build.gradle
Leftover from the old time when all subprojects share one directory.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/354)
> Delete obsolet gradle config in root project

- core/src/test/java/google/registry/server/RegistryTestServerMain.java
- core/src/test/java/google/registry/webdriver/TestServerRule.java
As previously written, the AppEngineRule wraps the infinite loop of the server handling requests. This changes the code so that we'll have a chain that does both the AppEngine management and the JPA transaction manager management so we can actually use SQL in tests and in the test server.
Tested with #336 to show that the verification page acted appropriately both in the test server and in the screenshot tests. 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/356)
> Run both the AppEngineRule and JpaTransactionManagerRule in tests

- core/src/main/java/google/registry/beam/invoicing/InvoicingPipeline.java
- core/src/main/java/google/registry/beam/spec11/Spec11Pipeline.java
Fixed the issue by just marking the nested interface public per the error log. Tested the deployment
in alpha and manually kicked off the spec11 and invoicing pipeline. The spec11 pipeline
succeeded without any issue. The invoicing pipeline failed due to missing some data in BigQuery as the alpha environment just doesn't have those data, but it should be not related to this fix.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/360)
> Fix beam pipeline deployment issue

- core/src/main/java/google/registry/persistence/DateTimeConverter.java
- core/src/main/resources/META-INF/persistence.xml
- core/src/test/java/google/registry/persistence/DateTimeConverterTest.java
- core/src/test/java/google/registry/schema/integration/SqlIntegrationTestSuite.java
Implement a converter for the DateTime class.  Once again, we convert to SQL via java.sql.Timestamp, which has the effect of normalizing the timezone to UTC.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/346)
> Add converter for DateTime

- core/src/main/java/google/registry/persistence/HibernateSchemaExporter.java
- core/src/main/java/google/registry/persistence/PersistenceXmlUtility.java
- core/src/main/java/google/registry/tools/GenerateSqlSchemaCommand.java
- core/src/test/java/google/registry/model/transaction/JpaTransactionManagerRule.java
This PR added the `PersistenceXmlUtility` class which provides a few methods to help manipulate `persistence.xml` and refactored `HibernateSchemaExporter`, `GenerateSqlSchemaCommand` and `JpaTransactionManagerRule` by using the provided method to simply the code.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/357)
> Add PersistenceXmlUtility and refactor related code

- db/README.md
- db/build.gradle
Disabled Flyway Gradle tasks with side effects on Cloud SQL
instances. They can still be used on local databases.
Also switched Flyway Gradle tasks to get credentials from
new locations (in domain-registry-dev).
Updated README file on schema push process. Also reformatted
the entire file.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/363)
> Update schema deployment doc and flyway tool

- config/presubmits.py
- core/build.gradle
- core/src/main/java/google/registry/tools/GenerateSqlSchemaCommand.java
- core/src/test/java/google/registry/model/transaction/JpaTransactionManagerRule.java
- core/src/test/java/google/registry/persistence/HibernateSchemaExporterTest.java
- core/src/test/java/google/registry/persistence/PersistenceModuleTest.java
- core/src/test/java/google/registry/tools/GenerateSqlSchemaCommandTest.java
- db/build.gradle
- db/src/main/java/google/registry/persistence/NomulusPostgreSql.java
- db/src/test/java/google/registry/sql/flyway/SchemaTest.java
Defined a util class to return docker tag of desired PSQL version.
Class is defined in ':db' and shared by ':db' and ':core'. Used
an artifact declaration to exclude unnecesary compile dependencies.
Added a presubmit check for instantiations without explicit tag.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/368)
> Require explict tag when starting psql docker

- core/src/main/java/google/registry/model/transaction/TransactionManagerFactory.java
- core/src/main/java/google/registry/tools/RegistryCli.java
- core/src/main/java/google/registry/tools/RegistryToolEnvironment.java
JpaTransactionManager has been enabled in sandbox since 11/6 and I verified that
the claims list has been generated successfully in Cloud SQL. Also, there is no any
JpaTransactionManager related errors in the stackdriver. So, it should be fine to
enable it in all environments.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/352)
> Enable JpaTransactionManager in all environment

- core/src/main/java/google/registry/model/registry/Registries.java
- core/src/test/java/google/registry/model/registry/RegistriesTest.java
This is useful for things that need to know more than just the TLD strings
themselves, which is all Registries currently provides.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/373)
> Add a new method to load all Registry entities of a given type

- docs/operational-procedures/premium-list-management.md
- docs/operational-procedures/reserved-list-management.md
They were a little bit out of date.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/380)
> Update premium and reserved list management docs

- core/src/main/java/google/registry/model/registry/Registries.java
- core/src/main/java/google/registry/model/registry/Registry.java
- core/src/test/java/google/registry/export/ExportReservedTermsActionTest.java
- core/src/test/java/google/registry/model/registry/RegistryTest.java
This is accomplished by also providing a loadAll() method on the Registry cache
that can be used to load an entire batch of Registry objects at once.
This improves efficiency, because now, any operation on Registries that loads
all the Registry entities (getTlds(), getTldsOfType(), and getTldEntities()), is
plumbed through the Registry cache, therefore loading it from that cache if it
exists and only hitting the DB if not. If not, this populates the Registry cache
upon loading, so that subsequent calls to Registry.get() will now hit the cache
instead of the DB.
To give a concrete example, the following code:
```
for (String tld : Registries.getTlds()) {
// ...
doSomethingWith(Registry.get(tld));
// ...
}
```
is now much more efficient, because the initial call to Registries.getTlds() …
> Update the Registries cache to leverage/populate the Registry cache

- db/build.gradle
- java_common.gradle
- projects.gradle
We should not hardcode our dev project in the public config file.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/371)
> Make dev project configurable

- release/cloudbuild-nomulus.yaml
The original purpose of the maven publication is for
use by the server/schema compatibility tests. A command line
flag can direct a test run to use difference versions of
the schema jar. However, this won't work due to dependency
locking.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/383)
> Stop publish Cloud SQL schema jar to maven repo

- java-format/google-java-format-git-diff.sh
Print the names of all java files that need reformatting during the check and
reformat operations.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/386)
> Print filenames that need to be reformatted

- networking/build.gradle
- networking/gradle/dependency-locks/compile.lockfile
- networking/gradle/dependency-locks/compileClasspath.lockfile
- networking/gradle/dependency-locks/default.lockfile
- networking/gradle/dependency-locks/runtime.lockfile
- networking/gradle/dependency-locks/runtimeClasspath.lockfile
- networking/gradle/dependency-locks/testCompile.lockfile
- networking/gradle/dependency-locks/testCompileClasspath.lockfile
- networking/gradle/dependency-locks/testRuntime.lockfile
- networking/gradle/dependency-locks/testRuntimeClasspath.lockfile
- networking/src/main/java/google/registry/networking/handler/SslServerInitializer.java
- networking/src/test/java/google/registry/networking/handler/NettyRule.java
- networking/src/test/java/google/registry/networking/handler/SslClientInitializerTest.java
- networking/src/test/java/google/registry/networking/handler/SslInitializerTestUtils.java
- networking/src/test/java/google/registry/networking/handler/SslServerInitializerTest.java
- proxy/src/main/java/google/registry/proxy/EppProtocolModule.java
- proxy/src/main/java/google/registry/proxy/WebWhoisProtocolsModule.java
Client SSL handler already performs the necessary validation. Only tests are
added.
Server SSL handler does not currently check for the validity period of
the client certificate as the insecure trust manager is used. This PR
added the check but does not actually terminate the connection yet. It
will log the expired certificates so that we can contact the registrars
to update them.
Once we are certain that all certificates are updated, we can turn off
dryrun mode.
We should also consider checking if the certificate has too long a
validity period as it defeats the purpose of using regularly updated
certificates to deprecate insecure cipher suites.
--- …
> Respect certificate validity period

- core/src/test/java/google/registry/schema/integration/SqlIntegrationMembershipTest.java
In some cases, we define JpaTransactionManagerRule in a TestCase
class which is extended by the concrete test class. So, we need
to check if JpaTransactionManagerRule is also defined in the super
class.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/398)
> Check SQL dependency in super class for SqlIntegrationMembershipTest

- networking/src/main/java/google/registry/networking/handler/SslClientInitializer.java
The factory method passes a null trustedCertificates instead of an empty
list.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/407)
> Fix null pointer excpetion bug

- core/src/test/java/google/registry/model/transaction/JpaTransactionManagerRuleTest.java
One test breaks if path to external schema is set and
test is run from the sqlIntegrationTest task.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/412)
> Fix test on use of external schema jar

- networking/src/main/java/google/registry/networking/handler/SslServerInitializer.java
The promise should be set outside the try block because if we want
warning only, we still want the promise to be set even if the
clientCertificate.checkValidity() throws an error.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/419)
> Fix another bug in the proxy

- core/src/main/java/google/registry/persistence/HibernateSchemaExporter.java
- core/src/test/java/google/registry/model/transaction/JpaTransactionManagerRule.java
- core/src/test/java/google/registry/persistence/JodaMoneyConverterTest.java
JpdaMoneyConverterTest relies on Hibernate to deploy its schema.
This introduces an extra jdbc connection in the middle of a test
suite, and may break the connection count checks between tests made
by JpaTransactionManagerRule.
This change updated HibernateSchemaExporter to include Hibernate
proprietary mappings in META-INF/orm.xml.
This change also disabled Hibernate schema push for all tests,
and enabled sql statement logging.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/421)
> Fix flakiness in JodaMoneyConverterTest

- core/src/main/java/google/registry/model/common/Cursor.java
- core/src/main/java/google/registry/reporting/icann/IcannReportingUploadAction.java
- core/src/test/java/google/registry/reporting/icann/IcannReportingUploadActionTest.java
getFileName now sets the file name of the report to upload to use the month before cursor time.
IcannReportingUploadAction no longer uploads the MANIFEST.txt file since it is not required based on (https://tools.ietf.org/html/draft-lozano-icann-registry-interfaces-07#page-9) and the previous implementation of this action did not upload it.
Deletes the ICANN_UPLOAD_MANIFEST cursor since it is no loner needed.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/425)
> Fix IcannReportingUploadAction to upload reports from the previous month

- core/src/main/java/google/registry/schema/tld/PremiumListDao.java
- core/src/test/java/google/registry/schema/tld/PremiumListDaoTest.java
We need to be able to simultaneously update premium lists that already exist in
Datastore and create them in Cloud SQL (because they haven't been migrated over
yet). This temporarily relaxes the existence check for Cloud SQL so that
"updates" will work even when the list doesn't yet exist there.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/428)
> Relax premium list existence check to allow Cloud SQL migration

- core/src/test/java/google/registry/model/transaction/JpaTransactionManagerRule.java
- core/src/test/java/google/registry/webdriver/DockerWebDriverRule.java
See https://github.com/google/nomulus/issues/401
Specifically:
- Use getContainerIpAddress() instead of localhost to insulate us from
off-machine docker usage.
- Remove shutdown hook to close the container, as testcontainers does this for
us.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/426)
> Implement changes suggested by testcontainer dev

- release/cloudbuild-nomulus.yaml
- release/cloudbuild-release.yaml
Generate env-specific schema-deploy configs and upload them to GCS.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/435)
> Upload Cloud Build schema-deploy config to GCS

- java_common.gradle
By default Jacoco only looks at execution data from
the 'test' task. This is a problem to 'core' which
has multiple test sets.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/437)
> Make Jacoco work with multiple test tasks

- core/src/main/java/google/registry/persistence/GenericCollectionUserType.java
- core/src/main/java/google/registry/persistence/MapUserType.java
- core/src/main/java/google/registry/persistence/MutableUserType.java
- core/src/main/java/google/registry/persistence/NomulusPostgreSQLDialect.java
- core/src/test/java/google/registry/persistence/MapUserTypeTest.java
- core/src/test/java/google/registry/schema/integration/SqlIntegrationTestSuite.java
- db/src/main/resources/sql/flyway/V14__load_extension_for_hstore.sql
- db/src/main/resources/sql/schema/nomulus.golden.sql
This PR added `MapUserType` which can be used to convert a Java `Map<String, String>` to/from a PostgreSQL column with hstore type.
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/443)
> Add MapUserType to support converstion between Map and hstore

- core/src/main/java/google/registry/flows/ResourceFlowUtils.java
- core/src/main/java/google/registry/flows/domain/DomainTransferApproveFlow.java
- core/src/main/java/google/registry/flows/domain/DomainTransferQueryFlow.java
- core/src/main/java/google/registry/flows/domain/DomainTransferRequestFlow.java
- core/src/main/java/google/registry/model/ResourceTransferUtils.java
- core/src/main/java/google/registry/model/domain/DomainBase.java
- core/src/main/java/google/registry/rde/DomainBaseToXjcConverter.java
- core/src/test/java/google/registry/batch/ResaveEntityActionTest.java
- core/src/test/java/google/registry/flows/EppLifecycleDomainTest.java
- core/src/test/java/google/registry/flows/domain/DomainTransferCancelFlowTest.java
- core/src/test/java/google/registry/flows/domain/DomainTransferFlowTestCase.java
- core/src/test/java/google/registry/flows/domain/DomainTransferQueryFlowTest.java
- core/src/test/java/google/registry/flows/domain/DomainTransferRequestFlowTest.java
- core/src/test/java/google/registry/model/domain/DomainBaseTest.java
- core/src/test/java/google/registry/rde/DomainBaseToXjcConverterTest.java
- core/src/test/java/google/registry/rde/RdeFixtures.java
- core/src/test/java/google/registry/testing/DatastoreHelper.java
- core/src/test/resources/google/registry/flows/domain/domain_transfer_request_response_autorenew_grace_at_request_only.xml
- core/src/test/resources/google/registry/flows/domain/domain_transfer_request_response_autorenew_grace_throughout_transfer_window.xml
- core/src/test/resources/google/registry/flows/domain_info_response_after_transfer_after_argp.xml
- core/src/test/resources/google/registry/flows/domain_info_response_after_transfer_during_argp.xml
- core/src/test/resources/google/registry/flows/domain_info_response_before_transfer_and_argp.xml
- core/src/test/resources/google/registry/flows/domain_info_response_before_transfer_during_argp.xml
- core/src/test/resources/google/registry/flows/domain_info_response_during_transfer_during_argp.xml
- core/src/test/resources/google/registry/flows/domain_transfer_query_response_completed_fakesite.xml
- core/src/test/resources/google/registry/flows/domain_transfer_query_response_wildcard.xml
- core/src/test/resources/google/registry/flows/domain_transfer_query_response_wildcard_not_requested.xml
- core/src/test/resources/google/registry/flows/domain_transfer_response.xml
- core/src/test/resources/google/registry/rde/testMapReduce_withDomain_producesExpectedXml.xml
This fixes both b/25084229 and b/145229815 where the TransferResponses from the domain transfer flows are incorrectly calculating exDate.
ExDate is currently always calculated based on the current domain expiration time which causes issues when a domain is autorenewed before or during transfer. 
Steps taken to fix this issue:
1. Add a computeExDateForApprovalTime function to ResourceFlowUtils to call ExtendRegistrationWithCap with the correct number of years based on whether the domain is in Auto Renew Grace Period at given transferTime.
2. When the transfer is requested, computeExDateForApprovalTime is called with approvalTime = automatedTransferTime and stored in TransferData. DomainTransferRequestFlow, however, returns exDate based on if the approval time were now.
3. When the transfer …
> Fix exDate calculation in domain transfer flows

- core/src/main/java/google/registry/persistence/EnumSetUserType.java
- core/src/main/java/google/registry/persistence/GenericCollectionUserType.java
- core/src/test/java/google/registry/persistence/EnumSetUserTypeTest.java
Leverage GenericCollectionUserType to store enum fields as an array of
strings.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/446)
> Implement a hibernate type for enums

- core/src/test/java/google/registry/persistence/MapUserTypeTest.java
- core/src/test/java/google/registry/schema/integration/SqlIntegrationTestSuite.java
Integration tests should only test features that would break the server binary.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/449)
> Remove MapUserTypeTest from Integration TestSuite

- core/src/main/java/google/registry/model/registry/label/ReservedList.java
- core/src/main/java/google/registry/schema/tld/ReservedListCache.java
- core/src/main/java/google/registry/schema/tld/ReservedListDao.java
- core/src/test/java/google/registry/schema/tld/ReservedListDaoTest.java
This PR added a logic to compare reserved list in Cloud SQL to the list in Datastore every time when caching the Datastore list. This can help us understand if the Cloud SQL list is always same as the
Datastore list.
Also, it added a ReservedListCache class which can be used later to replace the Datastore cache.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/423)
> Add dual read for ReservedList

- core/src/main/java/google/registry/batch/ExpandRecurringBillingEventsAction.java
- core/src/main/java/google/registry/export/sheet/SyncRegistrarsSheet.java
- core/src/main/java/google/registry/model/common/Cursor.java
- core/src/main/java/google/registry/rde/EscrowTaskRunner.java
- core/src/main/java/google/registry/rde/PendingDepositChecker.java
- core/src/main/java/google/registry/rde/RdeStagingReducer.java
- core/src/main/java/google/registry/rde/RdeUploadAction.java
- core/src/main/java/google/registry/reporting/icann/IcannReportingUploadAction.java
- core/src/main/java/google/registry/schema/cursor/CursorDao.java
- core/src/main/java/google/registry/tools/UpdateCursorsCommand.java
- core/src/test/java/google/registry/backup/CommitLogCheckpointStrategyTest.java
- core/src/test/java/google/registry/batch/ExpandRecurringBillingEventsActionTest.java
- core/src/test/java/google/registry/export/sheet/SyncRegistrarsSheetTest.java
- core/src/test/java/google/registry/model/common/CursorTest.java
- core/src/test/java/google/registry/rde/EscrowTaskRunnerTest.java
- core/src/test/java/google/registry/rde/PendingDepositCheckerTest.java
- core/src/test/java/google/registry/rde/RdeStagingActionTest.java
- core/src/test/java/google/registry/rde/RdeUploadActionTest.java
- core/src/test/java/google/registry/reporting/icann/IcannReportingUploadActionTest.java
- core/src/test/java/google/registry/schema/cursor/CursorDaoTest.java
- core/src/test/java/google/registry/schema/integration/SqlIntegrationTestSuite.java
- core/src/test/java/google/registry/tools/UpdateCursorsCommandTest.java
This adds a helper method that is used in all places where the code saves a cursor. The helper function saves the cursor to Datastore. If that succeeds, it constructs a new Cursor object and attempts to save it to Cloud SQL. All Cloud SQL exceptions are caught and logged, but don't cause the helper method to fail. 
Note: There were a few places in the code that saved the cursor to Datastore transactionally. With this helper method, no cursors will be saved transactionally.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/414)
> Add dual write for Cursors

- core/src/main/java/google/registry/model/registry/label/ReservationType.java
- core/src/test/java/google/registry/flows/CheckApiActionTest.java
- core/src/test/java/google/registry/flows/domain/DomainCheckFlowTest.java
In domain check reasons for unavailable domains, we were previously saying that
domains were "Reserved" regardless of whether the domain was fully blocked or
reserved for an anchor tenant or other specific use (e.g. the .new Limited
Release Program). This commit changes the message for the latter situations to
be "Allocation token required", so that registrars have a hint that domain will
show as available if the correct allocation token is supplied to the domain
check command using the allocation token extension.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/455)
> Change reserved messages for domains w/ required allocation token

- core/build.gradle
Add a build task for generateSqlSchema so we don't have to fill in all of the parameters.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/454)
> Add generateSqlSchema as a build task

- core/src/main/java/google/registry/reporting/icann/IcannReportingStagingAction.java
- core/src/main/java/google/registry/reporting/icann/IcannReportingUploadAction.java
- core/src/test/java/google/registry/reporting/icann/IcannReportingStagingActionTest.java
- core/src/test/java/google/registry/reporting/icann/IcannReportingUploadActionTest.java
This fixes getFileName so that it uses the correct year when uploading the reports for December in January. The files to be updated are from the month before the cursor time. In the previous implementation the getFileName method was using the same year as the cursor time to construct the filename. This only caused an issue in the case where the cursor time is in January and the files to upload are from December of the previous year. 
This also changes IcannReportingUploadAction to no longer take in a sub directory as a parameter. Instead the sub directory is inferred based on the cursor time.  This allows for reports from different sub directories to be uploaded at the same time if the different cursors point to files located in different sub directories.
--- …
> Fix IcannReportingUploadAction to use correct year in January

- core/src/main/java/google/registry/model/EppResource.java
- core/src/main/java/google/registry/model/domain/DesignatedContact.java
- core/src/main/java/google/registry/model/domain/DomainBase.java
- core/src/main/java/google/registry/model/eppcommon/StatusValue.java
- core/src/test/java/google/registry/model/domain/DomainBaseSqlTest.java
- core/src/test/java/google/registry/schema/integration/SqlIntegrationTestSuite.java
- db/src/main/resources/sql/flyway/V14__add_epp_resources.sql
- db/src/main/resources/sql/flyway/V15__add_epp_resources.sql
- db/src/main/resources/sql/schema/db-schema.sql.generated
- db/src/main/resources/sql/schema/nomulus.golden.sql
Fix all of the existing problems with DomainBase persistence:
- Remove "final" keywords on getters that cause errors during startup.
- Remove Transient from creationTime (since there's a converter for
CreateAutoTimestamp)
- Fix DesignatedContext persistence so that it only creates a single table.
This is a lot more efficient given that these are many-to-one with their
domains.
- Add a flyway script, update the golden schema.
- Create a unit test, add it to the integration test suite.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/438)
> Get persistence of DomainBase actually working

- core/src/main/java/google/registry/schema/tld/PremiumListDao.java
- core/src/test/java/google/registry/schema/tld/PremiumListDaoTest.java
The decimal places of JPY is 0 which caused failure when `Money.of(JPY, 1000.00)` is invoked. Set the scale of the amount to the decimal places of currency unit fixed the problem.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/463)
> Fix money conversion for JPY in PremiumListDao

- release/cloudbuild-deploy.yaml
- release/cloudbuild-schema-deploy.yaml
- release/cloudbuild-sync.yaml
- release/cloudbuild-tag.yaml
Cloud Build variable reference need to stay from the  ${var} pattern
to prevent Spinnaker from trying to resolve it. In all files that
are used by Spinnaker, we change variable reference to the $var form.
We made the minimum amount of change possible, and will review this
issue after the permanent solution is available.
TESTED=In the deploy schema to sandbox pipeline
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/465)
> Work around Spinnaker issue wrt variables

- networking/build.gradle
Stay with the legacy behavior to unblock release build.
We will update the test cert generation code later.
TESTED=reproduced and fixed test failures in builder container
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/468)
> Allow non-CA cert as trust anchor in tests

- core/src/main/java/google/registry/tools/DomainLockUtils.java
- core/src/main/java/google/registry/tools/LockDomainCommand.java
- core/src/main/java/google/registry/tools/LockOrUnlockDomainCommand.java
- core/src/main/java/google/registry/tools/UnlockDomainCommand.java
- core/src/main/java/google/registry/ui/server/registrar/RegistryLockPostAction.java
- core/src/main/java/google/registry/ui/server/registrar/RegistryLockVerifyAction.java
- core/src/test/java/google/registry/model/registry/RegistryLockDaoTest.java
- core/src/test/java/google/registry/tools/DomainLockUtilsTest.java
- core/src/test/java/google/registry/tools/LockDomainCommandTest.java
- core/src/test/java/google/registry/tools/UnlockDomainCommandTest.java
- core/src/test/java/google/registry/ui/server/registrar/RegistryLockGetActionTest.java
- core/src/test/java/google/registry/ui/server/registrar/RegistryLockPostActionTest.java
- core/src/test/java/google/registry/ui/server/registrar/RegistryLockVerifyActionTest.java
We were using UUIDs before which are also fine, but unnecessarily long.
The RegistryLock class itself does not enforce any particular format for
the lock verification codes.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/464)
> Use randomly-generated base-58 strings for RegistryLock verification codes

- networking/build.gradle
- networking/src/main/java/google/registry/networking/module/CertificateSupplierModule.java
- networking/src/main/java/google/registry/networking/util/SelfSignedCaCertificate.java
- networking/src/test/java/google/registry/networking/handler/SslClientInitializerTest.java
- networking/src/test/java/google/registry/networking/handler/SslInitializerTestUtils.java
- networking/src/test/java/google/registry/networking/handler/SslServerInitializerTest.java
- networking/src/test/java/google/registry/networking/module/CertificateSupplierModuleTest.java
- proxy/src/test/java/google/registry/proxy/EppProtocolModuleTest.java
- proxy/src/test/java/google/registry/proxy/handler/EppServiceHandlerTest.java
Our tests were using a self-signed cert created by a netty utility.
That cert is not CA, and cannot be used with newer JDK versions
(starting from u242 with Ubuntu openjdk).
Now we generate a unsafe cert for tests. The new cert,
SelfSignedCaCertificate, needs to be made test-only.
To do so we need to refactor both prober and proxy.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/475)
> Use CA cert in tests

- .gitignore
- config/presubmits.py
- java_common.gradle
- release/build_nomulus_for_env.sh
Make Gradle put its caches in the source tree so that
they can be preserved across steps. When left at their
default location, caches are lost after each step. This
results in repeated downloads of the same dependencies,
which might be the cause of the recent build errors.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/479)
> Make Gradle dependency cache shareable in GCB

- release/build_nomulus_for_env.sh
- release/cloudbuild-nomulus.yaml
Make the initial test and the final publishing steps use the shared
dependency cache.
Also make the initial test use the registry's own maven repo instead
of Maven Central.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/481)
> Use dependency cache in all Gradle tasks in GCB

- release/build_nomulus_for_env.sh
- release/cloudbuild-nomulus.yaml
- release/cloudbuild-proxy.yaml
The url pattern https://storage.googleapis.com/{Bucket}/{Path}
uses the legacy XML API, which seems to be less robust than
the JSON API. We have observed connection resets after a few
thousand-file download bursts over 30 minutes.
This PR changes all urls to registry's Maven repo on GCS to
gcs://{Bucket}/{Path}. Gradle uses the JSON API for such urls.
TESTED=In Cloud Build with local change
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/483)
> Use JSON API for Maven Repo on GCS

- core/src/main/java/google/registry/persistence/transaction/TransactionManagerFactory.java
- core/src/main/java/google/registry/tools/RegistryCli.java
- core/src/test/java/google/registry/persistence/transaction/JpaTransactionManagerRule.java
This fixes an exception we were seeing in production where commands that only
implemented CommandWithRemoteApi (and that had nothing to do with Cloud SQL)
were nevertheless trying to initialize a JPA TM instance, and then failing.
That stacktrace looked like:
com.google.api.client.http.HttpResponseException: 400 Bad Request
{
"error": "invalid_grant",
"error_description": "Bad Request"
}
at com.google.api.client.http.HttpRequest.execute(HttpRequest.java:1113)
at com.google.auth.oauth2.UserCredentials.refreshAccessToken(UserCredentials.java:193)
at com.google.auth.oauth2.OAuth2Credentials.refresh(OAuth2Credentials.java:165)
at com.google.auth.oauth2.OAuth2Credentials.getRequestMetadata(OAuth2Credentials.java:151)
at com.google.auth.http.HttpCredentialsAdapter.initialize(HttpCredentialsAdapt …
> Lazily instantiate jpaTm

- core/src/main/java/google/registry/flows/domain/token/AllocationTokenFlowUtils.java
- core/src/test/java/google/registry/flows/domain/token/AllocationTokenFlowUtilsTest.java
- docs/flows.md
In addition, we should be returning an authorization exception for an
invalid token, not a parameter syntax exception. See https://tools.ietf.org/html/draft-ietf-regext-allocation-token-04#section-2.1
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/489)
> Check for an empty/null allocation token

- core/src/main/java/google/registry/tools/CountDomainsCommand.java
- core/src/test/java/google/registry/tools/CountDomainsCommandTest.java
This makes the command consistent with list_domains. I use both frequently and it
was annoying forgetting which one takes -t and which uses main parameters. Now
they both work the same way.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/493)
> Use -t instead of main params for TLDs in nomulus count_domains command

- core/src/main/java/google/registry/env/production/default/WEB-INF/cron.xml
This job checks each ICANN cursor's cursorTime. If all cursorTime values are in the future, the action exits and does nothing. For each cursor that has a cursorTime in the past, the corresponding report is uploaded if it is staged, or logs an error message if the report has not been staged yet.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/385)
> Add daily cron job for IcannReportingUploadAction

- core/src/main/javascript/google/registry/ui/js/registrar/registry_lock.js
If there's a domain (this is an unlock) then it means the domain field is disabled so we should focus on the password field. If there isn't a domain (this is a lock) then we should focus on the domain field since it's first. 
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/499)
> Set focus correctly in lock modal

- core/src/main/java/google/registry/flows/domain/DomainCreateFlow.java
- core/src/main/java/google/registry/flows/domain/token/AllocationTokenFlowUtils.java
- core/src/main/java/google/registry/tools/LockOrUnlockDomainCommand.java
- core/src/main/java/google/registry/tools/javascrap/BackfillRegistryLocksCommand.java
- core/src/test/java/google/registry/flows/domain/DomainCheckFlowTest.java
- core/src/test/java/google/registry/flows/domain/DomainCreateFlowTest.java
- docs/flows.md
This is in response to a client-reported error, where they accidentally sent the
wrong domain name on a domain create that included an allocation token. What
should have happened (and that now happens as of this commit) is an error being
thrown that the allocation token does not match the domain name being created.
What happened instead was that, since the incorrectly submitted domain name was
not reserved, the create succeeded (as it would for all creates of unreserved
domains in GA) and the allocation token was redeemed, which is not what you'd
expect.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/498)
> Always validate domain name on allocation token

- core/src/main/java/google/registry/ui/server/RegistrarFormFields.java
- core/src/main/resources/google/registry/ui/soy/registrar/ContactSettings.soy
- core/src/test/javascript/google/registry/ui/js/registrar/contact_settings_test.js
Basically, no matter how we quote it in the Soy file, sometimes it's true/false, and sometimes it's "true"/"false with hidden input fields. This is annoying.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/500)
> Handle both ways the UI passes in booleans

- core/src/main/java/google/registry/model/server/Lock.java
- core/src/main/java/google/registry/schema/server/LockDao.java
- core/src/test/java/google/registry/model/server/LockTest.java
- core/src/test/java/google/registry/schema/integration/SqlIntegrationTestSuite.java
- core/src/test/java/google/registry/schema/server/LockDaoTest.java
Modifies acquire() and release() to write lock to Cloud SQL and delete lock from Cloud SQL whenever a create or delete is done for a lock in Datastore.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/496)
> Add Lock dual write

- build.gradle
- buildSrc/build.gradle
- common/build.gradle
- core/build.gradle
- db/build.gradle
- dependencies.gradle
- networking/build.gradle
- prober/build.gradle
- proxy/build.gradle
- settings.gradle
- util/build.gradle
Gradle 6.2.1 apparently introduces a behavior change wrt boolean
expression: empty string used to eval to false, but now evals to
true.
Pre Gradle 6.2.1, root project's Gradle properties apparently were
not set to buildSrc. Now they are passed on to buildSrc -- mavenUrl
in buildSrc changes from null to "".
Both changes break the project when mavenUrl and/or pluginsUrl are
not set on command line.
Also added junit.jupiter-api as testCompile dependencies to projects.
This is a directly used dependency, whose absence causes a Lint
warning.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/509)
> Fix broken builds when Maven Central is used

- core/src/main/java/google/registry/persistence/VKey.java
- core/src/test/java/google/registry/persistence/transaction/JpaTransactionManagerImplTest.java
- core/src/test/java/google/registry/schema/registrar/RegistrarDaoTest.java
- core/src/test/java/google/registry/tools/UpdateRegistrarCommandTest.java
It was discovered in the course of trying to convert the larger codebase
to VKey.create() calls that method overloading isn't a very effective
discriminator in cases where "Object" is one of the distinguishing
argument types:-)
Convert the two specialized create() methods to createOfy() and
createSql() so that (at least in the former case) we'll get a
compile-time error if we aim to create a VKey for an Ofy key from an
object of the incorrect type.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/513)
> Disambiguate naming of VKey.create() overloads

- core/build.gradle
- core/gradle/dependency-locks/compile.lockfile
- core/gradle/dependency-locks/compileClasspath.lockfile
- core/gradle/dependency-locks/nonprodCompile.lockfile
- core/gradle/dependency-locks/nonprodCompileClasspath.lockfile
- core/gradle/dependency-locks/nonprodRuntime.lockfile
- core/gradle/dependency-locks/nonprodRuntimeClasspath.lockfile
- core/gradle/dependency-locks/runtime.lockfile
- core/gradle/dependency-locks/testCompile.lockfile
- core/gradle/dependency-locks/testCompileClasspath.lockfile
This PR is a preparation for #515 which added `CloudSqlCredentialFactory` implementing `CredentialFactory` provided by the cloud sql library.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/516)
> Change cloud sql library to compile level dependency

- core/src/test/java/google/registry/server/RegistryTestServerMain.java
This rule isn't necessary any more since we merged the SQL-starting rule
into the AppEngineRule logic. Furthermore, it actually causes the test
server to crash because we try to drop-and-create the DB twice, the
second time while the first instance is still connected.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/521)
> Fix the test server

- core/build.gradle
- core/gradle/dependency-locks/compile.lockfile
- core/gradle/dependency-locks/compileClasspath.lockfile
- core/gradle/dependency-locks/nonprodCompile.lockfile
- core/gradle/dependency-locks/nonprodCompileClasspath.lockfile
- core/gradle/dependency-locks/nonprodRuntime.lockfile
- core/gradle/dependency-locks/nonprodRuntimeClasspath.lockfile
- core/gradle/dependency-locks/runtime.lockfile
- core/gradle/dependency-locks/testCompile.lockfile
- core/gradle/dependency-locks/testCompileClasspath.lockfile
It turns out that we need `com.google.cloud.sql:jdbc-socket-factory-core` as a compile dependency instead of `com.google.cloud.sql:postgres-socket-factory`. Though, `com.google.cloud.sql:postgres-socket-factory` depends on `com.google.cloud.sql:jdbc-socket-factory-core`.
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/522)
> Set postgres package back to runtime dependency

- core/src/test/java/google/registry/persistence/transaction/JpaTransactionManagerRule.java
- core/src/test/resources/google/registry/persistence/transaction/cleanup_database.sql
Speed up the database cleanup between tests by dropping the 'schema'
(Postgresql term, not the DDL scripts) instead of the database. The new 
approach is much faster.
Ad hoc measurement on my desktop shows that :core:sqlIntegrationTest
improves from 73 seconds to 48 seconds, and :core:standardTest
improves from 12m40 to 7m40.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/530)
> Drop postgresql schema instead of database in Sql tests

- core/src/main/java/google/registry/ui/server/registrar/RegistryLockGetAction.java
- core/src/test/java/google/registry/testing/AppEngineRule.java
- core/src/test/java/google/registry/tools/RegistrarContactCommandTest.java
- core/src/test/java/google/registry/ui/server/registrar/RegistryLockGetActionTest.java
Unfortunately in our testing environments, we're all admins so it's easy to miss things like this.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/531)
> Handle null GAE user IDs gracefully (for non-admins)

- core/src/main/javascript/google/registry/ui/js/registrar/registry_lock.js
We don't have the field when it's an admin user that's logged in. A
nicer language would have caught this unfortunately.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/534)
> Don't rely on the password field's existence for admins

- core/src/test/java/google/registry/persistence/transaction/JpaTransactionManagerRule.java
Reuse EntityManagerFactory instance in tests if the requested schema
stays the same. Only truncate tables and reset sequences when reusing.
Note that the jdbc driver needs to be informed to expect out-of-band
schema changes.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/533)
> Reuse JPA EntityManagerFactory in tests

- core/src/main/java/google/registry/persistence/VKey.java
- core/src/test/java/google/registry/persistence/VKeyTest.java
We should have used ofNullable() instead of of() for key creation.  Also add a
unit test.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/539)
> Fix optional access for VKey nested keys

- core/src/main/java/google/registry/model/server/Lock.java
Fix for b/152539854. Replace null TLDs on Cloud SQL Locks with "GLOBAL".
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/536)
> Fix IllegalArgumentException

- core/src/main/java/google/registry/schema/tld/PremiumEntry.java
- core/src/main/resources/META-INF/orm.xml
This PR resolved the warnings displayed when running a nomulus command:
```shell
Mar 27, 2020 5:07:56 PM org.hibernate.cfg.annotations.reflection.JPAOverriddenAnnotationReader checkForOrphanProperties
WARN: HHH000207: Property org.joda.money.Money.money not found in class but described in <mapping-file/> (possible typo error)
Mar 27, 2020 5:07:56 PM org.hibernate.cfg.annotations.reflection.JPAOverriddenAnnotationReader checkForOrphanProperties
WARN: HHH000207: Property org.joda.money.BigMoney.currency not found in class but described in <mapping-file/> (possible typo error)
Mar 27, 2020 5:07:56 PM org.hibernate.mapping.RootClass checkCompositeIdentifier
WARN: HHH000038: Composite-id class does not override equals(): google.registry.schema.tld.PremiumEntry
Mar 27, 2020 5:07:56 PM …
```
> Resolve warnings in the Hibernate log

- core/build.gradle
- core/src/test/java/google/registry/testing/AppEngineRule.java
- java_common.gradle
In Gradle, JUnit 5 must be explicitly enabled with a call to
test.useJUnitPlatform().
The FilteringTest used in :core must also enable JUnit5 separately.
Fixed AppEngineRule to work with the few tests that have migrated
to JUnit5 (all in one of the two classes named PremiumListTest).
More work is needed with AppEngine before we can migrate tests
that actually use Cloud SQL.
For context, with @EnableRuleMigrationSupport, JUnit 5 runner calls
an external resource's before() and after() methods. TestRule.apply()
is not called, therefore any setup done their will be bypassed with
JUnit 5.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/545)
> Actually run JUnit 5 tests

- core/src/test/java/google/registry/model/EntityTestCase.java
- core/src/test/java/google/registry/model/domain/DomainBaseSqlTest.java
- core/src/test/java/google/registry/model/registry/RegistryLockDaoTest.java
- core/src/test/java/google/registry/schema/registrar/RegistrarDaoTest.java
- core/src/test/java/google/registry/schema/server/LockDaoTest.java
- core/src/test/java/google/registry/schema/tld/PremiumListDaoTest.java
- core/src/test/java/google/registry/schema/tld/ReservedListDaoTest.java
- core/src/test/java/google/registry/schema/tmch/ClaimsListDaoTest.java
- core/src/test/java/google/registry/testing/InjectRule.java
Made InjectRule and EntityTestCase work with both JUnit4 and 5.
Note that "@RunWith(JUnit4.class)" is no longer needed on
JUnit4 test classes. Therefore, its removal from EntityTestCase
has no impact on child classes. All of them are still included in
tests.
Migrated remaining member classes in SqlIntegrationTestSuite to JUnit5.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/550)
> Migrate SqlIntegrationTestSuite members  to Junit5

- core/src/nonprod/java/google/registry/tools/DumpGoldenSchemaCommand.java
On Arch Linux, DumpGoldenSchemaCommandTest failed due to the follow
error:
java.lang.RuntimeException: Container.ExecResult(exitCode=1, stdout=, stderr=pg_dump: [archiver] could not open output file "/tmp/pg_dump.out": Is a directory)
However I cannot figure out why this permission error happens, as the
docker command is executed as root. Saving the pg_dump output to a
temporary file and copy it over the mapped file works, so I don't
know...
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/552)
> Add a Test workaround for certain Linux distro

- core/src/main/java/google/registry/tools/CheckDomainCommand.java
- core/src/main/resources/google/registry/tools/soy/DomainCheck.soy
- core/src/test/java/google/registry/tools/CheckDomainCommandTest.java
- core/src/test/resources/google/registry/tools/server/domain_check_fee_allocationtoken.xml
This isn't strictly necessary and can be done via the raw EPP xml command, but it'll make things easier to test.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/556)
> Allow a --token option when checking a domain

- core/src/test/java/google/registry/model/EntityTestCase.java
- core/src/test/java/google/registry/model/domain/DomainBaseSqlTest.java
- core/src/test/java/google/registry/model/registry/RegistryLockDaoTest.java
- core/src/test/java/google/registry/schema/cursor/CursorDaoTest.java
- core/src/test/java/google/registry/schema/registrar/RegistrarDaoTest.java
- core/src/test/java/google/registry/schema/tld/PremiumListDaoTest.java
- core/src/test/java/google/registry/testing/AppEngineRule.java
Only members of SqlIntegrationTestSuite should enable the check,
which incurs per-test overhead.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/555)
> Disable JpaEntityCoverageCheck by default

- core/build.gradle
No sensitve data exposed.
Added a todo to modify the release process and stop
building the foss jar on the merged repo.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/558)
> Exclude proxy configs from the FOSS jar

- core/src/main/java/google/registry/persistence/converter/VKeyConverter.java
- core/src/test/java/google/registry/persistence/converter/VKeyConverterTest.java
Implement a SQL converter that can be used for VKey objects.
Caveats:
- This only works with string columns (there's an excellent chance that all of
our VKeys will use SQL string columns).
- Using this dpesn't establish a foreign key constraint between the referenced
type (the "T" in VKey<T>) and the entity itself: this needs to be
defined manually in the schema.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/538)
> Implement VKeyConverter

- core/src/main/java/google/registry/persistence/EntityCallbacksListener.java
- core/src/main/resources/META-INF/orm.xml
- core/src/test/java/google/registry/persistence/EntityCallbacksListenerTest.java
This PR added a listener class to invoke entity callbacks in cases where Hibernate doesn't invoke the callback as expected.
JPA defines a few annotations, e.g. `@PostLoad`, that we can use for the application to react to certain events that occur inside the persistence mechanism. However, Hibernate only supports a few basic use cases, e.g. defining a `@PostLoad` method directly in an `Entity` class or in an `Embeddable` class. If the annotated method is defined in an `Embeddable` class that is a property of another `Embeddable` class, or it is defined in a parent class of the `Embeddable` class, Hibernate doesn't invoke it.
See Also [HHH-13316](https://hibernate.atlassian.net/browse/HHH-13316)
--- …
> Add a listener to invoke entity callbacks

- core/build.gradle
- core/src/test/java/google/registry/schema/integration/SqlIntegrationTestSuite.java
JUnit 5 runner does not support @BeforeAll and @AfterAll declared
in the Suite class (as opposed to the member classes). However,
staying with the JUnit 4 suite runner would prevent any member
classes from migrating to JUnit 5.
We use a hack to invoke suite-level set up and teardown from tests.
This change is safe in that if the JUnit 5 runner implementation changes
behavior, we will only see false alarms.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/560)
> Hack to call setup and teardown in JUnit5 suite

- core/src/test/java/google/registry/model/domain/DomainBaseSqlTest.java
- core/src/test/java/google/registry/schema/registrar/RegistrarDaoTest.java
- core/src/test/java/google/registry/testing/DatastoreEntityExtension.java
- core/src/test/java/google/registry/tools/CompareDbBackupsTest.java
Defined an extension that sets up a fake AppEngine environment
so that Datastore entities can be instantiated.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/559)
> Allow Entity instantiation without AppEngineRule

- core/src/main/java/google/registry/model/domain/DomainBase.java
- core/src/main/java/google/registry/model/host/HostResource.java
- core/src/main/resources/META-INF/persistence.xml
- core/src/test/java/google/registry/model/domain/DomainBaseSqlTest.java
- db/src/main/resources/sql/flyway/V22__update_ns_hosts.sql
- db/src/main/resources/sql/schema/db-schema.sql.generated
- db/src/main/resources/sql/schema/nomulus.golden.sql
Sending this pull request to illustrate how VKey persistence will work in the context of the DomainBase.nsHosts field.
This change depends on #538, which is not yet submitted, so that portion of the PR should go away once we get past that PR.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/541)
> Persist DomainBase.nsHosts VKeys to SQL 

- core/src/main/java/google/registry/model/domain/DomainBase.java
- core/src/main/java/google/registry/model/registrar/Registrar.java
- core/src/main/java/google/registry/schema/replay/DatastoreAndSqlEntity.java
- core/src/main/java/google/registry/schema/replay/DatastoreEntity.java
- core/src/main/java/google/registry/schema/replay/SqlEntity.java
- core/src/test/java/google/registry/schema/replay/EntityTest.java
These will be used when replaying transactions from either the Datastore
commit logs or the SQL Transaction objects.
When Datastore is the primary database, we will read in the
Datastore commit logs, convert each saved entity to however many SQL
entities, then save those SQL entities in SQL.
When SQL is the primary database, we will read in the SQL objects from a
yet-to-be-created SQL table, convert them to however many Datastore
entities, then save those Datastore entities in Datastore.
This PR includes an example of how this will work for entities that are
saveable in both SQL and Datastore (the simple case).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/562)
> Add SqlEntity and DatastoreEntity interfaces

- appengine_war.gradle
We added a step to explicitly copy persistence.xml because for some reason it
wasn't originally getting deployed to app-engine, resulting in failures on
startup.  However, this file is now included in core.jar and we are now
getting a warning about multiple persistence units with the same name as it
reads the files from both the filesystem and core.jar.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/563)
> Remove separate deployment of persistence.xml

- core/src/main/java/google/registry/persistence/converter/VKeyConverter.java
- core/src/main/java/google/registry/tools/DomainLockUtils.java
- core/src/main/java/google/registry/tools/RegistryCli.java
- core/src/main/java/google/registry/ui/server/RegistrarFormFields.java
- core/src/nonprod/java/google/registry/tools/DumpGoldenSchemaCommand.java
- core/src/test/java/google/registry/persistence/converter/VKeyConverterTest.java
- core/src/test/java/google/registry/tools/RegistrarContactCommandTest.java
- core/src/test/java/google/registry/tools/RegistryToolTest.java
This occurred when an environment was specified but without a subcommand. Now,
the list of valid subcommands is outputted instead of seeing a generic NPE.
This also makes some formatting changes in other files that were causing the
incremental format check to fail.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/564)
> Don't NPE when nomulus tool is run without a subcommand

- core/src/main/java/google/registry/tools/RenewDomainCommand.java
- core/src/test/java/google/registry/flows/domain/DomainRenewFlowTest.java
- core/src/test/java/google/registry/tools/RenewDomainCommandTest.java
This means that a superuser can renew a domain and have the associated history
entry, one time billing event, and renewal grace period be recorded against a
specified registrar rather than the owning registrar of the domain.  This is
useful to e.g. renew a domain for free by "charging" the renewal to the
registry's fake registrar.  Since the grace period is written to the specified
cliend id as well, if the actual registrar deletes the domain, they don't get
back the money that they didn't pay in the first place.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/567)
> Allow the `nomulus renew_domain` command to specify the client ID

- config/presubmits.py
- core/src/main/java/google/registry/model/ofy/ObjectifyService.java
- core/src/test/java/google/registry/backup/ExportCommitLogDiffActionTest.java
- core/src/test/java/google/registry/backup/RestoreCommitLogsActionTest.java
- core/src/test/java/google/registry/model/CreateAutoTimestampTest.java
- core/src/test/java/google/registry/model/ImmutableObjectTest.java
- core/src/test/java/google/registry/model/UpdateAutoTimestampTest.java
- core/src/test/java/google/registry/model/ofy/OfyCommitLogTest.java
- core/src/test/java/google/registry/model/translators/CommitLogRevisionsTranslatorFactoryTest.java
- core/src/test/java/google/registry/persistence/VKeyTest.java
- core/src/test/java/google/registry/testing/AppEngineRule.java
- core/src/test/java/google/registry/testing/AppEngineRuleTest.java
- core/src/test/java/google/registry/testing/TestObject.java
Objectify siliently replaces current registration of a given kind
when another class is registered for this kind. There are
several TestObject classes in the current code base, which by
default are all mapped to the same kind.
Tests have only been flaky because impacted tests need to run
in specific orders for failures to happen. Using multiple executors
in Gradle also reduced the likely hood of errors. To reproduce the
problem run the following tests in order (e.g., by putting them in
a test suite):
1. ExportCommitLogDiffActionTest
2. CreateAutoTimestampTest
3. RestoreCommitLogsActionTest
In this PR, we
- Made sure all entities have unique kinds.
- Made all test entities register with AppEngineRule instead of directly
with ObjectifyService.
- Added code in AppEngineRule to check for …
> Fix flaky tests due to Entity name conflicts

- core/src/main/java/google/registry/config/RegistryConfig.java
- core/src/main/java/google/registry/config/RegistryConfigSettings.java
- core/src/main/java/google/registry/config/files/default-config.yaml
- core/src/main/java/google/registry/persistence/PersistenceModule.java
- core/src/test/java/google/registry/persistence/transaction/JpaTransactionManagerRule.java
Reverts commit d8066ca752ec662249a344a2cc13199029121836 because it caused b/155383029.
This PR reduced the `hikariMaximumPoolSize` to 10 based on the fact that our Cloud SQL instance can only handle 600 concurrent connections and we can have ~50 instances running at the same time during peak.
Also, To mitigate the issue that #557 tried to fix, `hikariMinimumIdle` was increased from 0 to 1.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/573)
> Revert "Remove minimumIdle config in HikariCP (#557)"

- core/src/main/java/google/registry/model/ofy/DatastoreTransactionManager.java
- core/src/main/java/google/registry/persistence/transaction/JpaTransactionManagerImpl.java
- core/src/main/java/google/registry/persistence/transaction/TransactionManager.java
- core/src/test/java/google/registry/model/contact/ContactResourceTest.java
- core/src/test/java/google/registry/persistence/EntityCallbacksListenerTest.java
- core/src/test/java/google/registry/persistence/transaction/JpaTransactionManagerImplTest.java
- core/src/test/java/google/registry/schema/registrar/RegistrarDaoTest.java
- core/src/test/java/google/registry/tools/UpdateRegistrarCommandTest.java
Since we rarely (if ever) want to check the result of a single element load,
make TransactionManager.load(VKey) return non-optional, non-nullable and just
throw a NoSuchElementException if the entity is not found.
Also add a maybeLoad() that does return an optional in case we ever want to do
this (exists() should suffice for an existence check).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/576)
> Improve return value semantices for tm().load()

- core/build.gradle
On certain machines (one of mine) the outcastTest consistently fails due
to the following error:
java.lang.NoClassDefFoundError: Could not initialize class
google.registry.persistence.transaction.JpaTestRules$JpaIntegrationTestRule
If I reduce maxparallelForks to 3 it consistently passes. This issue was
mentioned here:
https://discuss.gradle.org/t/junit-test-fails-with-noclassdeffounderror-only-when-maxparallelforks-1/6047
But this post was 8 years old and no solution was identified.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/571)
> Fix test failures on certain machines

- core/src/main/java/google/registry/flows/domain/DomainDeleteFlow.java
- core/src/test/java/google/registry/flows/EppLifecycleDomainTest.java
- core/src/test/java/google/registry/flows/EppTestCase.java
- core/src/test/java/google/registry/flows/domain/DomainDeleteFlowTest.java
- core/src/test/java/google/registry/tools/EppLifecycleToolsTest.java
- core/src/test/resources/google/registry/flows/domain_info_response_addperiod_wildcard.xml
- core/src/test/resources/google/registry/flows/domain_info_response_graceperiod.xml
- core/src/test/resources/google/registry/flows/domain_info_response_graceperiod_add_and_renew.xml
- core/src/test/resources/google/registry/flows/domain_info_response_redemptionperiod_wildcard.xml
This doesn't make any change at the time of the domain deletion itself, but it
will matter if the domain is then undeleted, because we need to know what
expiration date to restore, and if there were any renew or autorenew charges
that were refunded by the deletion because they were in a grace period, they
shouldn't be coming back during the restore.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/579)
> Reflect refunded billing events on deletion in expiration time

- core/src/main/java/google/registry/model/ofy/DatastoreTransactionManager.java
- core/src/main/java/google/registry/persistence/transaction/JpaTransactionManager.java
- core/src/main/java/google/registry/persistence/transaction/JpaTransactionManagerImpl.java
- core/src/main/java/google/registry/persistence/transaction/TransactionManager.java
- core/src/test/java/google/registry/model/ofy/DatastoreTransactionManagerTest.java
- core/src/test/java/google/registry/persistence/transaction/JpaTransactionManagerImplTest.java
In the course of this:
- Make assertDelete() specific to JpaTransactionManager, remove the return
value from delete()
- Converter "in transaction" assertion to IllegalStateException, which is less
JPA specific.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/581)
> Implement all DatastoreTransactionManager methods

- core/build.gradle
- core/src/main/java/google/registry/persistence/transaction/TransactionManagerFactory.java
- core/src/test/java/google/registry/persistence/transaction/JpaTransactionManagerImplTest.java
- core/src/test/java/google/registry/persistence/transaction/TransactionManagerTest.java
- core/src/test/java/google/registry/testing/AppEngineRule.java
- core/src/test/java/google/registry/testing/DualDatabaseTest.java
- core/src/test/java/google/registry/testing/DualDatabaseTestInvocationContextProvider.java
This PR added a JUint 5 extension `DualDatabaseTestInvocationContextProvider` which can execute annotated test twice against different databases, i.g. Datastore and PostgresQL.
This helps us easily expand the existing Datastore tests to work with both Datastore and PostgresQL.
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/588)
> Add JUnit5 extension to run test twice against different databases

- core/src/main/java/google/registry/request/HttpException.java
Normal HttpException logs at INFO because they usually do not indicate
anything out of the ordinary and is meant to convey to the client that
there is some expected error. However InternalServerErrorException is
something that we do care about being alerted for so we log it at SEVERE.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/585)
> Log InternalServerErrorException at SEVERE

- core/src/main/java/google/registry/tools/CompareDbBackups.java
- core/src/main/java/google/registry/tools/LevelDbLogReader.java
- core/src/main/java/google/registry/tools/RecordAccumulator.java
- core/src/test/java/google/registry/tools/LevelDbFileBuilderTest.java
- core/src/test/java/google/registry/tools/LevelDbLogReaderTest.java
- core/src/test/java/google/registry/tools/RecordAccumulatorTest.java
Made LevelDbLogReader an iterator over a LevelDb data stream,
Reducing memory footprint which is important when used in a
Dataflow pipeline.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/593)
> Read LevelDb incrementally

- core/src/main/java/google/registry/tools/LevelDbLogReader.java
- core/src/test/java/google/registry/tools/LevelDbLogReaderTest.java
Input channel should be closed when all data has been read.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/594)
> Close input channel in LevelDbLogReader

- core/src/main/java/google/registry/model/ofy/ObjectifyService.java
- core/src/main/java/google/registry/model/translators/VKeyTranslatorFactory.java
EntityClasses.ALL_CLASSES has all of our registered entities so
we can use it to initialize VKeyTranslatorFactory.classRegistry
to avoid adding them one by one.
Also, this PR changed to use Key.getKind() to get the kind of
the entity to solve the problem that when the entity class
is an inner class, its kind should still be the class name
instead of OuterClass$InnerClass.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/595)
> Add all existing entities to VKeyTranslatorFactory

- core/src/main/java/google/registry/export/BigqueryPollJobAction.java
- core/src/test/java/google/registry/export/BigqueryPollJobActionTest.java
If the import from Datastore to BigQuery fails, there is no point
enqueuing a job to update the snapshot view.
Also when there's an error updating the snapshot view, log it at severe
level. The HTTP exception thrown is logged at info and triggers a retry
implicitly. I'm not sure if we want this behavior though. Do we want to
retry upon snapshot updating failures? Unless the failurs are transient,
retrying doesn't help. In our case the failure (End of time out of range
in Standard SQL) is not transient.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/578)
> Do not enqueue update snapshot task if import fails

- core/src/test/java/google/registry/persistence/transaction/JpaTestRulesSqlLoggingTest.java
Verifies that SQL statements are logged by Hibernate when
configured to do so.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/598)
> Add a test for SQL logging config

- core/src/main/java/google/registry/tools/ComparableEntity.java
- core/src/main/java/google/registry/tools/CompareDbBackups.java
- core/src/main/java/google/registry/tools/EntityWrapper.java
- core/src/main/java/google/registry/tools/RecordAccumulator.java
- core/src/test/java/google/registry/tools/CompareDbBackupsTest.java
- core/src/test/java/google/registry/tools/EntityWrapperTest.java
- core/src/test/java/google/registry/tools/LevelDbFileBuilder.java
- core/src/test/java/google/registry/tools/LevelDbFileBuilderTest.java
- core/src/test/java/google/registry/tools/RecordAccumulatorTest.java
Builder now can directly work with Datastore Entity objects.
No need to wrap data in ComparableEntity.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/599)
> Refactor LevelDbFileBuilder to accept DS Entity

- core/src/main/java/google/registry/flows/ResourceFlowUtils.java
- core/src/main/java/google/registry/flows/domain/DomainCreateFlow.java
- core/src/main/java/google/registry/flows/domain/DomainFlowUtils.java
- core/src/main/java/google/registry/flows/domain/DomainUpdateFlow.java
- core/src/main/java/google/registry/model/EppResource.java
- core/src/main/java/google/registry/model/EppResourceUtils.java
- core/src/main/java/google/registry/model/domain/DomainCommand.java
- core/src/main/java/google/registry/model/index/ForeignKeyIndex.java
- core/src/main/java/google/registry/rdap/RdapDomainSearchAction.java
- core/src/main/java/google/registry/tools/CommandUtilities.java
- core/src/main/java/google/registry/tools/GetHistoryEntriesCommand.java
- core/src/main/java/google/registry/tools/ResaveEppResourceCommand.java
- core/src/main/java/google/registry/whois/DomainWhoisResponse.java
- core/src/test/java/google/registry/flows/host/HostUpdateFlowTest.java
- core/src/test/java/google/registry/model/EppResourceTest.java
- core/src/test/java/google/registry/model/index/ForeignKeyIndexTest.java
- core/src/test/resources/google/registry/model/schema.txt
Replace Ofy calls with TransactionManager for most interactions involving
hosts and contacts.  In the course of this, also convert ForeignKeyIndex and
the EppResourceCache.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/603)
> Use TransactionManager for hosts and contacts

- core/src/main/java/google/registry/beam/initsql/BackupPaths.java
- core/src/main/java/google/registry/beam/initsql/ExportLoadingTransforms.java
- core/src/main/java/google/registry/beam/initsql/README.md
- core/src/test/java/google/registry/beam/initsql/BackupPathsTest.java
- core/src/test/java/google/registry/beam/initsql/BackupTestStore.java
- core/src/test/java/google/registry/beam/initsql/BackupTestStoreTest.java
- core/src/test/java/google/registry/beam/initsql/ExportloadingTransformsTest.java
- core/src/test/java/google/registry/testing/AppEngineRule.java
- core/src/test/java/google/registry/tools/LevelDbFileBuilder.java
Created a tool that can export from a test instance of Datastore.
Defined Beam pipeline transforms for loading raw records back from
the export.
This is the first part of the effort to create a consistent snapshot
of Datastore. The next step is to load entity records from CommitLog
files.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/605)
> Load raw records from Datastore export

- core/src/main/java/google/registry/model/ofy/DatastoreTransactionManager.java
- core/src/main/java/google/registry/persistence/transaction/JpaTransactionManagerImpl.java
- core/src/main/java/google/registry/persistence/transaction/TransactionManager.java
- core/src/test/java/google/registry/persistence/transaction/TransactionManagerTest.java
This PR also cleaned up the `TransactionManagerTest` by extracting some helper functions and removing some duplicate `fakeClock.advanceOneMilli()` calls.
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/604)
> Add deleteAll method to TransactionManager

- core/src/test/java/google/registry/testing/DualDatabaseTestInvocationContextProviderTest.java
Added a simple test to verify that `@DualDatabaseTest` extension executes each `@TestTemplate` test twice with different databases.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/606)
> Add test to verify the behavior of @DualDatabaseTest

- core/src/main/java/google/registry/model/domain/DomainBase.java
Given that we currently have no way of reconstituting a symmetric key
from the asymmetric key (or at least, we don't have a 100% reliable way
of doing so) it's best to keep keys as asymmetrical, referring to the
correct database. That way, we don't get situations where we cannot
compare equality of two keys due to one being asymmetrical and one being
symmetrical.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/611)
> Only use asymmetric VKeys for EPP resources

- core/src/test/java/google/registry/persistence/transaction/JpaTestRules.java
- core/src/test/java/google/registry/persistence/transaction/JpaTransactionManagerRule.java
We silently made `JpaUnitTestRule` bring in the nomulus tables when initializing the test db instance. This was not a problem until I tried to merge the `ReservedList` entities. The problem was that the merged `ReservedList` entity has a field `Key<EntityGroupRoot> parent = getCrossTldKey();` which requires the Datastore API environment when instantiating its object, so any test using `JpaUnitTestRule` will be broken because the nomulus schema was added to the test and Hibernate tried to instantiate the entity class. Removing the entity class from the `JpaUnitTestRule` fixed the problem.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/613)
> Make JpaUnitTestRule not depend on the nomulus schema

- networking/src/main/java/google/registry/networking/handler/SslServerInitializer.java
It appears that most client certificates are RSA certs, but we should
make sure that is indeed the case. Print out the strength of the cert
if it is RSA.
Also adds supports for TLS 1.3 and print out the supported cipher suites.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/622)
> Log client certificate type and length

- core/src/main/java/google/registry/ui/server/registrar/RegistryLockPostAction.java
- core/src/test/java/google/registry/ui/server/registrar/RegistryLockPostActionTest.java
The app doesn't know about any external configuration that may point to
this app, so there's no way of finding out that, for instance,
registry.google points to the app. Thus, we have to use what the user
gives us so that, in our case, the registry-lock verification
emails can point to https://registry.google/registry-lock-verify instead
of https://domain-registry.appspot.com/registry-lock-verify. The former
is used by clients / users to authenticate, and unfortunately
authenticating on registry.google does not give authentication to
domain-registry.apspot.com.
Tested using the RDAP code that uses getServerName() -- in that case, if
you access registry.google/rdap/<>, it uses registry.google in the URLs
but if you use domain-registry.appspot.com/rdap/<>, it uses …
> Use the requested server host when creating the registry lock verification URL

- core/src/main/java/google/registry/model/domain/DomainBase.java
- core/src/main/java/google/registry/model/translators/VKeyTranslatorFactory.java
- core/src/test/java/google/registry/model/translators/VKeyTranslatorFactoryTest.java
When translating from a datastore Key to a VKey, see if the "kind" class
contains a createVKey(com.googlecode.objectify.Key) static method and if it
does, use it to construct a symmetric VKey instead of simply creating an
objectify-sided asymmetric VKey.
As a test case for this, implement the createVKey() static function for
DomainBase.  Also, create unit tests for VKeyTranslatorFactory, which
continues to house the functionality.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/625)
> Allow class-specific creation of symmetric VKeys

- core/src/main/java/google/registry/rdap/UpdateRegistrarRdapBaseUrlsAction.java
- core/src/test/java/google/registry/rdap/UpdateRegistrarRdapBaseUrlsActionTest.java
The existing code only does cookie processing on the _first_ Set-Cookie
header.  Therefore, if the "id" cookie used for authentication is defined in
anything other than the first Set-Cookie header (as it now is), we don't find
it.
Replace the cookie processing stanza with a line that processes all cookies in
all Set-Cookie headers.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/630)
> Fix cookie processing for RDAP URL update

- core/src/main/java/google/registry/persistence/transaction/JpaTransactionManagerImpl.java
- core/src/test/java/google/registry/persistence/transaction/TransactionManagerTest.java
For all `JpaTransactionManager.transactNew()` methods, we just call `JpaTransactionManager.transact()` to reuse the current transaction if it exists. This is because Postgresql's transaction doesn't have the limitation that Datastore's transaction has(See [here](https://cloud.google.com/datastore/docs/concepts/transactions#what_can_be_done_in_a_transaction)).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/633)
> Implement remaining methods in JpaTransactionManager

- core/src/main/java/google/registry/model/ofy/Ofy.java
- core/src/main/java/google/registry/persistence/VKey.java
- core/src/main/java/google/registry/persistence/transaction/Transaction.java
- core/src/test/java/google/registry/persistence/transaction/TransactionTest.java
Implement Transaction, which encapsulates a sequence of datastore mutations
that can be serialized and written to the Cloud SQL Transaction table and
subsequently replayed to Datastore from a backend cron job.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/614)
> Implement a persistable Transaction object

- core/src/main/java/google/registry/flows/domain/DomainCheckFlow.java
- core/src/main/java/google/registry/flows/domain/DomainFlowUtils.java
- core/src/main/java/google/registry/flows/domain/DomainInfoFlow.java
- core/src/test/java/google/registry/flows/domain/DomainCheckFlowTest.java
- core/src/test/resources/google/registry/flows/domain/domain_check_allocationtoken_fee_specificuse.xml
- core/src/test/resources/google/registry/flows/domain/domain_check_allocationtoken_fee_specificuse_response.xml
- core/src/test/resources/google/registry/flows/domain/domain_check_duplicates.xml
When the registrar passes the fee extension, this shows the price of the domain
on a check command for reserved domains if the provided allocation token is a
match. Of course, the price is already always displayed on non-reserved names
(regardless of whether the specific provided token is a match or not).
This affects domain checks only; the price is already always displayed on domain
creates because you already by definition have access to register the domain in
question.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/632)
> Show price of reserved domains when using matching allocation token

- core/src/test/java/google/registry/persistence/transaction/TransactionManagerTest.java
- core/src/test/java/google/registry/persistence/transaction/TransactionTest.java
- core/src/test/java/google/registry/testing/AppEngineRuleTest.java
Overrode the 'kind' of two test entities to prevent name conflicts.
Tests are flaky because of this.
Added a check in AppEngineRuleTest to check for conflicting kinds.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/636)
> Fix flakiness caused by ofy entity name conflict

- core/src/main/java/google/registry/model/transfer/TransferData.java
- core/src/test/java/google/registry/model/poll/PollMessageTest.java
Added a test to verify that `jpaTm` can load the entity from a VKey with polymorphic type. For example, when we want to load a `PollMessage.OneTime` entity, we can use `VKey.createSql(PollMessage.class, id)`. Hibernate is able to figure out the exact type of the poll message by checking the `type` column in the schema. This makes sure that the vkey reconstructed by `VKeyTranslatorFactory` would not cause any problem when used for Cloud SQL.
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/642)
> Add a test to verify JPA supports polymorphic VKey

- core/src/main/java/google/registry/flows/domain/DomainCheckFlow.java
- core/src/main/java/google/registry/flows/domain/DomainFlowUtils.java
- core/src/main/java/google/registry/flows/domain/DomainInfoFlow.java
- core/src/main/java/google/registry/flows/domain/DomainPricingLogic.java
- core/src/main/java/google/registry/flows/domain/DomainRestoreRequestFlow.java
- core/src/test/java/google/registry/flows/domain/DomainInfoFlowTest.java
- core/src/test/java/google/registry/flows/domain/DomainRestoreRequestFlowTest.java
- core/src/test/resources/google/registry/flows/domain/domain_info_fee_restore_response.xml
- core/src/test/resources/google/registry/flows/domain/domain_info_fee_restore_response_no_renewal.xml
- core/src/test/resources/google/registry/flows/domain/domain_info_fee_restore_response_with_renewal.xml
- core/src/test/resources/google/registry/flows/domain/domain_update_restore_request_fee_no_renewal.xml
- core/src/test/resources/google/registry/flows/domain/domain_update_restore_request_premium_no_renewal.xml
- core/src/test/resources/google/registry/flows/domain/domain_update_restore_request_response_fee_no_renewal.xml
This is a fix on top of #632 so that domain restore commands don't require
acking an illusory renewal fee for 1 year when that isn't actually happening
(i.e. if the domain isn't yet past its original expiration).
Unfortunately, there's still a problem remaining wherein the restore fee on a
domain check will always include the additional year even if it's not
necessary. We don't have a good solution to that. Also note that in versions of
the fee extension more recent than 0.6, the fee extension cannot be passed on a
domain info command at all, so the domain check command is the only way you have
to determine what the restore fee should be. So we definitely do want to get
that right so that the apparent restore fee on a check is the same as the actual
restore fee when running the restore …
> Don't expect a renewal fee on restores when one isn't due

- core/src/main/java/google/registry/beam/initsql/BackupPaths.java
- core/src/main/java/google/registry/beam/initsql/BeamJpaModule.java
- core/src/main/java/google/registry/beam/initsql/CloudSqlCredentialDecryptor.java
- core/src/main/java/google/registry/beam/initsql/SqlAccessInfo.java
- core/src/main/java/google/registry/beam/initsql/Transforms.java
- core/src/main/java/google/registry/keyring/kms/KmsConnection.java
- core/src/main/java/google/registry/persistence/PersistenceModule.java
- core/src/test/java/google/registry/beam/initsql/BackupPathsTest.java
- core/src/test/java/google/registry/beam/initsql/BeamJpaModuleTest.java
- core/src/test/java/google/registry/persistence/PersistenceModuleTest.java
- core/src/test/java/google/registry/persistence/transaction/JpaTransactionManagerRule.java
- java_common.gradle
Added modules and utilities to create JpaTransactionManager in BEAM
pipelines.
Not wanting to set up AppEngine Remote API to access Keyring in the
Datastore, we instead use the credential files in GCS, which are
used by Spinnaker/Cloud Build and desktop access. Added utility
to download, decrypt, and parse the file. Also added/modified dagger
modules.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/639)
> Set up JpaTransactionManager in BEAM pipelines

- core/src/main/java/google/registry/batch/DeleteContactsAndHostsAction.java
- core/src/main/java/google/registry/batch/RefreshDnsOnHostRenameAction.java
- core/src/main/java/google/registry/model/billing/BillingEvent.java
- core/src/main/java/google/registry/model/contact/ContactResource.java
- core/src/main/java/google/registry/model/domain/DesignatedContact.java
- core/src/main/java/google/registry/model/domain/DomainBase.java
- core/src/main/java/google/registry/model/domain/token/AllocationToken.java
- core/src/main/java/google/registry/model/host/HostBase.java
- core/src/main/java/google/registry/model/host/HostHistory.java
- core/src/main/java/google/registry/model/host/HostResource.java
- core/src/main/java/google/registry/model/poll/PollMessage.java
- core/src/main/java/google/registry/model/reporting/HistoryEntry.java
- core/src/main/java/google/registry/model/translators/VKeyTranslatorFactory.java
- core/src/main/java/google/registry/persistence/VKey.java
- core/src/main/java/google/registry/rdap/RdapDomainSearchAction.java
- core/src/test/java/google/registry/flows/EppTestCase.java
- core/src/test/java/google/registry/flows/domain/DomainTransferApproveFlowTest.java
- core/src/test/java/google/registry/flows/domain/DomainTransferRequestFlowTest.java
- core/src/test/java/google/registry/model/contact/ContactResourceTest.java
- core/src/test/java/google/registry/model/domain/DomainBaseTest.java
- core/src/test/java/google/registry/model/host/HostResourceTest.java
- core/src/test/java/google/registry/model/transfer/TransferDataTest.java
- core/src/test/java/google/registry/model/translators/VKeyTranslatorFactoryTest.java
- core/src/test/java/google/registry/persistence/VKeyTest.java
Replace all of the calls that currently create asymmetric (ofy-only) VKeys with calls to do complete symmetric key creation.  Add code to VKeyTranslatorFactory that will automatically create symmetric keys from non-hierarchical ofy keys, removing the static createVKey() method from classes that don't need it and adding it to the hierarchical (BillingEvent and PollMessage) types.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/641)
> Convert all VKeys to symmetric VKeys

- core/src/main/java/google/registry/model/contact/ContactResource.java
Hibernate complained that `ContactResource.getTransferData()` should not be
final:
```shell
WARN: HHH000305: Could not create proxy factory
for:google.registry.model.contact.ContactResource
org.hibernate.HibernateException: Getter methods of lazy classes cannot
be final: google.registry.model.contact.ContactResource#getTransferData
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/645)
> Fix a warning from Hibernate

- core/src/main/java/google/registry/persistence/transaction/TransactionManagerFactory.java
- core/src/main/java/google/registry/tools/RegistryCli.java
- core/src/main/java/google/registry/tools/RegistryToolComponent.java
- core/src/test/java/google/registry/persistence/transaction/JpaTransactionManagerRule.java
During Cloud SQL migration, Cloud SQL password setup in Registry
server requires a few tool commands. Such commands must be able
to run before Cloud SQL is configured.
In this change, we deplay SQL credential loading until access is
needed.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/643)
> Delay SQL availability check during Tool start

- core/src/main/java/google/registry/beam/invoicing/sql/billing_events.sql
- core/src/main/java/google/registry/model/registry/Registry.java
- core/src/main/java/google/registry/tools/CreateOrUpdateTldCommand.java
- core/src/test/resources/google/registry/beam/invoicing/billing_events_test.sql
- core/src/test/resources/google/registry/model/schema.txt
The added property will by default be `null` for existing entities and `false` for new entities. We could write a temporary MapReduce to set it to false for all existing ones, but it seems easier to just modify the query to account for the nullness of the column. The need to check for null won't exist once we migrate the `Registry` entity to Cloud SQL.
TESTED=deployed to alpha, set the property for tld zombo to true and triggered an export, verified that the column is null for all rows other than the row for zombo.
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/644)
> Add a property in Registry to disable invoicing

- core/src/main/java/google/registry/xml/XmlTransformer.java
- core/src/test/java/google/registry/flows/EppXmlSanitizerTest.java
- core/src/test/java/google/registry/flows/FlowTestCase.java
- core/src/test/java/google/registry/xml/XmlTestUtils.java
This fixes the double-spacing bug with logged EPP XML on App Engine that started
appearing after App Engine switching from using Java 8 to Java 11. Java 9 made
some changes to XML Transformer classes that needed a little bit of work to
accommodate.
This also fixes the unit tests that were failing in Java 11 (all of which were
related to said XML Transformer changes).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/649)
> Make nomulus compatible with Java 11

- buildSrc/src/main/java/google/registry/gradle/plugin/CoverPageGenerator.java
- buildSrc/src/main/java/google/registry/gradle/plugin/GcsPluginUtils.java
- core/src/main/java/google/registry/flows/domain/token/AllocationTokenCustomLogic.java
- core/src/main/java/google/registry/model/domain/rgp/GracePeriodStatus.java
- core/src/main/java/google/registry/model/registry/Registries.java
- core/src/main/java/google/registry/model/registry/label/ReservedList.java
- core/src/main/java/google/registry/persistence/converter/StringMapConverterBase.java
- core/src/main/java/google/registry/persistence/converter/TimedTransitionPropertyConverterBase.java
- core/src/main/java/google/registry/reporting/icann/IcannReportingUploadAction.java
- core/src/main/java/google/registry/schema/cursor/CursorDao.java
- core/src/main/java/google/registry/tools/SetNumInstancesCommand.java
- core/src/test/java/google/registry/flows/domain/token/AllocationTokenFlowUtilsTest.java
- core/src/test/java/google/registry/testing/AppEngineRuleTest.java
- core/src/test/java/google/registry/tools/GenerateAllocationTokensCommandTest.java
- util/src/main/java/google/registry/util/CollectionUtils.java
This adds an entriesToImmutableMap() collector that can be used in place of
toImmutableMap(Map.Entry::getkey, Map.Entry::getValue()).
It also fixes up some existing calls that use toImmutableMap() when terser
alternatives exist.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/654)
> Make ImmutableMap Stream collect()ion nicer

- core/src/main/java/google/registry/model/reporting/Spec11ThreatMatch.java
- core/src/main/java/google/registry/persistence/converter/Spec11ThreatMatchThreatTypeSetConverter.java
- core/src/main/resources/META-INF/persistence.xml
- core/src/test/java/google/registry/model/reporting/Spec11ThreatMatchTest.java
- core/src/test/java/google/registry/schema/integration/SqlIntegrationTestSuite.java
- db/src/main/resources/sql/flyway/V37__update_spec11threatmatch.sql
- db/src/main/resources/sql/schema/db-schema.sql.generated
- db/src/main/resources/sql/schema/nomulus.golden.sql
Rename the SafeBrowsingThreat table to Spec11ThreatMatch to store generic ThreatMatches from different sources and create a converter for a set of ThreatTypes.
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/650)
> Allow multiple threat types in the Spec11ThreatMatch table

- core/src/main/java/google/registry/model/EppResource.java
- core/src/main/java/google/registry/model/ofy/DatastoreTransactionManager.java
- core/src/main/java/google/registry/persistence/transaction/JpaTransactionManagerImpl.java
- core/src/main/java/google/registry/persistence/transaction/TransactionManager.java
- core/src/main/java/google/registry/rdap/RdapJsonFormatter.java
- core/src/main/java/google/registry/tools/UniformRapidSuspensionCommand.java
- core/src/main/java/google/registry/tools/server/GenerateZoneFilesAction.java
- core/src/test/java/google/registry/persistence/transaction/TransactionManagerTest.java
Use a batched fetch (ofy().load().keys(...)) from datastore in
EppResource.loadCached().
To support this, convert TransactionManager.load(Iterable<VKey>) to accept the
more flexible generic parameters and return a map.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/652)
> Make EppResource.loadCached() use batched fetch

- core/src/main/java/google/registry/rde/RdeStagingMapper.java
- core/src/test/java/google/registry/rde/RdeStagingMapperTest.java
Registrars used for testing and monitoring should not be included
in Data escrow. They also lack the required ianaIdentifier property
and would fail ICANN data validation.
Note that since alpha and crash environments have bad data that
break the RDE process, we need to verify this change in Sandbox.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/655)
> Exclude Test/Monitoring Registrars from escrow

- core/src/main/java/google/registry/backup/AppEngineEnvironment.java
- core/src/main/java/google/registry/beam/initsql/Transforms.java
- core/src/test/java/google/registry/beam/initsql/BeamJpaModuleTest.java
- core/src/test/java/google/registry/beam/initsql/CommitLogTransformsTest.java
- core/src/test/java/google/registry/beam/initsql/ExportloadingTransformsTest.java
- core/src/test/java/google/registry/beam/initsql/InitSqlTestUtils.java
- core/src/test/java/google/registry/beam/initsql/LoadDatastoreSnapshotTest.java
Defined a composite transform that loads from a Datastore export and
concurrent CommitLog files, identify entities that still exist at the
end of the time window, and resolve their latest states in the window.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/660)
> Load Datastore snapshot from backup files

- core/src/main/java/google/registry/beam/initsql/BeamJpaModule.java
- core/src/main/java/google/registry/beam/initsql/CloudSqlCredentialDecryptor.java
- core/src/main/java/google/registry/beam/spec11/Spec11Pipeline.java
- core/src/main/java/google/registry/keyring/kms/KmsConnectionImpl.java
- core/src/main/java/google/registry/keyring/kms/KmsKeyring.java
- core/src/main/java/google/registry/keyring/kms/KmsModule.java
- core/src/main/java/google/registry/keyring/kms/KmsUpdater.java
- core/src/main/java/google/registry/persistence/PersistenceModule.java
- core/src/main/java/google/registry/tools/AuthModule.java
- core/src/main/java/google/registry/tools/RegistryCli.java
- core/src/main/java/google/registry/tools/RegistryToolComponent.java
This allows us to also inject the BeamJpaModule into RegistryTool, which
allows us to use the SocketJpaTransactionManager in Beam pipelines.
Some side effects of this include:
- duplication of KMS connections -- one standard, one Beam
- duplication of the creation of the partial Hibernate SQL configs
- removal of ambiguity between credentialFileName, credentialFilename,
and credentialFilePath -- we now use the latter.
- Performing the credential null check when instantiating the SQL
connection rather than when instantiating the module object. See the code
comments for more details on this.
I verified that this compiles and the tests run successfully when
injecting a @SocketFactoryJpaTm into a Beam pipeline.
--- …
> Disambiguate injected Cloud SQL parameter names

- core/src/main/java/google/registry/flows/poll/PollAckFlow.java
- core/src/main/java/google/registry/flows/poll/PollFlowUtils.java
- core/src/main/java/google/registry/tools/AckPollMessagesCommand.java
- core/src/test/java/google/registry/tools/AckPollMessagesCommandTest.java
This PR expanded `AckPollMessagesCommand` to support acknowledging `Autorenew` poll messages(see [here](https://b.corp.google.com/issues/159207551#comment9) for more context), and it also changed some of the `ofy()` calls to `tm()` in relevant code.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/647)
> Expand AckPollMessagesCommand to ack PollMessage.Autorenew

- core/src/main/java/google/registry/beam/invoicing/BillingEvent.java
- core/src/test/java/google/registry/beam/invoicing/BillingEventTest.java
- core/src/test/java/google/registry/beam/invoicing/InvoicingPipelineTest.java
The PO number header was added during the beam migration but we forgot
to print the actual data in the corresponding column. This resulted in a
misalignment of columns in the detailed report.
This PR fixes it. Note that we cannot drop PO number from the header (as is not
useful in the detailed report) because the header represents all fields
that are to be parsed from the SQL query results, and PO number *is*
needed when generating the invoice itself. By dual-purposing the header
(both as the required fields in the parser and the first line in the
detailed report) we have to include the value of PO number in the
detailed report CSV as well.
--- …
> Output PO number in detailed report

- core/src/main/java/google/registry/persistence/transaction/JpaTransactionManagerImpl.java
The try block around commit that catches RuntimeException should also
catch Error, which is also unchecked.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/665)
> Make sure uncommitted txn is rolled back

- core/src/main/java/google/registry/env/production/pubapi/WEB-INF/appengine-web.xml
We may also consider switching to an automatic scaling mode soon, on the hope
that it's working better than the last time we tried it (it would help to keep
resource costs down at least).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/671)
> Double the # of pubapi instances to better handle traffic spikes

- core/src/test/java/google/registry/model/EntityTestCase.java
- core/src/test/java/google/registry/model/billing/BillingEventTest.java
- core/src/test/java/google/registry/model/contact/ContactResourceTest.java
- core/src/test/java/google/registry/model/history/ContactHistoryTest.java
- core/src/test/java/google/registry/model/history/HostHistoryTest.java
- core/src/test/java/google/registry/model/poll/PollMessageTest.java
- core/src/test/java/google/registry/model/registry/RegistryLockDaoTest.java
- core/src/test/java/google/registry/model/reporting/Spec11ThreatMatchTest.java
It's more clear to use an enum rather than just a simple boolean
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/669)
> Use an enum instead of boolean in EntityTestCase constructor

- core/src/main/java/google/registry/beam/spec11/SafeBrowsingTransforms.java
- core/src/main/java/google/registry/beam/spec11/Spec11Pipeline.java
- core/src/main/java/google/registry/beam/spec11/Subdomain.java
- core/src/main/java/google/registry/beam/spec11/sql/subdomains.sql
- core/src/test/java/google/registry/beam/spec11/Spec11PipelineTest.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/674)
In order for the ThreatMatch objects to be able to reference the foreign key of the Domain table, we need to have a domainRepoId field in the Subdomain Java class. This PR enables the sql code in subdomains.sql to pull those keys from that table and have them be retrievable from Subdomain.java.
> Add domainRepoId to Subdomain class

- .gitignore
For some reason, Intellij 2020.1 puts some auto-generated Java classes to `${workspace}/core/src/test/generated_tests/` and `${workspace}/util/src/main/generated/` when running tests. So, add them to `.gitignore` to avoid interference.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/679)
> Add two folders of auto-generated Java classes to .gitignore

- core/src/main/java/google/registry/batch/DeleteContactsAndHostsAction.java
- core/src/main/java/google/registry/batch/RefreshDnsOnHostRenameAction.java
- core/src/main/java/google/registry/model/BackupGroupRoot.java
- core/src/main/java/google/registry/model/EppResourceUtils.java
- core/src/main/java/google/registry/model/ofy/CommitLoggedWork.java
- core/src/test/java/google/registry/batch/ResaveAllEppResourcesActionTest.java
- core/src/test/java/google/registry/model/EppResourceTestUtils.java
- core/src/test/java/google/registry/model/EppResourceUtilsTest.java
- core/src/test/java/google/registry/model/contact/ContactResourceTest.java
- core/src/test/java/google/registry/model/domain/DomainBaseSqlTest.java
- core/src/test/java/google/registry/model/ofy/OfyCommitLogTest.java
- core/src/test/java/google/registry/model/ofy/OfyTest.java
- db/src/main/resources/sql/flyway/V39__add_updatetime_column.sql
- db/src/main/resources/sql/schema/db-schema.sql.generated
- db/src/main/resources/sql/schema/nomulus.golden.sql
Property was inadvertently left out.
Renamed getter and setter to match the property name.
Added a test helper to compare EppResources while ignoring
lastUpdateTime, which changes every time an instance is persisted.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/683)
> Add lastUpdateTime column to epp resources

- core/src/main/java/google/registry/env/sandbox/default/WEB-INF/cron.xml
This will allow the cursor to catch up to current date if
it somehow falls behind.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/684)
> Run rdeStaging twice daily in Sandbox

- core/src/test/java/google/registry/beam/initsql/WriteToSqlTest.java
- core/src/test/java/google/registry/testing/DatastoreEntityExtension.java
Made DatastoreExtension a JUnit4 Rule.
Nomulus model objects need Datastore API when manipulating Ofy keys.
As a result, JpaIntegrationTestRule must be used with AppEngineRule
or DatastoreExtension.
Also fixed WriteToSqlTest, which is the only JUnit4 test that uses
JpaIntegrationTestRule.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/687)
> Fix JpaIntegrationRule in JUnit4

- core/src/main/java/google/registry/beam/spec11/sql/subdomains.sql
Change the name of the registrar client Id retrieved from SQL to have the alias "registrarId" so that the field in subdomains.sql can match Subdomain.java
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/692)
> Change clientId -> registrarId in subdomains.sql

- core/src/main/java/google/registry/batch/AsyncTaskEnqueuer.java
- core/src/test/java/google/registry/batch/AsyncTaskEnqueuerTest.java
- core/src/test/java/google/registry/tools/DomainLockUtilsTest.java
I believe this is why we are seeing 404s currently -- we should be
specifying the backend host as the target like we do for the
resave-entity async action.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/699)
> Add a 'Host' parameter to the relock action enqueuer

- core/src/test/java/google/registry/model/ImmutableObjectSubject.java
- core/src/test/java/google/registry/model/history/HostHistoryTest.java
Many times, when comparing objects that are loaded in from / saved to
SQL in tests, there are some fields we don't care about. Specifically,
we might not care about the last update time, revision ID, or other
things like that that are autoassigned by the DB. If we use this, we can
ignore those fields while still comparing the other ones.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/695)
> Create an ImmutableObjectSubject for comparing SQL objects

- core/src/main/java/google/registry/beam/initsql/BeamJpaModule.java
- core/src/main/java/google/registry/tools/RegistryCli.java
There are two issues fixed here.
1. Without calling `FileSystems.setDefaultPipelineOptions(PipelineOptionsFactory.create()), the Nomulus tool doesn't know how to handle gs:// scheme files. Thus, if you try to deploy (for instance) the Spec11 pipeline using a GCS credential file, it fails.
2. There was a misunderstanding before about what the credential file
actually refers to -- there is a credential file in JSON format that is
used for gcloud authorization, and there is a space-delimited SQL access
info file that has the instance name, username, and password. These are
separate options and should have separate command-line params.
--- …
> Fix some SQL credential issues identified when deploying Beam pipelines

- db/build.gradle
Let the flyway tasks use the sql credential files set up for BEAM
pipelines. 
Credential files have been created for each environment in GCS
at gs://${project}-beam/cloudsql/admin_credential.enc. They are
meant for the BEAM pipeline runner accounts in each project.
Alpha and crash accounts use the 'nomulus-tools-key' in their own project to
decrypt the credential file.
Sandbox and production accounts use the 'nomulus-tools-key' in
domain-registry-dev to decrypt the credential file.
Previously all flyway tasks use the 'nomulus-tools-key' in
domain-registry-dev, which was meant for the Cloud Build tasks.
It is a little cleaner to limit this key to sandbox and production.
Note that this setup is temporary. It will become obsolete once
we migrate to Cloud Secret Manager for secret storage. …
> Use rearranged sql credentials in flyway task

- db/src/main/resources/sql/flyway/V40__spec11threatmatch_remove_registrar_foreign_key.sql
- db/src/main/resources/sql/schema/nomulus.golden.sql
The Registrar table in SQL hasn't been migrated over from Datastore yet, so the foreign key reference to Registrar is temporarily removed so that the Spec11Pipeline can properly store new ThreatMatches into Spec11ThreatMatch.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/715)
> Remove Registrar foreign key reference from Spec11ThreatMatch

- core/src/main/java/google/registry/tools/DomainLockUtils.java
- core/src/main/java/google/registry/tools/LockDomainCommand.java
- core/src/main/java/google/registry/tools/LockOrUnlockDomainCommand.java
- core/src/main/java/google/registry/tools/UnlockDomainCommand.java
- core/src/test/java/google/registry/tools/DomainLockUtilsTest.java
- core/src/test/java/google/registry/tools/LockDomainCommandTest.java
- core/src/test/java/google/registry/tools/UnlockDomainCommandTest.java
- core/src/test/java/google/registry/ui/server/registrar/RegistryLockPostActionTest.java
There are a couple things going on here in this commit.
First, we add an external JPA transaction in the
LockOrUnlockDomainCommand class. This doesn't appear to do much, but it
avoids a situation similar to deadlock if an error occurs in Datastore
when saving the domain object (e.g. a contention issue). Specifically, DomainLockUtils relies on
the fact that any error in Datastore will be re-thrown in the JPA
transaction, meaning that any Datastore error will back out of the SQL
transaction as well. However, this is no longer true if we are already
in a Datastore transaction when calling DomainLockUtils (unless, again,
we are also in a JPA transaction). Basically, we require that the outer
transaction is the JPA one.
Secondly, this just allows for more breakglass operations in the lock or …
> Run the (Un)lockDomainCommand in an outer JPA txn

- core/src/main/java/google/registry/beam/initsql/BeamJpaModule.java
- core/src/main/java/google/registry/beam/initsql/InitSqlPipeline.java
- core/src/main/java/google/registry/beam/initsql/InitSqlPipelineOptions.java
- core/src/main/java/google/registry/beam/initsql/JpaSupplierFactory.java
- core/src/main/java/google/registry/tools/DeploySpec11PipelineCommand.java
- core/src/main/java/google/registry/tools/RegistryCli.java
- core/src/main/java/google/registry/tools/RegistryToolComponent.java
- core/src/test/java/google/registry/beam/initsql/BeamJpaExtension.java
- core/src/test/java/google/registry/beam/initsql/BeamJpaModuleTest.java
There are a few things going on here. 
1. We tell the Beam JPA module how to handle gs:// paths
2. We rename the credentialFilePath to make it clear that this should contain the SQL access info (as opposed to the JSON credential file that can be used for gcloud access)
3. Allow for configuration of the project that stores the keyring necessary to decrypt the SQL access info file
4. Refactor the DeploySpec11Pipeline command -- we'll need to create the SerializableSupplier<JpaTransactionManager> when we use the transaction manager in the Spec11Pipeline. As a result, we'll need to have the ability to create it there. 
5. Use an AppEngineEnvironment whenever we deal with ImmutableObject creation
--- …
> Set up deployment of the Spec11 pipeline with JPA TM

- core/src/main/java/google/registry/model/registry/label/ReservationType.java
- core/src/test/java/google/registry/flows/CheckApiActionTest.java
- core/src/test/java/google/registry/flows/domain/DomainCheckFlowTest.java
Apparently, in domain check responses, `avail=false, reason=Allocation token
required` was not sufficiently understood by all registrars. This changes it to
`avail=false, reason=Reserved; alloc. token required` to hopefully make it
crystal clear that the domain in question is reserved, i.e. if you were supposed
to be able to register this domain you'd already know it because we'd have
already given you the requisite allocation token.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/725)
> Clarify un-avail reason on allocation-token-reserved domains

- core/src/main/java/google/registry/tools/RegistryCli.java
This PR removed the line `AppEngineEnvironment env = new AppEngineEnvironment()` which was introduced in #716. The created `env` object is not used by any of the subsequent code and during the course of its instantiation, `AppEngineEnvironment` sets up the AppEngine remote API which conflicts with the similar process that `RegistryCli` itself does. The symptom is when running a registry tool command using AppEngine remote API, we will get the below error:
```java
Exception in thread "main" com.google.apphosting.api.ApiProxy$CallNotFoundException: The API package 'urlfetch' or call 'Fetch()' was not found.
at com.google.apphosting.api.ApiProxy.makeSyncCall(ApiProxy.java:111)
at com.google.appengine.api.urlfetch.URLFetchServiceImpl.fetch(URLFetchServiceImpl.java:40)
at …
```
> Fix broken RegistryCli

- core/build.gradle
- core/src/main/java/google/registry/beam/initsql/BackupPaths.java
- core/src/main/java/google/registry/beam/initsql/InitSqlPipeline.java
- core/src/test/java/google/registry/beam/initsql/BackupTestStoreTest.java
- core/src/test/java/google/registry/beam/initsql/ExportloadingTransformsTest.java
Added the main() method to InitSqlPipeline.
Added a Gradle task to run InitSqlPipeline from command line. This
task is meant for testing and experiments.
Corrected the file name prefix of Datastore export files. Should
be 'output-', defined as 'input-'.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/727)
> Run InitSqlPipeline

- build.gradle
- core/build.gradle
- docs/build.gradle
- java_common.gradle
Add the class paths of the source files generated by annotation processors to
the javadoc task's class path so that it doesn't complain about missing
Dagger classes.
Also remove empty <p> tags in all generated source files, because jaxb
genrerates files in multiple locations.
Lastly, for unkown reasons when the source level is set to > 8, the core
subproject throws a warning about a Gradle internal annotator processor
that only supports up to Java 8 and cause the Java compliation to fail because
we set -Werror on all java compilation tasks. I don't think there is a
strong reason that we set -Werror anyway, so this commit removes it.
--- …
> Some more changes to make it possible to use Java 11 to compile

- core/build.gradle
It is not clear to me why this folder is deleted in standardTest first,
presumably this is done when the webdriver tests were part of
standardTest?
Also not clear to me is why screenshots are only deleted in presubmits
but not locally. At least on my workstation standardTest runs after
fragileTest, just like in kokoro, so it should have deleted the screenshots
folder, but it didn't.
Regardless, the correct thing to do is to delete this folder first in
fragileTest so that it doesn't interfere with the results.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/735)
> Delete screenshots folder in fragile test first

- release/builder/build.sh
The default node version from the base image (Ubuntu 18.04) is too older
and karma is not happy about it.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/741)
> Use the latest version of node in the builder image

- core/src/main/java/google/registry/tools/CreateOrUpdateDomainCommand.java
- core/src/main/java/google/registry/tools/DsRecord.java
- core/src/main/java/google/registry/tools/UniformRapidSuspensionCommand.java
- core/src/main/java/google/registry/tools/UpdateDomainCommand.java
- core/src/main/resources/google/registry/tools/soy/UniformRapidSuspension.soy
- core/src/test/java/google/registry/tools/UniformRapidSuspensionCommandTest.java
- core/src/test/resources/google/registry/tools/server/uniform_rapid_suspension_undo_client_hold.xml
- core/src/test/resources/google/registry/tools/server/uniform_rapid_suspension_with_client_hold.xml
- Reuse DS record format processing from the create/update domain commands
(BIND format, commonly used in URS requests)
- Remove the CLIENT_HOLD status from domains that have it (this blocks us from
serving the new nameservers and DS record)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/739)
> Improve the uniform_rapid_suspension command

- core/src/main/java/google/registry/persistence/JpaRetries.java
- core/src/main/java/google/registry/persistence/transaction/JpaTransactionManager.java
- core/src/main/java/google/registry/persistence/transaction/JpaTransactionManagerImpl.java
- core/src/test/java/google/registry/persistence/transaction/JpaTransactionManagerImplTest.java
Right now this retrier will only retry exceptions that we have seen so far which are OptimisticLockException and JDBCConnectionException. If more exceptions come up that we determine are safe to be retried, they can be added to the retrier.
Note that It is only safe to retry JDBCConnectionException on read only and non-transactional queries.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/693)
> Add retrier to JpaTransactionManager

- release/builder/build.sh
The node installed by nvm gives errors when running "npm install".
Also installs Python as it is need. Presumbly the system provided npm
version has python as a dependency so it was installed when npm was
installed.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/742)
> Use nodesource to install node

- core/src/main/java/google/registry/flows/domain/DomainPricingLogic.java
- core/src/main/java/google/registry/model/BackupGroupRoot.java
- core/src/main/java/google/registry/model/domain/DomainContent.java
- core/src/main/java/google/registry/model/domain/DomainHistory.java
- core/src/main/java/google/registry/model/domain/token/AllocationToken.java
- core/src/main/java/google/registry/tools/GenerateAllocationTokensCommand.java
- core/src/main/java/google/registry/tools/GetAllocationTokenCommand.java
- core/src/main/java/google/registry/tools/UpdateAllocationTokensCommand.java
- core/src/test/java/google/registry/flows/domain/DomainCheckFlowTest.java
- core/src/test/java/google/registry/flows/domain/DomainCreateFlowTest.java
- core/src/test/java/google/registry/model/domain/token/AllocationTokenTest.java
- core/src/test/java/google/registry/model/history/ContactHistoryTest.java
- core/src/test/java/google/registry/model/history/DomainHistoryTest.java
- core/src/test/java/google/registry/testing/DatastoreHelper.java
- core/src/test/java/google/registry/tools/GenerateAllocationTokensCommandTest.java
- core/src/test/java/google/registry/tools/UpdateAllocationTokensCommandTest.java
- core/src/test/resources/google/registry/flows/domain/domain_check_allocationtoken_promotion.xml
- core/src/test/resources/google/registry/flows/domain/domain_check_allocationtoken_promotion_response.xml
- core/src/test/resources/google/registry/flows/domain/domain_create_allocationtoken.xml
- core/src/test/resources/google/registry/flows/domain/domain_create_premium_allocationtoken.xml
- core/src/test/resources/google/registry/flows/domain/domain_create_response_wildcard.xml
- core/src/test/resources/google/registry/model/schema.txt
- java-format/google-java-format-git-diff.sh
- util/src/main/java/google/registry/util/CollectionUtils.java
- util/src/main/java/google/registry/util/PreconditionsUtils.java
These are optional and default to off, but as of this PR we will have the ability to, when we want it, create an allocation token with a discount valid for premium names as well as standard names, and that will discount as many years of the initial registration as we want (rather than just the first).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/744)
> Allow allocation token discounts on premiums and for multiple years

- core/src/main/java/google/registry/model/billing/BillingEvent.java
- core/src/main/java/google/registry/model/poll/PollMessage.java
This PR removed the code to construct a fake SQL key for VKey in PollMessage and BillingEvent
because it doesn't work with some entities having old key structure.
The reason why we construct the fake SQL key is because we discovered that there were some PollMessage
and BillingEvent entities having duplicate ids. So, we wanted the fake SQL key to be served as an alert to
remind us to fix the data problem before migrating to Cloud SQL. The problem has been fixed for 
PollMessage entities and we are actively working on the fix for BillingEvent entities.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/747)
> Fix vkey construction in PollMessage and BillingEvent

- release/cloudbuild-nomulus.yaml
For reasons unclear at the moment the tests are not passing. Disabling
them for now so that release candidates can be built. We have CI runs
after each merge so we should be pretty confident if the build is broken
or not.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/752)
> Disable tests in RC builds

- release/cloudbuild-deploy.yaml
The current setup causes the GCB job to fail validation and not run because it
uses backticks in the configuration yaml, which is not allowed -- there is no
shell to perform backtick substitution. See the error message here:
https://spinnaker.endpoints.domain-registry-dev.cloud.goog/gate/pipelines/01EF5GRMD625613H6Z033DBD3Z
In the future please make sure to test the GCB pipeline as instructed in
the comments at the beginning of each file before committing.
I tried to work around it by downloading the nomulus tool jar file
instead (running the nomulus-tool docker image inside a docker image is
not advisable). However the "nomulus deploy_spec11_pipeline" command
still fails. I'm not sure why. Has the command itself been tested
locally? The error message is shown blew:
```
Step #2: Aug 09, …
```
> Temporarily disable spec 11 pipeline deployment in GCB

- core/src/test/java/google/registry/webdriver/RegistrarConsoleScreenshotTest.java
This test is flaky and the going theory is that we take a screenshot
immediately after we click the "Add" button and the CSS hover effect is
somehow still playing on the button.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/756)
> Wait for contact add page to load before doing screenshot diff

- core/src/test/java/google/registry/model/reporting/Spec11ThreatMatchTest.java
- db/src/main/resources/sql/flyway/V47__remove_spec11_domain_foreign_key.sql
- db/src/main/resources/sql/schema/nomulus.golden.sql
We'll want this eventually but until the Domain SQL table is populated,
we can't rely on domains' existence.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/757)
> Remove spec11 domain foreign key

- core/src/test/java/google/registry/webdriver/WebDriverTestCase.java
My theory is that this timeout is being applied to all retries of a failing test
rather than each one, and thus flaky screenshot tests aren't being given
sufficient time to complete any attempt past the first.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/758)
> Double the timeout length for WebDriver screenshot tests

- core/src/main/java/google/registry/tools/MutatingCommand.java
- core/src/main/java/google/registry/tools/RegistryTool.java
- core/src/main/java/google/registry/tools/ResaveEntitiesWithUniqueIdCommand.java
- core/src/test/java/google/registry/tools/ResaveEntitiesWithUniqueIdCommandTest.java
This PR adds ResaveEntitiesWithUniqueIdCommand to address the duplicate id issue we found for certain BillingEvent.OneTime and PollMessage.Autorenew entities. The command reassigns an application wide unique id to the problematic entity and resaves it, it also resaves the entity having reference to the problematic entity with the updated id.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/656)
> Add a nomulus command to resave entity with unique id

- release/cloudbuild-deploy.yaml
Now that beam deployment is compatible with Java 11. Re-enable this
step.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/764)
> Re-enable invoicing pipeline deployment

- core/src/main/java/google/registry/persistence/HibernateSchemaExporter.java
HibernateSchemaExporterTest is failing with "Driver not found" error
after Java 11 upgrade. Reason is that ServiceLoader now only checks
modules for services.
Proper fix is to define modules.
This short term fix is to declare the driver class explicitly.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/777)
> Fix missing-driver in HibernateSchemaExporterTest

- core/src/main/java/google/registry/model/EntityClasses.java
- core/src/main/java/google/registry/model/contact/ContactHistory.java
- core/src/main/java/google/registry/model/domain/DomainHistory.java
- core/src/main/java/google/registry/model/host/HostHistory.java
- core/src/main/java/google/registry/model/ofy/DatastoreTransactionManager.java
- core/src/main/java/google/registry/model/reporting/HistoryEntry.java
- core/src/test/java/google/registry/model/history/ContactHistoryTest.java
- core/src/test/java/google/registry/model/history/DomainHistoryTest.java
- core/src/test/java/google/registry/model/history/HostHistoryTest.java
- core/src/test/resources/google/registry/model/schema.txt
While Datastore is the primary database, we will store *History objects
as HistoryEntry objects and convert to/from the proper objects in the
Datastore transaction manager. This means that History objects will not
properly store the copy of the EppResource until we move to SQL as
primary, but this is the way the world exists anyway so it's not a
problem.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/749)
> Persist *History objects as HistoryEntry objects

- core/src/test/java/google/registry/webdriver/OteSetupConsoleScreenshotTest.java
- core/src/test/java/google/registry/webdriver/RegistrarConsoleScreenshotTest.java
- core/src/test/java/google/registry/webdriver/RegistrarConsoleWebTest.java
- core/src/test/java/google/registry/webdriver/RegistrarCreateConsoleScreenshotTest.java
- core/src/test/java/google/registry/webdriver/WebDriverPlusScreenDifferExtension.java
Fix flaky web driver tests
Identified two flaky tests in RegistrarConsoleScreenshotTest through
local testing and fixed them by waiting for specific web elements instead
of using fixed delays.
Refactored the wait methods to support different test scenarios,
and removed unnecessary delays.
Extensively tested locally. Also ran multiple presubmits on Kokoro.
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/784)
> Fix flaky web driver tests

- core/build.gradle
- core/src/main/java/google/registry/persistence/converter/DurationConverter.java
- core/src/test/java/google/registry/persistence/converter/DurationConverterTest.java
Apparently, the behavior of converting from `Duration` to `Period` by using `new Period(duration)` is not deterministic.
We expect that it behaves the same as `duration.toPeriod()` which stores the remaining duration to `hours` when the duration
is more than a day. However, sometimes, it just drops the remaining duration and only keeps the part that less than a day, e.g.,
if the duration is 1 day and 1 hour, the converted period is only 1 hour, and if the duration is exact 1 day, the persisted period
would become `null` because the whole duration is dropped during conversion(This is the reason why there was failing test in `DomainLockUtilsTest `). The exact reason is not clear but I guess `new Period(duration)` depends on some OS setup or timezone of the host running the code.
---
This …
> Consolidate conversion from Duration to Period in DurationConverter

- core/src/main/java/google/registry/model/domain/DomainBase.java
- core/src/main/java/google/registry/model/domain/DomainContent.java
- core/src/test/java/google/registry/model/domain/DomainBaseSqlTest.java
This PR fixed the cascade issues when loading/saving `GracePeriod` entities through `Domain`:
1. We need to add `insertable = false, updatable = false` to `@JoinColumn` annotation attached to `Set<GracePeriod>`.
The exact reason is not clear but many Hibernate users encountered the same problem(See [here](https://stackoverflow.com/questions/27309075/hibernate-not-deleting-the-foreign-key-row-rather-setting-it-as-null)).
Without setting these two options to false, Hibernate would try to update the foreign key to null instead of executing
the deletion when an element is removed from the collection.
2. For the sake of `Datastore`, the builder of `EppResource` sets any empty collection to null. However, Hibernate would
complain about this because it expects a non-null collection. We have a …
> Fix cascade issue for GracePeriod

- core/src/main/java/google/registry/model/billing/BillingEvent.java
- core/src/main/java/google/registry/model/contact/ContactHistory.java
- core/src/main/java/google/registry/model/domain/DomainHistory.java
- core/src/main/java/google/registry/model/host/HostHistory.java
- core/src/main/java/google/registry/model/index/EppResourceIndex.java
- core/src/main/java/google/registry/model/index/EppResourceIndexBucket.java
- core/src/main/java/google/registry/model/index/ForeignKeyIndex.java
- core/src/main/java/google/registry/model/poll/PollMessage.java
- core/src/main/java/google/registry/model/registry/label/PremiumList.java
- core/src/main/java/google/registry/model/reporting/HistoryEntry.java
- core/src/main/java/google/registry/persistence/transaction/TransactionEntity.java
- core/src/test/java/google/registry/model/CreateAutoTimestampTest.java
- core/src/test/java/google/registry/model/ImmutableObjectTest.java
- core/src/test/java/google/registry/model/UpdateAutoTimestampTest.java
- core/src/test/java/google/registry/model/ofy/OfyTest.java
- core/src/test/java/google/registry/model/translators/CommitLogRevisionsTranslatorFactoryTest.java
- core/src/test/java/google/registry/schema/replay/EntityTest.java
- core/src/test/java/google/registry/testing/TestObject.java
We still have many more classes to go, but this gets us closer to
guaranteeing that we can convert from Datastore to SQL objects and back
again.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/788)
> Implement DatastoreEntity/SqlEntity for many more classes

- core/src/main/java/google/registry/model/contact/ContactHistory.java
- core/src/main/java/google/registry/model/domain/DomainHistory.java
- core/src/main/java/google/registry/model/host/HostHistory.java
- core/src/main/resources/META-INF/orm.xml
- db/src/main/resources/sql/flyway/V53__add_temp_history_id_sequence.sql
- db/src/main/resources/sql/schema/db-schema.sql.generated
- db/src/main/resources/sql/schema/nomulus.golden.sql
We changed `history_id_sequence` to use `INCREMENT BY 50` in #767. However, this change cannot be applied correctly by our release process. Our release process always deploy the code change first then apply the schema change, after the code change is deployed, Hibernate throws the an exception that indicates it expects the sequence to be `INCREMENT BY 50` in the database  as well though at that time the schema change is not applied yet.
So, the work around I made in this PR is to create a temporary sequence for all history tables and also keep the previous change for `history_id_sequence`. After this PR is deployed, we can create another PR to switch back to use `history_id_sequence` for all history tables.
--- …
> Add and use temp_history_id_sequence to avoid release error

- core/src/main/java/google/registry/persistence/transaction/JpaTransactionManagerImpl.java
- core/src/test/java/google/registry/persistence/transaction/TransactionManagerTest.java
JpaTransactionManagerImpl doesn't respect @Id fields in mapped superclasses.
Replace calls to getDeclaredId() and getDeclaredField() with superclass
friendly counterparts.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/799)
> Fix accessing superclass fields in checkExists()

- proxy/deploy-proxy-for-env.sh
- proxy/kubernetes/proxy-service-canary.yaml
- proxy/kubernetes/proxy-service.yaml
This supposedly can fix our deployment problem. Tested on alpha.
Also updated the deployment script to replace the service object as
well.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/807)
> Use the save API version for the HPA controller and the deployment

- core/src/main/java/google/registry/reporting/icann/IcannHttpReporter.java
1. It appears that when we have a 200 response, the response content is
garbled, but we don't care since we know the request is successful.
When we have a 400 response, the response is indeed UTF-8 encoded.
Print the stack trace of the HTTP exception doesn't help anymore.
2. The result code is a complex type which includes the xml element with
all its attributes, which don't care. We only want to print the
value.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/808)
> Update ICANN activity reporting logging

- core/src/main/java/google/registry/model/registry/Registry.java
- core/src/main/java/google/registry/tools/CreateOrUpdateTldCommand.java
- core/src/main/java/google/registry/tools/DomainLockUtils.java
- core/src/test/java/google/registry/flows/domain/DomainRenewFlowTest.java
- core/src/test/java/google/registry/flows/domain/DomainRestoreRequestFlowTest.java
- core/src/test/java/google/registry/tools/CreateTldCommandTest.java
- core/src/test/java/google/registry/tools/DomainLockUtilsTest.java
- core/src/test/java/google/registry/tools/UpdateTldCommandTest.java
- core/src/test/java/google/registry/ui/server/registrar/RegistryLockVerifyActionTest.java
- core/src/test/resources/google/registry/model/schema.txt
Currently we use the standard server status change cost for this, but
this might not be ideal at some point in the future if we wish to allow
manual forced updates outside of the standard registry lock system (we
would charge for these manual forced updates, even if we don't charge
for registry locks).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/800)
> Create a separate per-tld registry lock/unlock cost

- proxy/kubernetes/proxy-deployment-sandbox-canary.yaml
- proxy/kubernetes/proxy-deployment-sandbox.yaml
This is suggested as a mitigation to allow us to deploy to sandbox. The default
value is 100m.
See: https://b.corp.google.com/issues/167295064#comment36.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/813)
> Request 101m CPU in sandbox proxy

- build.gradle
- config/nom_build.py
- db/build.gradle
- db/src/test/java/google/registry/sql/flyway/SchemaTest.java
- gradle.properties
- integration/run_compatibility_tests.sh
- integration/run_schema_check.sh
Current test is git-based. It is difficult to maintain and does not
catch out-of-order version numbers. It is also more aggressive than
necessary, failing on changes to submitted scripts that have not been
deployed yet.
The new test starts a database, deploys the current Sandbox schema to it,
then deploys the set of Flyway scripts in this repository to the database.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/815)
> Enhance the test for forbidden Schema changes

- core/src/main/java/google/registry/persistence/VKey.java
- core/src/test/java/google/registry/persistence/VKeyTest.java
Add a restoreOfy() instance method and a restoreOfyFrom() static method to
assist in restoring the objectify key for classes that have composite keys
that do not restore automatically.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/820)
> Add VKey.restoreOfy() method for fixing ofy keys

- util/src/main/java/google/registry/util/CertificateChecker.java
- util/src/main/java/google/registry/util/SelfSignedCaCertificate.java
- util/src/test/java/google/registry/util/CertificateCheckerTest.java
This ends up being nicer to deal with from callsites than class instances, while
still permitting full configurability of all parameters. There are various other
changes/fixes as well.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/829)
> Convert CertificateViolation into an enum

- release/cloudbuild-deploy.yaml
Keep track of the mapping between Nomulus release tags and AppEngine
version ids with a mapping file. This is necessary because AppEngine
does not support custom versioning. With this mapping, rollbacks could
be automated. Automation of rollbacks is important since there are
test-supporting metadata to be updated, but are easily forgotten.
During the last stage of deployment, current per-service version ids
are fetched using gcloud and are appended to a file on GCS. Each line
is of the format "{RELEASE_TAG},{APPENGINE_SERVICE},{APPENGINE_VERSION}.
This change has been tested in crash. The rollback script is still a
work in progress.
--- …
> Maintain a release-to-Version map in deployment

- config/nom_build.py
- docs/install.md
Use dataclasses instead of attrs. The former is part of the standard lib
while the latter may need to be installed separately. For now we are not
using advanced features in attrs. Ran nom_build_test by hand and it passes.
Also added python3 to the list of prerequisites in docs.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/832)
> Minor python changes

- release/rollback/plan.py
- release/rollback/rollback_test.py
- release/rollback/steps.py
To update the nomulus tool on corp desktop, the artifacts from the
rollback target release should be copied to the 'live' folder.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/854)
> Sync the live folder after Nomulus rollback

- core/src/main/java/google/registry/model/billing/BillingEvent.java
- core/src/main/java/google/registry/model/domain/secdns/DomainDsDataBase.java
- core/src/main/java/google/registry/model/domain/secdns/DomainDsDataHistory.java
- Abstract classes shouldn't implement DatastoreEntity/SqlEntity
- We aren't persisting Modification in SQL
- Because DelegationSignerData is embedded, we don't need to worry about
converting and persisting it
- DomainDsDataHistory isn't persisted in Datastore
After this, there are only three classes left to fix before we can enable EntityTest
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/856)
> Fix entity annotations for a few classes

- core/src/main/java/google/registry/model/registry/label/PremiumList.java
- core/src/main/java/google/registry/model/registry/label/ReservedList.java
- core/src/test/java/google/registry/model/registry/RegistriesTest.java
- core/src/test/java/google/registry/model/registry/RegistryTest.java
- core/src/test/java/google/registry/testing/DatastoreHelper.java
- core/src/test/java/google/registry/testing/DualDatabaseTestInvocationContextProvider.java
This PR converted `RegistryTest` and `RegistriesTest` to working with SQL, and it also made the necessary `ofy() -> tm()` changes in the related code.
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/862)
> Convert Registry related tests to working with SQL

- core/src/main/java/google/registry/model/rde/RdeRevision.java
- core/src/main/java/google/registry/model/registry/label/PremiumList.java
- core/src/main/java/google/registry/model/registry/label/ReservedList.java
- core/src/main/java/google/registry/model/server/KmsSecretRevision.java
- core/src/main/java/google/registry/model/smd/SignedMarkRevocationList.java
- core/src/main/java/google/registry/schema/replay/DuallyWrittenEntity.java
- core/src/main/java/google/registry/schema/replay/NonReplicatedEntity.java
- core/src/test/java/google/registry/schema/replay/EntityTest.java
For classes that are dually written we don't need to worry about replay
conversion, so this just allows us to remove unnecessary unimportant
methods
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/866)
> Add DuallyWrittenEntity convenience interface

- core/src/main/java/google/registry/model/registry/Registry.java
- core/src/main/java/google/registry/model/registry/label/PremiumList.java
- core/src/main/java/google/registry/model/registry/label/ReservedList.java
- Add a createVKey() method to Registry (Registry vkeys are composite)
- Add/fix toSqlEntities() methods in premium and reserved list classes.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/863)
> Small SQL persistence fixes to model classes

- core/src/main/java/google/registry/model/registrar/Registrar.java
- core/src/test/java/google/registry/model/registrar/RegistrarTest.java
- core/src/test/java/google/registry/testing/DatastoreHelper.java
This PR converted `RegistrarTest` to working with SQL, and it also made the necessary ofy() -> tm() changes in the related code.
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/865)
> Convert RegistrarTest to working with Postgresql

- core/src/main/java/google/registry/model/domain/token/AllocationToken.java
- core/src/main/java/google/registry/model/ofy/CommitLoggedWork.java
- core/src/main/java/google/registry/model/ofy/ReplayQueue.java
- core/src/main/java/google/registry/model/ofy/TransactionInfo.java
- core/src/main/java/google/registry/model/registry/label/BaseDomainLabelList.java
- core/src/test/java/google/registry/flows/FlowTestCase.java
- core/src/test/java/google/registry/flows/domain/DomainCreateFlowTest.java
- core/src/test/java/google/registry/model/ofy/TransactionInfoTest.java
- core/src/test/java/google/registry/testing/AppEngineExtension.java
- core/src/test/java/google/registry/testing/DatastoreHelper.java
- core/src/test/java/google/registry/testing/ReplayExtension.java
- core/src/test/resources/google/registry/flows/domain/domain_create_response_eap_fee.xml
- core/src/test/resources/google/registry/flows/domain/domain_create_response_premium_eap.xml
- db/src/main/resources/sql/er_diagram/brief_er_diagram.html
- db/src/main/resources/sql/er_diagram/full_er_diagram.html
- db/src/main/resources/sql/flyway.txt
- db/src/main/resources/sql/flyway/V77__fixes_for_replay.sql
- db/src/main/resources/sql/schema/db-schema.sql.generated
- db/src/main/resources/sql/schema/nomulus.golden.sql
Add ReplayExtension, which can be applied to test suites to verify that
transactions committed to datastore can be replayed to SQL.
This introduces a ReplayQueue class, which serves as a stand-in for the
current lack of replay-from-commit-logs.  It also includes replay logic in
TransactionInfo which introduces the concept of "entity class weights."
Entity weighting allows us store and delete objects in an order that is
consistent with the direction of foreign key and deferred foreign key
relationships.  As a general rule, lower weight classes must have no direct or
indirect non-deferred foreign key relationships on higher weight classes.
It is expected that much of this code will change when the final replay
mechanism is implemented.
NOTE: this code currently breaks the one test that it …
> Add an extension to verify transaction replay

- core/src/test/java/google/registry/testing/DualDatabaseTestInvocationContextProvider.java
Display the concrete test method name in the build result and test report for `@DualDatabaseTest` to provide better context.
After this change, the build result for failed test will look like:
And the test report will look like:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/876)
> Display concrete test method name for @DualDatabaseTest

- core/src/main/java/google/registry/model/translators/VKeyTranslatorFactory.java
- core/src/test/java/google/registry/model/translators/VKeyTranslatorFactoryTest.java
- core/src/test/java/google/registry/testing/TestObject.java
This allows us to create VKeys from Keys for test objects that may not
be part of the original codebase.
This isn't used anywhere directly yet but it will be useful in the
future when testing the replay of SQL transactions.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/877)
> Allow addition of extra entity classes for VKey conversion

- util/src/main/java/google/registry/util/StringGenerator.java
This is intended for the purpose of generating maximally secure passwords for
PostgreSQL and others. We may need to remove a few of these punctuation
characters if they prove to be more trouble than they're worth (e.g. backtick).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/882)
> Add a full ASCII StringGenerator alphabet

- core/src/main/java/google/registry/model/domain/DomainContent.java
- core/src/main/java/google/registry/model/domain/GracePeriod.java
- core/src/test/java/google/registry/model/domain/DomainBaseTest.java
The GracePeriod method with ofy @OnLoad annotation is not called.
Apparently Ofy only checks for @OnLoad on first-class entities,
not embedded ones.
Added a call to this method from DomainContent's OnLoad method.
Reproduced issue with a test and verified that the fix works.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/878)
> Make sure post load work happens in GracePeriod

- core/src/main/java/google/registry/model/domain/DomainHistory.java
- core/src/main/java/google/registry/model/registry/Registries.java
- core/src/test/java/google/registry/model/history/DomainHistoryTest.java
- core/src/test/resources/google/registry/model/schema.txt
Make dsDataHistories and gracePeriodHistories in DomainHistory default to empty immutable sets (instead of null) and annotate them as "Ignore" since they should not be persisted in datastore.  This fixes problems we see trying to merge a detached instance of this entity type.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/884)
> Fix DomainHistory merge issues

- core/src/test/java/google/registry/backup/DeleteOldCommitLogsActionTest.java
- core/src/test/java/google/registry/model/index/EppResourceIndexTest.java
Fix a few comments that still make reference to DatastoreHelper.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/885)
> Fix DatastoreHelper -> DatabaseHelper in comments

- release/rollback/appengine.py
- release/rollback/appengine_test.py
- release/rollback/common.py
- release/rollback/common_test.py
- release/rollback/plan.py
- release/rollback/rolling_restart.py
- release/rollback/rolling_restart_test.py
- release/rollback/steps.py
Add a script to restart Nomulus non-disruptively. This can be used after
a configuration change to external resources (e.g.,  Cloud SQL
credential) to make Nomulus pick up the latest config.
Also added proper support to paging based List api methods, replacing the
current hack that forces the server to return everything in one response.
The List method for instances has a lower limit on page size than others
which is not sufficient for our project.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/888)
> Script to rolling-start Nomulus

- core/src/main/java/google/registry/model/contact/ContactHistory.java
- core/src/main/java/google/registry/model/domain/DomainHistory.java
- core/src/main/java/google/registry/model/domain/secdns/DomainDsDataHistory.java
- core/src/main/java/google/registry/model/host/HostHistory.java
- core/src/main/java/google/registry/model/ofy/TransactionInfo.java
- core/src/main/java/google/registry/model/reporting/HistoryEntry.java
- core/src/main/java/google/registry/model/reporting/Spec11ThreatMatch.java
- core/src/main/java/google/registry/model/tmch/TmchCrl.java
- core/src/main/java/google/registry/persistence/transaction/TransactionEntity.java
- core/src/main/java/google/registry/schema/cursor/Cursor.java
- core/src/main/java/google/registry/schema/domain/RegistryLock.java
- core/src/main/java/google/registry/schema/replay/DatastoreAndSqlEntity.java
- core/src/main/java/google/registry/schema/replay/DatastoreEntity.java
- core/src/main/java/google/registry/schema/replay/DatastoreOnlyEntity.java
- core/src/main/java/google/registry/schema/replay/NonReplicatedEntity.java
- core/src/main/java/google/registry/schema/replay/SqlEntity.java
- core/src/main/java/google/registry/schema/replay/SqlReplayCheckpoint.java
- core/src/main/java/google/registry/schema/server/Lock.java
- core/src/main/java/google/registry/schema/tld/PremiumEntry.java
We don't have any entities that convert to more than one entity, so we
can use an Optional instead for clarity and simplicity.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/894)
> Convert DatastoreEntity/SqlEntity to return Optional, not List

- core/src/main/java/google/registry/model/billing/BillingEvent.java
- core/src/main/java/google/registry/model/poll/PollMessage.java
- core/src/main/java/google/registry/persistence/WithLongVKey.java
- core/src/main/java/google/registry/persistence/WithStringVKey.java
- core/src/main/java/google/registry/persistence/converter/VKeyConverter.java
- core/src/test/java/google/registry/model/domain/DomainBaseSqlTest.java
- core/src/test/java/google/registry/model/history/DomainHistoryTest.java
- core/src/test/java/google/registry/persistence/converter/LongVKeyConverterTest.java
- core/src/test/java/google/registry/persistence/converter/StringVKeyConverterTest.java
- processor/build.gradle
- processor/src/main/java/google/registry/processors/AbstractVKeyProcessor.java
AbstractVKeyConverter had never been updated to generate symmetric VKeys for
simple (i.e. non-composite) VKey types.  Update it to default to generating a
VKey with a simple Ofy key.
With this change, composite VKeys must specify the "compositeKey = true" field
in the With*VKey annotations.  Doing so creates an asymmetric (SQL only) VKey
that can trigger higher-level logic to generate a corrected VKey containing
the composite Key.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/899)
> Resurrect symmetric vkeys when possible.

- core/src/main/java/google/registry/batch/ResaveAllEppResourcesAction.java
The intended/desired effect is to have a larger number of GCS commit log diffs
spread out over a longer period of time, with each diff itself being
significantly smaller. This should retain roughly the same amount of total work
for the async Cloud SQL replication action to have to deal with, but spread
across 10X as much time.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/904)
> Use 10 workers instead of the default 100 for re-save all EPP resources

- core/src/main/java/google/registry/model/UpdateAutoTimestamp.java
- core/src/main/java/google/registry/model/translators/UpdateAutoTimestampTranslatorFactory.java
- core/src/main/java/google/registry/persistence/converter/UpdateAutoTimestampConverter.java
- core/src/test/java/google/registry/model/UpdateAutoTimestampTest.java
Allow us to disable timestamp updates within a try-with-resources block for a
given thread.  This functionality will be needed for transaction replays both
to and from datastore.
As part of this, also upgrade the UpdateAutoTimestampTest to a
DualDatabaseTest so we can verify that the functionality works both on
Datastore and Cloud SQL.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/906)
> Allow disabling UpdateAutoTimestamp updates

- config/presubmits.py
For some reason, our docker build image has started using a non-utf8 default
encoding.  Specify the encoding explicitly on python "open()" to override.
Note that this might not entirely fix the build: it's possible that this
problem may affect other portions of the build.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/908)
> Make config/presubmits.py use explicit encodings

- core/src/main/java/google/registry/beam/initsql/BeamJpaModule.java
- core/src/main/java/google/registry/persistence/PersistenceComponent.java
- core/src/main/java/google/registry/persistence/PersistenceModule.java
- core/src/main/java/google/registry/privileges/secretmanager/SecretManagerModule.java
- core/src/main/java/google/registry/privileges/secretmanager/SqlUser.java
- core/src/test/java/google/registry/privileges/secretmanager/SecretManagerClientTest.java
- java_common.gradle
Load SQL credentials from the SecretManager and compare them with the
ones currently in use in Nomulus server, beam pipeline, and the registry
tool. Normal operations are not affected by failures related to the
SecretManager, be it IOException, insufficient permission , or wrong or
missing credential.
The appengine and compute engine default service accounts must be
granted the permission to access the secret data. In the short term, we
will grant the secretmanager.secretAccessor role to these accounts. In
the long term, with the proposed privilege service, access will be granted
on per-secret basis.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/907)
> Validate SQL credentials in Secret Manager

- core/src/main/java/google/registry/flows/domain/token/AllocationTokenFlowUtils.java
- core/src/main/java/google/registry/reporting/spec11/Spec11RegistrarThreatMatchesParser.java
- core/src/main/java/google/registry/tools/DeleteAllocationTokensCommand.java
- core/src/main/java/google/registry/tools/GenerateAllocationTokensCommand.java
- core/src/main/java/google/registry/tools/GetAllocationTokenCommand.java
- core/src/main/java/google/registry/tools/UpdateAllocationTokensCommand.java
- core/src/main/java/google/registry/tools/UpdateOrDeleteAllocationTokensCommand.java
- core/src/test/java/google/registry/model/domain/token/AllocationTokenTest.java
- core/src/test/java/google/registry/tools/CommandTestCase.java
- core/src/test/java/google/registry/tools/DeleteAllocationTokensCommandTest.java
- core/src/test/java/google/registry/tools/GenerateAllocationTokensCommandTest.java
- core/src/test/java/google/registry/tools/UpdateAllocationTokensCommandTest.java
For the most part this is a fairly simple converstion -- changing Key
references to VKey references, using JPA transactions when necessary,
and using the TransactionManager interface. There's a bit of cleanup too
in related code
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/909)
> Convert AllocationToken-related classes to tm()

- core/src/main/java/google/registry/batch/ResaveAllEppResourcesAction.java
- core/src/main/java/google/registry/env/alpha/default/WEB-INF/cron.xml
- core/src/main/java/google/registry/env/production/default/WEB-INF/cron.xml
- core/src/main/java/google/registry/env/qa/default/WEB-INF/cron.xml
- core/src/main/java/google/registry/env/sandbox/default/WEB-INF/cron.xml
- core/src/main/java/google/registry/mapreduce/MapreduceModule.java
- core/src/main/java/google/registry/mapreduce/MapreduceRunner.java
- core/src/main/java/google/registry/model/UpdateAutoTimestamp.java
- core/src/test/java/google/registry/batch/ResaveAllEppResourcesActionTest.java
This new mode avoids writing no-op mutations for entities that don't actually
have any changes to write. The cronjobs use fast mode by default, but manual
invocations do not, as manual invocations are often used to trigger @OnLoad
migrations, and fast mode won't pick up on those changes.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/912)
> Add a fast mode to the ResaveAllEppResourcesAction mapreduce

- core/src/main/java/google/registry/model/domain/DomainBase.java
- core/src/main/java/google/registry/model/domain/DomainHistory.java
- db/src/main/resources/sql/er_diagram/brief_er_diagram.html
- db/src/main/resources/sql/er_diagram/full_er_diagram.html
- db/src/main/resources/sql/flyway.txt
- db/src/main/resources/sql/flyway/V83__add_indexes_on_domainhost.sql
- db/src/main/resources/sql/schema/db-schema.sql.generated
- db/src/main/resources/sql/schema/nomulus.golden.sql
Add unique constraints on DomainHost (child of DomainBase) and
DomainHistoryHost (child of DomainHistory). DomainHost is non-entity
embedded object and Hibernate does not define indexes automatically.
This should improve read and write performance of the parent entities.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/911)
> Add unique constraints on domain_hosts

- core/src/main/java/google/registry/flows/host/HostCreateFlow.java
- core/src/main/java/google/registry/model/EppResourceUtils.java
- core/src/main/java/google/registry/model/index/ForeignKeyIndex.java
- core/src/main/java/google/registry/persistence/transaction/JpaTransactionManagerImpl.java
- core/src/test/java/google/registry/flows/FlowTestCase.java
- core/src/test/java/google/registry/flows/ResourceFlowTestCase.java
- core/src/test/java/google/registry/flows/host/HostCheckFlowTest.java
- core/src/test/java/google/registry/flows/host/HostCreateFlowTest.java
- core/src/test/java/google/registry/flows/host/HostFlowUtilsTest.java
- core/src/test/java/google/registry/model/EppResourceUtilsTest.java
- core/src/test/java/google/registry/model/index/ForeignKeyIndexTest.java
- core/src/test/java/google/registry/testing/AppEngineExtension.java
- core/src/test/java/google/registry/testing/DualDatabaseTestInvocationContextProvider.java
- core/src/test/java/google/registry/tools/CommandTestCase.java
This is the first PR that tried to convert EPP flows to use `tm()` APIs in its application and test code. So, there are
also some corresponding changes in `EppResourceUtils` and `ForeignKeyIndex`.
For the changes in `ForeignKeyIndex`, as we no longer maintain the entity in Cloud SQL, we need to read the original
entity table to reconstruct the instance. This approach helps keep a single code path as `ForeignKeyIndex` are used in
many EPP flows.
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/910)
> Convert HostCreateFlow and HostCheckFlow to tm()

- core/src/main/java/google/registry/model/domain/GracePeriodBase.java
The 'id' property no longer exists in the entity hierarchy
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/920)
> Remove unnecessary method

- core/src/main/java/google/registry/beam/initsql/BeamJpaModule.java
- core/src/main/java/google/registry/persistence/PersistenceModule.java
- core/src/test/java/google/registry/persistence/PersistenceModuleTest.java
Some BEAM pipelines may only perform READ-ONLY (e.g., reporting) or
blind-write (datastore to sql data migration) operations, which do not
need the default TRANSACTION_SERIALIZABLE isolation level. In such
cases, a less strict level allows better performance.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/916)
> Allow BEAM pipeline to choose JDBC isolation levels

- core/src/main/java/google/registry/flows/ResourceFlowUtils.java
- core/src/main/java/google/registry/flows/contact/ContactDeleteFlow.java
- core/src/main/java/google/registry/flows/contact/ContactInfoFlow.java
- core/src/main/java/google/registry/flows/host/HostDeleteFlow.java
- core/src/main/java/google/registry/flows/host/HostInfoFlow.java
- core/src/main/java/google/registry/model/EppResourceUtils.java
- core/src/main/java/google/registry/rdap/RdapJsonFormatter.java
- core/src/test/java/google/registry/flows/contact/ContactDeleteFlowTest.java
- core/src/test/java/google/registry/flows/contact/ContactInfoFlowTest.java
- core/src/test/java/google/registry/flows/host/HostDeleteFlowTest.java
This PR converted `HostDeleteFlow`, `ContactDeleteFlow` and `ContactInfoFlow` to use `tm()`. The main reason we put them in the same PR is because they all use some common methods in `ResourceFlowUtils` and `EppResourceUtils` that need to be converted together as well.
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/921)
> Convert some Host and Contact flows to tm()

- core/src/main/java/google/registry/flows/contact/ContactCreateFlow.java
- core/src/main/java/google/registry/flows/contact/ContactUpdateFlow.java
- core/src/main/java/google/registry/model/eppcommon/Address.java
- core/src/test/java/google/registry/flows/contact/ContactCheckFlowTest.java
- core/src/test/java/google/registry/flows/contact/ContactCreateFlowTest.java
- core/src/test/java/google/registry/flows/contact/ContactUpdateFlowTest.java
- core/src/test/java/google/registry/model/contact/ContactCommandTest.java
Converted the remaining Contact flows, i.e. `ContactCreateFlow`, `ContactUpdateFlow` and `ContactCheckFlow` to use `tm()`.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/924)
> Convert remaining Contact flows to tm()

- core/src/main/java/google/registry/model/billing/BillingEvent.java
- core/src/test/java/google/registry/model/billing/BillingEventTest.java
- core/src/test/resources/google/registry/model/schema.txt
- db/src/main/resources/sql/er_diagram/brief_er_diagram.html
- db/src/main/resources/sql/er_diagram/full_er_diagram.html
- db/src/main/resources/sql/flyway.txt
- db/src/main/resources/sql/flyway/V84__add_vkey_columns_in_billing_cancellation.sql
- db/src/main/resources/sql/schema/db-schema.sql.generated
- db/src/main/resources/sql/schema/nomulus.golden.sql
This PR used `BillingEventVKey` and `BillingRecurrenceVKey` to replace the raw `VKey` fields in `BillingEvent.Cancellation` help restore the symmetric VKey.
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/928)
> Restore symmetric VKey referenced by BillingEvent.Cancellation

- core/src/main/java/google/registry/model/EppResource.java
- core/src/main/java/google/registry/model/ImmutableObject.java
- core/src/main/java/google/registry/model/domain/DomainContent.java
- core/src/main/java/google/registry/model/domain/DomainHistory.java
- core/src/main/java/google/registry/model/ofy/ReplayQueue.java
- core/src/main/java/google/registry/model/ofy/TransactionInfo.java
- core/src/main/java/google/registry/model/poll/PollMessage.java
- core/src/main/java/google/registry/model/registry/label/PremiumListUtils.java
- core/src/main/java/google/registry/model/reporting/DomainTransactionRecord.java
- core/src/main/java/google/registry/model/reporting/HistoryEntry.java
- core/src/test/java/google/registry/flows/domain/DomainCreateFlowTest.java
- core/src/test/java/google/registry/flows/domain/DomainDeleteFlowTest.java
- core/src/test/java/google/registry/flows/domain/DomainRenewFlowTest.java
- core/src/test/java/google/registry/flows/domain/DomainUpdateFlowTest.java
- core/src/test/java/google/registry/model/ImmutableObjectSubject.java
- core/src/test/java/google/registry/testing/ReplayExtension.java
Allow optional object comparison in the replay test extension and enable it
for the DomainCreateFlow test.
To faciliate this, add two new field annotations to ImmutableObject:
DoNotCompare, to be used for fields that are not relevant to either database,
and Insignificant, to be used for fields that are mutated after they have been                                                                    
accessed and therefore violate immutability (there is currently only one of                                                                       
these, however we might discover more in the course of adding more comparisons
to the replay test.
--- …
> Add object comparison to replay tests

- core/src/main/java/google/registry/backup/ReplayCommitLogsToSqlAction.java
- core/src/main/java/google/registry/flows/domain/token/AllocationTokenFlowUtils.java
- core/src/main/java/google/registry/tools/DeleteAllocationTokensCommand.java
- core/src/main/java/google/registry/tools/GetAllocationTokenCommand.java
isEmpty() is not available in the version of Java GAE uses and is throwing
runtime errors (!!). I think these got into our codebases because people don't
have the language version set correctly in IntelliJ; they show as outright
errors for me (I'm on language level 8).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/934)
> Change java.util.Optional.isEmpty() to !isPresent()

- core/src/test/java/google/registry/model/contact/ContactCommandTest.java
Same place as the last one, but I missed it :-(
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/938)
> Fix another "extra parens" warning

- core/src/main/java/google/registry/model/ofy/DatastoreTransactionManager.java
- core/src/main/java/google/registry/model/reporting/HistoryEntryDao.java
- core/src/main/java/google/registry/persistence/transaction/JpaTransactionManagerImpl.java
- core/src/main/java/google/registry/rdap/RdapJsonFormatter.java
- core/src/main/java/google/registry/tools/GetHistoryEntriesCommand.java
- core/src/main/java/google/registry/tools/javascrap/BackfillRegistryLocksCommand.java
- core/src/test/java/google/registry/flows/domain/DomainCreateFlowTest.java
- core/src/test/java/google/registry/model/reporting/HistoryEntryDaoTest.java
- core/src/test/java/google/registry/model/reporting/HistoryEntryTest.java
- core/src/test/java/google/registry/rdap/RdapDomainActionTest.java
- core/src/test/java/google/registry/rdap/RdapDomainSearchActionTest.java
- core/src/test/java/google/registry/rdap/RdapJsonFormatterTest.java
- core/src/test/java/google/registry/rdap/RdapTestHelper.java
- core/src/test/java/google/registry/testing/FullFieldsTestEntityHelper.java
- core/src/test/java/google/registry/tools/GetHistoryEntriesCommandTest.java
- core/src/test/java/google/registry/tools/javascrap/BackfillRegistryLocksCommandTest.java
- core/src/test/resources/google/registry/rdap/rdap_domain.json
- core/src/test/resources/google/registry/rdap/rdap_domain_cat2.json
- core/src/test/resources/google/registry/rdap/rdap_domain_deleted.json
- core/src/test/resources/google/registry/rdap/rdap_domain_no_contacts_with_remark.json
- core/src/test/resources/google/registry/rdap/rdap_domain_unicode.json
- core/src/test/resources/google/registry/rdap/rdap_domain_unicode_no_contacts_with_remark.json
- core/src/test/resources/google/registry/rdap/rdapjson_domain_full.json
- core/src/test/resources/google/registry/rdap/rdapjson_domain_logged_out.json
- core/src/test/resources/google/registry/rdap/rdapjson_domain_no_nameservers.json
- core/src/test/resources/google/registry/rdap/rdapjson_registrant_nobase.json
As part of this change, it was necessary to do changes in the JPATM that
are similar (but the opposite) of the changes that we did in
DatastoreTM with regards to converting HistoryEntries to and from the
*History classes.
We leave the ofy() calls in the MapReduce ResaveAllHistoryEntriesAction
for now; that can be converted during the Beam pipeline transition.
Some other tests required registrar-name fixes as well -- because
*History objects have a foreign key on the Registrar table, we have to
use a "real" registrar name in tests.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/933)
> Convert (most) HistoryEntry ofy calls to tm

- core/src/main/java/google/registry/flows/TlsCredentials.java
- core/src/test/java/google/registry/flows/FlowRunnerTest.java
FlowRunner.run() logs these credentials to the GAE logs by implicitly using the
toString() method, so we need to add it if we want it to appear in the logs.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/945)
> Add clientCertificate to TlsCredentials.toString()

- core/src/main/java/google/registry/flows/TlsCredentials.java
- core/src/test/java/google/registry/flows/TlsCredentialsTest.java
Hopefully this will fix the issue with the cert requirements rollout to sandbox. This header is a magic string and should be specified in only one place to prevent future issues like this. I will fix this in a follow up PR.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/946)
> Fix typo in header name in Client Certificate Provider

- core/src/main/java/google/registry/flows/TlsCredentials.java
- core/src/main/java/google/registry/flows/certs/CertificateChecker.java
- core/src/main/java/google/registry/tools/ValidateLoginCredentialsCommand.java
- core/src/test/java/google/registry/flows/EppLoginTlsTest.java
- core/src/test/java/google/registry/flows/EppTestCase.java
- core/src/test/java/google/registry/flows/session/LoginFlowViaTlsTest.java
- proxy/src/test/java/google/registry/proxy/handler/EppServiceHandlerTest.java
- util/src/main/java/google/registry/util/X509Utils.java
This prevents the issue seen in Sandbox where the encoded certificate string passed from the proxy is not in the same format as the certificate String stored in the Registrar object. By converting both strings to certificates, we can check equality of the actual certificates rather than the String representation of them which always have a potential to be different due to separate formatting, extra spaces, etc. See b/178530285 for more info.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/948)
> Convert Strings to X509 Certificates before validating

- core/src/test/java/google/registry/model/ImmutableObjectSubject.java
- core/src/test/java/google/registry/model/ImmutableObjectSubjectTest.java
- core/src/test/java/google/registry/testing/ReplayExtension.java
Cross-database comparison was previously just a shallow check: fields marked
with DoNotCompare on nested objects were still compared.  This causes problems
in some cases where there are nested immutable objects.
This change introduces recursive comparison.  It also provides a
hasCorrectHashCode() method that verifies that an object has not been mutated
since the hash code was calculated, which has been a problem in certain cases.
Finally, this also fixes the problem of objects that are mutated in multiple
transactions: we were previously comparing against the value in datastore, but
this doesn't work in these cases because the object in datastore may have
changed since the transaction that we are verifying.  Instead, check against
the value that we would have persisted in the original …
> Make cross database comparison recursive

- core/src/main/java/google/registry/model/domain/DomainContent.java
- core/src/test/java/google/registry/testing/FullFieldsTestEntityHelper.java
Datastore inequality queries don't work correctly for null; null is treated as
the lowest value possible which is definitely the opposite of the intended
meaning here.
This includes an @OnLoad for backfilling purposes using the ResaveAll mapreduce.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/949)
> Use END_OF_TIME as sentinel value for domain's autorenewEndTime

- core/src/main/java/google/registry/tools/CreateOrUpdateRegistrarCommand.java
- core/src/main/java/google/registry/tools/CreateRegistrarCommand.java
- core/src/main/java/google/registry/tools/UpdateRegistrarCommand.java
- core/src/test/java/google/registry/tools/CreateRegistrarCommandTest.java
- core/src/test/java/google/registry/tools/UpdateRegistrarCommandTest.java
As discussed, we're keeping registrar in the "replicated" category.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/952)
> Remove dual-write of registrar from tool commands

- config/presubmits.py
- core/src/main/java/google/registry/persistence/transaction/JpaTransactionManagerImpl.java
- core/src/main/java/google/registry/tools/javascrap/BackfillSpec11ThreatMatchesCommand.java
This PR proposes a coding style convention that helps prevent
SQL-injection attacks, and is easy to enforce in the presubmit check.
SQL-injections can be effectively prevented if all parameterized queries
are generated using the proper param-binding methods. In our project
which uses Hibernate exclusively, this can be achieved if we all follow
a simple convention: only use constant sql templates assigned to static
final String variables as the first parameter to creat(Native)Query
methods.
This PR adds a presubmit check to enforce the proposed rule, and
modified one class as a demo. If the team agrees with this proposal, we
will change all other use cases.
--- …
> Add a presubmit check to require use of templated SQL string literals

- core/src/main/java/google/registry/model/domain/DomainContent.java
- core/src/main/java/google/registry/model/poll/PollMessage.java
- core/src/main/java/google/registry/model/transfer/DomainTransferData.java
- core/src/main/java/google/registry/model/transfer/TransferData.java
- core/src/test/java/google/registry/flows/domain/DomainDeleteFlowTest.java
- core/src/test/java/google/registry/flows/domain/DomainRenewFlowTest.java
- core/src/test/java/google/registry/flows/domain/DomainUpdateFlowTest.java
Add database comparison to the replay tests for DomainDeleteFlowTest,
DomainRenewFlowTest and DomainUpdateFlowTest.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/963)
> Add db-compare tests to three more flows

- core/src/main/java/google/registry/persistence/PersistenceModule.java
Stop using the SecretManager for SQL credential in BEAM for now. The
SecretManager cannot be injected into the code on pipeline workers
because RegistryEnvironment is not set.
See b/179839014 for details.
The SecretManager is verified to work with Registry server and Nomulus tool.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/961)
> Revert BEAM pipeline back to SQL credential file

- core/src/main/java/google/registry/flows/domain/DomainCheckFlow.java
- core/src/test/java/google/registry/flows/domain/DomainCheckFlowTest.java
- core/src/test/resources/google/registry/flows/domain/domain_check_fee_reserved_dupes_response_v12.xml
- core/src/test/resources/google/registry/flows/domain/domain_check_fee_reserved_dupes_v06.xml
- core/src/test/resources/google/registry/flows/domain/domain_check_fee_reserved_dupes_v12.xml
- core/src/test/resources/google/registry/flows/domain/domain_check_fee_reserved_response_dupes_v06.xml
There were instances of "java.lang.IllegalArgumentException: Multiple entries
with same key" in the logs, caused by attempting to construct an ImmutableMap
containing duplicate keys. It turns out this was happening in the domain check
flow when the following conditions were all simultaneously met:
1. The older v06 fee extension is used
2. The same domain name is being queried multiple times in a single check
command (which is valid per the spec but doesn't actually make any sense)
3. Said domain exists
4. The cost of a restore (an uncommon operation) is being checked
When all of those conditions were met, an error was being thrown when the
dupe-containing list of domain names was used as the keys of a new Map. This
fixes that bug by calling .distinct() first.
Give enough registrars enough …
> Fix obscure bug when checking restore prices of duplicate domain names

- core/src/main/java/google/registry/model/poll/PollMessage.java
- core/src/test/java/google/registry/flows/contact/ContactTransferApproveFlowTest.java
ContactTransferData is currently loaded back from SQL as an unspecialized
TransferData object.  Replace it with the ContactTransferData object that we
use it to reconstitute.
It's likely that this could be done more straightforwardly with a schema
change.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/967)
> Fix ContactTransferData SQL loads

- core/src/main/java/google/registry/model/registrar/Registrar.java
- core/src/main/java/google/registry/rdap/RdapEntityAction.java
- core/src/main/java/google/registry/rdap/RdapJsonFormatter.java
- core/src/main/java/google/registry/rdap/RdapSearchActionBase.java
- core/src/main/java/google/registry/rdap/UpdateRegistrarRdapBaseUrlsAction.java
- core/src/test/java/google/registry/rdap/RdapEntityActionTest.java
- core/src/test/java/google/registry/rdap/RdapJsonFormatterTest.java
- core/src/test/java/google/registry/rdap/UpdateRegistrarRdapBaseUrlsActionTest.java
This converts the simple retrieval actions but does not touch the more
complicated search actions -- those use some ofy() query searching logic
and will likely end up being significantly more complicated than this
change. Here, though, we are just changing the calls that can be
converted easily to tm() lookups.
To change in future PRs:
- RdapDomainSearchAction
- RdapEntitySearchAction
- RdapNameserverSearchAction
- RdapSearchActionBase
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/964)
> Partially convert RDAP ofy calls to tm calls

- core/src/main/java/google/registry/model/ofy/EntityWritePriorities.java
- core/src/test/java/google/registry/flows/contact/ContactCreateFlowTest.java
This test exposed a write priority issue between ContactResource and
ContactHistory entries.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/976)
> Add replay & compare to ContactCreateFlowTest test

- config/presubmits.py
- core/src/main/java/google/registry/model/common/DatabaseTransitionSchedule.java
- core/src/main/java/google/registry/persistence/transaction/CriteriaQueryBuilder.java
- core/src/main/java/google/registry/rdap/RdapActionBase.java
- core/src/main/java/google/registry/rdap/RdapEntitySearchAction.java
- core/src/main/java/google/registry/rdap/RdapSearchActionBase.java
- core/src/test/java/google/registry/persistence/transaction/CriteriaQueryBuilderTest.java
- core/src/test/java/google/registry/rdap/RdapEntitySearchActionTest.java
- core/src/test/java/google/registry/testing/AppEngineExtension.java
- Adds a CriteriaQueryBuilder class that allows us to build
CriteriaQuery objects with sane and modular WHERE and ORDER BY clauses.
CriteriaQuery requires that all WHERE and ORDER BY clauses be specified
at the same time (else later ones will overwrite the earlier ones) so in
order to have a proper builder pattern we need to wait to build the
query object until we are done adding clauses.
- In addition, encapsulating the query logic in the CriteriaQueryBuilder
class means that we don't need to deal with the complicated Root/Path
branching, otherwise we'd have to keep track of CriteriaQuery and Root
objects everywhere.
- Adds the logic to use that query builder in RdapSearchActionBase to query SQL for the items we want to search for.
- Adds a REPLAYED_ENTITIES TransitionId that will …
> Add SQL searching to RdapEntitySearchAction and RdapSearchActionBase

- core/src/main/java/google/registry/export/ExportPremiumTermsAction.java
- core/src/main/java/google/registry/model/registry/label/PremiumList.java
- core/src/main/java/google/registry/tools/GetPremiumListCommand.java
- core/src/main/java/google/registry/tools/RegistryTool.java
- core/src/test/java/google/registry/tools/GetPremiumListCommandTest.java
When testing the premium list refactor, it would have been nice and
convenient to have this. Currently we have no way of inspecting premium
list contents that I'm aware of that doesn't involve manually looking
at the Datastore or SQL entries.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/972)
> Add GetPremiumListCommand

- core/src/main/java/google/registry/env/production/default/WEB-INF/cron.xml
GAE cron only issuse HTTP GET requests to the endpoint in question. This
particular only allows POSTs. As a result this cron job never succeeded.
This is not a big problem as this job is meant to catch up any
unforeseen upload failures and in case it needs to catch up but fails,
every month the staging job (which is enqueued corrected by cron) will
eventually catch everything to date.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/984)
> Use fanout action to run ICANN report upload job in cron

- build.gradle
- projects.gradle
This depends on a PR in the internal repo.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/986)
> Allow AppEngine deployment to qa environment

- core/src/main/java/google/registry/request/RequestHandler.java
This seems like more reasonable. It will potential issues with how
requests are generated more discoverable in the log.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/983)
> Log forbidden HTTP request method at warning

- config/nom_build.py
- db/build.gradle
Simplified the command line by revising the semantics of some
properties.
Added examples of Flyway task invocations.
This script still uses the GCS file-based credential. We will migrate it
to the Secret Manager soon.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/990)
> Clean up Gradle Flyway tasks in :db

- core/src/main/java/google/registry/model/EntityClasses.java
- core/src/main/java/google/registry/model/ofy/Ofy.java
- core/src/main/java/google/registry/persistence/transaction/Transaction.java
- core/src/main/java/google/registry/persistence/transaction/TransactionEntity.java
- core/src/main/java/google/registry/schema/replay/LastSqlTransaction.java
- core/src/main/java/google/registry/schema/replay/ReplicateToDatastoreAction.java
- core/src/test/java/google/registry/persistence/transaction/TransactionTest.java
- core/src/test/java/google/registry/schema/replay/ReplicateToDatastoreActionTest.java
- core/src/test/resources/google/registry/export/backup_kinds.txt
- core/src/test/resources/google/registry/model/schema.txt
Implement the ReplicateToDatastore cron job that will apply all Cloud SQL
transactions to the datastore.  The last transaction id is stored in a
LastSqlTransaction entity in datastore.
Note that this will not be activate in production until a) the cron
configuration is updated and b) the cloudSql.replicateTransactions flag is set
to true in the nomulus config file.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/738)
> Replay Cloud SQL transactions against datastore

- core/build.gradle
- core/src/main/java/google/registry/tools/RegistryToolComponent.java
- core/src/main/java/google/registry/whois/BaseWhoisModule.java
- core/src/main/java/google/registry/whois/DomainLookupCommand.java
- core/src/main/java/google/registry/whois/NameserverLookupByHostCommand.java
- core/src/main/java/google/registry/whois/NonCachingWhoisModule.java
- core/src/main/java/google/registry/whois/RegistrarLookupCommand.java
- core/src/main/java/google/registry/whois/WhoisCommandFactory.java
- core/src/main/java/google/registry/whois/WhoisReader.java
- core/src/test/java/google/registry/whois/WhoisActionTest.java
- core/src/test/java/google/registry/whois/WhoisCommandFactoryTest.java
- core/src/test/java/google/registry/whois/WhoisHttpActionTest.java
- core/src/test/java/google/registry/whois/WhoisReaderTest.java
The whois commands previously served output generated from cached EppResource
objects in most cases.  While this is entirely appropriate from server-side,
it is less useful when these commands are run from nomulus tool and, in fact,
when run from the "shell" command this results in changes that have been
applied from the shell not being visible from a subsequent "whois".  The
command may instead serve information on an earlier, cached version of the
resource instead of the latest version.
This implementation uses dagger for parameterization of cached/non-cached
modes.  I did consider the possibility of simply parameterizing the query
commands in all cases as discussed, however, having gone down the
daggerization path and having gotten it to work, I have to say I find this
approach …
> Disable whois caching in nomulus tool

- core/src/main/java/google/registry/flows/ResourceFlowUtils.java
- core/src/main/java/google/registry/flows/domain/DomainFlowUtils.java
- core/src/main/java/google/registry/flows/domain/DomainTransferRejectFlow.java
- core/src/main/java/google/registry/model/ResourceTransferUtils.java
- core/src/main/java/google/registry/model/ofy/DatastoreTransactionManager.java
- core/src/main/java/google/registry/model/poll/PollMessage.java
- core/src/main/java/google/registry/model/transfer/DomainTransferData.java
- core/src/main/java/google/registry/model/transfer/TransferData.java
- core/src/main/java/google/registry/persistence/transaction/JpaTransactionManagerImpl.java
- core/src/main/java/google/registry/persistence/transaction/TransactionManager.java
- core/src/test/java/google/registry/flows/domain/DomainTransferRejectFlowTest.java
- core/src/test/java/google/registry/model/ImmutableObjectSubject.java
- core/src/test/java/google/registry/model/domain/DomainBaseSqlTest.java
- core/src/test/java/google/registry/testing/DatabaseHelper.java
This change includes a few other necessary dependencies to converting
DomainTransferRejectFlowTest to be a dual-database test. Namely:
- The basic "use tm() instead of ofy()" and "branching database
selection on what were previously raw ofy queries"
- Modification of the PollMessage convertVKey methods to do what they
say they do
- Filling the generic pending / response fields in PollMessage based on what type of
poll message it is (this has to be done because SQL is not very good at
storing ambiguous superclasses)
- Setting the generic pending / repsonse fields in PollMessage upon
build
- Filling out the serverApproveEntities field in DomainTransferData with
all necessary poll messages / billing events that should be cancelled on
rejection
- Scattered changes in DatabaseHelper to make …
> Convert DomainTransferRejectFlow to use tm() methods

- config/nom_build.py
- db/build.gradle
Script wrongly assumed that Flyway task is invoked if --environment is
set.
Bug was introduced in go/r3pr/940
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/993)
> Fix flyway invocation in Gradle script

- java-format/google-java-format-diff.py
- java-format/google-java-format-git-diff.sh
Print out JAVA_HOME and PATH variable in the google-java-format-diff.py script
immediately prior to running the underlying java program that does the actual
format checking.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/998)
> Print out env variables in java format

- core/src/main/java/google/registry/config/files/default-config.yaml
We should choose a different database name for nomulus data since using
'postgres' is bad practice. See b/181693544 more background.
We have decided to delay the db change to the time when we upgrade
postgresql version. This PR adds TODOs to all occurrences of the jdbcUrl
property, including those in the internal-repo. This property will change
when we upgrade, so the TODOs will be noticed.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/1005)
> Add TODOs regarding cloud sql database name change

- java-format/google-java-format-git-diff.sh
It turns out that the --fork-point option is subtle and error-prone.  Its
intent is not to show the nearest common base commit, but rather the commit
on a branch that the HEAD (in this case) was originally forked off of,
_whether it is currently part of the history of the specified branch or not_
(this can happen if the branch is rewritten).  The option also relies on the
presence of the fork point in the reflog for the branch, which can be
discarded in the course of a "git gc".
It is fairly easy to construct a case where the use of --fork-point causes an
error and outputs nothing.  In fact, I discovered the problem as a result of
this occuring spontaneously on one of my own branches (likely related to a
rebase).  Since the fork-point is empty, we end up diffing against the index
instead …
> Don't use --fork-point to determine merge base

- core/src/main/java/google/registry/flows/domain/DomainTransferRequestFlow.java
- core/src/main/java/google/registry/model/transfer/DomainTransferData.java
- core/src/test/java/google/registry/flows/FlowTestCase.java
- core/src/test/java/google/registry/flows/domain/DomainTransferRequestFlowTest.java
Besides the standard ofy-to-tm conversions this includes storing the
billing event cancellation VKey in the DomainTransferData object so that
we know to handle it on process / cancellation.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/1002)
> Convert DomainTransferRequestFlow to tm() calls

- core/src/main/java/google/registry/config/files/default-config.yaml
I believe the similarity in trace to https://github.com/brettwooldridge/HikariCP/issues/1212
is misleading.
The real cause of the exceptions may be that we ran out of connections. At the
time, the production Cloud SQL server could handle 500 connections at the
maximum. That number was within reach of a busy Nomulus server.
The maximum connection in production has been increased to 1000. We
haven't encountered this issue for a long time. All connection problems
are due to Cloud SQL maintenance or other GCP related issues.
This issue is tracked by b/154720215, which is being closed with this
PR.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/1012)
> Closing the bug regarding Cloud SQL connection configs

- core/build.gradle
- core/src/main/java/google/registry/beam/datastore/BulkDeleteDatastorePipeline.java
- core/src/main/resources/google/registry/beam/bulk_delete_datastore_pipeline_metadata.json
- core/src/test/java/google/registry/beam/datastore/BulkDeleteDatastorePipelineTest.java
- release/cloudbuild-nomulus.yaml
- release/stage_beam_pipeline.sh
Allow multiple BEAM pipelines with the same classes and dependencies to
share one Uber jar.
Added metadata for BulkDeleteDatastorePipeline.
Updated shell and Cloud Build scripts to stage all pipelines in one
step.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/1008)
> Use shared jar to stage BEAM pipeline if possible

- core/src/main/java/google/registry/model/domain/DomainContent.java
- core/src/main/java/google/registry/model/domain/GracePeriod.java
- core/src/test/java/google/registry/model/domain/DomainBaseTest.java
I verified in BigQuery that all grace period IDs are now allocated (as expected
given that the re-save all EPP resource mapreduce has been run several times
since this migration started last year). The query I used for verification is:
SELECT fullyQualifiedDomainName, gp, ot
FROM `domain-registry.latest_datastore_export.DomainBase`
JOIN UNNEST(gracePeriods.billingEventRecurring) AS gp
JOIN UNNEST(gracePeriods.billingEventOneTime) AS ot
WHERE gp.id IS NULL or ot.id IS NULL
BUG=169873747
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/1016)
> Remove grace period ID @OnLoads now that migration is complete

- core/src/main/java/google/registry/flows/domain/DomainRestoreRequestFlow.java
- core/src/main/java/google/registry/model/domain/DomainContent.java
- core/src/test/java/google/registry/flows/domain/DomainRestoreRequestFlowTest.java
This allows us to still see in the database which now-deleted domains had
reached expiration, while correctly not re-deleting the domain immediately if
the registrar pays to explicitly restore the domain.
This also resolves some TODOs around data migration for this field on domain so
that it's not null, as said migration has already been completed.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/1015)
> Clear autorenew end time when a domain is restored

- core/src/main/java/google/registry/privileges/secretmanager/SqlUser.java
- core/src/main/java/google/registry/tools/GetSqlCredentialCommand.java
- db/src/main/resources/sql/user/create_schema_deployer_user.sql
Add the 'schema_deployer' user to the SecretManager so that its
credential can be set up. The schema deployment process will use this
user instead of the 'postgres' user.
Changed the output of the get_sql_credential command for the schema
deployment process.
Added a sql script that documents the privileges granted to
'schema_deployer'.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/1018)
> Add schema_deployer SQL user to SecretManager

- release/builder/build.sh
Our builder comes with python3.6 and cannot support nom_build out of
box. Nom_build requires dataclasses which is introduced in v3.7.
I haven't found an easy way to get python3.7+ without changing the base
linux image. This PR explicitly installs dataclasses.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/1021)
> Allow nom_build to run in Cloudbuild

- core/src/test/java/google/registry/batch/DeleteExpiredDomainsActionTest.java
Though hard to reproduce locally, the test_deletesThreeDomainsInOneRun
test has failed multiple times on Kokoro. The root cause may be the
non-transactional query executed by the Action object, which was by
design. Observing that the other test never fails, this PR follows its behavior
and adds a transactional query before invoking the action.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/1022)
> Attempt to fix flakey deleteExpiredDomain test

- core/src/test/java/google/registry/flows/contact/ContactUpdateFlowTest.java
- core/src/test/java/google/registry/flows/domain/DomainCheckFlowTest.java
- core/src/test/java/google/registry/flows/domain/DomainInfoFlowTest.java
- core/src/test/java/google/registry/flows/domain/DomainRenewFlowTest.java
- core/src/test/java/google/registry/flows/host/HostCreateFlowTest.java
- core/src/test/java/google/registry/flows/host/HostDeleteFlowTest.java
- core/src/test/java/google/registry/flows/host/HostInfoFlowTest.java
- core/src/test/java/google/registry/flows/host/HostUpdateFlowTest.java
- core/src/test/java/google/registry/flows/poll/PollAckFlowTest.java
- core/src/test/java/google/registry/flows/poll/PollRequestFlowTest.java
- core/src/test/java/google/registry/testing/DatabaseHelper.java
- core/src/test/java/google/registry/testing/SetClockExtension.java
- core/src/test/resources/google/registry/flows/poll/poll_response_contact_transfer.xml
- db/src/main/resources/sql/er_diagram/brief_er_diagram.html
- db/src/main/resources/sql/er_diagram/full_er_diagram.html
- db/src/main/resources/sql/flyway.txt
- db/src/main/resources/sql/flyway/V89__host_history_host_deferred.sql
- db/src/main/resources/sql/schema/nomulus.golden.sql
Convert all remaining flow tests to do replay/compare testing.  In the course
of this:
- Move the class specific SetClock extension into its own place.
- Fix another "cyclic" foreign key (there may be another solution in this case
because HostHistory is actually different from HistoryEntry, but that would
require changing the way we establish priority since HostHistory is not
distinguished from HistoryEntry in the current methodology)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/1020)
> Add replay to remaining (non-trivial) flow tests

- config/presubmits.py
- core/src/main/java/google/registry/rdap/RdapDomainSearchAction.java
- core/src/main/java/google/registry/rdap/RdapNameserverSearchAction.java
- core/src/main/java/google/registry/rdap/RdapSearchActionBase.java
- core/src/test/java/google/registry/rdap/RdapNameserverSearchActionTest.java
This has the same issue as the domain-search action where the database
ordering is not consistent between Objectify and SQL -- as a result,
there is one test that we have to duplicate in order to account for the
two sort orders.
In addition, there isn't a way to query @Convert-ed fields in Postgres
via the standard Hibernate / JPA query language, meaning we have to use
a raw Postgres query for that.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/987)
> Add SQL queries to RdapNameserverSearchAction

- core/src/main/java/google/registry/request/auth/AppEngineInternalAuthenticationMechanism.java
- core/src/test/java/google/registry/request/auth/RequestAuthenticatorTest.java
Stop simply relying on the presence of the X-AppEngine-QueueName as an
indicator that an endpoint has been triggered internally, as this allows
admins to trigger a remote execution vulnerability.
We now supplement this check by ensuring that there is no authenticated user.
Since only an admin user can set these headers, this means that the header
must have been set by an internal request.
Tested:
In addition to the new unit test, verified on Crash that:
- Internal requests are still getting authenticated via the internal auth
mechanism.
- Admin requests with the X-AppEngine-QueueName header are rejected as
"unauthorized."
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/1030 …
> Disallow admin triggering of internal endpoints

- core/build.gradle
- docs/install.md
Add a Gracle task to stage flex-template based pipelines for alpha and
crash environments.
This is a follow up to go/r3pr/1028, which is also under review.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/1031)
> Add Gradle tasks to stage BEAM pipelines

- core/src/test/java/google/registry/flows/contact/ContactTransferRequestFlowTest.java
- core/src/test/java/google/registry/flows/domain/DomainTransferRequestFlowTest.java
- core/src/test/java/google/registry/flows/host/HostUpdateFlowTest.java
- core/src/test/java/google/registry/model/billing/BillingEventTest.java
- core/src/test/java/google/registry/model/domain/token/AllocationTokenTest.java
- core/src/test/java/google/registry/testing/DatabaseHelper.java
- core/src/test/java/google/registry/tools/DeleteAllocationTokensCommandTest.java
- core/src/test/java/google/registry/tools/GenerateAllocationTokensCommandTest.java
These can only be called by test code, and they automatically wrap the load
in a transaction if one isn't already specified (for convenience).
In production code we don't want to be able to use these, as we have to be
more thoughtful about transactions in production code (e.g. make sure that
we aren't loading and then saving a resource in separate transactions in a
way that makes it prone to contention errors).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/1038)
> Add some load convenience methods to DatabaseHelper

- core/src/main/java/google/registry/batch/WipeOutCloudSqlAction.java
- core/src/main/java/google/registry/env/common/backend/WEB-INF/web.xml
- core/src/main/java/google/registry/env/qa/default/WEB-INF/cron.xml
- core/src/main/java/google/registry/module/backend/BackendComponent.java
- core/src/main/java/google/registry/module/backend/BackendRequestComponent.java
- core/src/main/java/google/registry/persistence/PersistenceModule.java
- core/src/test/java/google/registry/batch/WipeOutCloudSqlActionTest.java
- core/src/test/resources/google/registry/module/backend/backend_routing.txt
Added the WipeOutSqlAction that deletes all data in Cloud SQL.
Wipe out is restricted to the QA environment, which will get production
data during migration testing.
Also added a cron job that invokes wipeout on every saturday morning.
This is part of the privacy requirments for using production data in QA.
Tested in QA.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/1035)
> Add SQL wipeout action in QA

- core/src/main/java/google/registry/export/AnnotatedEntities.java
- core/src/main/java/google/registry/export/BackupDatastoreAction.java
- core/src/main/java/google/registry/model/annotations/InCrossTld.java
- core/src/main/java/google/registry/model/common/CrossTldSingleton.java
- core/src/main/java/google/registry/model/common/Cursor.java
- core/src/main/java/google/registry/model/common/DatabaseTransitionSchedule.java
- core/src/main/java/google/registry/model/ofy/DatastoreTransactionManager.java
- core/src/main/java/google/registry/model/registrar/Registrar.java
- core/src/main/java/google/registry/model/registrar/RegistrarContact.java
- core/src/main/java/google/registry/model/registry/Registry.java
- core/src/main/java/google/registry/model/registry/label/BaseDomainLabelList.java
- core/src/main/java/google/registry/model/registry/label/PremiumList.java
- core/src/main/java/google/registry/model/server/KmsSecret.java
- core/src/main/java/google/registry/model/server/KmsSecretRevision.java
- core/src/main/java/google/registry/model/smd/SignedMarkRevocationList.java
- core/src/main/java/google/registry/model/tmch/ClaimsListShard.java
- core/src/main/java/google/registry/persistence/transaction/TransactionManager.java
- core/src/main/java/google/registry/tools/LoadSnapshotCommand.java
- core/src/test/java/google/registry/export/AnnotatedEntitiesTest.java
- core/src/test/java/google/registry/export/BackupDatastoreActionTest.java
- core/src/test/java/google/registry/model/ofy/DatastoreTransactionManagerTest.java
- core/src/test/resources/google/registry/export/crosstld_kinds.txt
The loadAllOf() method will now automatically append the cross-TLD entity group
ancestor query as necessary, iff the entity class being loaded is tagged with
the new @IsCrossTld annotation.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/1040)
> Make TransactionManager.loadAllOf() smart w.r.t the cross-TLD entity group

- core/src/main/java/google/registry/flows/FlowUtils.java
- core/src/main/java/google/registry/flows/custom/EntityChanges.java
- core/src/main/java/google/registry/model/index/ForeignKeyIndex.java
- core/src/main/java/google/registry/model/poll/PollMessage.java
- core/src/main/java/google/registry/model/smd/SignedMarkRevocationListDao.java
- core/src/main/java/google/registry/model/tmch/ClaimsListShard.java
- core/src/main/java/google/registry/persistence/transaction/JpaTransactionManagerImpl.java
- core/src/test/java/google/registry/flows/ResourceFlowTestCase.java
- core/src/test/java/google/registry/flows/domain/DomainCreateFlowTest.java
- core/src/test/java/google/registry/persistence/transaction/TransactionManagerTest.java
Various necessary changes included as part of this:
- Make ForeignKeyIndex completely generic. Previously, only the load()
method that took a DateTime as input could use SQL, and the cached flow
was particular to Objectify Keys. Now, the cached flow and the
non-cached flow can use the same (ish) piece of code to load / create
the relevant index objects before filtering or modifying them as
necessary.
- EntityChanges should use VKeys
- FlowUtils should persist entity changes using tm(), however not all
object types are storable in SQL.
- Filling out PollMessage fields with the proper object type when
loading from SQL
- Changing a few tm() calls to ofyTm() calls when using objectify. This
is because creating a read-only transaction in SQL is quite a footgun at
the moment, because it makes …
> Convert DomainCreateFlow to use generic tm() methods

- core/src/main/java/google/registry/flows/domain/DomainTransferApproveFlow.java
- core/src/test/java/google/registry/flows/domain/DomainFlowUtilsTest.java
- core/src/test/java/google/registry/flows/domain/DomainTransferApproveFlowTest.java
- core/src/test/java/google/registry/flows/domain/DomainTransferFlowTestCase.java
The only tricky part to this is that the order of entities that we're
saving during the DomainTransferApproveFlow matters -- some entities
have dependencies on others so we need to save the latter first. We
change `entitiesToSave` to be a list to reinforce this.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/1045)
> Convert DomainTAF and DomainFlowUtils to SQL

- core/src/main/java/google/registry/model/UpdateAutoTimestamp.java
- core/src/main/java/google/registry/model/common/GaeUserIdConverter.java
- core/src/main/java/google/registry/model/registrar/RegistrarContact.java
- core/src/main/java/google/registry/ui/server/registrar/ConsoleRegistrarCreatorAction.java
- core/src/main/java/google/registry/ui/server/registrar/RegistrarSettingsAction.java
- core/src/test/java/google/registry/ui/server/registrar/ConsoleRegistrarCreatorActionTest.java
- core/src/test/java/google/registry/ui/server/registrar/RegistrarSettingsActionTest.java
- core/src/test/java/google/registry/ui/server/registrar/RegistrarSettingsActionTestCase.java
Relevant potentially-unclear changes:
- Making sure the last update time is always correct and up to date in
the auto timestamp object
- Reloading the domain upon return when updating in a new transaction to
make sure that we use the properly-updated last update time (SQL returns
the correct result if retrieved within the same txn but DS does not)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/1042)
> Update RegistrarSettingsAction and RegistrarContact to SQL calls

- core/src/main/java/google/registry/persistence/VKey.java
- core/src/main/java/google/registry/tools/DedupeOneTimeBillingEventIdsCommand.java
- core/src/main/java/google/registry/tools/MutatingCommand.java
- core/src/main/java/google/registry/tools/ReadEntityFromKeyPathCommand.java
- core/src/test/java/google/registry/tools/DedupeOneTimeBillingEventIdsCommandTest.java
- core/src/test/java/google/registry/tools/MutatingCommandTest.java
Convert ofy -> tm for MutatingCommand and DedupeOneTimeBillingEventIdsCommand.
Note that DedupeOneTimeBillingEventIdsCommand will not be needed after
migration, so this conversion is just to remove the ofy uses from the
codebase.  We don't update the test (other than to keep it working) and it
wouldn't currently work in SQL.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/1049)
> Convert ofy -> tm for two more classes

- core/src/main/java/google/registry/flows/poll/PollAckFlow.java
- core/src/main/java/google/registry/flows/poll/PollFlowUtils.java
- core/src/main/java/google/registry/flows/poll/PollRequestFlow.java
- core/src/main/java/google/registry/model/poll/PollMessage.java
- core/src/main/java/google/registry/model/poll/PollMessageExternalKeyConverter.java
- core/src/main/java/google/registry/tools/AckPollMessagesCommand.java
- core/src/test/java/google/registry/flows/poll/PollAckFlowTest.java
- core/src/test/java/google/registry/flows/poll/PollRequestFlowTest.java
- core/src/test/java/google/registry/model/poll/PollMessageExternalKeyConverterTest.java
- core/src/test/java/google/registry/testing/DatabaseHelper.java
- core/src/test/java/google/registry/tools/AckPollMessagesCommandTest.java
- core/src/test/resources/google/registry/model/schema.txt
Two relatively complex parts. The first is that we needed a small
refactor on the AckPollMessagesCommand because we could theoretically be
acking more poll messages than the Datastore transaction size boundary.
This means that the normal flow of "gather the poll messages from the DB
into one collection, then act on it" needs to be changed to a more
functional flow.
The second is that acking the poll message (deleting it in most cases)
reduces the number of remaining poll messages in SQL but not in
Datastore, since in Datastore the deletion does not take effect until
after the transaction is over.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/1050)
> Convert poll-message-related classes to use SQL as well

- db/build.gradle
- release/cloudbuild-schema-deploy.yaml
- release/schema-deployer/deploy_sql_schema.sh
Fetch the schema_deployer credential from SecretManager when deploying
the schema to Cloud SQL.
Tested: deployed to crash using alpha's cloudbuild.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/1055)
> Use credential in secretmanager to deploy schema

- vnames.json
This change should allow generated classes like AutoValue or Dagger
classes to be cross-referencable on cs.nomulus.foo
See b/184284124 for context.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/1057)
> Enable cross referencing for generated sources

- core/src/main/java/google/registry/batch/RefreshDnsOnHostRenameAction.java
- core/src/main/java/google/registry/model/server/Lock.java
- core/src/main/java/google/registry/persistence/VKey.java
- core/src/test/java/google/registry/batch/RefreshDnsOnHostRenameActionTest.java
- core/src/test/java/google/registry/testing/DualDatabaseTestInvocationContextProvider.java
This is not quite complete because it also requires the conversion of a
map-reduce which is in scope for an entirely different work.  Tests of the
map-reduce functionality are excluded from the SQL run.
This also requires the following additional fixes:
-  Convert Lock to tm, as doing so was necessary to get this action to work.
As Lock is being targeted as DatastoreOnly, we convert all calls in it to
use ofyTm()
-  Fix a bug in DualDatabaseTest (the check for an AppEngineExtension field is
wrong, and captures fields of type Object as AppEngineExtension's)
-  Introduce another VKey.from() method that creates a VKey from a stringified
Ofy Key.
--- …
> Convert RefreshDnsOnHostRenameAction to tm

- release/cloudbuild-sync.yaml
Release folders now are no longer flat. Each of them has a 'beam'
subfolder with pipeline metadata files.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/1063)
> Add -r when rsync a release to the live folder

- core/src/main/java/google/registry/model/EppResourceUtils.java
- core/src/main/java/google/registry/model/index/ForeignKeyIndex.java
- core/src/main/java/google/registry/whois/NameserverLookupByIpCommand.java
- core/src/test/java/google/registry/testing/FullFieldsTestEntityHelper.java
- core/src/test/java/google/registry/whois/WhoisActionTest.java
- core/src/test/java/google/registry/whois/WhoisCommandFactoryTest.java
- core/src/test/java/google/registry/whois/WhoisHttpActionTest.java
- core/src/test/java/google/registry/whois/WhoisReaderTest.java
Some of the rest will depend on b/184578521.
The primary conversion in this PR is the change in
NameserverLookupByIpCommand as that is the only place where the removed
EppResourceUtils method was called. We also convert to DualDatabaseTest
the tests of the callers of NLBIC. and use a CriteriaQueryBuilder in the
foreign key index SQL lookup (allowing us to avoid the String.format
call).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/1060)
> Partially convert EppResourceUtils to SQL

- core/build.gradle
BSD sed behaves differently than Linux sed. By adding a "-e" flag the
comand works in both systems.
See: https://unix.stackexchange.com/questions/101059/sed-behaves-different-on-freebsd-and-on-linux
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/1070)
> Make Numulus compile on macOS

- core/src/main/java/google/registry/tools/CompareReservedListsCommand.java
- core/src/main/java/google/registry/tools/RegistryTool.java
- core/src/test/java/google/registry/tools/CompareReservedListCommandTest.java
This command loads the list of all ReservedLists in Datastore and Cloud SQL and returns the name of any list that is either missing from one of the DBs or that has differing content. The output of this command does not indicate what the actual diff between the lists are, so GetReservedListCommand should be used to actually view the contents of the offending lists. 
I already ran this comparison test on Sandbox and Production and fixed all the issues it found. (One list I missed in Sandbox when resaving, and 7 lists that were only in Cloud SQL in production.)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/1054)
> Add a CompareReservedListCommand

- core/src/main/java/google/registry/keyring/kms/KmsKeyring.java
- core/src/main/java/google/registry/keyring/kms/KmsUpdater.java
- core/src/main/java/google/registry/module/frontend/FrontendComponent.java
- core/src/main/java/google/registry/module/pubapi/PubApiComponent.java
- core/src/main/java/google/registry/module/tools/ToolsComponent.java
- core/src/main/java/google/registry/privileges/secretmanager/KeyringSecretStore.java
- core/src/main/java/google/registry/privileges/secretmanager/SecretManagerClient.java
- core/src/main/java/google/registry/privileges/secretmanager/SqlCredentialStore.java
- core/src/main/java/google/registry/tools/MigrateKmsKeyringCommand.java
- core/src/main/java/google/registry/tools/RegistryTool.java
- core/src/main/java/google/registry/tools/RegistryToolComponent.java
- core/src/test/java/google/registry/keyring/kms/KmsKeyringTest.java
- core/src/test/java/google/registry/keyring/kms/KmsUpdaterTest.java
- core/src/test/java/google/registry/privileges/secretmanager/FakeSecretManagerClient.java
- core/src/test/java/google/registry/privileges/secretmanager/KeyringSecretStoreTest.java
Implented dual-read of Keyring secrets with Datastore as primary.
Implemented dual-write of keyring secrets with Datastore as primary.
Secret manager write failures are simply thrown. This is fine since all
keyring writes are manual, throught eh update_kms_keyring command.
Added a one-way migration command that copies all data to secret manager
(unencrypted).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/1072)
> Migrate Keyring secrets to Secret Manager

- core/src/main/java/google/registry/tools/SetDatabaseTransitionScheduleCommand.java
- core/src/test/java/google/registry/tools/SetDatabaseTransitionScheduleCommandTest.java
We cannot use the standard MutatingCommand because the DB schedule is
explicitly always stored in Datastore, and once we transition to
SQL-as-primary, MutatingCommand will stage the entity changes to SQL.
In addition, we remove the raw ofy() call from the test.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/1081)
> Specify explicit ofyTm usage in SetDatabaseTransitionScheduleCommand

- core/src/main/java/google/registry/tools/SendEscrowReportToIcannCommand.java
The injected object in SendEscrowReportToIcannCommand creates Ofy keys
in its static initialization routine. This happens before the RemoteApi
setup. Use lazy injection to prevent failure.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/1086)
> Use lazy injection in SendEscrow command

- core/src/main/java/google/registry/model/common/Cursor.java
- core/src/main/java/google/registry/rde/RdeReportAction.java
- core/src/main/java/google/registry/rde/RdeStagingReducer.java
- core/src/main/java/google/registry/rde/RdeUploadAction.java
- core/src/main/java/google/registry/reporting/icann/IcannReportingUploadAction.java
- core/src/test/java/google/registry/rde/RdeReportActionTest.java
- core/src/test/java/google/registry/rde/RdeUploadActionTest.java
In fact, the Cursor entity does not always exist (i.e. if an upload has never
previously been done on this TLD, i.e. it's a new TLD), and the code needs to be
resilient to its non-existence.
This bug was introduced in #1044.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/1088)
> Fix bug that was incorrectly assuming Cursor would always exist

- core/src/main/java/google/registry/model/ofy/DatastoreTransactionManager.java
- core/src/main/java/google/registry/persistence/transaction/CriteriaQueryBuilder.java
- core/src/main/java/google/registry/persistence/transaction/JpaTransactionManagerImpl.java
- core/src/main/java/google/registry/persistence/transaction/QueryComposer.java
- core/src/main/java/google/registry/persistence/transaction/TransactionManager.java
- core/src/main/java/google/registry/reporting/spec11/Spec11EmailUtils.java
- core/src/test/java/google/registry/persistence/transaction/QueryComposerTest.java
- core/src/test/java/google/registry/reporting/spec11/Spec11EmailUtilsTest.java
Implement a query abstraction layer ("QueryComposer") that allows us to
construct fluent-style queries that work across both Objectify and JPA.
As a demonstration of the concept, convert Spec11EmailUtils and its test to
use the new API.
Limitations:
-  The primary limitations of this system are imposed by datastore, for
example all queryable fields must be indexed, orderBy must coincide with
the order of any inequality queries, inequality filters are limited to one
property...
-  JPA queries are limited to a set of where clauses (all of which must match)
and an "order by" clause.  Joins, functions, complex where logic and
multi-table queries are simply not allowed.
-  Descending sort order is currently unsupported (this is simple enough to
add).
--- …
> Implement query abstraction

- core/src/main/java/google/registry/model/rde/RdeRevision.java
- core/src/main/java/google/registry/rde/RdeReportAction.java
- core/src/main/java/google/registry/rde/RdeUploadAction.java
- core/src/test/java/google/registry/rde/RdeReportActionTest.java
- core/src/test/java/google/registry/testing/GcsTestingUtils.java
Currently the RdeReportAction is hard coded to load the initial version
of a report. This is wrong when reports have been regenerated.
Changed lines are copied from RdeUploadAction.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/1089)
> Upload latest version of RDE report to icann

- core/src/main/java/google/registry/persistence/transaction/JpaTransactionManagerImpl.java
- core/src/test/java/google/registry/flows/EppTestCase.java
- core/src/test/java/google/registry/flows/FlowTestCase.java
- core/src/test/java/google/registry/model/CreateAutoTimestampTest.java
- core/src/test/java/google/registry/testing/DatabaseHelper.java
- core/src/test/java/google/registry/tmch/LordnTaskUtilsTest.java
- core/src/test/java/google/registry/tools/CreateRegistrarCommandTest.java
- core/src/test/java/google/registry/tools/UpdateCursorsCommandTest.java
The main weird bit here is adding a method in DatabaseHelper to
retrieve and initialize all objects in either database. The
initialization is necessary since it's used post-command-dry-run to make
sure that no changes were actually made.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/1078)
> Update various tests to work with SQL as well

- core/src/main/java/google/registry/flows/domain/DomainDeleteFlow.java
- core/src/test/java/google/registry/flows/domain/DomainDeleteFlowTest.java
- core/src/test/java/google/registry/testing/DatabaseHelper.java
This poll message is in addition to the normal poll message that is sent when
the domain's deletion is effective (typically 35 days later). It's needed
because, in the event of a superuser deletion, the owning registrar won't
otherwise necessarily know it's happening.
Note that, in the case of a --immediate superuser deletion, the normal poll
message is already being sent immediately, so this additional poll message is
not necessary.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/1096)
> Send an immediate poll message for superuser domain deletes

- core/src/main/java/google/registry/keyring/kms/KmsKeyring.java
If a secret does not exist in datastore, log and skip it.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/1098)
> Skip undefined secrets in keyring migration

- db/src/main/resources/sql/er_diagram/brief_er_diagram.html
- db/src/main/resources/sql/er_diagram/full_er_diagram.html
- db/src/main/resources/sql/flyway.txt
- db/src/main/resources/sql/flyway/V93__defer_all_fkeys.sql
- db/src/main/resources/sql/schema/nomulus.golden.sql
The main difference here is that the constraint violation exceptions
won't be thrown until the transaction is completed, rather than when the
insert is first performed within the transaction. We get the same error
message either way. The primary benefit to this is that when dealing
with large operations inside a single transaction (flows), we don't need
to worry about the order of insertions of removals with regards to
foreign keys.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/1094)
> Defer all foreign keys in SQL

- core/src/main/java/google/registry/flows/FlowModule.java
- core/src/main/java/google/registry/flows/domain/DomainCreateFlow.java
- core/src/main/java/google/registry/model/contact/ContactHistory.java
- core/src/main/java/google/registry/model/domain/DomainHistory.java
- core/src/main/java/google/registry/model/domain/GracePeriodBase.java
- core/src/main/java/google/registry/model/host/HostHistory.java
- core/src/main/java/google/registry/model/ofy/DatastoreTransactionManager.java
- core/src/main/java/google/registry/model/reporting/HistoryEntryDao.java
- core/src/main/java/google/registry/persistence/transaction/JpaTransactionManagerImpl.java
- core/src/test/java/google/registry/flows/EppLifecycleDomainTest.java
- core/src/test/java/google/registry/flows/domain/DomainTransferCancelFlowTest.java
- core/src/test/java/google/registry/mapreduce/inputs/ChildEntityInputTest.java
- core/src/test/java/google/registry/model/poll/PollMessageExternalKeyConverterTest.java
- core/src/test/java/google/registry/model/reporting/HistoryEntryDaoTest.java
- core/src/test/java/google/registry/model/reporting/HistoryEntryTest.java
- core/src/test/java/google/registry/rde/DomainBaseToXjcConverterTest.java
- core/src/test/java/google/registry/testing/DatabaseHelper.java
- core/src/test/java/google/registry/tools/DedupeRecurringBillingEventIdsCommandTest.java
- core/src/test/java/google/registry/tools/EppLifecycleToolsTest.java
- core/src/test/java/google/registry/tools/UpdateDomainCommandTest.java
- core/src/test/resources/google/registry/flows/poll_response_unrenew.xml
- core/src/test/resources/google/registry/model/schema.txt
We use DomainCreateFlow as an example here of how this will work. There
were a few changes necessary:
- various changes around GracePeriod / GracePeriodHistory so that we can
actually store them without throwing NPEs
- Creating one injectable *History.Builder field and using in place of
the HistoryEntry.Builder injected field in DomainCreateFlow
- Saving the EppResource as the parent in the *History.Builder setParent
calls
- Converting to/from HistoryEntry/*History classes in
DatastoreTransactionManager. Basically, we'll want to return the
*History subclasses (and similar in the ofy portions of HistoryEntryDao)
- Converting a few HistoryEntry.Builder usages to DomainHistory.Builder
usages. Eventually we should convert all of them.
--- …
> Begin saving the EppResource parent in *History objects

- core/src/main/java/google/registry/reporting/spec11/Spec11EmailUtils.java
- core/src/test/java/google/registry/reporting/spec11/Spec11EmailUtilsTest.java
We should be checking to see if there are _any_ active domains for a given
reported domain, not to see if _the_ domain for the name is active.
The last change caused an exception for domains with soft-deleted past domains
of the same name.  The original code only checked the first domain returned
from the query, which may have been soft-deleted.  This version checks all
domain records to see if any are active.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/1105)
> Fix Spec11 domain check

- core/src/main/java/google/registry/flows/domain/DomainDeleteFlow.java
- core/src/main/java/google/registry/flows/host/HostInfoFlow.java
- core/src/test/java/google/registry/flows/EppLifecycleContactTest.java
- core/src/test/java/google/registry/flows/EppLifecycleDomainTest.java
- core/src/test/java/google/registry/flows/EppLifecycleHostTest.java
- core/src/test/java/google/registry/flows/EppTestCase.java
- core/src/test/java/google/registry/flows/domain/DomainDeleteFlowTest.java
- core/src/test/java/google/registry/keyring/kms/KmsUpdaterTest.java
- core/src/test/java/google/registry/model/server/KmsSecretRevisionTest.java
- core/src/test/java/google/registry/model/server/KmsSecretTest.java
- core/src/test/java/google/registry/ui/server/registrar/RegistryLockVerifyActionTest.java
- db/src/main/resources/sql/er_diagram/brief_er_diagram.html
- db/src/main/resources/sql/er_diagram/full_er_diagram.html
Nothing super crazy here other than persisting the entity changes in
DomainDeleteFlow at the end of the flow rather than almost at the end.
This means that when we return the results we give the results as they
were originally present, rather than the subsequently-changed values.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/1101)
> Convert more tests to use @DualDatabaseTest and SQL in general

- core/src/main/java/google/registry/flows/domain/token/AllocationTokenFlowUtils.java
- core/src/test/java/google/registry/flows/domain/DomainCheckFlowTest.java
- core/src/test/java/google/registry/flows/domain/DomainClaimsCheckFlowTest.java
- core/src/test/java/google/registry/flows/domain/token/AllocationTokenFlowUtilsTest.java
- core/src/test/java/google/registry/flows/host/HostInfoFlowTest.java
Note that there are many flow tests that aren't
@DualDatabaseTest-annotated yet but those will come later, as they will
require more changes to the flows (other PRs are coming or in progress).
This only includes the remaining EppResource flows that don't create a
history entry.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/1107)
> Convert remaining read-only flow tests to dual-DB

- core/src/test/java/google/registry/dns/ReadDnsQueueActionTest.java
These tests are flaky due to some kind of contention/collision on the mock task
queue. Retrying seems to fix the vast majority of flakes, is easy to implement,
and is more performant than moving these tests into the fragileTests test suite.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/1114)
> Make the ReadDnsQueueAction tests retry on failures

- config/nom_build.py
nom_build tries to verify that it is in the root of the tree prior to doing
anything, however checking for a .git directory doesn't work in a merged
directory.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/1110)
> Make nom_build not check for ".git" directory

- core/src/main/java/google/registry/batch/WipeOutCloudSqlAction.java
- core/src/test/java/google/registry/batch/WipeOutCloudSqlActionTest.java
- core/src/test/java/google/registry/batch/WipeOutCloudSqlIntegrationTest.java
Replace the "drop owned" statement with ones that drops only tables and
sequences. The former statement also drops default grants for the
nomulus user, which must be restored before the database can be used by
the nomulus server and tools.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/1118)
> Improve usability of WipeOutCloudSqlAction

- core/src/main/java/google/registry/beam/datastore/BulkDeleteDatastorePipeline.java
- core/src/main/java/google/registry/beam/initsql/InitSqlPipeline.java
- core/src/main/java/google/registry/beam/invoicing/InvoicingPipeline.java
- core/src/main/java/google/registry/beam/spec11/Spec11Pipeline.java
- core/src/test/java/google/registry/beam/initsql/InitSqlPipelineGraphTest.java
- core/src/test/java/google/registry/beam/initsql/InitSqlPipelineTest.java
In tests we use a TestPipelineExtension which does some static
initialization that should not be repeated the same JVM. In our
XXXPipeline classes we save the pipeline as a field and usually write lambdas
that are pass to the pipeline. Because lambdas are effectively anonymous inner
classes they are bound to their enclosing instances. When they get serialized
during pipeline execution, their enclosing classes also do. This might result
in undefined behavior when multiple lambdas in the same XXXPipeline are used
on the same JVM (such as in tests) where the static initialization may be done
multiple times if different class loaders are used. This is very
unlikely to happen but as a best practice we still remove them as
fields.
--- …
> Remove Pipeline as a field in pipeline classes

- networking/build.gradle
- networking/src/main/java/google/registry/networking/handler/SslServerInitializer.java
- networking/src/test/java/google/registry/networking/handler/SslServerInitializerTest.java
- proxy/src/main/java/google/registry/proxy/EppProtocolModule.java
- proxy/src/main/java/google/registry/proxy/ProxyConfig.java
- proxy/src/main/java/google/registry/proxy/WebWhoisProtocolsModule.java
- proxy/src/main/java/google/registry/proxy/config/default-config.yaml
The enforcement data has passed and ICANN has confirmed that their web
WHOIS prober conforms to our requirements.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/1117)
> Remove enforcement date from the SslServerInitializer

- core/src/test/java/google/registry/flows/EppLoginTlsTest.java
- core/src/test/java/google/registry/flows/EppTestCase.java
- core/src/test/java/google/registry/flows/session/LoginFlowViaTlsTest.java
- core/src/test/java/google/registry/tools/ValidateLoginCredentialsCommandTest.java
Some unit tests began failing because the test certificate expired on April 30th. In order to prevent the need to create a new test certificate once a year, this PR modifies the tests to mock the time in the CertificateChecker. 
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/1121)
> Use FakeClock to prevent Expired Certificate Violations

- core/src/main/java/google/registry/beam/initsql/Transforms.java
Ignore or fix bad entites when populating SQL with production data in
Datastore. These are mostly inconsistent foreign keys.
See b/185954992 for details.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/1120)
> Handle bad production data when migrating to SQL

- .gcloudignore
- release/builder/build.sh
- release/cloudbuild-deploy.yaml
- release/cloudbuild-dev-resource.yaml
- release/cloudbuild-kythe.yaml
- release/cloudbuild-nomulus.yaml
- release/cloudbuild-proxy.yaml
- release/cloudbuild-release.yaml
- release/cloudbuild-schema-deploy.yaml
- release/cloudbuild-sync.yaml
- release/cloudbuild-tag.yaml
There has been a case where the CI was broken on Friday and no one
noticied or fixed it and a RC build was built with broken tests.
The tests were disabled due to unknown test failures that have since
been fixed.
Also update the machine type used by GCB to be more powerful. This is
necessary for the tests to past because N1_HIGHCPU_8 is RAM constraint
and the tests crashes. I updated all jobs to use the new type which
hopefully will make the build faster as well.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/1130)
> Re-enable tests in RC build

- core/src/main/java/google/registry/flows/FlowModule.java
- core/src/main/java/google/registry/flows/contact/ContactCreateFlow.java
- core/src/main/java/google/registry/flows/contact/ContactDeleteFlow.java
- core/src/main/java/google/registry/flows/contact/ContactFlowUtils.java
- core/src/main/java/google/registry/flows/contact/ContactTransferApproveFlow.java
- core/src/main/java/google/registry/flows/contact/ContactTransferCancelFlow.java
- core/src/main/java/google/registry/flows/contact/ContactTransferRejectFlow.java
- core/src/main/java/google/registry/flows/contact/ContactTransferRequestFlow.java
- core/src/main/java/google/registry/flows/contact/ContactUpdateFlow.java
- core/src/main/java/google/registry/model/contact/ContactBase.java
- core/src/main/java/google/registry/model/contact/ContactHistory.java
- core/src/test/java/google/registry/flows/ResourceFlowTestCase.java
- core/src/test/java/google/registry/flows/contact/ContactCreateFlowTest.java
- core/src/test/java/google/registry/flows/contact/ContactDeleteFlowTest.java
- core/src/test/java/google/registry/flows/contact/ContactTransferApproveFlowTest.java
- core/src/test/java/google/registry/flows/contact/ContactTransferCancelFlowTest.java
- core/src/test/java/google/registry/flows/contact/ContactTransferRejectFlowTest.java
- core/src/test/java/google/registry/flows/contact/ContactTransferRequestFlowTest.java
- core/src/test/java/google/registry/flows/contact/ContactUpdateFlowTest.java
Minimal interesting changes here
- a bit of reconstruction in ContactHistory to get the repo ID from the
key
- making the History revision ID Long instead of long so that it can be
null in non-built intermediate entities
- adding a copyFrom(HistoryEntry.Builder) method in HistoryEntry.Builder
so that we don't need to allocate quite as many unnecessary IDs, i.e.
removing the .build() lines in provideContactHistory and
provideDomainHistory
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/1111)
> Populate the contact in ContactHistory objects created in Contact flows

- core/src/main/java/google/registry/batch/DeleteContactsAndHostsAction.java
- core/src/main/java/google/registry/flows/ResourceFlowUtils.java
- core/src/main/java/google/registry/flows/contact/ContactDeleteFlow.java
- core/src/main/java/google/registry/flows/host/HostDeleteFlow.java
- core/src/test/java/google/registry/flows/EppLifecycleContactTest.java
- core/src/test/java/google/registry/flows/contact/ContactDeleteFlowTest.java
- core/src/test/resources/google/registry/flows/contact/contact_delete_response.xml
- core/src/test/resources/google/registry/flows/contact/contact_delete_response_no_cltrid_pending.xml
- core/src/test/resources/google/registry/flows/contact/contact_delete_response_pending.xml
- core/src/test/resources/google/registry/flows/contact_delete_response_sh8013.xml
- core/src/test/resources/google/registry/flows/contact_delete_response_sh8013_pending.xml
- core/src/test/resources/google/registry/flows/session/contact_delete_response_sh8013_pending.xml
In SQL the contact of a domain is an indexed field and therefore we can
find linked domains synchronously, without the need for MapReduce.
The delete logic is mostly lifted from DeleteContactsAndHostsAction, but
because everything happens in a transaction we do not need to recheck a
lot of the preconditions that were necessary to ensure that the async
delete request still meets the conditions that when the request was
enqueued.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/1137)
> Perform synchronous contact delete in SQL

- core/src/test/java/google/registry/beam/TestPipelineExtension.java
- core/src/test/java/google/registry/beam/spec11/Spec11PipelineTest.java
- core/src/test/java/google/registry/testing/DatastoreEntityExtension.java
It appears when the test fails the call to isAppEngine() returns true. It
is still not clear where that comes from, but it is likely due to the
DatastoreEntityExtension trying to setup an App Engine environment for
Ofy. All Ofy needs is a project ID so we explicitly clear the system
proporty for ApiProxy in the hope that isAppEngine() will now always
return false.
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/1133)
> Fix flaky Spec11PipelineTest

- core/src/main/java/google/registry/flows/FlowModule.java
- core/src/main/java/google/registry/flows/host/HostDeleteFlow.java
- core/src/test/java/google/registry/flows/EppLifecycleContactTest.java
- core/src/test/java/google/registry/flows/EppLifecycleHostTest.java
- core/src/test/java/google/registry/flows/contact/ContactDeleteFlowTest.java
- core/src/test/java/google/registry/flows/host/HostDeleteFlowTest.java
- core/src/test/resources/google/registry/flows/host/host_delete_response.xml
- core/src/test/resources/google/registry/flows/host/host_delete_response_no_cltrid_pending.xml
- core/src/test/resources/google/registry/flows/host/host_delete_response_pending.xml
Also put some common logic in helper funcions in ContactDeleteFlowTest
to reduce clutter.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/1141)
> Delete hosts synchronously when using SQL

- core/src/main/java/google/registry/beam/initsql/Transforms.java
- core/src/main/java/google/registry/mapreduce/inputs/ChildEntityReader.java
- core/src/main/java/google/registry/mapreduce/inputs/CommitLogManifestReader.java
- core/src/main/java/google/registry/mapreduce/inputs/EppResourceBaseReader.java
- core/src/main/java/google/registry/mapreduce/inputs/EppResourceEntityReader.java
- core/src/main/java/google/registry/mapreduce/inputs/RetryingInputReader.java
- core/src/main/java/google/registry/model/ofy/ObjectifyService.java
- core/src/main/java/google/registry/persistence/transaction/Transaction.java
- core/src/main/java/google/registry/persistence/transaction/TransactionManager.java
- core/src/main/java/google/registry/rdap/RdapDomainSearchAction.java
- core/src/main/java/google/registry/rdap/RdapSearchActionBase.java
This will allow us to make sure that every usage of ofy() has been
hand-examined and specifically allowed.
This PR includes a few examples of its usage in a few classes, based on the list found in https://docs.google.com/spreadsheets/d/1aFEFuyH6vVW6b-h71O9f5CuUc6Y7YjZ2kdRL3lwXcVk/edit?resourcekey=0-guwZVKfSH-pntER1tUit6w#gid=1355213322 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/1138)
> Add an auditedOfy marker method for allow-listed ofy() calls

- common/src/testing/java/google/registry/testing/FakeClock.java
- core/src/test/java/google/registry/batch/DeleteExpiredDomainsActionTest.java
- core/src/test/java/google/registry/flows/poll/PollAckFlowTest.java
- core/src/test/java/google/registry/model/history/DomainHistoryTest.java
- core/src/test/java/google/registry/model/registry/RegistryTest.java
- core/src/test/java/google/registry/model/registry/label/PremiumListDualDaoTest.java
- core/src/test/java/google/registry/model/registry/label/ReservedListDualDatabaseDaoTest.java
- core/src/test/java/google/registry/model/registry/label/ReservedListTest.java
- core/src/test/java/google/registry/persistence/transaction/TransactionManagerTest.java
- core/src/test/java/google/registry/rde/PendingDepositCheckerTest.java
- core/src/test/java/google/registry/rde/RdeStagingActionTest.java
- core/src/test/java/google/registry/testing/ReplayExtension.java
- core/src/test/java/google/registry/tools/GetDatabaseTransitionScheduleCommandTest.java
- core/src/test/java/google/registry/tools/UnrenewDomainCommandTest.java
- core/src/test/java/google/registry/ui/server/registrar/ContactSettingsTest.java
Set the number of commitLog buckets to 1 in CommitLog replay tests to
expose all timestamp inversion problem.
Fixed PollAckFlowTest.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/1144)
> Fix timestamp inversion bug

- core/src/main/java/google/registry/model/ofy/DatastoreTransactionManager.java
- core/src/main/java/google/registry/persistence/transaction/JpaTransactionManagerImpl.java
- core/src/main/java/google/registry/tools/AckPollMessagesCommand.java
- core/src/main/java/google/registry/tools/CompareReservedListsCommand.java
- core/src/main/java/google/registry/tools/DedupeRecurringBillingEventIdsCommand.java
- core/src/main/java/google/registry/tools/DeleteTldCommand.java
- core/src/main/java/google/registry/tools/GenerateDnsReportCommand.java
- core/src/main/java/google/registry/tools/GetResourceByKeyCommand.java
- core/src/main/java/google/registry/tools/ReadEntityFromKeyPathCommand.java
- core/src/main/java/google/registry/tools/RegistryCli.java
- core/src/main/java/google/registry/tools/ResaveEntitiesCommand.java
- core/src/main/java/google/registry/tools/ResaveEnvironmentEntitiesCommand.java
- core/src/main/java/google/registry/tools/javascrap/BackfillSpec11ThreatMatchesCommand.java
- core/src/main/java/google/registry/tools/javascrap/DeleteContactByRoidCommand.java
- core/src/main/java/google/registry/tools/server/DeleteEntityAction.java
- core/src/main/java/google/registry/tools/server/KillAllEntitiesReducer.java
- core/src/main/java/google/registry/tools/server/KillAllEppResourcesAction.java
- core/src/main/java/google/registry/tools/server/ListDomainsAction.java
- core/src/main/java/google/registry/tools/server/ResaveAllHistoryEntriesAction.java
- core/src/test/java/google/registry/persistence/transaction/QueryComposerTest.java
A couple of these use the QueryComposer interface to avoid branching.
In addition, we enforce the Datastore restriction that there can be at
most 1 field with an inequality query, see https://cloud.google.com/appengine/docs/standard/go111/datastore/query-restrictions#inequality_filters_are_limited_to_at_most_one_property
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/1152)
> Convert more ofy() to auditedOfy() calls

- core/src/main/java/google/registry/beam/common/RegistryJpaIO.java
- core/src/main/java/google/registry/persistence/transaction/JpaTransactionManagerImpl.java
- core/src/main/java/google/registry/persistence/transaction/QueryComposer.java
- core/src/test/java/google/registry/beam/common/RegistryJpaReadTest.java
Allow result set streaming by setting the fetchSize on JDBC statements.
Many JDBC drivers by default buffers the entire result set, causing
delays in first result and/or out of memory errors.
Also fixed a entity instantiation problem exposed in production runs.
Lastly, removed incorrect comments.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/1155)
> Fix the JPA Read connector for large data

- core/src/main/java/google/registry/tools/CreateOrUpdatePremiumListCommand.java
- core/src/main/java/google/registry/tools/CreatePremiumListCommand.java
- core/src/main/java/google/registry/tools/UpdatePremiumListCommand.java
- core/src/test/java/google/registry/tools/CreateOrUpdatePremiumListCommandTestCase.java
- core/src/test/java/google/registry/tools/CreatePremiumListCommandTest.java
- core/src/test/java/google/registry/tools/UpdatePremiumListCommandTest.java
- change the implementation of premium list command to be based on the mutating command in order to use the method  stageEntityChange(old_entity, new_entity, vkey) from mutating command; 
- no longer use client/servlet model + action files
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/1123)
> Change premium list command to be based off of mutating command 

- core/src/main/java/google/registry/model/domain/secdns/DomainDsDataHistory.java
- core/src/main/java/google/registry/model/reporting/Spec11ThreatMatch.java
- core/src/main/java/google/registry/model/smd/SignedMarkRevocationList.java
- core/src/main/java/google/registry/persistence/transaction/TransactionEntity.java
- core/src/main/java/google/registry/schema/domain/RegistryLock.java
- core/src/main/java/google/registry/schema/replay/SqlOnlyEntity.java
- core/src/main/java/google/registry/schema/replay/SqlReplayCheckpoint.java
- core/src/main/java/google/registry/schema/tld/PremiumEntry.java
This started as having a better check for when to run the
ReplayCommitLogsToSqlAction but that'll require a bit more thought, and
this is a fairly simple PR that can be split out.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/1158)
> Clean up some SqlEntity classes

- core/src/main/java/google/registry/beam/common/RegistryJpaIO.java
- core/src/main/java/google/registry/model/ofy/DatastoreTransactionManager.java
- core/src/main/java/google/registry/persistence/transaction/JpaTransactionManagerImpl.java
- core/src/main/java/google/registry/persistence/transaction/QueryComposer.java
- core/src/main/java/google/registry/tools/GenerateLordnCommand.java
- core/src/main/java/google/registry/tools/javascrap/BackfillSpec11ThreatMatchesCommand.java
- core/src/test/java/google/registry/beam/common/RegistryJpaReadTest.java
The read connector needs to detach loaded entities.
Also removed the 'transaction mode' property from the Read connector.
There are no obvious use cases for non-transaction query, and
implementation is not straightforward with the current code base.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/1161)
> Fix RegistryJpaIO.Read problem with large data

- core/src/main/java/google/registry/flows/poll/PollFlowUtils.java
- core/src/main/java/google/registry/model/ofy/DatastoreTransactionManager.java
- core/src/main/java/google/registry/persistence/transaction/QueryComposer.java
- core/src/main/java/google/registry/tools/AckPollMessagesCommand.java
- core/src/test/java/google/registry/persistence/transaction/QueryComposerTest.java
We can't convert all of the poll ack logic, but we can convert most of it to QueryComposer.  This significantly simplifies the implementation and commonality of the code.
As part of this, introduce an SQL-only "LIKE" operator to query composer.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/1151)
> Convert most poll message queries to QueryComposer

- core/src/main/java/google/registry/model/registry/label/PremiumList.java
- core/src/main/java/google/registry/schema/tld/PremiumEntry.java
- core/src/main/java/google/registry/tools/server/ListPremiumListsAction.java
- core/src/test/java/google/registry/backup/ReplayCommitLogsToSqlActionTest.java
- db/src/main/resources/sql/schema/db-schema.sql.generated
Add the ImmutableObject.Insignificant annotation to labelsToPrices and also
mark it as Transient.  In order to do lazy-loads on this field, we need to do
so explicitly: doing otherwise breaks the immutability contract and prevents
detaching the object upon load.
Note that this is an expedient solution to this problem, but not the optimal
one.  Ideally, the disassociation between PremiumList and its PremiumEntry's
would be more explicit.  However, breaking labelsToPrices out would at minimum
require reworking the Create/UpdatePremiumList commands, which currently rely
on passing around a self-contained PremiumList object, both from the parser
interfaces and to the database.
If this approach is acceptable, we can apply it to ReservedList and ClaimsList
as well (though it may be easier to …
> Make PremiumList.labelsToPrices "insignificant"

- core/src/main/java/google/registry/model/EntityClasses.java
- core/src/main/java/google/registry/model/common/DatabaseMigrationStateWrapper.java
- core/src/test/java/google/registry/model/common/DatabaseMigrationStateWrapperTest.java
- core/src/test/resources/google/registry/export/backup_kinds.txt
- core/src/test/resources/google/registry/export/crosstld_kinds.txt
- core/src/test/resources/google/registry/model/schema.txt
go/registry-3.0-stage-management for more details
This basically boils down to storing an enum in the database so that we
can tell what stage of the migration we're in.
We use a cross-TLD parent so that we can have strong transactional
consistency on retrieval.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/1170)
> Add an object to store database migration stages

- core/build.gradle
- core/src/main/java/google/registry/model/reporting/HistoryEntryDao.java
- core/src/test/java/google/registry/testing/DatabaseHelper.java
- dependencies.gradle
This is useful when we expect a specific subtype in the return value so
that we can set the parent resource (e. g. DomainContent for
DomainHistory) on it, or when a specific subtype is needed from the call
site.
This PR also fixes some use of generic return values. It is always better to
return <HistoryEntry> than a wildcard <? extends HistoryEntry>, because for
immutable collections, <? extends HistoryEntry> is no different than
<HistoryEntry> as return value -- you can only get a HistoryEntry from it.
The wildcard return value means that even if you are indeed getting a
<DomainHistory> from the query, the call site has no compile time knowledge of
it and can only assume it is a <HistoryEntry>.
--- …
> Add methods to return subtypes of HistoryEntry when querying

- core/src/main/java/google/registry/tools/server/ListPremiumListsAction.java
- core/src/test/java/google/registry/tools/server/ListPremiumListsActionTest.java
Remove the ability to show all of the labels associated with a premium list in
the list_premium_lists command.  Supporting this requires loading the entire
contents of all premium lists from the database as opposed to just the list
records, and the information can be obtained using get_premium_list.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/1182)
> Remove labels from output of list_premium_lists

- core/src/main/java/google/registry/batch/DeleteExpiredDomainsAction.java
- core/src/main/java/google/registry/env/common/default/WEB-INF/datastore-indexes.xml
- core/src/test/java/google/registry/batch/DeleteExpiredDomainsActionTest.java
I think this one needed to wait until the detach-on-load PR went in, but
now we should be all set.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/1180)
> Convert DeleteExpiredDomainsAction to QueryComposer

- core/src/main/java/google/registry/persistence/transaction/JpaTransactionManager.java
- core/src/main/java/google/registry/persistence/transaction/JpaTransactionManagerImpl.java
- core/src/test/java/google/registry/persistence/transaction/JpaTransactionManagerImplTest.java
Detach all entity result objects obtained through `TypedQuery`s returned by the `jpaTm().query()` method.
This is in line with the general practice of always detaching objects on load, which prevents issues with implicit saves and immutability violations.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/1183)
> Detach result objects obtained through jpaTm().query()

- release/cloudbuild-deploy.yaml
- release/cloudbuild-schema-deploy.yaml
Store cloudbuild's nomulus-tool credential in SecretManager and make the
deployment pipeline load it from the SecretManager.
The tool-credential.json.enc file in the
gs://domain-registry-dev-deploy/secrets folder is no longer needed.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/1188)
> Use SecretManager for nomulus-tool-cloudbuild cred

- core/src/main/java/google/registry/beam/invoicing/BillingEvent.java
- core/src/main/resources/google/registry/beam/invoicing/sql/billing_events.sql
- core/src/test/java/google/registry/beam/invoicing/BillingEventTest.java
- core/src/test/java/google/registry/beam/invoicing/InvoicingPipelineTest.java
- core/src/test/resources/google/registry/beam/invoicing/billing_events_test.sql
There are cases where periodYears is not set when creating a OneTime
billing event, for example when performing a registry lock (default cost = $0)
or when performing a server status update, such as applying the
serverUpdateProhibited status (default cost = $20). This is not currently
handled correctly in the billing pipeline because the parseFromRecord
method checks for nullness for all fields. Even if it does not validate
the fields, the null periodYears will still cause problem when the
billing event is converted to CSV files.
This PR alters the BigQuery SQL file to convert a NULL to 0 when
creating the BillingEvent in the invoicing pipeline. It also sets the EndDate
in the invoice CSV to an empty string when periodYears is 0. Note that when the
cost is also 0, the billing event is …
> Handle cases where periodYears is NULL in a OneTime

- core/src/main/java/google/registry/model/EppResource.java
- core/src/main/java/google/registry/model/contact/ContactHistory.java
- core/src/main/java/google/registry/model/domain/DomainHistory.java
- core/src/main/java/google/registry/model/host/HostHistory.java
- core/src/main/java/google/registry/model/transfer/DomainTransferData.java
The creation of a builder to set the DomainContent repo id in DomainHistory
triggers an equality check which causes the hash code of an associated
transfer data object to be calculated prematurely, before the Ofy keys are
reconstituted.  Replace this with a simple setter, which is acceptable in this
case because the object is being loaded and is considered to be not fully
constructed yet.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/1189)
> Fix copy causing premature hash calculation

- core/src/main/java/google/registry/model/index/ForeignKeyIndex.java
- core/src/main/java/google/registry/model/reporting/HistoryEntryDao.java
- core/src/main/java/google/registry/persistence/transaction/JpaTransactionManager.java
- core/src/main/java/google/registry/persistence/transaction/JpaTransactionManagerImpl.java
- core/src/main/java/google/registry/rdap/RdapDomainSearchAction.java
- core/src/main/java/google/registry/rdap/RdapSearchActionBase.java
- core/src/test/java/google/registry/persistence/transaction/CriteriaQueryBuilderTest.java
- core/src/test/java/google/registry/persistence/transaction/JpaTransactionManagerImplTest.java
Add a query(CriteriaQuery) method to JpaTransactionManager and replace all of the criteria query executions with it.  The new query method wraps the underlying TypedQuery with a DetachingTypedQuery, enabling "detach on load" for all criteria query objects.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/1192)
> Use detaching queries for all criteria queries

- core/src/test/java/google/registry/batch/ExpandRecurringBillingEventsActionTest.java
These tests should run in both Ofy and SQL. They were temporarily
changed to only run in SQL to make debugging faster but I forgot to
change them back.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/1196)
> Fix a few test annotations

- core/src/main/java/google/registry/model/common/DatabaseMigrationStateSchedule.java
- core/src/test/java/google/registry/tools/SetDatabaseMigrationStateCommandTest.java
The cache is static so some odd state may stick around between tests --
we should clear it
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/1198)
> Fix a test flake in SetDatabaseMigrationScheduleCommandTest

- core/src/main/java/google/registry/env/alpha/default/WEB-INF/cron.xml
- core/src/main/java/google/registry/env/crash/default/WEB-INF/cron.xml
- core/src/main/java/google/registry/env/qa/default/WEB-INF/cron.xml
- core/src/main/java/google/registry/env/sandbox/default/WEB-INF/cron.xml
This should be a no-op since we haven't enabled it but this means that
when we set the schedule, we'll start replaying
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/1199)
> Start the DS->SQL replay cron job in non-prod environments

- core/src/main/java/google/registry/model/ofy/DatastoreTransactionManager.java
The objectify "count()" method doesn't work for result sets larger than 1000
elements, use the original trick from "count domains" that fetches the keys
and counts them.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/1201)
> Fix Datastore "count" queries

- core/src/main/java/google/registry/model/EppResourceUtils.java
- core/src/main/java/google/registry/model/contact/ContactHistory.java
- core/src/main/java/google/registry/model/domain/DomainHistory.java
- core/src/main/java/google/registry/model/domain/GracePeriod.java
- core/src/main/java/google/registry/model/domain/secdns/DelegationSignerData.java
- core/src/main/java/google/registry/model/host/HostHistory.java
- core/src/main/java/google/registry/model/reporting/HistoryEntry.java
- core/src/test/java/google/registry/flows/EppPointInTimeTest.java
- core/src/test/java/google/registry/model/EppResourceUtilsTest.java
This required the following changes:
- The branching / conversion logic itself, where we load the most recent
history object for the resource in question (or just return the resource
itself)
- For simplicity's sake, adding a method in the *History objects that
returns the generic resource -- this means that it can be called when we
don't know or care which subclass it is.
- Populating the domain's dsData and gracePeriods fields from the
DomainHistory fields, and adding factories in the relevant classes to
allow us to do the conversions nicely (the history classes are almost
the same as the regular ones, but not quite).
- Change the tests to use the clocks properly and to allow comparison of
e.g. DomainContent to DomainBase. The objects aren't the same (one is a
superclass of the other) …
> Convert EppResourceUtils::loadAtPointInTime to SQL+DS

- core/src/main/java/google/registry/backup/DeleteOldCommitLogsAction.java
- core/src/main/java/google/registry/batch/ResaveAllEppResourcesAction.java
- core/src/main/java/google/registry/tools/server/KillAllCommitLogsAction.java
- core/src/main/java/google/registry/tools/server/RefreshDnsForAllDomainsAction.java
- core/src/main/java/google/registry/tools/server/ResaveAllHistoryEntriesAction.java
- core/src/test/java/google/registry/tools/server/RefreshDnsForAllDomainsActionTest.java
Also marks a few mapreduce actions as @Deprecated as they are no longer
needed in SQL.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/1197)
> Make RefreshDnsForAllDomains SQL-aware

- core/src/main/java/google/registry/model/EppResourceUtils.java
- core/src/main/java/google/registry/rde/RdeStagingMapper.java
- core/src/main/java/google/registry/tools/server/GenerateZoneFilesAction.java
- core/src/test/java/google/registry/flows/EppPointInTimeTest.java
- core/src/test/java/google/registry/model/EppResourceUtilsTest.java
In SQL we do not need to wrap it in a Result. Unfortunately we cannot
overload a function based on its return value so we renamed the existing
one and created a new one with the old name that returns the resource
directly. Once we no longer have use of Datastore we can delete the now
renamed function that returns a Result<? extends EppResource>
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/1205)
> Unwrap the return value of loadAtPointInTime

- core/src/main/java/google/registry/model/registry/Registry.java
- core/src/main/java/google/registry/tools/RegistryTool.java
- core/src/main/java/google/registry/tools/javascrap/ResaveAllTldsCommand.java
- core/src/test/resources/google/registry/model/schema.txt
As part of b/186247597, this adds new fields to the Registry object that represent Premium and Reserved list. Once this code is live, all existing Registry entities should be resaved in order to populate these new fields. Then, the old premiumList and ReservedList fields can be removed to allow for the removal of Premium and Reserved list entities from the Datastore schema.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/1208)
> Add new domain list fields to Registry objects

- config/presubmits.py
- core/src/main/java/google/registry/beam/common/RegistryJpaIO.java
- core/src/main/java/google/registry/beam/common/RegistryQuery.java
- core/src/main/java/google/registry/beam/spec11/Spec11Pipeline.java
- core/src/main/java/google/registry/persistence/transaction/QueryComposer.java
- core/src/main/java/google/registry/tools/GenerateLordnCommand.java
- core/src/test/java/google/registry/beam/common/RegistryJpaReadTest.java
QueryComposer could be used when the transaction manager is not
determined (i. e. it supports both ofy and sql), but this also imposes
limits on what you can do with it. For example it does not support IN
operator in the where clause.
Since QueryComposer itself creates a CriteriaQuery for JPA TM it make
sense to have RegistryJpaIO take a CriteriaQuery directly as it only
uses JPA.
Also add some more helper methods to use native queries and typed
queires, and fix some generic type warnings.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/1209)
> Make RegistryJpaIO use CriteriaQuery intead of QueryComposer

- core/src/main/java/google/registry/beam/common/JpaDemoPipeline.java
- core/src/main/java/google/registry/persistence/PersistenceModule.java
- core/src/main/java/google/registry/persistence/transaction/JpaTransactionManager.java
- core/src/main/java/google/registry/persistence/transaction/JpaTransactionManagerImpl.java
With Postgresql, we must override the default fetchSize (0) to enable
scrollable result sets. Previously we only did this in QueryComposer.
In this change we enable scrollable results for all queries by default.
We also provide a helper function
(JpaTransactionManager.setQueryFetchSize) that can override the default.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/1214)
> Make SQL queries return scrollable results

- core/src/main/java/google/registry/batch/DeleteLoadTestDataAction.java
- core/src/main/java/google/registry/model/ofy/DatastoreTransactionManager.java
- core/src/main/java/google/registry/persistence/transaction/JpaTransactionManagerImpl.java
- core/src/main/java/google/registry/persistence/transaction/TransactionManager.java
- core/src/main/java/google/registry/tools/AckPollMessagesCommand.java
This isn't directly meant to be run in production so some of the rough
edges (doesn't delete domains, can't delete contacts that are referenced
by an existing domain) are fine. We can handle those in
DeleteProberTestAction when we do the more comprehensive deletions.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/1211)
> Add SQL functionality to DeleteLoadTestDataAction

- core/src/main/java/google/registry/model/registry/label/PremiumList.java
- core/src/main/java/google/registry/schema/tld/PremiumListDao.java
- core/src/test/java/google/registry/model/registry/label/PremiumListTest.java
- core/src/test/java/google/registry/schema/tld/PremiumListDaoTest.java
Different currencies have different numbers of decimal places (e.g. USD has 2,
JPY has 0, and some even have 3). Thus, when loading the contents of a premium
list, we need to set the precision correctly on all of the BigDecimal prices.
This issue was introduced as part of the Registry 3.0 database migration when we
changed each PremiumEntry to being a Money to a BigDecimal (to remove the
redundancy of storing the same currency value over and over).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/1221)
> Fix BigDecimal precision of PremiumList.getLabelsToPrices()

- core/src/main/java/google/registry/flows/FlowModule.java
- core/src/main/java/google/registry/flows/contact/ContactCreateFlow.java
- core/src/main/java/google/registry/flows/contact/ContactDeleteFlow.java
- core/src/main/java/google/registry/flows/contact/ContactTransferApproveFlow.java
- core/src/main/java/google/registry/flows/contact/ContactTransferCancelFlow.java
- core/src/main/java/google/registry/flows/contact/ContactTransferRejectFlow.java
- core/src/main/java/google/registry/flows/contact/ContactTransferRequestFlow.java
- core/src/main/java/google/registry/flows/contact/ContactUpdateFlow.java
- core/src/main/java/google/registry/flows/domain/DomainCreateFlow.java
- core/src/main/java/google/registry/flows/domain/DomainDeleteFlow.java
- core/src/main/java/google/registry/flows/domain/DomainRenewFlow.java
- core/src/main/java/google/registry/flows/domain/DomainRestoreRequestFlow.java
- core/src/main/java/google/registry/flows/domain/DomainTransferApproveFlow.java
- core/src/main/java/google/registry/flows/domain/DomainTransferCancelFlow.java
- core/src/main/java/google/registry/flows/domain/DomainTransferRejectFlow.java
- core/src/main/java/google/registry/flows/domain/DomainTransferRequestFlow.java
- core/src/main/java/google/registry/flows/domain/DomainUpdateFlow.java
- core/src/main/java/google/registry/flows/host/HostCreateFlow.java
- core/src/main/java/google/registry/flows/host/HostDeleteFlow.java
- core/src/main/java/google/registry/flows/host/HostUpdateFlow.java
Rather than having to set it individually to now (the current transaction time)
in every transactional flow, just do it once at the beginning when the
HistoryEntry.Builder is first being provided. This is also safer, as just doing
it in one place gives us stronger guarantees that it always corresponds to the
execution time of the flow, rather than leaving the potential open that in one
flow it's unintentionally set to the wrong thing.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/1222)
> Set HistoryEntry modification time in FlowModule

- core/src/test/java/google/registry/schema/replay/ReplicateToDatastoreActionTest.java
The occassional failures seem to be caused by the test Datastore.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/1226)
> Retry flaky tests for ReplicateToDatastoreAction

- core/src/main/java/google/registry/backup/ReplayCommitLogsToSqlAction.java
- core/src/test/java/google/registry/backup/ReplayCommitLogsToSqlActionTest.java
I suspect this may be the reason the logs are missing on the happy path (when it
runs successfully), but are visible on the exception paths (which do set the
payload response). I don't think App Engine likes it when a Web request
terminates without a response.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/1229)
> Set payload response in happy path of ReplayCommitLogsToSqlAction

- core/src/main/java/google/registry/persistence/BillingVKey.java
- core/src/main/java/google/registry/persistence/DomainHistoryVKey.java
- core/src/main/java/google/registry/persistence/EppHistoryVKey.java
- core/src/main/java/google/registry/persistence/VKey.java
- core/src/main/java/google/registry/persistence/converter/VKeyConverter.java
- core/src/main/java/google/registry/persistence/transaction/JpaTransactionManagerImpl.java
Tighten field type so that non-serializable object cannot be set as
sqlKey.
This would make it easier to make EppResource entities Serializable in
the future.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/1235)
> Ensure VKey is actually serializable

- core/src/main/java/google/registry/backup/BackupModule.java
- core/src/main/java/google/registry/backup/GcsDiffFileLister.java
- core/src/main/java/google/registry/backup/ReplayCommitLogsToSqlAction.java
- core/src/main/java/google/registry/backup/RestoreCommitLogsAction.java
- core/src/test/java/google/registry/backup/GcsDiffFileListerTest.java
- core/src/test/java/google/registry/backup/ReplayCommitLogsToSqlActionTest.java
- core/src/test/java/google/registry/backup/RestoreCommitLogsActionTest.java
Allow non-production projects to restore commit logs from another
project. This feature can be used to duplicate a realistic testing
environment.
An optional parameter is added that can override the default commit log
location.
Tested successfully in QA.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/1236)
> Restore commit logs from other project

- core/src/main/java/google/registry/model/registry/label/BaseDomainLabelList.java
- core/src/main/java/google/registry/model/registry/label/PremiumList.java
- core/src/main/java/google/registry/model/registry/label/ReservedList.java
These keys are no longer necessary since Reserved and Premium list are no longer Read or written to Datastore
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/1239)
> Remove key references from BaseDomainLabelList

- core/src/main/java/google/registry/persistence/transaction/TransactionManagerFactory.java
- core/src/test/java/google/registry/backup/ReplayCommitLogsToSqlActionTest.java
- core/src/test/java/google/registry/beam/rde/RdePipelineTest.java
- core/src/test/java/google/registry/beam/spec11/Spec11PipelineTest.java
- core/src/test/java/google/registry/model/common/DatabaseMigrationStateScheduleTest.java
- core/src/test/java/google/registry/schema/replay/ReplicateToDatastoreActionTest.java
- core/src/test/java/google/registry/testing/DualDatabaseTestInvocationContextProvider.java
- core/src/test/java/google/registry/tools/GetDatabaseMigrationStateCommandTest.java
- core/src/test/java/google/registry/tools/SetDatabaseMigrationStateCommandTest.java
We still allow the "manual" specification of a particular transaction
manager, most useful in @DualDatabaseTest classes. If that isn't
specified, we examine the migration schedule to see which to return.
Notes:
- This requires that any test that sets the migration schedule clean up
after itself so that it won't affect future test runs of other classes
(because the migration schedule cache is static)
- One alternative would, instead of having a "test override" for the
transaction manager, be to examine the registry environment and only
override the transaction manager in the UNIT_TEST environment. This
doesn't work because there are many instances in which tests simulate
non-test environments.
--- …
> Use the DatabaseMigrationSchedule to determine which TM to use

- core/src/main/java/google/registry/backup/BackupModule.java
- core/src/main/java/google/registry/backup/GcsDiffFileLister.java
- core/src/test/java/google/registry/backup/GcsDiffFileListerTest.java
- core/src/test/java/google/registry/backup/ReplayCommitLogsToSqlActionTest.java
- core/src/test/java/google/registry/backup/RestoreCommitLogsActionTest.java
Basically, whenever we request threads using the request thread factory,
we must be on the request thread itself. Dagger doesn't guarantee this
for us if we provide the ExecutorService directly in the action (or in
the GcsDiffFileLister), but we can gurantee that we're on the request
thread itself by simply injecting a Lazy, so that the executor is
instantiated inside the request itself.
Tested on Alpha and it works + we get logs after adding the `shutdown` call 
In addition, add a timeout on the futures just in case.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/1243)
> Fix hanging threads in GcsDiffFileLister

- core/src/test/java/google/registry/beam/rde/RdePipelineTest.java
- core/src/test/java/google/registry/persistence/transaction/JpaTransactionManagerImplTest.java
- core/src/test/java/google/registry/persistence/transaction/QueryComposerTest.java
- core/src/test/java/google/registry/testing/DatabaseHelper.java
These aren't "flakes" in the usual sense but it doesn't seem like you show up if you run the standard testing tasks through Gradle. Rather, they show up if you run the individual tests. 
Using `tm()` calls now has a dependency on Objectify -- JpaTransactionManagerImplTest shouldn't need that so we can modify the assertDetached calls to remove that. 
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/1246)
> Fix flaky test issues caused by lack of ofy init

- core/src/main/java/google/registry/backup/GcsDiffFileLister.java
- core/src/main/java/google/registry/backup/ReplayCommitLogsToSqlAction.java
- core/src/test/java/google/registry/backup/GcsDiffFileListerTest.java
- core/src/test/java/google/registry/backup/ReplayCommitLogsToSqlActionTest.java
- core/src/test/java/google/registry/backup/RestoreCommitLogsActionTest.java
- We now use a more intelligent prefix to narrow the listObjects search
space in GCS. Otherwise, we're returning >30k objects which can take
roughly 50 seconds. This results in a listObjects time of 1-3 seconds.
- We now search hour by hour to efficiently make use of the prefixing.
Basically, we keep searching for new files until we hit the current time
or until we hit the overall replay timeout.
- Dry-run only prints out the first hour's worth of files
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/1240)
> Fix runtime issues with commit-log-to-SQL replay

- core/src/main/java/google/registry/flows/certs/CertificateChecker.java
- core/src/test/java/google/registry/flows/certs/CertificateCheckerTest.java
- isNearingExpiration() will no longer necessary once shouldReceiveExpiringNotification() is added to the code base. isNearingExpiration() was originally added to check whether the certificate is nearing expiration and shouldReceiveExpiringNotification() was based on the logic of isNearingExpiration() with additional checks. 
- isNearingExpiration() was added along with test cases but not being used in the any features at the moment.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/1255)
> Remove isNearingExpiration() after shouldReceiveExpiringNotification() being added to code base

- core/src/main/java/google/registry/backup/ReplayCommitLogsToSqlAction.java
- core/src/main/java/google/registry/model/contact/ContactHistory.java
- core/src/main/java/google/registry/model/domain/DomainHistory.java
- core/src/main/java/google/registry/model/host/HostHistory.java
- core/src/main/java/google/registry/schema/replay/ReplaySpecializer.java
- core/src/main/java/google/registry/schema/replay/SqlEntity.java
- core/src/main/java/google/registry/tools/javascrap/CreateSyntheticHistoryEntriesAction.java
- core/src/test/java/google/registry/model/history/ContactHistoryTest.java
- core/src/test/java/google/registry/model/history/DomainHistoryTest.java
- core/src/test/java/google/registry/model/history/HostHistoryTest.java
- core/src/test/java/google/registry/model/history/LegacyHistoryObjectTest.java
- core/src/test/java/google/registry/testing/TestObject.java
If we use the transaction manager methods, JpaTransactionManagerImpl
will attempt to detach the EppResource in question that we're loading --
this fails because that entity has been saved in the same transaction
already. We don't need detaching during these methods (it's just for
resource population) so we can use the raw loads to get around it.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/1253)
> Use raw EntityManager to load during beforeSqlSave

- core/src/main/java/google/registry/config/RegistryConfig.java
- core/src/main/java/google/registry/config/RegistryConfigSettings.java
- core/src/main/java/google/registry/config/files/default-config.yaml
- core/src/main/java/google/registry/model/common/DatabaseMigrationStateSchedule.java
- core/src/main/java/google/registry/persistence/transaction/JpaTransactionManagerImpl.java
- core/src/test/java/google/registry/backup/ReplayCommitLogsToSqlActionTest.java
- core/src/test/java/google/registry/model/common/DatabaseMigrationStateScheduleTest.java
- core/src/test/java/google/registry/persistence/transaction/JpaTransactionManagerExtension.java
- core/src/test/java/google/registry/persistence/transaction/TransactionTest.java
- core/src/test/java/google/registry/schema/replay/ReplicateToDatastoreActionTest.java
- core/src/test/java/google/registry/testing/DatabaseHelper.java
- core/src/test/java/google/registry/testing/ReplayExtension.java
- core/src/test/java/google/registry/tools/GetDatabaseMigrationStateCommandTest.java
- core/src/test/java/google/registry/tools/SetDatabaseMigrationStateCommandTest.java
This is instead of the current configuration parameter.
In addition, this adds some helpers to DatabaseHelper to make the
transitions easier, since we more frequently need to alter + reset the
schedule.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/1242)
> Use the DB migration schedule for SQL->DS replay

- core/src/test/java/google/registry/backup/ReplayCommitLogsToSqlActionTest.java
This is related ti b/181758163. That bug seems to think that cascading deletes don't work in replay but unless I'm mistaken, this test shows that they do work.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/1259)
> Add a test for replaying cascading deletes to SQL

- core/src/main/java/google/registry/reporting/icann/IcannReportingStager.java
- core/src/main/java/google/registry/reporting/icann/IcannReportingUploadAction.java
After the migration to the new GCS API it becomes apparent that the
BlobId.of() method needs to take the bucket name (without any trailing
directories) as the first argument. I did a search on all occurrences of
"BlobId.of" in the code base and verified that it is only in the ICANN
reporting job that the API was misused.
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/1265)
> Fix GCS bucket/subdir handling in IcannReportingStager

- core/src/main/java/google/registry/model/common/DatabaseMigrationStateSchedule.java
- core/src/main/java/google/registry/model/ofy/Ofy.java
This performs a direct load-by-key (the most efficient Datastore operation),
rather than attempting to load all entities by type using an ancestor query. The
existing implementation is possibly more error-prone as well, and might be
responsible for the "cross-group transaction need to be explicitly specified"
error we're seeing.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/1273)
> Load DatabaseMigrationStateSchedule in a more performant way

- core/src/main/java/google/registry/model/common/DatabaseMigrationStateSchedule.java
- core/src/test/java/google/registry/model/replay/ReplicateToDatastoreActionTest.java
- core/src/test/java/google/registry/persistence/transaction/JpaTransactionManagerExtension.java
- core/src/test/java/google/registry/persistence/transaction/TransactionTest.java
- core/src/test/java/google/registry/testing/ReplayExtension.java
This occurs because if we do a standard transaction, the JpaTxnManager
checks to see if we should be doing backups, which involves loading the
migration state schedule (causing the recursion). When starting the
transaction to load the schedule, we should explicitly
transactWithoutBackup so there's no need to check.
This wasn't hit in tests because we previously manually set the
replication to not occur in the JpaTransactionManagerExtension -- we
remove that and related setters.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/1286)
> Remove recursive load in DBMSS cache

- core/src/main/java/google/registry/env/crash/default/WEB-INF/cron.xml
Add wipeout cron jobs for the duration of migration testing with
production data.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/1284)
> Update cron jobs in crash

- core/src/main/java/google/registry/tools/RegistryCli.java
We shouldn't reference tm() at all before initializing the JPA
transaction manager, since tm() looks at the database migration schedule
when figuring out which transaction manager to use.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/1287)
> Use direct ofyTm reference when clearing cache in tool

- core/src/main/java/google/registry/env/crash/default/WEB-INF/cron.xml
- core/src/test/java/google/registry/reporting/spec11/GenerateSpec11ReportActionTest.java
This is causing the release build to fail, see https://pantheon.corp.google.com/cloud-build/builds;region=global/22ec980b-c2b6-43fe-994a-aa98c0dbc9d4?project=domain-registry-dev
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/1289)
> Remove -- from crash cron comment

- core/src/main/java/google/registry/env/production/default/WEB-INF/cron.xml
This won't do anything until we set the migration schedule to
DATASTORE_PRIMARY. Actions in order:
1. Add this cron job (it'll be a no-op)
2. Run the init-sql-pipeline to populate production's SQL DB
3. Set the SqlReplayCheckpoint to a time before the smear backup that
was used in step #1 (maybe 30 minutes)
4. Set the database migration schedule to transition to
DATASTORE_PRIMARY at some point
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/1292)
> Add DS->SQL replay cron job to production

- core/src/main/java/google/registry/model/replay/ReplicateToDatastoreAction.java
- core/src/main/java/google/registry/persistence/transaction/Transaction.java
- core/src/main/java/google/registry/persistence/transaction/TransactionEntity.java
- core/src/test/java/google/registry/flows/host/HostCheckFlowTest.java
- core/src/test/java/google/registry/flows/host/HostCreateFlowTest.java
- core/src/test/java/google/registry/flows/host/HostDeleteFlowTest.java
- core/src/test/java/google/registry/flows/host/HostUpdateFlowTest.java
- core/src/test/java/google/registry/testing/ReplayExtension.java
Add double-replay to the Host*Flow tests to show how this works. The
only change to the double replay itself is that now we store the
Datastore entity in the TransactionEntity object -- this is because we
use Objectify to serialize the objects into bytes and we need it to know
about the entity in question.
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/1291)
> Compare SQL and Datastore objects in SQL->DS replay testing

- core/src/main/java/google/registry/model/transfer/DomainTransferData.java
- core/src/test/java/google/registry/batch/ExpandRecurringBillingEventsActionTest.java
- core/src/test/java/google/registry/flows/contact/ContactCheckFlowTest.java
- core/src/test/java/google/registry/flows/contact/ContactCreateFlowTest.java
- core/src/test/java/google/registry/flows/contact/ContactDeleteFlowTest.java
- core/src/test/java/google/registry/flows/contact/ContactInfoFlowTest.java
- core/src/test/java/google/registry/flows/contact/ContactTransferApproveFlowTest.java
- core/src/test/java/google/registry/flows/contact/ContactTransferCancelFlowTest.java
- core/src/test/java/google/registry/flows/contact/ContactTransferQueryFlowTest.java
- core/src/test/java/google/registry/flows/contact/ContactTransferRejectFlowTest.java
- core/src/test/java/google/registry/flows/contact/ContactTransferRequestFlowTest.java
- core/src/test/java/google/registry/flows/contact/ContactUpdateFlowTest.java
- core/src/test/java/google/registry/flows/domain/DomainCheckFlowTest.java
- core/src/test/java/google/registry/flows/domain/DomainClaimsCheckFlowTest.java
- core/src/test/java/google/registry/flows/domain/DomainCreateFlowTest.java
- core/src/test/java/google/registry/flows/domain/DomainDeleteFlowTest.java
- core/src/test/java/google/registry/flows/domain/DomainInfoFlowTest.java
- core/src/test/java/google/registry/flows/domain/DomainRenewFlowTest.java
- core/src/test/java/google/registry/flows/domain/DomainRestoreRequestFlowTest.java
- core/src/test/java/google/registry/flows/domain/DomainTransferApproveFlowTest.java
- core/src/test/java/google/registry/flows/domain/DomainTransferCancelFlowTest.java
- core/src/test/java/google/registry/flows/domain/DomainTransferQueryFlowTest.java
- core/src/test/java/google/registry/flows/domain/DomainTransferRejectFlowTest.java
- core/src/test/java/google/registry/flows/domain/DomainTransferRequestFlowTest.java
- core/src/test/java/google/registry/flows/domain/DomainUpdateFlowTest.java
- core/src/test/java/google/registry/flows/poll/PollAckFlowTest.java
- core/src/test/java/google/registry/flows/poll/PollRequestFlowTest.java
The only other change is that we need to reconstitute
serverApproveEntities for DomainTransferData in more situations (to fill
out the ofy keys)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/1297)
> Add double-replay to remaining existing ReplayExtension calls

- core/src/main/java/google/registry/batch/DeleteProberDataAction.java
- core/src/main/java/google/registry/persistence/transaction/JpaTransactionManagerImpl.java
- core/src/test/java/google/registry/batch/DeleteProberDataActionTest.java
- core/src/test/java/google/registry/persistence/transaction/JpaTransactionManagerImplTest.java
- core/src/test/java/google/registry/testing/DatabaseHelper.java
This includes a change to how the JPA transaction manager handles
existence and load checks for entities with compound IDs. Previously, we
relied on the fields all being named the same in the ID entity and the
parent entity. This didn't work for History objects (e.g. DomainHistory)
so existence checks were broken. Now, we use the methods the same way
that Hibernate does (if possible).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/1218)
> Add SQL functionality to DeleteProberDataAction

- core/src/test/java/google/registry/beam/rde/RdePipelineTest.java
I'm not sure why this test is failing. It's failing saying that the
listObjects call is failing to include
"soy_2000-01-01_thin_S1_R1.xml.ghostryde" in the results, however the
verifyFiles method that we call right beforehand verifies that file and
its contents
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/1306)
> Add RetryingTest annotation to flaky RDE test

- core/src/main/java/google/registry/flows/domain/DomainFlowUtils.java
This snuck in before during a refactor; we should be using the domain in question
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/1309)
> Select correct history entries when creating canceling records

- core/src/main/java/google/registry/model/translators/VKeyTranslatorFactory.java
- core/src/test/java/google/registry/model/translators/VKeyTranslatorFactoryTest.java
- core/src/test/java/google/registry/persistence/VKeyTest.java
This method serves the same function as VKey.fromWebsafeKey(), and isn't used
anywhere.  Move the test for it into VKeyTest and use it to instead test
fromWebsafeKey() (which didn't previously have a test).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/1312)
> Remove VKeyTranslatorFactory.createVKey(String)

- core/src/main/java/google/registry/beam/common/RegistryQuery.java
- core/src/main/java/google/registry/persistence/transaction/ReadOnlyCheckingTypedQuery.java
Make RegistryQuery (exclusively used by BEAM) use EntityManager.clear()
to detach entities. This is a temporary measure to unblock work in BEAM. We
will revert the work once JpaTransactionManager can detach entities properly
for all types of queries.
Also fixed regression bugs that broke query result streaming:
- The code that sets query fetch size was not carried over from
QueryComposer.
- The new ReadOnlyCheckingTypedQuery class did not override parent's
getResultStream() method, which calls getList().
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/1314)
> Add a temporary fix to Hibernate detach in BEAM queries

- core/src/main/java/google/registry/rdap/AbstractJsonableObject.java
- core/src/main/java/google/registry/rdap/RdapActionBase.java
- core/src/main/java/google/registry/rdap/RdapDataStructures.java
- core/src/main/java/google/registry/rdap/RdapDomainSearchAction.java
- core/src/main/java/google/registry/rdap/RdapEntityAction.java
- core/src/main/java/google/registry/rdap/RdapEntitySearchAction.java
- core/src/main/java/google/registry/rdap/RdapJsonFormatter.java
- core/src/main/java/google/registry/rdap/RdapNameserverSearchAction.java
- core/src/main/java/google/registry/rdap/RdapObjectClasses.java
- core/src/main/java/google/registry/rdap/RdapSearchActionBase.java
- core/src/main/java/google/registry/rdap/RdapSearchPattern.java
- core/src/main/java/google/registry/rdap/RdapSearchResults.java
There were minor changes to the RDAP RFCs used -- we don't need to
change anything since we already comply with all of the changes, but we
should refer to the newer RFCs in the code.
https://docs.google.com/document/d/1Y89mJm_5VRp890LhrLajx5-5hmi07N4jAK9ZZS31xLQ/edit#heading=h.uyb2kr1ik95h for a bit more context but it's probably not necessary 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/1313)
> Update references to RDAP RFCs

- core/src/main/java/google/registry/beam/common/RegistryJpaIO.java
- core/src/main/java/google/registry/beam/initsql/InitSqlPipeline.java
- core/src/test/java/google/registry/beam/initsql/InitSqlPipelineTest.java
Prevent InitSqlPipeline from changing the UpdateAutoTimestamp fields in
entities.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/1316)
> Preserve update_time when replicating to SQL

- db/src/main/resources/sql/er_diagram/brief_er_diagram.html
- db/src/main/resources/sql/er_diagram/full_er_diagram.html
- db/src/main/resources/sql/flyway.txt
- db/src/main/resources/sql/flyway/V102__add_indexes_to_domain_history_sub_tables.sql
- db/src/main/resources/sql/schema/nomulus.golden.sql
Add indexes to DomainTransactionRecord and DomainDsDataHistory to speed
up query for DomainHistory. Without these indexes, DomainHistory loading
is extremely slow: 2 QPS with current production data.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/1319)
> Add indexes to DomainHistory sub tables

- core/src/main/java/google/registry/flows/certs/CertificateChecker.java
- core/src/test/java/google/registry/flows/certs/CertificateCheckerTest.java
Initially, if a registrar has never received a notification email regarding expiring certificate, then lastExpiringNotificationSentDate should be null in the database. To avoid null value being the initial value, we decided to set the initial value as START_OF_TIME. 
During testing, I noticed in code that it checks if the value is null but not START_OF_TIME but the value should never be null. 
The existing code still works because the check ```!lastValidDate.after(now.plusDays(expirationWarningDays).toDate()) ``` ensures that certificate is definitely expiring within the warning period and it always checks if ```!lastExpiringNotificationSentDate
.plusDays(expirationWarningIntervalDays)
.toDate()
.after(now.toDate()));```. 
For the expiring notifications that have never received anything …
> Update the initial value for lastExpiringCertNotificationSentDate to START_OF_TIME

- core/src/main/java/google/registry/flows/certs/CertificateChecker.java
- core/src/test/java/google/registry/backup/ReplayCommitLogsToSqlActionTest.java
The build is generating the following lint warnings:
core/src/main/java/google/registry/flows/certs/CertificateChecker.java:246:
warning: [ReferenceEquality] Compariso
n using reference equality instead of value equality
&& (lastExpiringNotificationSentDate == START_OF_TIME
^
(see https://errorprone.info/bugpattern/ReferenceEquality)
core/src/test/java/google/registry/backup/ReplayCommitLogsToSqlActionTest.java:350:
warning: [UnnecessaryParenthes
es] These grouping parentheses are unnecessary; it is unlikely the code will
be misinterpreted without them
.that(jpaTm().transact((() -> jpaTm().loadByEntity(contactResource))))
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/1324 …
> Clean up a few lint warnings

- config/presubmits.py
- core/src/main/java/google/registry/model/index/ForeignKeyIndex.java
- core/src/main/java/google/registry/model/reporting/HistoryEntryDao.java
- core/src/main/java/google/registry/persistence/transaction/JpaTransactionManager.java
- core/src/main/java/google/registry/persistence/transaction/JpaTransactionManagerImpl.java
- core/src/main/java/google/registry/rdap/RdapDomainSearchAction.java
- core/src/main/java/google/registry/rdap/RdapSearchActionBase.java
- core/src/main/java/google/registry/tools/javascrap/CreateSyntheticHistoryEntriesAction.java
- core/src/test/java/google/registry/persistence/transaction/CriteriaQueryBuilderTest.java
- core/src/test/java/google/registry/persistence/transaction/JpaTransactionManagerImplTest.java
- core/src/test/java/google/registry/tools/javascrap/CreateSyntheticHistoryEntriesActionTest.java
The reason for creating synthetic history entries is so that we can
guarantee that each EppResource's most recent *History object contains
that resource at that point in time. If the most recent *History object
in SQL contains that resource already, there is no need to create a
synthetic *History object for that resource.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/1320)
> Skip synthetic history entries for resources that don't need them

- core/src/main/java/google/registry/beam/initsql/InitSqlPipeline.java
- core/src/main/java/google/registry/model/common/Cursor.java
- core/src/test/java/google/registry/beam/initsql/InitSqlPipelineTest.java
- core/src/test/resources/google/registry/beam/initsql/pipeline_golden.dot
The test for this also required a bit of a fix in the Cursor scope
initialization. If you persist a Key<?> in some object in Datastore, it
persists just the standard data you'd expect, basically the parent, the
kind, and the object's ID/name. Then, when you load it back in from
Datastore it uses the app ID of whatever environment you're loading in
(the Key contains this info even though it isn't included in the
toString() of Key)
If you persist the websafe string format of a Key (which is what we do
for Cursors), it includes the app ID so when you load it, it contains
the old app ID not the new one (if the app ID has changed).
In the pipelines, we use the standard default environment which has a
different app ID from the test environment that's set up by the
DatastoreEntityExtension.
As a …
> Include Cursor in the initial SQL population

- core/src/main/java/google/registry/persistence/transaction/ReadOnlyCheckingQuery.java
Following up to PR 1314: fix one more query defaulting to List when
stream() is invoked.
This fixes the Spec11Pipeline's query.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/1329)
> Fix ReadOnlyCheckingQuery's streaming method

- config/presubmits.py
Verify that we have a known set of javascript dependencies.  This guards
against the inadvertent introduction of a new dependency with a disallowed
license.
TESTED: Added a new package to packages.json, observed presubmit failure.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/1334)
> Add a presubmit to verify no new JS dependencies

- core/src/main/java/google/registry/tools/CommandUtilities.java
Also provides a workaround in the error message.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/1340)
> Remove mention of bazel run

- core/src/main/java/google/registry/tools/RegistryToolComponent.java
- core/src/main/java/google/registry/tools/javascrap/BackfillRegistryLocksCommand.java
It would have been nice if this had failed at compile-time rather than
an NPE, but we need to make sure to specify that we need to inject this
command to get e.g. the random string generator
In addition, print out only the names of the failed domains (rather than
the entire domain object) for readability.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/1337)
> Fix injection with BackfillRegistryLocksCommand
