- core/src/main/java/google/registry/model/UpdateAutoTimestamp.java
- core/src/test/java/google/registry/model/registrar/RegistrarTest.java
- core/src/test/java/google/registry/schema/replay/SqlEntityTest.java
- core/src/test/java/google/registry/testing/AppEngineExtension.java
- core/src/test/java/google/registry/testing/DatabaseHelper.java
It's not clear why this is sometimes causing test flakes, but getting better
logging involved should help clear it up.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/1341)
> Add handling for UpdateAutoTimestamp when not in a transaction

- build.gradle
- config/presubmits.py
When running presubmit, we were using /usr/bin/python3, which works fine on
systems that have a reasonably recent python version there.  However, our CI
system has a very old version of python there and prefers the use of "pyenv"
to modify the PATH to provide the desired version of python as simply
"python".  So add a check to use the first of "python" or "/usr/bin/python3"
that is at least version 3.7.3.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/1338)
> Find a suitable version of python.

- core/src/main/java/google/registry/tools/javascrap/CreateSyntheticHistoryEntriesAction.java
We need these to get created (we are blocked from moving to SQL until 30
days after their creation) so reduce this to 3 in the hopes of avoiding
the SQL overloads while we debug why those are occurring in the first
place.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/1344)
> Reduce # shards in CreateSyntheticHistoryEntriesAction

- release/builder/Dockerfile
- release/builder/build.sh
The debian10 image is generally a bit more recent and, in particular, includes
python 3.7.3, which we're currently using as a baseline for our builds.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/1345)
> Use debian10 image for builder, not ubuntu1804

- core/build.gradle
The "cleanTest" target doesn't work for our specialized tests derived from
FilterTest.  Make them all explicit dependencies of cleanTest so we can reset
the tests from a single target.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/1342)
> Make :core:cleanTest depend on FilterTests

- release/cloudbuild-nomulus.yaml
The uber jar name was changed in #1351.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/1367)
> Change Beam uber jar name in Nomulu release GCB config

- core/src/main/java/google/registry/env/sandbox/default/WEB-INF/cron.xml
"synchronized" can only be used to specify a 24h time range that is
evenly divided by the interval value, e. g. "every 2 hours
synchronized".
https://cloud.google.com/appengine/docs/flexible/java/scheduling-jobs-with-cron-yaml#formatting_the_schedule
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/1366)
> Fix sandbox cron

- release/cloudbuild-nomulus.yaml
- release/stage_beam_pipeline.sh
uberjar task and uberjar name are now different (beamPipelineCommon and
beam_pipeline_common, respectively). This is more idiomatic with regard
to naming conventions but we need to take two different variables now.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/1369)
> Fix beam deployment script again.

- .lgtm.yml
- build.gradle
Our presubmit requires a version of python that is more recent than what
lgtm.com's build environments have installed. LGTM shouldn't be 
running the presubmit, but the check will happen regardless of whether 
the presubmit is run or not, since the check is in the task closure instead 
of in a task action.
Attempt to fix this by moving the check to a "doFirst" (a task action).  
This solves the problem when building locally, unfortunately there's no 
easy way to test it on lgtm.com, since lgtm.com appears to fail on a
"./gradlew clean" build of the baseline commit before even getting to
the PR and a) we don't seem to retain logs from a successful run and b)
I can't find any documentation of what lgtm.com's autobuild does by 
default.
In short, this PR fixes a problem (the build won't run …
> Defer python discovery until presubmit task

- config/presubmits.py
- core/src/main/java/google/registry/tools/javascrap/CreateSyntheticHistoryEntriesAction.java
SELECT EXISTS statements will be faster / use fewer read-locks than statements that try to do sorting or return full resources
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/1354)
> Use a more efficient query to find resources in histories

- core/src/main/java/google/registry/persistence/transaction/TransactionManagerFactory.java
- core/src/test/java/google/registry/beam/invoicing/InvoicingPipelineTest.java
- core/src/test/java/google/registry/beam/rde/RdePipelineTest.java
- core/src/test/java/google/registry/beam/spec11/Spec11PipelineTest.java
- core/src/test/java/google/registry/persistence/transaction/JpaTransactionManagerImplTest.java
- core/src/test/java/google/registry/schema/registrar/RegistrarContactTest.java
- core/src/test/java/google/registry/schema/registrar/RegistrarDaoTest.java
- core/src/test/java/google/registry/schema/replay/SqlEntityTest.java
- core/src/test/java/google/registry/testing/DualDatabaseTestInvocationContextProvider.java
- core/src/test/java/google/registry/testing/TmOverrideExtension.java
This is safer to use than calling setTmForTest() directly because this extension
also handles the corresponding call to removeTmOverrideForTest() automatically,
the forgetting of which has been a source of test flakiness/instability in the
past.
There are now broadly two ways to get tests to run in JPA: either use
DualDatabaseTest, an AppEngineExtension, and the corresponding JPA-specific
@Test annotations, OR use this override alongside a
JpaTransactionManagerExtension.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/1382)
> Add TmOverrideExtension for more safe TM overrides in tests

- core/src/main/java/google/registry/reporting/icann/IcannReportingUploadAction.java
- core/src/test/java/google/registry/reporting/icann/IcannReportingUploadActionTest.java
Relevant error log message: 
```
com.google.apphosting.runtime.jetty9.JettyLogger warn: /_dr/task/icannReportingUpload (JettyLogger.java:30)
java.lang.IllegalArgumentException: invalid handle: 9856709681728204953
at com.google.appengine.api.datastore.DatastoreApiHelper.translateError(DatastoreApiHelper.java:49)
at com.google.appengine.api.datastore.DatastoreApiHelper$1.convertException(DatastoreApiHelper.java:127)
at com.google.appengine.api.utils.FutureWrapper.get(FutureWrapper.java:97)
at com.google.appengine.api.datastore.AsyncDatastoreServiceImpl$5.getFutureWithOptionalTimeout(AsyncDatastoreServiceImpl.java:335)
at com.google.appengine.api.datastore.AsyncDatastoreServiceImpl$5.aggregate(AsyncDatastoreServiceImpl.java:306)
at com.google.appengine.api.datastore.AsyncDatastoreServiceImpl$ …
```
> Use multiple transactions in IcannReportingUploadAction

- core/src/main/java/google/registry/model/domain/DomainBase.java
- core/src/main/java/google/registry/model/domain/DomainHistory.java
- core/src/main/java/google/registry/model/host/HostHistory.java
- core/src/main/java/google/registry/model/host/HostResource.java
- core/src/test/java/google/registry/model/domain/DomainBaseTest.java
- core/src/test/java/google/registry/model/history/DomainHistoryTest.java
- core/src/test/java/google/registry/model/history/HostHistoryTest.java
- core/src/test/java/google/registry/model/host/HostResourceTest.java
We do this on host/domain creation now, but there are still some old names from before this was enforced. We should take this opportunity to canonicalize everything. 
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/1350)
> Canonicalize domain/host names in async DS->SQL replay

- config/presubmits.py
- core/src/main/java/google/registry/beam/common/DatabaseSnapshot.java
- core/src/main/java/google/registry/beam/common/RegistryJpaIO.java
- core/src/main/java/google/registry/model/AppEngineEnvironment.java
- core/src/main/java/google/registry/persistence/transaction/JpaTransactionManager.java
- core/src/main/java/google/registry/persistence/transaction/JpaTransactionManagerImpl.java
- core/src/test/java/google/registry/beam/common/DatabaseSnapshotTest.java
- core/src/test/java/google/registry/beam/initsql/InitSqlPipelineTest.java
- core/src/test/java/google/registry/testing/DatastoreEntityExtension.java
Allow multiple workers to share a CONSISTENT database snapshot. The
motivating use case is SQL database snapshot loading, where it is too
slow to depend on one worker to load everything.
This currently is postgresql-specific, but will be improved to be
vendor-independent.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/1403)
> Support shared database snapshot

- core/src/main/java/google/registry/beam/initsql/Transforms.java
There are a few bad domains in Datastore that we hardcoded to ignore
during SQL population. They didn't have history so we didn't try to
filter when writing history.
Recently we created synthesized history for domains, including the bad
domains. Now we need to filter History entries.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/1404)
> Fix InitSqlPipeline regarding synthesized history

- config/presubmits.py
- core/src/main/java/google/registry/persistence/transaction/JpaTransactionManagerImpl.java
Remove the ineffective SQL-injection attack check in go/r3pr/954. It is
quite restrictive, causing a long exempt list. It also doesn't protect
queries made through helpers such as QueryComposer etc.
We will start from scratch for a new solution.
See also: b/179158393
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/1412)
> Remove the ineffective SQL injection check

- core/src/main/java/google/registry/backup/CommitLogCheckpointAction.java
There's an ongoing effort to move away from App Engine API to Cloud Task APIs.  The old task APIs in CommitLogCheckPointAction.java and its test case were replaced after PR#1409 : Change TaskQueueUtils to CloudTaskUtils in CommitLogCheckPointAction (https://github.com/google/nomulus/pull/1409/files) 
The HTTP Method used for the task was not explicitly declared and the task is supposed to be created via POST instead of GET.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/1413)
> Correct HTTP method in CommitLogCheckPointAction

- core/src/test/java/google/registry/testing/CloudTasksHelper.java
TaskOptions.Builder.withUrl() defaults to POST methods.  Therefore, it seems
reasonable to verify that task queue methods are using the POST method,
especially given that the method must now be identified explicitly when using
CloudTaskUtils.  This check would have guarded against the bug fixed by #1413.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/1418)
> Make TaskMatcher default to POST methods

- core/build.gradle
BSD sed requires a parameter to -i to indicate the backup suffix. By
adding a blank suffix the sed command works on both Linux and macOS.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/1421)
> Make Nomulus compile on macOS

- core/src/main/java/google/registry/backup/ReplayCommitLogsToSqlAction.java
- core/src/main/java/google/registry/model/replay/ReplicateToDatastoreAction.java
It's always acquired in SQL, so it should always be released in SQL.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/1422)
> Release the replay lock in SQL, not Datastore

- core/src/main/java/google/registry/model/EntityClasses.java
- core/src/main/java/google/registry/model/tmch/TmchCrl.java
- core/src/test/java/google/registry/backup/ReplayCommitLogsToSqlActionTest.java
- core/src/test/java/google/registry/model/tmch/TmchCrlTest.java
- core/src/test/resources/google/registry/export/crosstld_kinds.txt
- core/src/test/resources/google/registry/model/schema.txt
The TmchCrl singleton has been dual-written for a long time with no issues. This change fully migrates TmchCrl to CloudSql. Since this data is rewritten everyday, a formal staged migration is not necessary. 
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/1419)
> Remove TmchCrl singleton from Datastore

- core/src/main/java/google/registry/backup/BackupUtils.java
- core/src/main/java/google/registry/backup/CommitLogCheckpointAction.java
We need to be able to continue running the backup and async replay code
while the database is in read-only mode
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/1424)
> Ignore read-only mode when running commit logs / backups

- core/src/main/java/google/registry/model/EppResource.java
- core/src/main/java/google/registry/model/replay/ReplicateToDatastoreAction.java
We need to be able to save indices and save data about the replication
even when we're in read-only mode.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/1432)
> Ignore read-only mode in SQL->DS replication process

- core/src/main/java/google/registry/model/domain/DomainBase.java
- core/src/main/java/google/registry/model/domain/DomainHistory.java
This is a result of bad data (we should never allow a null digest) and
we'll need to fix that separately, but this allows us to not fail on
this during replay
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/1439)
> Filter missing dsData digests during replay

- core/src/main/java/google/registry/persistence/VKey.java
- core/src/main/java/google/registry/tools/GetResourceByKeyCommand.java
- core/src/test/java/google/registry/persistence/VKeyTest.java
- core/src/test/java/google/registry/tools/GetResourceByKeyCommandTest.java
- core/src/test/java/google/registry/tools/SetupOteCommandTest.java
Currently, there's only pretty print ofy key info not vkey. If we are replacing ofy keys with vkeys, we need to replace the output statement about ofy keys with vkeys' as well. 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/1431)
> Add method to show readable key info

- core/src/main/java/google/registry/backup/BackupUtils.java
- core/src/main/java/google/registry/backup/CommitLogCheckpointAction.java
- core/src/main/java/google/registry/backup/ReplayCommitLogsToSqlAction.java
- core/src/main/java/google/registry/model/EppResource.java
- core/src/main/java/google/registry/model/common/DatabaseMigrationStateSchedule.java
- core/src/main/java/google/registry/model/ofy/DatastoreTransactionManager.java
- core/src/main/java/google/registry/model/ofy/Ofy.java
- core/src/main/java/google/registry/model/replay/ReplicateToDatastoreAction.java
- core/src/main/java/google/registry/model/replay/SqlReplayCheckpoint.java
- core/src/main/java/google/registry/model/server/Lock.java
- core/src/main/java/google/registry/persistence/transaction/JpaTransactionManagerImpl.java
- core/src/main/java/google/registry/persistence/transaction/Transaction.java
- core/src/main/java/google/registry/persistence/transaction/TransactionManager.java
- core/src/test/java/google/registry/backup/ReplayCommitLogsToSqlActionTest.java
- core/src/test/java/google/registry/persistence/transaction/TransactionTest.java
- core/src/test/java/google/registry/testing/DatabaseHelper.java
Previously, we had no way to ignore read-only mode while still writing
commit log backups. Now, we added this so we can write commit logs in
the SQL->DS replay.
Note:
- When moving to either of the DATASTORE_PRIMARY stages, one must
manually set the SqlReplayCheckpoint first. We don't write to SQL with
backup in this stage because we already wrote the transaction in
question to Datastore. The fact that we manually set the replay
checkpoint means that we'll ignore the extra commit logs that might
otherwise cause problems if we switched back and forth from
DATASTORE_PRIMARY to SQL_PRIMARY.
- The commit logs written during the SQL_PRIMARY phase will, ideally, be
unused. We write them here only so that in the event of a rollback to
Datastore, we will have them for RDE purposes.
---
This …
> Write commit logs during SQL->DS replay

- core/src/main/java/google/registry/model/domain/DomainHistory.java
- core/src/main/java/google/registry/model/ofy/ReplayQueue.java
- core/src/test/java/google/registry/flows/domain/DomainDeleteFlowTest.java
- core/src/test/java/google/registry/model/history/DomainHistoryTest.java
- core/src/test/java/google/registry/model/reporting/HistoryEntryTest.java
This is what's causing https://b.corp.google.com/issues/208274109, where
there are DTR rows with null foreign key values.
We should probably wait to make the columns officially non-null until we
get this in and verify that we can do so.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/1444)
> Remove orphaned DomainTransactionRecords

- core/src/main/java/google/registry/beam/comparedb/ValidateSqlUtils.java
- core/src/main/java/google/registry/model/billing/BillingEvent.java
- core/src/main/java/google/registry/model/tld/Registry.java
- core/src/main/java/google/registry/persistence/NomulusPostgreSQLDialect.java
- core/src/main/java/google/registry/persistence/converter/JodaMoneyType.java
- core/src/main/resources/META-INF/orm.xml
- core/src/test/java/google/registry/persistence/converter/JodaMoneyConverterTest.java
Joda Money has BigDecimal as amount, which is mapped to a numeric(19,2)
column in the database. As a result, the Money amount load from DB has
scale 2. This becomes a problem with currencies such as JPY, which
requires scale to be 0. To properly load a currency, we must adjust the
scale post-load.
The current approach, which uses Hibernate component mapping,  puts the
burden of post-load cleanup on each entity type that uses Money. It is
easy to forget this, as we just discovered.
This PR uses a CompositeUserType to map Money. It adjusts the scale
properly when loading Money instances. Although CompositeUserType appear
to be deprecated in Hibernate 6, it is the only proper solution right
now for mapping non-owned classes.
--- …
> Properly handle Joda Money in JPA

- core/src/main/java/google/registry/model/domain/DomainBase.java
- core/src/main/java/google/registry/model/domain/DomainHistory.java
- core/src/test/java/google/registry/model/history/DomainHistoryTest.java
Hibernate/SQL will get mad if the digest is null or empty, and
previously we only check for null. We should filter out empty digests as
well.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/1449)
> Filter out empty dsData objects, not just null ones

- core/src/main/java/google/registry/env/alpha/default/WEB-INF/cron.xml
- core/src/main/java/google/registry/env/crash/default/WEB-INF/cron.xml
- core/src/main/java/google/registry/env/qa/default/WEB-INF/cron.xml
- core/src/main/java/google/registry/env/sandbox/default/WEB-INF/cron.xml
This shouldn't do anything yet (since ReplicateToDatastoreAction checks the
migration state before doing anything) but we'll want to have this in
place.
We can add it to the prod file after verifying no errors with this.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/1450)
> Add replicateToDatastore to non-prod cron files

- core/src/main/java/google/registry/model/common/ClassPathManager.java
- core/src/main/java/google/registry/model/translators/VKeyTranslatorFactory.java
- core/src/test/java/google/registry/backup/ReplayCommitLogsToSqlActionTest.java
- core/src/test/java/google/registry/model/common/ClassPathManagerTest.java
- core/src/test/java/google/registry/model/translators/VKeyTranslatorFactoryTest.java
- core/src/test/java/google/registry/persistence/VKeyTest.java
Currently, CLASS_REGISTRY resides in VKeyTranslatorFactory. CLASS_REGISTRY stores class name and package/class path mapping, but this mapping really could be used for class path look up and add test entity classes, in other classes. 
In this PR, a new class ClassPathManager is created to encapsulate CLASS_REGISTRY and the methods are static. This manager will allow class info being passed around without explicitly showing class path in the URL.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/1440)
> Extract CLASS_REGISTRY from VKeyTranslatorFactory

- core/src/main/java/google/registry/request/RequestMetrics.java
The cardinality for the paths is unbound, and could generate a huge
amount of metrics if someone is scanning our web WHOIS endpoint.
See b/209488119 for an example of such a sudden increase in metric volume.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/1451)
> Truncate web WHOIS request path when recording metrics

- build.gradle
- gradle/dependency-locks/buildscript-classpath.lockfile
see https://b.corp.google.com/issues/208629747 for details; this brings
in an old Gradle version as a transitive dependency
Version 2.x of the task-tree plugin uses Gradle 6.8 (or higher)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/1452)
> Update task-tree dependency

- core/src/main/java/google/registry/model/domain/DomainHistory.java
- core/src/main/java/google/registry/model/reporting/HistoryEntry.java
In replay (and possibly in other cases) we're getting an exception:
Caused by: org.hibernate.HibernateException: A collection with cascade="all-delete-orphan" was no longer referenced by the owning entity instance: google.registry.model.domain.DomainHistory.internalDomainTransactionRecords
The main cause of this, according to research (StackOverflow :P) is that
when Hibernate is calling the setters for these sets of children it's
losing the connection to the previously-managed child entity (which it
needs, in order to know how to delete orphans). Thus, the solution is to
maintain the same instance of the persistent set and just add/remove
to/from it as necessary.
This is complicated by the fact that sometimes the setter is given the
persistent set (the one we want to keep) and sometimes …
> Copy DTRs into PersistentSet field if applicable in HistoryEntry

- core/src/main/java/google/registry/rde/RdeModule.java
- core/src/main/java/google/registry/rde/RdeStagingAction.java
- core/src/main/java/google/registry/tools/GenerateEscrowDepositCommand.java
- core/src/test/java/google/registry/tools/GenerateEscrowDepositCommandTest.java
This adds two new options:
1) An option to run RDE in lenient mode.
2) An option to run RDE with the new Beam pipeline regardless of the datastore setting.
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/1453)
> Add more options to the generate escrow deposit command

- core/src/main/java/google/registry/backup/GcsDiffFileLister.java
It looks like the diff file lister is doing a second constructDiffSequence()
when a commit diff file is missing from the final sequence for purely
informational purposes.  However, this purpose wasn't clear when investigating
an actual case of this.
This PR adds another warning to hopefully make the log output a bit more
useful, and also promotes the "gap" log message to a warning and adds a
comment indicating the purpose of the second constructDiffSequence().
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/1464)
> Improve logging/comments for commit log forks

- core/src/main/java/google/registry/model/ImmutableObject.java
- core/src/main/java/google/registry/model/common/Cursor.java
- core/src/main/java/google/registry/model/contact/ContactHistory.java
- core/src/main/java/google/registry/model/domain/DomainHistory.java
- core/src/main/java/google/registry/model/host/HostHistory.java
- core/src/main/java/google/registry/model/registrar/RegistrarContact.java
- core/src/test/java/google/registry/model/ImmutableObjectTest.java
Remove the identity hash from the output. There is no use case
(including debugging) for it.
Removing it allows us to also remove some overriding implementations in
subclasses, and may also simplify tests.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/1469)
> Make ImmutableObject.toString deterministic

- core/src/main/java/google/registry/beam/comparedb/ValidateSqlPipeline.java
- core/src/main/java/google/registry/beam/comparedb/ValidateSqlUtils.java
- core/src/main/java/google/registry/beam/initsql/Transforms.java
- core/src/main/java/google/registry/model/bulkquery/DomainHistoryHost.java
- core/src/main/java/google/registry/model/bulkquery/DomainHost.java
- core/src/main/java/google/registry/model/poll/PollMessage.java
Deletion of prober entities are not propagated to SQL, resulting in two
types of mismatches: entity only exists in SQL, or copies of an entity
differ in deleteTime. Both cases should not count as erros.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/1471)
> Ignore Prober related entities when comparing db

- core/src/main/java/google/registry/beam/rde/RdeIO.java
- core/src/main/java/google/registry/persistence/transaction/TransactionManagerFactory.java
- core/src/test/java/google/registry/beam/rde/RdePipelineTest.java
Beam does not have access to datastore. Using ofy on Beam always results
in an error. Normally we should use database migration state schedule to
determine which TM to use, but on Beam there's no point in doing so. By
hardcoding the TM on beam to be SQL we can start testing features before
we migrate to SQL mode, for example the new RDE pipeline.
TESTED=deployed the pipeline on production and ran a job.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/1474)
> Always use JPA TM on Beam

- core/src/main/java/google/registry/batch/BatchModule.java
- core/src/main/java/google/registry/batch/ResaveEntityAction.java
- core/src/main/java/google/registry/module/backend/BackendComponent.java
- core/src/main/java/google/registry/persistence/VKey.java
- core/src/main/java/google/registry/tools/GetResourceByKeyCommand.java
- core/src/main/java/google/registry/tools/ResaveEntitiesCommand.java
- core/src/test/java/google/registry/batch/ResaveEntityActionTest.java
- core/src/test/java/google/registry/persistence/VKeyTest.java
Currently, in ```ResaveEntityAction```, resource key is passed in as ```Key<ImmutableObject>``` from ```BatchModule``` . The problem with this is, if the resource key is in the new vkey string representation, this action will fail because a key cannot be created in ```BatchModule``` since the extracted string is not an acceptable websafe string used by ```Key```. 
Instead of creating a ```Key<ImmutableObject>``` object then creating a vkey by calling ```VKey.from(Key<ImmutableObject> object)```, we need to replace with```VKey.create() ``` which can handle both new vkey string representation and old vkey string representation (which is ofy key in string form).  
In this PR, ```throws Exception``` is dropped from the existing ```VKey.create()``` method since there's no unexpected exception …
> Change resource key type from Key to String for ResaveEntityAction

- core/src/main/java/google/registry/flows/domain/DomainUpdateFlow.java
- core/src/test/java/google/registry/flows/domain/DomainUpdateFlowTest.java
- core/src/test/resources/google/registry/flows/poll_response_server_hold.xml
This is necessary for the poll messages to contain the necessary context
explaining what domain name the relevant statuses were being added/removed
to/from.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/1478)
> Add pending action extension to server update poll messages

- core/src/main/java/google/registry/model/tld/label/PremiumListDao.java
- core/src/main/java/google/registry/model/tld/label/PremiumListUtils.java
- core/src/main/java/google/registry/tools/UpdatePremiumListCommand.java
- core/src/test/java/google/registry/model/tld/label/PremiumListDaoTest.java
- core/src/test/java/google/registry/tools/UpdatePremiumListCommandTest.java
This state is possible to get into when things go wrong and it shouldn't prevent
saving new revisions of the list. Note that it will continue to throw errors if
you attempt to save a new revision that is blank (which is usually a mistake).
See http://b/211774375
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/1479)
> Don't throw errors when existing premium list is empty

- release/cloudbuild-delete.yaml
Right now we are using the default credential of Cloud Build to run
gcloud, which does not have the necessary permission. By using the
service account credential (which is a GAE admin), we should be able to
delete unused versions as part of deployment.
Note: it looks like this never worked when it was added to the
deployment pipeline, not as a result of overground changes under our
feet.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/1484)
> Use the service account credential to delete unused versions

- core/src/main/java/google/registry/batch/AsyncTaskEnqueuer.java
- core/src/main/java/google/registry/model/index/EppResourceIndex.java
- core/src/main/java/google/registry/persistence/VKey.java
- core/src/main/java/google/registry/tools/GetEppResourceCommand.java
- core/src/test/java/google/registry/batch/AsyncTaskEnqueuerTest.java
- core/src/test/java/google/registry/batch/DeleteContactsAndHostsActionTest.java
- core/src/test/java/google/registry/batch/RefreshDnsOnHostRenameActionTest.java
- core/src/test/java/google/registry/batch/ResaveEntityActionTest.java
- core/src/test/java/google/registry/flows/ResourceFlowTestCase.java
- core/src/test/java/google/registry/flows/domain/DomainDeleteFlowTest.java
- core/src/test/java/google/registry/flows/domain/DomainTransferRequestFlowTest.java
- core/src/test/java/google/registry/flows/host/HostUpdateFlowTest.java
- core/src/test/java/google/registry/persistence/VKeyTest.java
- core/src/test/java/google/registry/tools/GetContactCommandTest.java
- core/src/test/java/google/registry/tools/GetDomainCommandTest.java
- core/src/test/java/google/registry/tools/GetHostCommandTest.java
- core/src/test/java/google/registry/tools/ResaveEntitiesCommandTest.java
This purpose of this PR is to replace all existing vkey strings with new vkey string representation strings created by stringify(). We need to make sure that the vkey strings from task queue (which are stringified) can be used to re-create the vkey successfully. 
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/1430)
> Replace all existing vkey string to vkey.stringify() 

- core/src/main/java/google/registry/beam/common/RegistryPipelineComponent.java
- core/src/main/java/google/registry/beam/common/RegistryPipelineWorkerInitializer.java
- core/src/main/java/google/registry/config/RegistryConfig.java
- core/src/main/java/google/registry/config/RegistryConfigSettings.java
- core/src/main/java/google/registry/config/files/default-config.yaml
- core/src/main/java/google/registry/persistence/PersistenceComponent.java
- core/src/main/java/google/registry/persistence/PersistenceModule.java
- core/src/main/java/google/registry/rde/RdeStagingAction.java
- core/src/main/resources/google/registry/beam/rde_pipeline_metadata.json
This adds the Dagger provider code for both the regular and the BEAM
environments, which are similar but not quite the same.
In addition, this demonstrates usage of the replica DB in the
RdePipeline. I tested this on alpha with a modified version of the
RdePipeline that attempts to write some dummy values to the database and
it failed with the expected message that one cannot write to a replica.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/1470)
> Allow usage of a read-only Postgres replica

- core/src/main/java/google/registry/config/RegistryConfig.java
- core/src/main/java/google/registry/config/RegistryConfigSettings.java
- core/src/main/java/google/registry/config/files/default-config.yaml
- core/src/main/java/google/registry/export/ExportPremiumTermsAction.java
- core/src/main/java/google/registry/model/tld/label/PremiumList.java
- core/src/main/java/google/registry/model/tld/label/PremiumListDao.java
- core/src/main/java/google/registry/persistence/PersistenceModule.java
- core/src/main/java/google/registry/tools/GetPremiumListCommand.java
- core/src/main/java/google/registry/tools/UpdatePremiumListCommand.java
- core/src/test/java/google/registry/model/tld/label/PremiumListDaoTest.java
- core/src/test/java/google/registry/testing/DatabaseHelper.java
- core/src/test/java/google/registry/tools/UpdatePremiumListCommandTest.java
There are two parts to this:
1. Don't load the premium entries in the command prompt (this isn't
necessary and we didn't display that information anyway).
2. Set a proper batch size (rather than just 1) when saving all the
premium entries. This means that we generate only one INSERT statement
rather than N statements.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/1482)
> Speed up updating of premium lists

- core/build.gradle
- core/src/main/java/google/registry/tools/RegistryTool.java
- core/src/main/java/google/registry/tools/RegistryToolComponent.java
- core/src/main/java/google/registry/tools/javascrap/CompareEscrowDepositsCommand.java
- core/src/test/java/google/registry/tools/CommandTestCase.java
- core/src/test/java/google/registry/tools/javascrap/CompareEscrowDepositsCommandTest.java
- core/src/test/resources/google/registry/rde/deposit_full_different.xml
- core/src/test/resources/google/registry/rde/deposit_full_out_of_order.xml
We already have ValidateEscrowDepositCommand to check for internal
reference consistency of two deposits, i. e. making sure that all
contacts and hosts referenced by domains exist in the same deposit.
Therefore to compare whether two deposits are equal we only need to make
sure that they contain the same domains and registrars, assuming they
both pass the validation. We don't compare their contents directly
because the MapReduce deposit contains all contacts and domains whereas
the Beam deposit only contains referenced ones, making a direct
comparison impossible.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/1476)
> Add a command to compare two escrow  deposits

- core/src/main/java/google/registry/beam/comparedb/DatastoreSnapshots.java
- core/src/main/java/google/registry/beam/comparedb/SqlSnapshots.java
- core/src/main/java/google/registry/beam/comparedb/ValidateSqlPipeline.java
- core/src/main/java/google/registry/beam/comparedb/ValidateSqlPipelineOptions.java
- core/src/test/java/google/registry/beam/comparedb/DatastoreSnapshotsTest.java
- core/src/test/java/google/registry/beam/comparedb/SqlSnapshotsTest.java
When comparing Datastore and SQL, ignore older History and EPP resource
objects. This cuts the run time in half compared with a full comparison.
The intention is to run a full comparison before the switch-over from
Datastore and SQL, and run this incremental comparison during the down
time.
The incremental comparison takes about 25 minutes in production.
Performance can be improved further by filtering out older billing
events (OneTime and Cancellation). However, we don't think further
optimization is worth the effort (considering that Recurring events
cannot be filtered since they are mutable but without lastUpdateTime).
Verified in Sandbox and prod with and without time filter.
--- …
> Only compare recent changes in Datastore and SQL

- core/src/main/java/google/registry/backup/CommitLogCheckpointAction.java
- core/src/main/java/google/registry/backup/DeleteOldCommitLogsAction.java
The tm() call will use JPA transaction manager after the switch-over to
SQL. These calls would lose their transaction semantics.
Both actions are to be invoked after the switchover in case we have to
switch back to Datastore as primary.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/1492)
> CommitLog handling code should call ofyTm

- core/src/test/java/google/registry/cron/TldFanoutActionTest.java
- core/src/test/java/google/registry/testing/CloudTasksHelper.java
- util/src/main/java/google/registry/util/CloudTasksUtils.java
- util/src/main/java/google/registry/util/CollectionUtils.java
- util/src/test/java/google/registry/util/CloudTasksUtilsTest.java
- util/src/test/java/google/registry/util/CollectionUtilsTest.java
The existing ```createTask()``` does not contain null or empty check for parameters. Therefore, the method throws an error if an empty map or null value is being passed in as ```params```. 
This can be fixed by 1) adding a guard against null or empty parameters so the existing code doesn't have to be modified. However, there might be existing use cases that would send requests without params, or 2) moving the existing logic under an if block ```if (params !=null || !params.isEmpty())```  
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/1448)
> Add support for empty or null params for createTask()

- core/src/main/java/google/registry/module/pubapi/PubApiComponent.java
- core/src/main/java/google/registry/persistence/PersistenceModule.java
- core/src/main/java/google/registry/rdap/RdapDomainSearchAction.java
- core/src/test/java/google/registry/persistence/transaction/ReplicaSimulatingJpaTransactionManager.java
- core/src/test/java/google/registry/rdap/RdapDomainSearchActionTest.java
We can use it more places later but this can serve as a template. We
should inject the connection to the read-only replica (only created
once) to the constructor of the action, then use that instead of the
regular transaction manager.
We add a transaction manager that simulates the read-only-replica
behavior for testing purposes as well.
In addition, we set the transaction isolation level to READ COMMITTED
for this transaction manager (this is fine since we're never writing to
it). Postgres requires this for replica SQL access (it fails if we try
to use SERIALIZABLE) transactions. We didn't see this with the pipelines
before since those already had transaction isolation level overrides
--- …
> Use a read-only replica SQL instance in RdapDomainSearchAction

- core/src/main/java/google/registry/beam/rde/RdeIO.java
- core/src/main/java/google/registry/env/production/default/WEB-INF/cron.xml
The Beam pipeline will save the deposit in a folder prefixed with the
Dataflow job name so it will not collide with the MapReduce ones. It
will not advance the cursor or trigger subsequent upload actions. The
deposits will be used to compare with MapReduce deposits.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/1500)
> Add a cron job to run the RDE Beam pipeline in parallel with MapReduce

- core/build.gradle
- core/src/main/java/google/registry/beam/comparedb/LatestDatastoreSnapshotFinder.java
- core/src/main/java/google/registry/beam/comparedb/ValidateDatastorePipeline.java
- core/src/main/java/google/registry/beam/comparedb/ValidateDatastorePipelineOptions.java
- core/src/main/java/google/registry/beam/comparedb/ValidateSqlPipeline.java
Add a BEAM pipeline that compares the secondary Datastore against SQL.
This is a dumb pipeline to be launched by a driver (in a followup PR).
Manually tested pipeline in sandbox.
Also updated the ValidateSqlPipeline and the snapshot finder class so
that an appropriate Datastore export is found (one that ends before the
replay checkpoint value).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/1497)
> Compare migration data with SQL as primary DB

- core/build.gradle
- core/src/main/resources/google/registry/beam/validate_datastore_pipeline_metadata.json
- release/cloudbuild-nomulus.yaml
Update release process to create container image for ValidateDatastorePipeline, so that it is launchable from the Nomulus server.
Tested in alpha with Cloud Build
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/1501)
> Release ValidateDatastorePipeline

- core/src/main/java/google/registry/model/EppResource.java
- core/src/main/java/google/registry/model/index/ForeignKeyIndex.java
- core/src/main/java/google/registry/persistence/transaction/TransactionManagerFactory.java
- core/src/test/java/google/registry/persistence/transaction/JpaTransactionManagerExtension.java
- core/src/test/java/google/registry/persistence/transaction/ReplicaSimulatingJpaTransactionManager.java
The cached methods are only used in situations where we don't really
care about being 100% synchronously up to date (e.g. whois), and they're
not used frequently anyway, so it's safe to use the replica in these
locations.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/1503)
> Use the replica jpaTm in FKI and EppResource cache methods

- core/src/main/java/google/registry/rde/RdeStagingAction.java
Standard mode will determine the watermarks based on the cursors and
kick off subsequent uploading steps. In order to run both the Beam and
the Mapreduce pipeline in parallel, we need to allow setting the beam
parameter when in standard mode. This changes should have been part of
https://github.com/google/nomulus/pull/1500.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/1505)
> Allow the beam parameter in RDE standard mode

- core/src/main/java/google/registry/rde/RdeStagingReducer.java
- core/src/test/java/google/registry/rde/RdeStagingActionDatastoreTest.java
- core/src/test/java/google/registry/rde/RdeStagingReducerTest.java
- core/src/test/java/google/registry/testing/CloudTasksHelper.java
Most of the changes are similar to the previous TaskQueueUtils-> CloudTasksUtils PRs, except `TaskQueueHelper` is still used for the `"mapreduce"` queue. Nothing related to the "mapreduce" queue, should be changed since it is enqueued by the map reduce utils class and not controlled by `CloudTasksUtil`. 
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/1411)
> Change from TaskQueueUtils to CloudTasksUtils in RdeStaging

- core/src/main/java/google/registry/rde/BrdaCopyAction.java
- core/src/test/java/google/registry/rde/BrdaCopyActionTest.java
The revision was hardcoded to 0, which caused problem when we need to
re-run BRDA.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/1508)
> Copy the latest revision of BRDA during upload

- core/src/main/java/google/registry/persistence/transaction/CriteriaQueryBuilder.java
- core/src/main/java/google/registry/persistence/transaction/JpaTransactionManagerImpl.java
- core/src/main/java/google/registry/rdap/RdapDomainSearchAction.java
- core/src/main/java/google/registry/rdap/RdapEntitySearchAction.java
- core/src/main/java/google/registry/rdap/RdapNameserverSearchAction.java
- core/src/main/java/google/registry/rdap/RdapSearchActionBase.java
- core/src/test/java/google/registry/persistence/transaction/JpaTransactionManagerExtensionTest.java
- core/src/test/java/google/registry/rdap/RdapDomainSearchActionTest.java
This includes a test for the replica-simulating transaction manager and
removal of any replica-specific code in RDAP tests, because it's
unnecessary due to the existing tests.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/1506)
> Use the built-in replicaJpaTm() in RDAP

- release/cloudbuild-delete.yaml
The gcloud command does some weird stuff with sorting when custom format
is used. Here we instead rely on linux sort and head command to sort the
versions list.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/1511)
> Correctly delete all stopped versions except for the most recent 3

- core/src/test/java/google/registry/backup/CommitLogCheckpointActionTest.java
- core/src/test/java/google/registry/testing/CloudTasksHelper.java
- util/src/main/java/google/registry/util/CloudTasksUtils.java
- util/src/test/java/google/registry/util/CloudTasksUtilsTest.java
Currently, there are two ways to create a task via `CloudTasksUtil`: one with no specific schedule time, and one with random delay. There needs to be a way to schedule a task by specifying the delay time.
Added `scheduleTime` as one of the matchers in `CloudTasksHelper`. `Instant` is used for time comparison since it allows us to create the time slightly easier by using millis. 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/1493)
> Add support for delay of duration when scheduling a task

- core/src/main/java/google/registry/beam/rde/RdeIO.java
- core/src/main/java/google/registry/rde/BrdaCopyAction.java
- core/src/main/java/google/registry/rde/RdeStagingReducer.java
- core/src/test/java/google/registry/rde/RdeStagingActionDatastoreTest.java
Fixed the most common cause that makes one method flaky (Clock and
timestamp problem). Added a TODO to rethink test case.
Also added notes on tasks potentially enqueued multiple times.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/1514)
> Fix flaky RdeStagingActionDatastoreTest

- core/src/main/java/google/registry/model/translators/CreateAutoTimestampTranslatorFactory.java
- core/src/main/java/google/registry/model/translators/UpdateAutoTimestampTranslatorFactory.java
- core/src/test/java/google/registry/batch/ExpandRecurringBillingEventsActionTest.java
- core/src/test/java/google/registry/flows/domain/DomainCreateFlowTest.java
- core/src/test/java/google/registry/flows/domain/DomainUpdateFlowTest.java
- core/src/test/java/google/registry/model/domain/DomainBaseSqlTest.java
- core/src/test/java/google/registry/testing/ReplayExtension.java
When CreateAutoTimestamp and UpdateAutoTimestamp are inserted into a
Transaction, their values are not populated in the same way as when they are
stored in the course of an SQL commit.  This results in different timestamp
values between SQL and datastore during the SQL -> DS replay.
Fix this by providing these values from the JPA transaction time when we're
doing transaction serialization.
This change also removes the initialization of the Ofy clock in
ExpandRecurringBillingEventsActionTest.  It's not necessary as the
ReplayExtension already takes care of this and doing it after the
ReplayExtension as we were breaks a test now that the update timestamps are
correct.
--- …
> Fix create/update timestamp replay problems

- core/build.gradle
- dependencies.gradle
In [#PR1491](https://github.com/google/nomulus/pull/1491/files), ```com.google.protobuf:protobuf-java-util:3.17.3``` was added to [build.gradle](https://github.com/rachelguan/nomulus/blob/e66f6caefd2f9bb4cd20f04b4add44bfb07fee00/core/build.gradle) via ```./gradlew fixGradleLint```. It fixed the dependency warnings but it was not the standard way to add it. 
The purpose of this PR is to fix the problem by adding the dependency to [dependencies.gradle](https://github.com/google/nomulus/blob/master/dependencies.gradle) and [build.gradle](https://github.com/rachelguan/nomulus/blob/e66f6caefd2f9bb4cd20f04b4add44bfb07fee00/core/build.gradle) following the same format as the other added dependencies.
--- …
> Fix protobuf-java-util dependency in gradle

- core/src/main/java/google/registry/model/BackupGroupRoot.java
- core/src/main/java/google/registry/model/EppResource.java
- core/src/main/java/google/registry/model/bulkquery/BulkQueryEntities.java
- core/src/main/java/google/registry/model/domain/DomainContent.java
- core/src/test/java/google/registry/beam/initsql/DomainBaseUtilTest.java
- core/src/test/java/google/registry/model/domain/DomainBaseSqlTest.java
We expect update timestamps to be updated whenever a containing entity is
modified and persisted, but unfortunately Hibernate doesn't seem to do this --
instead it appears to regard such an entity as unchanged.
To work around this, we explicitly reset the update timestamp whenever a
nested collection is modified in the Builder.
Note that this change only solves the problem for DomainContent.  All other
entitities containing UpdateAutoTimestamp will need to be audited and
instrumented with a similar change.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/1517)
> Fix update timestamps for DomainContent types

- core/src/main/java/google/registry/model/domain/DomainContent.java
- core/src/main/java/google/registry/model/ofy/CommitLoggedWork.java
- core/src/main/java/google/registry/model/registrar/Registrar.java
- core/src/main/java/google/registry/persistence/transaction/JpaTransactionManagerImpl.java
- core/src/main/java/google/registry/ui/server/registrar/RegistrarSettingsAction.java
- core/src/test/java/google/registry/flows/domain/DomainCreateFlowTest.java
- core/src/test/java/google/registry/flows/domain/DomainUpdateFlowTest.java
- core/src/test/java/google/registry/persistence/EntityCallbacksListenerTest.java
- core/src/test/java/google/registry/persistence/transaction/JpaEntityCoverageExtension.java
- core/src/test/java/google/registry/persistence/transaction/TransactionManagerTest.java
- core/src/test/java/google/registry/testing/ReplayExtension.java
- core/src/test/java/google/registry/ui/server/registrar/RegistrarSettingsActionTest.java
Replay tests currently only verify that the contents of a transaction
can be successfully replicated to the other database.  They do not verify that
the contents of both databases are equivalent.  As a result, we miss any
changes omitted from the transaction (as was the case with entity deletions).
This change adds a final database comparison to ReplayExtension so we can
safely say that the databases are in the same state at the end of a test.
Doing a full database comparison surfaces a number of problems.  Some of these
problems are fixed in this PR (notably, the lack of replication during 
`jpaTm().delete(entity)`, and update timestamp issues when changing a Registrar's
TLDs or DomainContent grace periods).  Others are simply suppressed by disabling
full database comparison for the …
> Do full database comparison during replay tests

- core/src/main/java/google/registry/env/sandbox/default/WEB-INF/cron.xml
This has caused some confusion for a registrar. Disable it for now while
we figure out how to re-word the email for sandbox, or if we should
leave it disabled permanently.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/1528)
> Disable sending cert expiration emails on sandbox

- core/src/main/java/google/registry/flows/domain/DomainFlowUtils.java
- core/src/main/java/google/registry/model/contact/ContactHistory.java
- core/src/main/java/google/registry/model/domain/DomainHistory.java
- core/src/main/java/google/registry/model/host/HostHistory.java
- core/src/main/java/google/registry/model/reporting/HistoryEntry.java
- core/src/test/java/google/registry/testing/ReplayExtension.java
We can't easily compare objects that are embedded in Datastore entities because when loading them from Datastore, we have no way of knowing their assigned SQL IDs. This shouldn't be super relevant because we're still comparing the parent entities to one another, so as long as those come back clean we should be OK.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/1529)
> Fix DTR creation in one location and clean up replay comparison

- core/src/main/java/google/registry/model/registrar/Registrar.java
- core/src/test/java/google/registry/testing/DatabaseHelper.java
It turns out that the reason that the Registrar update timestamp isn't updated
for some of the tests is because the record is updated unchanged.  We can
avoid this problem by not trying to update the registrar to the same value.
So in this case, if the registrar alreay contains the TLD we're adding, don't
try to add it.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/1532)
> Don't reset the update time for TLD updates

- core/src/main/java/google/registry/model/domain/DomainContent.java
- core/src/test/java/google/registry/flows/domain/DomainUpdateFlowTest.java
- core/src/test/java/google/registry/model/domain/DomainBaseTest.java
When setting contact fields from a set of DesignatedContact's, nullify the
existing fields so they don't stick around if they're not in the new set.
This fixes the remaining known SQL -> DS replication issue.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/1533)
> Nullify contact fields in setContactFields

- core/src/main/java/google/registry/beam/comparedb/ValidateDatabasePipeline.java
- core/src/main/java/google/registry/beam/comparedb/ValidateDatabasePipelineOptions.java
- core/src/main/java/google/registry/beam/comparedb/ValidateSqlUtils.java
- core/src/main/java/google/registry/tools/ValidateDatabaseMigrationCommand.java
- core/src/main/resources/google/registry/beam/validate_database_pipeline_metadata.json
Adds support for saving discrepancies in database comparison to a GCS bucket.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/1527)
> Save db discrepancies to GCS

- core/src/main/java/google/registry/model/replay/ReplicateToDatastoreAction.java
- core/src/main/java/google/registry/persistence/transaction/TransactionEntity.java
- core/src/test/java/google/registry/model/replay/ReplicateToDatastoreActionTest.java
As it turns out, gaps in the transaction id sequence number are expected
because rollbacks do not rollback sequence numbers.
To deal with this, stop checking these.
This change is not adequate in and of itself, as it is possible for a gap to
be introduced if two transactions are committed out of order of their sequence
number.  We are currently discussing several strategies to mitigate this.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/1539)
> Allow replicateToDatastore to skip gaps

- db/src/main/resources/sql/er_diagram/brief_er_diagram.html
- db/src/main/resources/sql/er_diagram/full_er_diagram.html
- db/src/main/resources/sql/flyway/V108__add_host_indexes_for_whois.sql
- db/src/main/resources/sql/schema/nomulus.golden.sql
The index on the 'inet_addresses array column should be of gin or gist
type, which index individual array elements. We use gin for now since
host updates are not often, and gin has better accuracy.
Since flyway script V108__... has not been deployed, we  edit the file
in place instead of adding a new script.
This will be followed up with a modified query that can take advantage
of the gin index. Until then we don't expect to see performance
improvement.
The suspected bottlenect query in the whois path is:
select * from "Host" where 'non-ip-string' = any(inet_address) and
deletion_time < now();
It needs to be revised into:
select * from "Host" where array['non-ip-string'] <@ inet_address and
deletion_time < now();
The combined change reduces the query time from 90ms to 30ms in Sandbox,
and …
> Revise Host index on inet_addresses

- core/src/main/java/google/registry/model/host/HostResource.java
- core/src/main/java/google/registry/whois/NameserverLookupByIpCommand.java
DO NOT SUBMIT: wait until pr 1549 (add gin index to inet_addresses)
is deployed to sandbox.
Submitting this pr before the index addition will slow down the query
that searches host by IP address.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/1550)
> Revise host.inet_addresses query to use gin index

- core/src/main/java/google/registry/config/files/default-config.yaml
- core/src/test/java/google/registry/batch/SendExpiringCertificateNotificationEmailActionTest.java
Currently, the email content of expiring certificate notification is in public default config and it needs to be moved to private repo's per-environment config file. This purpose of this PR is to replace the actual email text with placeholder text. 
There will be a PR in private repo that add the email template to the right environment config file.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/1530)
> Replace email content with placeholders

- core/src/main/java/google/registry/tools/GenerateEscrowDepositCommand.java
- core/src/main/java/google/registry/ui/server/registrar/RegistrarSettingsAction.java
- core/src/test/java/google/registry/batch/RelockDomainActionTest.java
- core/src/test/java/google/registry/batch/ResaveEntityActionTest.java
- core/src/test/java/google/registry/tools/DomainLockUtilsTest.java
- core/src/test/java/google/registry/tools/GenerateEscrowDepositCommandTest.java
- core/src/test/java/google/registry/ui/server/registrar/RegistrarSettingsActionTestCase.java
The ```AppEngineServiceUtils ``` instance is no longer required in some of the existing code after the conversion of task queue API to ```Cloud Task``` API.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/1534)
> Remove AppEngineServiceUtils dependency

- core/src/main/java/google/registry/model/tld/Registries.java
The loader for the TLD cache in Registries.java unnecessarily reads from
another cache when running with SQL, potentially triggering additional
database access. This code runs in the whois query path, and contributes
to the periodical high latency we are seeing in sandbox.
In crash with production data, this change reduces about 1 second in latency on cache miss.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/1558)
> Improve cache loading in Registries.java

- core/src/main/java/google/registry/model/EntityClasses.java
- core/src/main/java/google/registry/model/replay/ReplayGap.java
- core/src/main/java/google/registry/model/replay/ReplicateToDatastoreAction.java
- core/src/test/java/google/registry/model/common/ClassPathManagerTest.java
- core/src/test/java/google/registry/model/replay/ReplicateToDatastoreActionTest.java
- core/src/test/resources/google/registry/model/schema.txt
Id gaps in the Transaction table can be the result of a transactions committed
out of order.  To deal with this, keep track of gaps for up to five minutes
and check to see if they've been back-filled prior to applying the next batch
of transactions during reply.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/1557)
> Track and replay Transaction table gaps

- core/src/main/java/google/registry/beam/rde/RdeIO.java
- core/src/main/java/google/registry/rde/BrdaCopyAction.java
- core/src/main/java/google/registry/rde/RdeStagingReducer.java
- core/src/main/java/google/registry/rde/RdeUploadAction.java
- core/src/test/java/google/registry/rde/BrdaCopyActionTest.java
- core/src/test/java/google/registry/rde/RdeUploadActionTest.java
After the Cloud Tasks migration and #1508, the BRDA copy job now
routinely fail on the first try because the revision update is not
commited by the time the Cloud Tasks job enqueued in the same
transaction runs for  the first time. This is because the enqueueing is
a side effect and not part of the transaction. The job eventually
succeeds because of retries.
This PR attempts to mitigate the initial failure by saving the revisions
in a separate transaction before the enqueueing happens, insuring that
it is updated by the time the job runs.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/1556)
> Fix a subtle issue in BRDA copy caused by Cloud Tasks

- core/src/main/java/google/registry/export/BackupDatastoreAction.java
- core/src/main/java/google/registry/export/BigqueryPollJobAction.java
- core/src/main/java/google/registry/export/CheckBackupAction.java
- core/src/main/java/google/registry/export/UpdateSnapshotViewAction.java
- core/src/main/java/google/registry/export/UploadDatastoreBackupAction.java
- core/src/main/java/google/registry/request/RequestModule.java
- core/src/test/java/google/registry/export/BackupDatastoreActionTest.java
- core/src/test/java/google/registry/export/BigqueryPollJobActionTest.java
- core/src/test/java/google/registry/export/CheckBackupActionTest.java
- core/src/test/java/google/registry/export/UpdateSnapshotViewActionTest.java
- core/src/test/java/google/registry/export/UploadDatastoreBackupActionTest.java
The main goal of this PR was to move the static methods for enqueueing tasks to where the method was called. Since a `CloudTasksUtil` instance needs to be injected at where the task is enqueued, those static methods were replaced with `cloudTasksUtil.enqueue(queueName, task)`. 
These static methods were created in those backup action files. In order to completely remove the dependency of `TaskOptions` and related libraries from those action files, `BigqueryPollJobAction` and related files need to be modified as well. There is a static class BigqueryPollJobEnqueuer` in `BigqueryPollJobAction` that contains two methods of enqueueing tasks. Those two methods were called in multiple files. The easiest way to modify this class was to have the methods return `Task` and they can be enqueued …
> Remove static methods in back up actions

- core/src/test/java/google/registry/export/UploadDatastoreBackupActionTest.java
- core/src/test/java/google/registry/rde/RdeUploadActionTest.java
1. testRun_withPrefix() in RdeUploadActionTest does calls a mock lock
handler and does not actually try to read from the fake GCS
implementation. Therefore there's no point settig it up.
2. Remove an unused field in UploadDatastoreBackupActionTest.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/1563)
> Some code health fixes

- core/src/main/java/google/registry/request/Modules.java
- core/src/main/java/google/registry/request/UrlConnectionService.java
- core/src/main/java/google/registry/tmch/Marksdb.java
- core/src/main/java/google/registry/tmch/NordnUploadAction.java
- core/src/main/java/google/registry/tmch/NordnVerifyAction.java
- core/src/main/java/google/registry/tmch/TmchDnlAction.java
- core/src/main/java/google/registry/tmch/TmchSmdrlAction.java
The default Java 1.8 TLS version is 1.2 which isn't supported by the
ICANN upload site.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/1564)
> Use TLS v1.3 explicitly in RDE reporting

- core/src/main/java/google/registry/tools/ListTxnsCommand.java
- core/src/main/java/google/registry/tools/RegistryCli.java
- core/src/main/java/google/registry/tools/RegistryTool.java
- core/src/main/java/google/registry/tools/RegistryToolComponent.java
Add the list_txns command which can dump the entire contents of the
Transaction table, either in csv format or as human readable transactions.
The CSV format is useful for storing the transaction table at a specific point
in time for later reference without requiring us to repeatedly hit the
replica.
Creating this without tests because this command has a very short shelf-life
and is really only intended to be run by developers.  Tested all features
locally.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/1569)
> Add a "list_txns" to dump Transaction table

- java-format/google-java-format-git-diff.sh
The format check script currently outputs "true" if there were files that need
reformatting and "false" if not, which is useful for gradle but less so for
other applications (notably commit hooks).  Terminate with an exit code of 1
if the format check fails.
TESTED: Tried this from both a pre-commit hook and from the gradle build.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/1570)
> Terminate with exit code of 1 on format check fail

- core/src/main/java/google/registry/beam/common/RegistryJpaIO.java
- core/src/test/java/google/registry/beam/common/DatabaseSnapshotTest.java
The Postgresql set-snapshot statement (called in
JpaTransactionManager.setDatabaseSnapshot() method) must be the first
statement in the SQL transaction.
Currenty the JpaTransaction.transact() method may insert a query for
DatabaseMigrationStateSchedule before the user query when the cache is
empty or the cached value expires.
This PR proactively preloads the cache in RegistryJpaIO to prevent cache
loading  inside the transaction.
This PR also changes some DatabaseSnapshotTest tests to be retrying, in
case they run just after the cache expires. (This has happened before in
CI).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/1571)
> Fix sporadic SQL Snapshot failure

- core/src/main/java/google/registry/config/RegistryConfig.java
- core/src/main/java/google/registry/config/RegistryConfigSettings.java
- core/src/main/java/google/registry/config/files/default-config.yaml
- core/src/main/java/google/registry/rde/RdeStagingAction.java
- core/src/main/resources/google/registry/beam/rde_pipeline_metadata.json
This likely will speed up the pipeline by skipping the initially slow
process of spinning up instances.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/1572)
> Set the initial worker count for the RDE beam pipeline at 24

- core/src/main/java/google/registry/model/tmch/ClaimsList.java
- core/src/main/java/google/registry/model/tmch/TmchCrl.java
- core/src/main/java/google/registry/tmch/TmchCertificateAuthority.java
- core/src/main/java/google/registry/tmch/TmchCrlAction.java
Fix references to Datastore in the comments of classes that are now SQL-only.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/1576)
> Fix a few references to "Datastore" in comments

- core/src/main/java/google/registry/module/backend/BackendComponent.java
- core/src/main/java/google/registry/rde/RdeReporter.java
- core/src/main/java/google/registry/request/Modules.java
- core/src/main/java/google/registry/tools/RegistryToolComponent.java
- core/src/test/java/google/registry/rde/RdeReportActionTest.java
This removes the TLS 1.3-settings in the module providers and,
essentially, reverts the changes in #1535 only to the RdeReporter and
RdeReportActionTest
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/1578)
> Use UrlFetch for RDE and default TLS (1.2) for other URL connections

- core/src/main/java/google/registry/model/ofy/CommitLogMutation.java
- core/src/main/java/google/registry/model/ofy/CommitLoggedWork.java
- core/src/main/java/google/registry/persistence/transaction/TransactionManagerFactory.java
- core/src/test/java/google/registry/model/replay/ReplicateToDatastoreActionTest.java
Ignore read-only when saving commit logs and commit log mutations so that we
can safely replicate in read-only mode.  This should be safe, as we only ever
to the situation of saving commit logs and mutations when something has
already actually been modified in a transaction, meaning that we should have hit
the "read only" sentinel already.
This also introduces the ability to set the Clock in the
TransactionManagerFactory so that we can test this functionality.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/1584)
> Ignore read-only when saving commit logs

- build.gradle
- docs/build.gradle
- java_common.gradle
Use the new options.release Gradle property to make sure builds are
compatible with Java 8, which is the runtime on Appengine.
This new property replaces sourceCompatibility, targetCompatibility, and
bootclasspath (wasn't previously set, which is the reason why we
couldn't detect Java9 api usage when building).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/1586)
> Build Java8-compatible release

- core/src/main/java/google/registry/model/billing/BillingEvent.java
- core/src/main/java/google/registry/persistence/converter/JodaMoneyType.java
- core/src/test/java/google/registry/model/billing/BillingEventTest.java
- core/src/test/java/google/registry/persistence/converter/JodaMoneyConverterTest.java
- core/src/test/resources/google/registry/model/schema.txt
- db/src/main/resources/sql/schema/db-schema.sql.generated
After the schema change to `BillingRecurrence` (see [PR#1568](https://github.com/google/nomulus/pull/1568/files)), the corresponding code change could go in. The code changes happens in `BillingEvent`, where `BillingRecurrence` resides.  
The three renewal price behaviors  are in an `enum`, which are `DEFAULT`, `NONPREMIUM` and `SPECIFIED`. The price columns for internal registrations are `renewal_price_currency` and `renewal_price_amount`, and together they form `renewalPrice`.
There is an issue with the `Money` column. All the existing use cases have the amount and currency code as required columns. However, renewal price columns can have null values (either both contain values or both as null), and current method for `Money` construction does not support that.  `Money` construction …
> Add new columns to BillingEvent 

- core/src/test/java/google/registry/backup/DeleteOldCommitLogsActionTest.java
- core/src/test/java/google/registry/batch/SendExpiringCertificateNotificationEmailActionTest.java
- core/src/test/java/google/registry/beam/spec11/Spec11PipelineTest.java
- core/src/test/java/google/registry/model/replay/ReplicateToDatastoreActionTest.java
- core/src/test/java/google/registry/rde/BouncyCastleTest.java
- core/src/test/java/google/registry/request/JsonResponseTest.java
- core/src/test/java/google/registry/testing/CloudTasksHelper.java
- core/src/test/java/google/registry/tools/DomainLockUtilsTest.java
- core/src/test/java/google/registry/tools/GenerateAllocationTokensCommandTest.java
- core/src/test/java/google/registry/tools/javascrap/CreateSyntheticHistoryEntriesPipelineTest.java
There are different ways to verify the size of a list and `hasSize()` is the preferred way because it produces a more meaningful failure message. [Search for Java Readability Snippets in MOMA for more details] 
The purpose of the PR is to replace size comparison assertions in existing size comparison cases with `hasSize()`.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/1588)
> Change to hasSize() for assertions

- core/src/main/java/google/registry/beam/rde/RdePipeline.java
For some inexplicable reason, the RDE beam pipeline in both sandbox and
production has been broken for the past week or so. Our investigations
revealed that during the CoGropuByKey stage, some repo ID -> revision ID
pairs were duplicated. This may be a problem with the Dataflow runtime
which somehow introduced the duplicate during reshuffling.
This PR attempts to fix the symptom only by deduping the revision IDs. We
will do some more investigation and possibly follow up with the Dataflow
team if we determine it is an upstream issue.
TESTED=deployed the pipeline and successfully run sandbox RDE with it.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/1593)
> Fix a in issue with RDE

- core/src/main/java/google/registry/model/domain/token/AllocationToken.java
- core/src/test/java/google/registry/model/domain/token/AllocationTokenTest.java
- core/src/test/resources/google/registry/model/schema.txt
- db/src/main/resources/sql/schema/db-schema.sql.generated
This is the corresponding code change to [PR#1580: Add renewal price behavior to AllocationToken](https://github.com/google/nomulus/pull/1580). 
The enum used here is called `RenewalPriceBehavior`, which will be introduced by [PR#1573](https://github.com/google/nomulus/pull/1573). The use cases for `AllocationToken` are `DEFAULT` and `SPECIFIED`. Once PR#1573 goes in, the enum will be coming from `BillingEvent.java`.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/1581)
> Make code change for AllocationToken schema change

- core/build.gradle
- core/src/main/java/google/registry/batch/BatchModule.java
- core/src/main/java/google/registry/batch/ResaveAllEppResourcesPipelineAction.java
- core/src/main/java/google/registry/beam/initsql/InitSqlPipeline.java
- core/src/main/java/google/registry/beam/resave/ResaveAllEppResourcesPipeline.java
- core/src/main/java/google/registry/beam/resave/ResaveAllEppResourcesPipelineOptions.java
- core/src/main/java/google/registry/env/common/backend/WEB-INF/web.xml
- core/src/main/java/google/registry/module/backend/BackendRequestComponent.java
- core/src/main/resources/google/registry/beam/resave_all_epp_resources_pipeline.json
- core/src/test/java/google/registry/batch/ResaveAllEppResourcesActionTest.java
- core/src/test/java/google/registry/batch/ResaveAllEppResourcesPipelineActionTest.java
- core/src/test/java/google/registry/beam/resave/ResaveAllEppResourcesPipelineTest.java
- core/src/test/resources/google/registry/module/backend/backend_routing.txt
- release/cloudbuild-nomulus.yaml
This has two modes.
If `isFast` is false, then we will just load all EPP resources, project them to the current time, and save them.
If `isFast` is true, we will attempt to intelligently load and save only resources that we expect to have changes applied when we project them to the current time. This means resources with pending transfers that have expired, domains with expired grace periods, and non-deleted domains that have expired (we expect that they autorenewed).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/1553)
> Create a Dataflow pipeline to resave EPP resources

- core/src/test/java/google/registry/model/tld/RegistryLockDaoTest.java
- core/src/test/java/google/registry/model/tld/RegistryTest.java
- core/src/test/java/google/registry/model/tld/label/PremiumListDaoTest.java
- core/src/test/java/google/registry/model/tld/label/PremiumListTest.java
- core/src/test/java/google/registry/model/tmch/TmchCrlTest.java
- core/src/test/java/google/registry/ui/forms/FormFieldTest.java
When verifying the value in `Optional<?>` variables, the most intuitive way seems to be using `get()` to get the value then comparing the value by calling `isEqualTo()`. However, this way is not preferred way since manually calling `get()`returns a worse error message and might potentially throw `NullPointerException`. We can use `hasValue()` from `Truth8.assertThat` for value comparison.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/1589)
> Replace .get()).isEqualTo() with hasValue()

- core/src/test/java/google/registry/model/domain/token/AllocationTokenTest.java
`modifiedToken` was originally create for token comparison but it wasn't necessary since the assertion only requires the `RenewalPriceBehavior` enum.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/1594)
> Fix build warning for unused variable

- core/src/main/java/google/registry/env/production/default/WEB-INF/cron.xml
Now that SQL is the default, we do not need this side job to run
alongside the main one. Its purpose was to validate the BEAM pipeline
while Datastore was primary.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/1599)
> Remove the BEAM RDE pipeline side job

- core/src/main/java/google/registry/model/OteAccountBuilder.java
- core/src/main/java/google/registry/model/registrar/Registrar.java
- core/src/main/java/google/registry/model/tld/Registries.java
- core/src/main/java/google/registry/model/tld/Registry.java
- core/src/main/java/google/registry/tools/CreateOrUpdateRegistrarCommand.java
- core/src/main/java/google/registry/tools/RegistryTool.java
- core/src/main/java/google/registry/tools/RegistryToolComponent.java
- core/src/main/java/google/registry/tools/javascrap/BackfillRegistrarBillingAccountsCommand.java
- core/src/test/java/google/registry/export/sheet/SyncRegistrarsSheetTest.java
- core/src/test/java/google/registry/model/registrar/RegistrarTest.java
- core/src/test/java/google/registry/model/tld/RegistryTest.java
- core/src/test/java/google/registry/testing/AppEngineExtension.java
- core/src/test/java/google/registry/testing/DatabaseHelper.java
- core/src/test/java/google/registry/tools/CreateRegistrarCommandTest.java
- core/src/test/java/google/registry/tools/UpdateRegistrarCommandTest.java
This will require edits to a substantial number of registrars on sandbox (nearly
all of them) because almost all of them have access to at least one TLD, but
almost none of them have any billing accounts set. Until this is set, any updates
to the existing registrars that aren't adding the billing accounts will cause
failures.
Unfortunately, there wasn't any less invasive foolproof way to implement this
change, and we already had one attempt to implement it on create registrar
command that wasn't working (because allowed TLDs tend not to be added on
initial registrar creation, but rather, afterwards as an update).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/1601)
> Validate that a registrar has billing accounts for all its allowed TLDs

- release/rollback/common.py
`rollback_tool` tries to infer the root of the nomulus tree by checking for a
directory named "nomulus".  This is potentially problematic (and, indeed, was
for me) since there is no guarantee what that directory will be named.
There are a number of features that characterize the root directory.  Check
for the presence of the `rollback_tool` wrapper script, as this is both at
root level and tightly coupled to the python code, so hopefully we won't
move it without testing that the script still works.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/1602)
> Change check for root directory during rollback

- core/src/main/java/google/registry/persistence/transaction/Transaction.java
- core/src/main/java/google/registry/tools/RegistryTool.java
- core/src/main/java/google/registry/tools/ReplayTxnsCommand.java
When deserializing transactions for replay to datastore, ignore class version
UIDs that don't match those of the local classes and just use the local class
descriptors instead.  This is a simple solution for the problem of persisted
VKeys containing references to classes where the class has been updated and
the serial version UID has changed.
Also add a "replay_txns" command that replays the transactions from a given
start point so we can verify all transactions are deserializable.
TESTED:
Ran replay_txns against all transactions on sandbox beginning with
transaction id 1828385, which includes Recurring billing events containing
both the old and the new serial version UIDs.
--- …
> Ignore version UIDs during txn deserialization

- core/src/test/java/google/registry/model/OteAccountBuilderTest.java
- core/src/test/java/google/registry/model/common/DatabaseMigrationStateScheduleTest.java
- core/src/test/java/google/registry/rdap/AbstractJsonableObjectTest.java
- core/src/test/java/google/registry/rdap/UpdateRegistrarRdapBaseUrlsActionTest.java
- core/src/test/java/google/registry/request/auth/AuthenticatedRegistrarAccessorTest.java
- core/src/test/java/google/registry/tools/CreateOrUpdateReservedListCommandTestCase.java
- core/src/test/java/google/registry/tools/DomainLockUtilsTest.java
- core/src/test/java/google/registry/tools/SetDatabaseMigrationStateCommandTest.java
- core/src/test/java/google/registry/ui/server/registrar/RegistryLockGetActionTest.java
We usually inline our code to avoid a variable being declared then used only once. However, for test cases, it's actually preferred (at least on our team) to have `assertThrows()` being in a different line from `assertThat()` for readability. There are still places in the codebase with `assertThat(assertThrows())` in test cases and the purpose of this PR is to make the assertions for failure cases more consistent. 
For failure cases, we would like to use `assertThrows()` to first statement the failure, then use `assertThat()` to verify the error message.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/1606)
> Change to thrown = assertThrows() then assertThat(thrown)

- release/cloudbuild-nomulus.yaml
We have recently started to routinely breach the 1h timeout. Increasing
this value to 2h. We should also look into reusing the artifacts when
building RCs for different environments.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/1613)
> Increase Nomulus build timeout

- core/src/main/java/google/registry/whois/NameserverWhoisResponse.java
- core/src/test/java/google/registry/whois/NameserverWhoisResponseTest.java
- core/src/test/resources/google/registry/whois/whois_subord_nameserver.txt
Nameserver whois lookups are failing under SQL for hosts with superordinate
domains because the query in this case is not done in a transaction.  We
missed this during testing because a) we didn't have a test for lookups of
hosts with superordinate domains and b) we missed converting
NameserverWhoisResponseTest to a DualDatabaseTest.
This PR fixes the problem and adds the requisite testing.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/1614)
> Add missing transaction for whois lookups

- core/src/main/java/google/registry/flows/domain/DomainFlowUtils.java
- core/src/test/java/google/registry/flows/domain/DomainFlowUtilsTest.java
This was affecting monitoring (i.e. prober TLDs). Note that test TLDs are
already excluded from the billing account map check in the Registrar builder()
method (see PR #1601), but we forgot to make that same test TLD exclusion in the
EPP flows check (see PR #1605).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/1622)
> Don't enforce billing account map check on TEST TLDs

- core/src/main/java/google/registry/env/production/default/WEB-INF/appengine-web.xml
- core/src/main/java/google/registry/env/production/pubapi/WEB-INF/appengine-web.xml
- core/src/main/java/google/registry/env/sandbox/default/WEB-INF/appengine-web.xml
This is in the spirit of "not always running significantly over-provisioned",
which helps to save costs and also expose potential scaling issues when they are
still small rather than all at once when they're a big problem.
This can always be reverted if necessary, and can be instantaneously adjusted by
running the `nomulus set_num_instances` command.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/1620)
> Reduce the number of manually scaled instances for default/pubapi

- core/src/main/java/google/registry/model/domain/token/AllocationToken.java
- core/src/main/java/google/registry/tools/GenerateAllocationTokensCommand.java
- core/src/main/java/google/registry/tools/UpdateAllocationTokensCommand.java
- core/src/test/java/google/registry/model/domain/token/AllocationTokenTest.java
- core/src/test/java/google/registry/tools/GenerateAllocationTokensCommandTest.java
- core/src/test/java/google/registry/tools/UpdateAllocationTokensCommandTest.java
The purpose of this PR is to set up the renewal behavior in allocation token related commands, which will be used in domain create flow. 
The changes to `GenerateAllocationTokensCommand` and `UpdateAllocationTokensCommand` are in this PR since they are very similar. 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/1596)
> Add renewal logic in allocation token related commands 

- core/src/main/java/google/registry/tools/ForwardingServerReceiver.java
- core/src/main/java/google/registry/tools/LoginCommand.java
The Out-of-Band flow will be deprecated in October 2022. Unfortunately
there is no alternative provided that can perform login on a remote host
(which is probably WAI as the OOB flow is susceptible to remote phishing
attacks).
In this PR we switch to using the same loopback IP address redirect URI that a
normal local login session uses, and added instructions on how to set up
SSH port forwarding to complete the flow on a local host when the nomulus
tool runs remotely.
See https://developers.googleblog.com/2022/02/making-oauth-flows-safer.html for
more details on the deprecation.
TESTED=run the new login flow from a remote host and verified it worked.
--- …
> Remove to-be-deprecated OOB OAuth flow in nomulus login

- core/src/main/java/google/registry/batch/RefreshDnsOnHostRenameAction.java
- core/src/main/java/google/registry/env/alpha/default/WEB-INF/cron.xml
- core/src/main/java/google/registry/env/crash/default/WEB-INF/cron.xml
- core/src/main/java/google/registry/env/production/default/WEB-INF/cron.xml
- core/src/main/java/google/registry/env/qa/default/WEB-INF/cron.xml
- core/src/main/java/google/registry/env/sandbox/default/WEB-INF/cron.xml
We'll delete the associated code soon enough too, but it's safer to delete the
cron jobs first and run in that state for a week, so we can still run them
manually if need be.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/1615)
> Remove cron entries for Datastore-specific jobs

- core/src/main/java/google/registry/flows/domain/DomainCreateFlow.java
- core/src/test/java/google/registry/flows/domain/DomainCreateFlowTest.java
Renewal info will be added to recurring billing event when creating a domain (create flow). The code change mostly happens in `run()` which contains the logic of the flow. Since renewal price behavior needs to be set and that could be determined using existing boolean `isAnchorTenant` and `isValidReservedCreate`, a new helper method `getRenewalPriceBehavior` was created in this PR to determine the state of renewal price behavior, and this state replace the two existing booleans. As I was going through the flow, I noticed that some helper methods could be adjusted for minor improvements. For example, `isSunriseCreate` and `isReserved(domainName, isSunriseCreate) `were passed into `createOneTimeBillingEvent` and it could be `domainName` and `isSunriseCreate` and put the conditional in the …
> Add renewal support for AT and internal registrations in DomainCreateFlow

- core/src/main/java/google/registry/export/sheet/SyncRegistrarsSheet.java
- core/src/main/java/google/registry/model/registrar/Registrar.java
- core/src/main/java/google/registry/tools/CreateOrUpdateRegistrarCommand.java
- core/src/test/java/google/registry/export/sheet/SyncRegistrarsSheetTest.java
- core/src/test/java/google/registry/model/registrar/RegistrarTest.java
- core/src/test/java/google/registry/tools/CreateRegistrarCommandTest.java
- core/src/test/java/google/registry/tools/MutatingCommandTest.java
- core/src/test/java/google/registry/tools/UpdateRegistrarCommandTest.java
- core/src/test/resources/google/registry/model/schema.txt
This field is a remnant from before the Billing3 migration and is no longer used. The field will be removed from the SQL schema in a follow up PR once Nomulus is in SQL only mode.
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/1608)
> Remove all uses of the billingIdentifier field

- core/src/main/java/google/registry/batch/ExpandRecurringBillingEventsAction.java
- core/src/main/java/google/registry/config/RegistryConfig.java
- core/src/main/java/google/registry/config/RegistryConfigSettings.java
- core/src/main/java/google/registry/persistence/PersistenceModule.java
- core/src/test/java/google/registry/batch/ExpandRecurringBillingEventsActionTest.java
It's OOMing on trying to load every single BillingRecurrence that needs to be
expanded simultaneously (which is to be expected). So this processes them in
transactional batches of 50.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/1636)
> Add batching to ExpandRecurringBillingEventsAction

- core/src/main/java/google/registry/model/reporting/HistoryEntryDao.java
- core/src/main/java/google/registry/rdap/RdapJsonFormatter.java
- core/src/test/java/google/registry/rdap/RdapJsonFormatterTest.java
For each EPP entity, directly load the latest HistoryEntry per event type
instead of loading all events through the HistoryEntryDao.
Although most entities have a small number of history entries, there are
a few entities with many entries, enough to cause OutOfMemory error.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/1635)
> Optimize RDAP entity event query

- core/src/test/java/google/registry/flows/domain/DomainPricingLogicTest.java
THe build is giving a style warning over the extra parens.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/1643)
> Fix style warning

- core/src/test/java/google/registry/testing/DualDatabaseTestInvocationContextProvider.java
- core/src/test/java/google/registry/testing/DualDatabaseTestInvocationContextProviderTest.java
- core/src/test/java/google/registry/testing/TestOfyOnly.java
This change just turns off the Ofy tests at the root, by removing processing
for dual tests and disassociating the TestOfyOnly annotation from test
annotations.
This is far less comprehensive than #1631, but it's probably worth entering as
a stopgap solution just because it should speed up our test runs and unblock a
lot of other cleanup work.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/1644)
> Disable Ofy tests.

- core/src/main/java/google/registry/batch/ExpandRecurringBillingEventsAction.java
- core/src/test/java/google/registry/flows/domain/DomainPricingLogicTest.java
We don't need to log every single no-op batch of 50 Recurrences that are
processed (considering we have 1.5M total in our system), and we also don't need
to process Recurrences that already ended prior to the Cursor time (this gets us
down to 420k from 1.5M).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/1642)
> Slightly improve performance of ExpandRecurringBillingEventsAction

- core/src/main/java/google/registry/tools/GetAllocationTokenCommand.java
- core/src/main/java/google/registry/tools/UniformRapidSuspensionCommand.java
- core/src/test/java/google/registry/tools/GetAllocationTokenCommandTest.java
- core/src/test/java/google/registry/tools/UniformRapidSuspensionCommandTest.java
These weren't caught until I switched the default database type in tests
to be SQL (separate PR). Fortunately these don't seem to be catastrophic
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/1662)
> Fix some small transactional issues in SQL mode

- core/src/main/java/google/registry/flows/domain/DomainUpdateFlow.java
- core/src/main/java/google/registry/model/eppinput/ResourceCommand.java
- docs/build.gradle
The main purpose of this PR is to help debug b/234189023, where a
registrar reported that in sandbox they observed seemingly successful EPP
update responses to delete NS records, which are not actually deleted after
the commands executed.
To actually load the persisted domain resource after an update would
require us to execute another transaction immediately after the update
transaction and that can only be achieved outside the flow (i. e. in
FlowRunner or EppController) and we need to test for the type of flows
before logging, which seems unnecessarily complex.
For now we are just adding logs inside the update transaction itself to
validate that:
1. The NS records to delete are as expected.
2. The Current NS records are as expected.
3. The new NS records to persist are as expected.
The …
> Add logging for nameserver deletion

- core/src/main/java/google/registry/flows/domain/DomainUpdateFlow.java
- core/src/main/java/google/registry/persistence/VKey.java
When removing nameservers during an EPP update, we use the
Sets.difference(), which depends on the equals() method of the set
elements (VKey<HoseResource>), to compute the resulting NS set. The
equality check for a VKey checks for equality of all of its significant fields.
We are seeing strange issues where the removal of NS appeared to
have succeeded, but did not actually happen, because the equality check failed
for two VKey<HostResource> objects with identical SQL key, causing the VKeys to
not be removed by the Set.difference() method when they should have been.
The most likely cause is that the Ofy key field in VKey is no longer up-to-date,
now that we stopped replaying to datastore, and are actively tearing down
Ofy-related pieces.
While I did not check how the ofy keys were …
> Fix EPP update NS delete bug

- core/src/main/java/google/registry/model/common/GaeUserIdConverter.java
- core/src/main/java/google/registry/model/ofy/Ofy.java
- core/src/test/java/google/registry/model/common/GaeUserIdConverterTest.java
This is the only user of the ofy code that will stick around at least
until we move to the new registrar console. By removing references to
the transaction manager, we will be able to delete all the tm code
without interfering with this.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/1666)
> Remove TM references from GaeUserIdConverter

- core/src/main/java/google/registry/config/RegistryConfig.java
- core/src/main/java/google/registry/dns/ReadDnsQueueAction.java
- core/src/main/java/google/registry/flows/domain/DomainUpdateFlow.java
- core/src/test/java/google/registry/dns/DnsInjectionTest.java
- core/src/test/java/google/registry/dns/DnsTestComponent.java
- core/src/test/java/google/registry/dns/ReadDnsQueueActionTest.java
- core/src/test/java/google/registry/persistence/VKeyTest.java
- core/src/test/java/google/registry/testing/CloudTasksHelper.java
- util/src/main/java/google/registry/util/TaskQueueUtils.java
Also marked TaskQueueUtils as deprecated and fixed a few linter errors.
The Task Queue related tests in VKeyTest are also removed, because with CloudTasksHelper the tasks are not sent to a locally simulated Cloud Task environment like the local Task Queue set up by AppEngineExtension. Therefore there's no point in verifying that the parameters of enqueued tasks are not meddled by service, which is mocked entirely by ourselves.
Note that DNS pull queue still requires the use of the GAE Task Queue API.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/1669)
> Migrate ReadDnsQueueAction to use CloudTasksUtils

- core/src/test/java/google/registry/beam/common/RegistryJpaReadTest.java
- core/src/test/java/google/registry/model/tmch/ClaimsListDaoTest.java
- core/src/test/java/google/registry/persistence/transaction/JpaTestExtensions.java
- core/src/test/java/google/registry/persistence/transaction/JpaTransactionManagerExtension.java
Added methods that exist in AppEngineExtension that preload some canned
data. This data is loaded by default and a lot of tests rely on them. As
we migrate away from App Engine, it is helpful to have them in the JPA
test extension which will replace the app engine extension that is
used to set up the database in dual database tests.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/1673)
> Add some helper methods to JPA test extension

- core/src/test/java/google/registry/rde/BrdaCopyActionTest.java
- core/src/test/java/google/registry/rde/GhostrydeGpgIntegrationTest.java
- core/src/test/java/google/registry/rde/RdeUploadActionTest.java
- core/src/test/java/google/registry/rde/RydeGpgIntegrationTest.java
- core/src/test/java/google/registry/testing/GpgSystemCommandExtension.java
- release/builder/build.sh
GPG1 is deprecated and stuck in v1.4 from 2018. GPG2 is recommended. We
only use the GPG binary in tests and when the host system has both
versions it causes problems because we hardcode the GPG import command
in GpgSystemCommandExension to use the binary named "gpg", which could
be linked to either GPG1 or GPG2, causing the other test to fail when
the version of GPG that runs in tests is incompatible with the version of GPG
that imports the keys.
With this PR we only support GPG2 from now on.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/1676)
> Only use GPG2 in tests

- core/src/test/java/google/registry/model/ofy/DatastoreTransactionManagerTest.java
- core/src/test/java/google/registry/model/ofy/OfyTest.java
These tests use Ofy exclusively and should not run anymore, as any class
they test also use Ofy and should be deleted.
More importantly, running tests in Ofy mode makes it hard to remove Ofy
from entities, especially Registrar and RegistrarContact, as some of
them are created as canned data when tests are initiated, and the
creation would fail if they are not registered as Ofy entities.
It is therefore a prerequisite to disable these tests before we can
remove Ofy from those entities. We could have deleted them, but I think
that should be done when the corresponding classes tested by them are
deleted.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/1679)
> Disable all tests that uses Ofy

- core/src/main/java/google/registry/rde/RdeModule.java
- core/src/main/java/google/registry/tools/GenerateEscrowDepositCommand.java
- core/src/test/java/google/registry/tools/GenerateEscrowDepositCommandTest.java
The parameter was used to force a RDE beam run, which is no longer
necessary, now that the mapreduce pipeline is deleted.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/1684)
> Remove the beam parameter in RDE staging action

- config/dependency-license/allowed_licenses.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/1685)
> Fix license-checking on GWT 2.10.0, which is Apache 2.0

- core/src/test/java/google/registry/beam/common/DatabaseSnapshotTest.java
Retries no longer necessary after interfering DB access is removed.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/1690)
> Remove retries for DatabaseSnapshot tests

- core/src/main/java/google/registry/flows/ResourceFlowUtils.java
- core/src/main/java/google/registry/model/billing/BillingEvent.java
- core/src/main/java/google/registry/model/transfer/DomainTransferData.java
Now that ofy keys aren't necessarily being restored, it seemed prudent to
audit existing uses to verify that we aren't relying on any keys that may now
be null.
This fixes one case that appeared to be potentially problematic (in
ResourceFlowUtils), removes a few methods that call getOfyKey() but are no
longer used, and adds comments to one use of the key that appears to be safe
after visual inspection.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/1696)
> Deal with some getOfyKey() references

- core/src/main/java/google/registry/tmch/ClaimsListParser.java
- core/src/main/java/google/registry/tmch/Marksdb.java
- core/src/main/java/google/registry/tmch/SmdrlCsvParser.java
- core/src/main/java/google/registry/tmch/TmchDnlAction.java
- core/src/main/java/google/registry/tmch/TmchSmdrlAction.java
- core/src/test/java/google/registry/tmch/SmdrlCsvParserTest.java
This uses the Apache commons CSV parsing instead of rolling our own.
Annoyingly, the results that we're given aren't exactly proper CSVs
since they have a non-standard line of data at the top, and the header
is actually the second line.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/1704)
> Refactor SMDRL + Claims CSV parsing

- core/src/main/java/google/registry/rdap/UpdateRegistrarRdapBaseUrlsAction.java
- core/src/test/java/google/registry/rdap/UpdateRegistrarRdapBaseUrlsActionTest.java
tested on alpha (which I should have done before), our request header tells IANA to gzip the data but they're using Brotli instead. Instead of trying to worry about decoding whatever they happen to send, just don't encode it.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/1705)
> Tell IANA not to encode the RDAP base URL response

- core/src/main/java/google/registry/model/domain/token/AllocationToken.java
- core/src/main/java/google/registry/tools/GenerateAllocationTokensCommand.java
- core/src/main/java/google/registry/tools/UpdateAllocationTokensCommand.java
- core/src/test/java/google/registry/model/domain/token/AllocationTokenTest.java
- core/src/test/java/google/registry/tools/GenerateAllocationTokensCommandTest.java
- core/src/test/java/google/registry/tools/UpdateAllocationTokensCommandTest.java
- core/src/test/resources/google/registry/model/schema.txt
- db/src/main/resources/sql/er_diagram/brief_er_diagram.html
- db/src/main/resources/sql/er_diagram/full_er_diagram.html
- db/src/main/resources/sql/schema/db-schema.sql.generated
This is, as of now, unused but we can use it for b/237683906 and
b/237800445 in the future to allow for special behavior dictated by
allocation tokens rather than having to reserve specific domains.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/1695)
> Add a registration_behavior column to AllocationToken

- core/src/main/java/google/registry/reporting/icann/sql/cloud_sql_total_domains.sql
- core/src/test/java/google/registry/reporting/icann/TransactionsReportingQueryBuilderTest.java
- core/src/test/resources/google/registry/reporting/icann/total_domains_test_cloud_sql.sql
This shouldn't matter for billing or anything like that because the
actual actions performed that month are still correct, but before this
PR we're including all domains ever created in the total_domains number,
including deleted domains
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/1713)
> Don't include deleted domains in the ICANN reporting total_domains field

- build.gradle
- release/cloudbuild-kythe.yaml
The fix is based on b/240627423. I tested locally and was able to build
with the -PenableCrossReferencing=true flag successfully.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/1727)
> Make Kythe run work with Gradle 7

- appengine_war.gradle
For some reason after the upgrade to Gradle, the core.jar file is no
longer included in the generated WAR, even though the deploy_jar
configuration is specified as a dependency.
I could not figure out a way to tweak the configuration dependency to
have core.jar pulled into the .war, so I decided to just explicitly pick
it from its known location.
TESTED=deployed to alpha and verified that the instances can start.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/1730)
> Fix GAE build under Gradle 7

- core/src/main/java/google/registry/config/RegistryConfig.java
- core/src/main/java/google/registry/config/RegistryConfigSettings.java
- core/src/main/java/google/registry/config/files/default-config.yaml
- core/src/main/java/google/registry/model/tld/label/PremiumListDao.java
- core/src/main/java/google/registry/model/tld/label/ReservedList.java
- core/src/main/java/google/registry/model/tmch/ClaimsList.java
- core/src/main/java/google/registry/model/tmch/ClaimsListDao.java
- core/src/main/java/google/registry/tools/GetClaimsListCommand.java
- core/src/test/java/google/registry/flows/domain/DomainClaimsCheckFlowTest.java
- core/src/test/java/google/registry/model/tmch/ClaimsListDaoTest.java
- core/src/test/java/google/registry/testing/TestCacheExtension.java
- core/src/test/java/google/registry/tools/EppLifecycleToolsTest.java
We cache the ClaimsList Java object for six hours (we don't expect it to
change frequently, and the cron job to update it only runs every twelve
hours). Subsequent calls to ClaimsListDao::get will return the cached
value.
Within the ClaimsList Java object itself, we cache any labels that we
have retrieved. While we already have a form of a cache here in the
"labelsToKeys" map, that only handles situations where we've loaded the
entire map from the database. We want to have a non-guaranteed cache in
order to make repeated calls to getClaimKey fast.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/1731)
> Add caches to ClaimsListDao and ClaimsList

- core/src/main/java/google/registry/model/console/ConsolePermission.java
- core/src/main/java/google/registry/model/console/ConsoleRoleDefinitions.java
- core/src/main/java/google/registry/model/console/RegistrarRole.java
- core/src/main/java/google/registry/model/console/User.java
- core/src/test/java/google/registry/model/console/ConsoleRoleDefinitionsTest.java
- core/src/test/java/google/registry/model/console/UserTest.java
This allows us to distinguish between standard account managers and
users that might have the registry lock permission. This will make the
registry lock password-setting flow easier (user can reset their
password iff they have the REGISTRY_LOCK permission, instead of having a
separate boolean) and allows us to easily determine whether or not a
user should have access to registry lock views in the UI.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/1740)
> Create a registry lock permission and corresponding account manager role

- core/src/test/java/google/registry/flows/ResourceFlowTestCase.java
Basically, what's happening here is that some flow tests are adding
things to the claims list cache which is stored statically, meaning that
some other tests can pick those up when they shouldn't. By adding the
extension in RFTC, it'll clear out the caches after each test.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/1749)
> Add TestCacheExtension in ResourceFlowTC to fix flakes

- core/src/test/java/google/registry/tmch/TmchActionTestCase.java
- core/src/test/java/google/registry/tmch/TmchTestDataExpirationTest.java
ICANN hasn't provided updated files since 2018 and the current ones are
expired, so we should disable the test until then. This also adds the
TestCacheExtension to the TMCH test cases just in case.
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/1750)
> Add another TestCacheExtension usage and disable expired SMD test

- core/src/test/java/google/registry/tools/GetClaimsListCommandTest.java
- core/src/test/java/google/registry/tools/UploadClaimsListCommandTest.java
Unfortunately we're getting some flakes caused by the cache sticking around in tests after it shouldn't. This covers the rest of the cases where any test calls ClaimsListDao.save to reset the cache after the test finishes. 
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/1754)
> Reset the claims list cache in any test that saves to it

- core/src/main/java/google/registry/tools/CreateDomainCommand.java
- core/src/main/resources/google/registry/tools/soy/DomainCreate.soy
- core/src/test/java/google/registry/tools/CreateDomainCommandTest.java
- core/src/test/resources/google/registry/tools/server/domain_create_token.xml
Useful when doing internal registrations like get.boo
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/1756)
> Allow usage of allocation tokens in nomulus create_domain

- core/src/main/java/google/registry/rdap/RdapModule.java
- core/src/main/java/google/registry/request/auth/AuthResult.java
- core/src/main/java/google/registry/request/auth/AuthenticatedRegistrarAccessor.java
- core/src/main/java/google/registry/request/auth/UserAuthInfo.java
- core/src/main/java/google/registry/ui/server/registrar/ConsoleUiAction.java
- core/src/main/java/google/registry/ui/server/registrar/HtmlAction.java
- core/src/main/java/google/registry/ui/server/registrar/RegistryLockGetAction.java
- core/src/main/java/google/registry/ui/server/registrar/RegistryLockPostAction.java
- core/src/test/java/google/registry/request/RequestHandlerTest.java
- core/src/test/java/google/registry/request/auth/AuthenticatedRegistrarAccessorTest.java
- core/src/test/java/google/registry/request/auth/RequestAuthenticatorTest.java
- core/src/test/java/google/registry/ui/server/registrar/RegistryLockGetActionTest.java
- core/src/test/java/google/registry/ui/server/registrar/RegistryLockPostActionTest.java
This means that LegacyAuthenticationMechanism or a to-be-created
OAuth2AuthenticationMechanism) can return a UserAuthInfo object that
contains either the GAE User or the console User as appropriate. The
goal is that the non-auth flows shouldn't have to know about which user
type it is. Note: the registry lock flow (for now) needs to know about
the separate types of auth because it is a separate level of auth from
the standard AuthenticatedRegistrarAccessor.
The AuthenticatedRegistrarAccessor code is a bit odd because the new
role system doesn't quite fit neatly into the old registrar ->
OWNER,ADMIN system but this is a fine approximation.
- - - …
> Allow UserAuthInfo to contain either old GAE Users or new console Users

- core/src/main/java/google/registry/config/RegistryConfig.java
- core/src/main/java/google/registry/config/RegistryConfigSettings.java
- core/src/main/java/google/registry/config/files/default-config.yaml
- core/src/main/java/google/registry/dns/PublishDnsUpdatesAction.java
- core/src/test/java/google/registry/dns/PublishDnsUpdatesActionTest.java
This adds registry support email to bcc for when DNS failure occurs and we send DNS failure emails. This should help us to track how many and what kind of emails are getting sent by us and make sure partners don't get flooded with emails.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/1755)
> Add registry email to bcc for outgoing DNS failure emails

- config/checkstyle/checkstyle.xml
- core/src/main/java/google/registry/batch/DeleteProberDataAction.java
- core/src/main/java/google/registry/flows/contact/ContactCreateFlow.java
- core/src/main/java/google/registry/flows/domain/DomainCreateFlow.java
- core/src/main/java/google/registry/flows/domain/DomainDeleteFlow.java
- core/src/main/java/google/registry/flows/domain/DomainRestoreRequestFlow.java
- core/src/main/java/google/registry/flows/host/HostCreateFlow.java
- core/src/main/java/google/registry/flows/host/HostUpdateFlow.java
- core/src/main/java/google/registry/model/EntityClasses.java
- core/src/main/java/google/registry/model/ResourceTransferUtils.java
- core/src/main/java/google/registry/model/index/ForeignKeyIndex.java
- core/src/main/java/google/registry/persistence/transaction/JpaTransactionManagerImpl.java
- core/src/test/java/google/registry/flows/host/HostUpdateFlowTest.java
- core/src/test/java/google/registry/model/common/ClassPathManagerTest.java
- core/src/test/java/google/registry/model/index/ForeignKeyIndexTest.java
- core/src/test/java/google/registry/testing/DatabaseHelper.java
- core/src/test/resources/google/registry/model/schema.txt
- util/src/main/java/google/registry/util/TypeUtils.java
FKI used to be persisted in datastore to help speed up loading by foreign key.
Now it is just a helper class to do the same thing in SQL because
indexing is natively supported in SQL.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/1777)
> Remove ofy support from ForeignKeyIndex

- core/src/main/java/google/registry/module/backend/BackendComponent.java
- core/src/main/java/google/registry/module/frontend/FrontendComponent.java
- core/src/main/java/google/registry/module/pubapi/PubApiComponent.java
- core/src/main/java/google/registry/module/tools/ToolsComponent.java
- core/src/main/java/google/registry/request/Modules.java
- core/src/main/java/google/registry/request/auth/AuthModule.java
- core/src/main/java/google/registry/request/auth/CookieOAuth2AuthenticationMechanism.java
- core/src/main/java/google/registry/tools/RegistryToolComponent.java
- core/src/test/java/google/registry/request/auth/CookieOAuth2AuthenticationMechanismTest.java
This uses the GoogleIdTokenVerifier to verify ID tokens passed in
(presumably from a front end) via cookies. This isn't used anywhere yet
but it will be used for front-end API calls for the new console.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/1761)
> Add a cookie-based OAuth2 authenticator

- core/src/main/java/google/registry/tools/RegistryTool.java
- core/src/main/java/google/registry/tools/RegistryToolComponent.java
- core/src/main/java/google/registry/tools/javascrap/CreateCancellationsForOneTimesCommand.java
- core/src/test/java/google/registry/tools/javascrap/CreateCancellationsForOneTimesCommandTest.java
This allows us to correct situations where we have erroneously charged registrars for an action, without explicitly issuing a refund.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/1790)
> Create a scrap command to cancel OneTime billing events by ID

- core/src/main/java/google/registry/flows/domain/DomainUpdateFlow.java
- core/src/test/java/google/registry/flows/domain/DomainUpdateFlowTest.java
- core/src/test/resources/google/registry/flows/domain/domain_update_no_ds_change.xml
I believe this should safely fix the issue with triggering dns publish tasks for when they are not required. As far as I understand this process only **nameservers** and **ds data** change should trigger dns publish task.
I removed ```assertDnsTasksEnqueued``` from ```doSuccessfulTest``` as evidentaly it's not expected. Added the test for the this particular use case.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/1785)
> Do not enqueue DNS updates when flow doesn't affect nameservers

- core/src/main/java/google/registry/env/production/default/WEB-INF/cron.xml
- core/src/main/java/google/registry/reporting/billing/GenerateInvoicesAction.java
- core/src/test/java/google/registry/reporting/billing/GenerateInvoicesActionTest.java
In case expand billing events job overlaps with generate invoices job, there's a chance that some auto-renewals might not get properly billed. This PR ensures ```/_dr/task/generateInvoices``` fails if last successful ```/_dr/task/expandRecurringBillingEvents``` is older than 1 day.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/1791)
> Fail generate invoices job when billing events not finished expanding

- config/dependency-license/allowed_licenses.json
A missing GPL3 string causes sporadic failures when building on local desktop and not using our GCS maven repo.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/1800)
> Add a new allowed license string

- java_common.gradle
This was added in go/r3pr/1466 but accidentally overwritten in go/r3pr/1472.
Log4j is not in the current releases though. Our dependencies must have removed them too.
Still good to keep.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/1801)
> Restore log4j exclusion in gradle build

- core/src/main/java/google/registry/tools/javascrap/CreateSyntheticDomainHistoriesPipeline.java
- core/src/test/java/google/registry/tools/javascrap/CreateSyntheticDomainHistoriesPipelineTest.java
We're seeing some discrepancies with the history objects created with the previous READ_COMMITTED pipeline so we can make this change to create a new set of history objects in QA now that it's set to REPEATABLE_READ
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/1803)
> Modify the CreateSynthetic pipeline to run over all non-deleted domains

- core/src/main/java/google/registry/tools/GetEppResourceCommand.java
- core/src/main/java/google/registry/tools/UniformRapidSuspensionCommand.java
- core/src/test/java/google/registry/tools/CommandTestCase.java
- core/src/test/java/google/registry/tools/GetContactCommandTest.java
- core/src/test/java/google/registry/tools/GetDomainCommandTest.java
- core/src/test/java/google/registry/tools/GetHostCommandTest.java
- core/src/test/java/google/registry/tools/GetPackagePromotionCommandTest.java
- core/src/test/java/google/registry/tools/UniformRapidSuspensionCommandTest.java
We started getting failures because some of the tests used October. In general we should freeze the clock for testing as much as possible.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/1805)
> Use injected times in URSC and CommandTestCase

- core/src/main/java/google/registry/beam/spec11/ThreatMatch.java
- core/src/test/java/google/registry/reporting/spec11/Spec11RegistrarThreatMatchesParserTest.java
The issue we encountered with Spec11 failing to publish reports on 09/29/2022 is a side effect of https://github.com/google/nomulus/pull/1784 change. 
In nutshell the root cause is that Spec11 parser processes data with 1 day lag, so at the time release went through it went on processing data saved with ```fullyQualifiedDomainName```, the next day it autocorrected itself due to saved files usage of ```domainName``` as a field name. 
However we still want to be able to parse older files stored in a cloud, so this change adds a support for both older field and newer field.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/1806)
> Add fallback for Spec11 ThreatMatch parser

- core/src/main/java/google/registry/tools/RegistryToolComponent.java
go/r3pr/1805 introduced an injectable clock in a few commands, but we
forgot to add the corresponding injector in the component. This PR fixes
it.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/1812)
> Fix nomulus command

- core/src/main/java/google/registry/config/CredentialModule.java
- core/src/main/java/google/registry/export/DriveModule.java
- core/src/main/java/google/registry/export/sheet/SheetsServiceModule.java
- core/src/main/java/google/registry/privileges/secretmanager/SecretManagerModule.java
- core/src/main/java/google/registry/tools/AuthModule.java
This PR consists of the following changes:
- Added a new method to generate scope-less default credential when using it to access other non-workspace GCP APIs. Scopes are not needed here.
- Started to use the new credential in the SecreteManager.
- Will migrate other usages to this new credential gradually.
- Marked the old DefaultCredential as deprecated.
- Started applying scopes to the default credential when using to access Drive and Sheets APIs.
- Upgraded Drive access from the deprecated credential lib to the up-to-date one
- Switched Sheet access from the exported json credential to the scoped default credential.
This PR requires that the affected files be writable to the default service account (project-name@appspot.gserviceaccount.com) of the project.
- This is already the case …
> Properly create and use default credential

- core/src/main/java/google/registry/monitoring/whitebox/StackdriverModule.java
Switch MetricReporter in Appengine to the app default credential.
Verified in Alpha that MetricReporter successfully started and sent metrics to stackdriver.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/1837)
> Switch MetricReporter to App default credential

- core/src/main/java/google/registry/batch/AsyncTaskEnqueuer.java
- core/src/main/java/google/registry/batch/BatchModule.java
- core/src/main/java/google/registry/config/RegistryConfig.java
- core/src/main/java/google/registry/config/RegistryConfigSettings.java
- core/src/main/java/google/registry/config/files/default-config.yaml
- core/src/main/java/google/registry/env/common/default/WEB-INF/queue.xml
- core/src/main/java/google/registry/flows/host/HostUpdateFlow.java
- core/src/test/java/google/registry/batch/AsyncTaskEnqueuerTest.java
- core/src/test/java/google/registry/batch/ResaveEntityActionTest.java
- core/src/test/java/google/registry/flows/EppTestComponent.java
- core/src/test/java/google/registry/flows/contact/ContactDeleteFlowTest.java
- core/src/test/java/google/registry/flows/host/HostDeleteFlowTest.java
- core/src/test/java/google/registry/flows/host/HostUpdateFlowTest.java
- core/src/test/java/google/registry/testing/CloudTasksHelper.java
Note that the async-host-rename-pull queue were still being populated prior to this PR, but the queue hasn't been processed for several months. There is no point in keeping enqueuing to it. We will implement a SQL-based DNS refresh solution and run RefreshDnsForAllDomainAction action once to catch up on all stale changes.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/1841)
> Delete unused queues 

- core/src/main/java/google/registry/flows/domain/DomainInfoFlow.java
- core/src/test/resources/google/registry/flows/domain/domain_info_response_superuser_package.xml
- core/src/test/resources/google/registry/flows/domain/domain_info_response_unauthorized.xml
Per b/257081445 allows more information in domain info response, makes info command response similar to whois response.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/1842)
> Allow status, crDate, upDate, exDate and ns fields for all Domain Info responses

- core/src/main/java/google/registry/config/CredentialModule.java
- core/src/main/java/google/registry/groups/DirectoryModule.java
- core/src/main/java/google/registry/groups/GroupssettingsModule.java
- core/src/main/java/google/registry/keyring/api/KeyModule.java
- core/src/main/java/google/registry/keyring/secretmanager/SecretManagerKeyring.java
Use the new keyless delegated credential with `AdcDelegatedCredential` annotation for accessing Google Workspace APIs. This new cred is verified in production.
Removed everything related to @JsonCredential
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/1847)
> Use keyless delegated credential

- core/src/main/java/google/registry/config/RegistryConfig.java
- core/src/main/java/google/registry/config/RegistryConfigSettings.java
- core/src/main/java/google/registry/config/files/default-config.yaml
- core/src/main/java/google/registry/config/files/nomulus-config-production-sample.yaml
- core/src/main/java/google/registry/tools/CommandWithConnection.java
- core/src/main/java/google/registry/tools/CreateRegistrarCommand.java
- core/src/main/java/google/registry/tools/CreateRegistrarGroupsCommand.java
- core/src/main/java/google/registry/tools/CurlCommand.java
- core/src/main/java/google/registry/tools/EppToolCommand.java
- core/src/main/java/google/registry/tools/GenerateZoneFilesCommand.java
- core/src/main/java/google/registry/tools/ListObjectsCommand.java
- core/src/main/java/google/registry/tools/LoadTestCommand.java
- core/src/main/java/google/registry/tools/RegistryCli.java
- core/src/main/java/google/registry/tools/RegistryToolComponent.java
- core/src/main/java/google/registry/tools/RegistryToolEnvironment.java
- core/src/main/java/google/registry/tools/ServiceConnection.java
- core/src/main/java/google/registry/tools/VerifyOteCommand.java
- core/src/main/java/google/registry/tools/javascrap/CreateSyntheticDomainHistoriesCommand.java
- core/src/test/java/google/registry/tools/CreateRegistrarCommandTest.java
- core/src/test/java/google/registry/tools/CreateRegistrarGroupsCommandTest.java
- core/src/test/java/google/registry/tools/CurlCommandTest.java
- core/src/test/java/google/registry/tools/EppToolVerifier.java
- core/src/test/java/google/registry/tools/GcpProjectConnectionTest.java
- core/src/test/java/google/registry/tools/ListObjectsCommandTestCase.java
- core/src/test/java/google/registry/tools/LoadTestCommandTest.java
- core/src/test/java/google/registry/tools/RequestFactoryModuleTest.java
- core/src/test/java/google/registry/tools/VerifyOteCommandTest.java
It doesn't actually use any App Engine libraries or code -- it's just a generic connection with authentication to a service. This also involves changing that block of config to be "gcpProject" instead of "appEngine" since it's more generic.
Note: this will require an internal PR as well to change the corresponding private config block
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/1857)
> Rename AppEngineConnection to ServiceConnection

- core/src/main/java/google/registry/tools/RegistrarPocCommand.java
Apparently IntelliJ doesn't like the extra parens, but our own
ErrorProne checks want it for clarity.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/1862)
> Re-add parenthesis

- core/src/main/java/google/registry/model/ImmutableObject.java
- core/src/main/java/google/registry/tools/GetEppResourceCommand.java
- core/src/test/java/google/registry/tools/GetEppResourceCommandTest.java
Fixes a bug in read_timestamp validation.
Fixes string representation of Collection fields in Epp Resources.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/1865)
> Fix nomulus GetEppResourceCommand

- build.gradle
With newer versions of Java 11, javadoc fails to build due to unknown
tags in package-info.java files. These files are not important so we
exclude them.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/1866)
> Fix javadoc build

- core/src/main/java/google/registry/flows/domain/DomainFlowUtils.java
- core/src/test/java/google/registry/flows/domain/DomainCheckFlowTest.java
- core/src/test/resources/google/registry/flows/domain/domain_check_allocationtoken_fee_anchor_response.xml
These were always properly reflected in the actual creations, but when running a check flow it would still show a non-zero cost even when using an ANCHOR_TENANT allocation token. This changes it so that we accurately show the $0.00 cost.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/1868)
> Take anchor tenant tokens into account in domain check flows

- core/src/main/java/google/registry/env/common/tools/WEB-INF/web.xml
We no longer use App Engine Remote API as of #1858.
The pipeline endpoint is only for GAE mapreduce, which we stopped doing
for a while.
TESTED=deployed to alpha and used nomulus tool built from master to
connect to the tools service.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/1873)
> Remove unused endpoints on the Tools service

- core/src/main/java/google/registry/model/ImmutableObject.java
- core/src/main/java/google/registry/model/domain/DomainBase.java
- core/src/main/java/google/registry/model/domain/DomainHistory.java
- util/src/main/java/google/registry/util/CollectionUtils.java
This annotation was only used in cross-database comparison.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/1878)
> Remove @EmptySetToNull

- core/src/main/java/google/registry/beam/spec11/Spec11Pipeline.java
- core/src/main/java/google/registry/model/reporting/Spec11ThreatMatch.java
- core/src/test/java/google/registry/beam/spec11/Spec11PipelineTest.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/1810)
> Prevent saving duplicate rows in spec11 pipeline

- core/src/main/java/google/registry/model/EppResourceUtils.java
- core/src/main/java/google/registry/tools/UniformRapidSuspensionCommand.java
- core/src/main/java/google/registry/tools/params/NameserversParameter.java
- core/src/test/java/google/registry/testing/DatabaseHelper.java
- core/src/test/java/google/registry/tools/CreateDomainCommandTest.java
- core/src/test/java/google/registry/tools/UniformRapidSuspensionCommandTest.java
- core/src/test/java/google/registry/tools/UpdateDomainCommandTest.java
This allows use of the ns[1-4].foo.bar notation to specify multiple nameservers matching a common numeric pattern. It allows fixes hostname canonicalization in the existing create/update_domain command (though this is mostly a no-op as it just affects the input to the EPP flows; the EPP flows themselves perform canonicalization as well).
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/1886)
> Standardize hostname handling in URS command

- core/src/main/java/google/registry/beam/common/RegistryJpaIO.java
- core/src/test/java/google/registry/beam/common/RegistryJpaWriteTest.java
Remove the entity existence check in RegistryJpaIO. It was intended to disallow non-transactional writes but it cann't handle BEAM retries.
Will address this in b/263502442.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/1889)
> Remove aggressive check in RegistryJpaIO.Write

- core/src/main/java/google/registry/config/RegistryConfig.java
- core/src/main/java/google/registry/config/RegistryConfigSettings.java
- core/src/main/java/google/registry/config/files/default-config.yaml
- core/src/main/java/google/registry/tools/RequestFactoryModule.java
- core/src/test/java/google/registry/tools/RequestFactoryModuleTest.java
We can use the saved refresh token associated with the nomulus tool to request an ID token with an audience of the IAP client in order to satisfy IAP with with the Nomulus tool.
Note: this requires that the user of the Nomulus tool, e.g. "gbrodman@google.com" has a User object stored in SQL if using IAP.
Tested on QA
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/1887)
> Add an optional IAP-enabled ID token when using the Nomulus tool

- core/src/main/java/google/registry/tools/CreateOrUpdateTldCommand.java
- core/src/main/java/google/registry/tools/DeleteAllocationTokensCommand.java
- core/src/main/java/google/registry/tools/UpdateAllocationTokensCommand.java
- core/src/main/java/google/registry/tools/UpdateOrDeleteAllocationTokensCommand.java
- core/src/test/java/google/registry/tools/CreateTldCommandTest.java
- core/src/test/java/google/registry/tools/UpdateTldCommandTest.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/1888)
> Add default tokens to TLD using nomulus tool

- core/src/main/java/google/registry/beam/common/RegistryPipelineOptions.java
- core/src/main/java/google/registry/beam/common/RegistryPipelineWorkerInitializer.java
- core/src/main/java/google/registry/beam/rde/RdePipeline.java
- core/src/main/java/google/registry/model/IdService.java
We've been using it in production for three weeks now. Everything seems
to be working fine. Removing the code related to checking the migration
state and using the override.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/1899)
> Always use SQL based ID allocation

- core/src/main/java/google/registry/batch/CheckPackagesComplianceAction.java
- core/src/main/java/google/registry/config/files/default-config.yaml
- core/src/main/java/google/registry/model/domain/token/PackagePromotion.java
- core/src/test/java/google/registry/batch/CheckPackagesComplianceActionTest.java
Changing this since we decided that we will have GTech handle the communication with the partners for now. We will likely change this back in the future once we have more users of packages and decide to automate more of the tiering.
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/1900)
> Only email support for package non-compliance

- core/src/main/java/google/registry/batch/BatchModule.java
- core/src/main/java/google/registry/batch/ExpandRecurringBillingEventsAction.java
- core/src/main/java/google/registry/beam/billing/ExpandRecurringBillingEventsPipeline.java
- core/src/main/java/google/registry/env/alpha/default/WEB-INF/cron.xml
- core/src/main/java/google/registry/env/production/default/WEB-INF/cron.xml
- core/src/main/java/google/registry/env/sandbox/default/WEB-INF/cron.xml
- core/src/main/java/google/registry/reporting/billing/GenerateInvoicesAction.java
- core/src/test/java/google/registry/batch/ExpandRecurringBillingEventsActionTest.java
- core/src/test/java/google/registry/beam/billing/ExpandRecurringBillingEventsPipelineTest.java
- core/src/test/java/google/registry/reporting/billing/GenerateInvoicesActionTest.java
Due to the way the beam pipeline is designed, it will expand an
recurring billing event when its event time is in scope for expansion,
instead of billing time. This means that the one time will be generated
45 days earlier. This would negate the need to check if the expansion is
finished when generating monthly invoices.
We will need to backfill the past 45 days of onetimes before the new
code is deployed. As an illustration, with the old code, a cursor time
of 2023-01-17 means that all auto-renewals whose billing time is before
2023-01-17 were created, which corresponds to an effective cursor time
of 2022-12-03 (45 days before 2023-01-17) for event time. This cursor
will need to be brought to 2023-01-17 to ensure that there is no gap in
generated event times when switching to use the new …
> Update ExpandRecurringBillingEventsAction to use the beam pipeline

- core/src/main/java/google/registry/tools/RequestFactoryModule.java
- core/src/test/java/google/registry/tools/RequestFactoryModuleTest.java
https://cloud.google.com/iap/docs/authentication-howto#authenticating_from_proxy-authorization_header discusses how we can use Proxy-Authorization instead of the simple Authorization header to authenticate with IAP. This is helpful because it will allow us to seamlessly transition from non-IAP to IAP. That is, we can have a period where clients (e.g. Nomulus tool, cron jobs) send both the old Authorization and the new IAP Proxy-Authorization headers and the app will use either the old mechanism or IAP to authenticate the client based on whether or not IAP is enabled in Pantheon.
tested in QA that setting Proxy-Authorization works
- - - …
> Use the Proxy-Authorization header when using nomulus + IAP

- core/src/main/java/google/registry/model/EppResource.java
This annotation only works for Long or long field.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/1923)
> Remove @IdAllocation annotation from repoId

- release/schema-deployer/Dockerfile
- release/schema-verifier/Dockerfile
Ubuntu 18.04 is entering EOL and the Cloud Build jobs are failing,
seemingly due to connection error to 18.04 repos:
https://pantheon.corp.google.com/cloud-build/builds;region=global/126a7c90-4322-41f1-ba1c-a10e38a32dab;step=5?project=domain-registry-dev
We use Debian 10 for the main builder, so it's better to keep everything
on the same schedule:
https://cs.opensource.google/nomulus/nomulus/+/master:release/builder/Dockerfile
Debian 10 is supported till June 2024:
https://wiki.debian.org/LTS
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/1930)
> Change base image for schema-verifier and schema-deployer

- release/schema-verifier/Dockerfile
The schema verifier script needs pgrep and pkill, which do not come with
Debian.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/1932)
> Install procps

- proxy/src/main/java/google/registry/proxy/EppProtocolModule.java
- proxy/src/main/java/google/registry/proxy/ProxyConfig.java
- proxy/src/main/java/google/registry/proxy/ProxyModule.java
- proxy/src/main/java/google/registry/proxy/WhoisProtocolModule.java
- proxy/src/main/java/google/registry/proxy/config/default-config.yaml
- proxy/src/main/java/google/registry/proxy/handler/EppServiceHandler.java
- proxy/src/main/java/google/registry/proxy/handler/HttpsRelayServiceHandler.java
- proxy/src/main/java/google/registry/proxy/handler/WhoisServiceHandler.java
- proxy/src/test/java/google/registry/proxy/EppProtocolModuleTest.java
- proxy/src/test/java/google/registry/proxy/ProtocolModuleTest.java
- proxy/src/test/java/google/registry/proxy/TestUtils.java
- proxy/src/test/java/google/registry/proxy/WhoisProtocolModuleTest.java
- proxy/src/test/java/google/registry/proxy/handler/EppServiceHandlerTest.java
- proxy/src/test/java/google/registry/proxy/handler/WhoisServiceHandlerTest.java
This is only generated and used if "iapClientId" is set in the proxy config. If so, we use code similar to
https://cloud.google.com/iap/docs/authentication-howto#obtaining_an_oidc_token_for_the_default_service_account to generate an ID token that is valid for IAP. We set the token on the Proxy-Authorization header so that we can keep using the pre-existing access token as well -- IAP allows for us to use either the Authorization header or the Proxy-Authorization header.
Tested:
- Turned on IAP in QA and removed the standard OAuth authentication mechanism (to make sure we hit the IAP mechanism)
- Added the QA IAP client ID in the proxy's QA config, deployed this code, and ran some tests. We successfully parsed the token but failed because we haven't set up an account in the QA database for …
> Generate and use an IAP-enabled ID token in the proxy

- core/src/main/java/google/registry/env/common/default/WEB-INF/web.xml
- core/src/main/java/google/registry/model/CreateAutoTimestamp.java
- core/src/main/java/google/registry/model/EppResource.java
- core/src/main/java/google/registry/model/domain/DomainBase.java
- core/src/main/java/google/registry/module/frontend/FrontendRequestComponent.java
- core/src/main/java/google/registry/persistence/VKey.java
- core/src/main/java/google/registry/ui/server/console/ConsoleDomainGetAction.java
- core/src/main/java/google/registry/ui/server/registrar/RegistrarConsoleModule.java
- core/src/test/java/google/registry/ui/server/console/ConsoleDomainGetActionTest.java
- core/src/test/resources/google/registry/module/frontend/frontend_routing.txt
- util/src/main/java/google/registry/util/DateTimeTypeAdapter.java
- util/src/main/java/google/registry/util/UtilsModule.java
We might (likely will) modify some of the fiddly bits around this (maybe the GSON serialization, where we do the actual authorization, etc) but this should be a decent basic shell structure for endpoints that the new registrar console can call to retrieve JSON results.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/1916)
> Add a frontend endpoint for retrieving a domain in JSON form

- core/src/main/java/google/registry/beam/billing/ExpandRecurringBillingEventsPipeline.java
- core/src/main/java/google/registry/config/files/default-config.yaml
- core/src/main/resources/google/registry/beam/expand_recurring_billing_events_pipeline_metadata.json
For reasons that I cannot explain, the same expand recurring billing
event pipeline would fail in us-east1 but succeed in us-central1.
See:
https://pantheon.corp.google.com/dataflow/jobs/us-central1/2023-02-09_14_52_24-162498476138221714;graphView=0?project=domain-registry
https://pantheon.corp.google.com/dataflow/jobs/us-east1/2023-02-09_14_26_07-4564782062878841960;graphView=1?project=domain-registry
Also improved how the accuracy of the metrics:
It is observed that both counters are consistently higher for the same
start and end times when running in dry run mode. There is no way to
test for consistency when not running in dry run, for obviously reasons.
I can make the recurrings in scope counter consistent by not updating it
in a side-effect-causing transaction, but there is no way …
> Change default beam job region

- config/dependency-license/allowed_licenses.json
For some reason `./gradlew clean build` on master is failing for me on
multiple machines due to a new org.json:json version triggering license
violations, even though the lock files are not changing.
Note that the old versions are still present because if I remove
"The JSON license", which the old versions use, the check also fails...
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/1942)
> Add allowed license for json

- core/src/main/java/google/registry/idn/Latin-IDN.txt
- core/src/main/java/google/registry/tldconfig/idn/extended_latin.txt
ICANN doesn't like this character because it's confusable with a normal G (the stroke tends to get lost in the visual clutter of the descender), and .com's Extended Latin table doesn't use it either. Best to get rid of it.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/1938)
> Remove "letter G with stroke" from Extended Latin IDN table

- core/src/main/java/google/registry/tmch/TmchCertificateAuthority.java
- util/src/main/java/google/registry/util/X509Utils.java
There is no point comparing the old CRL to the new ones when the old one
is invalid. This could happen when the CA cert rotates, after which the
old CRL stop being valid as it fails signature verification against the
new cert.
This change will allow us to keep updating the CRL after a CA rotation without
having to manually delete the old CRL from the database.
See b/270983553.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/1946)
> Ignore invalid old CRL when performing update.

- core/src/main/java/google/registry/env/production/default/WEB-INF/cron.xml
- core/src/main/java/google/registry/flows/domain/DomainCreateFlow.java
- core/src/main/java/google/registry/model/common/DatabaseMigrationStateSchedule.java
- core/src/main/java/google/registry/tmch/LordnTaskUtils.java
- core/src/main/java/google/registry/tmch/NordnUploadAction.java
- core/src/main/java/google/registry/tmch/TmchModule.java
- core/src/main/java/google/registry/tools/GenerateLordnCommand.java
- core/src/test/java/google/registry/flows/domain/DomainCreateFlowTest.java
- core/src/test/java/google/registry/testing/DatabaseHelper.java
- core/src/test/java/google/registry/testing/DomainSubject.java
- core/src/test/java/google/registry/tmch/NordnUploadActionTest.java
This PR adds an alternative method to upload Lordn to Nordn server without
using App Engine pull queue. A new database migration stage is added to control
whether a new task is scheduled with the old or new method. The
NordnUploadAction is configured to process both kind of tasks. Once the tasks
scheduled for the old tasks are all processed, we can start using the
new method exclusively.
See: go/registry-pull-queue-redesign
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/1925)
> Add support for Nordn upload without using pull queues.

- core/src/main/java/google/registry/flows/domain/DomainCreateFlow.java
- core/src/main/java/google/registry/flows/domain/DomainFlowUtils.java
- core/src/main/java/google/registry/flows/domain/DomainRenewFlow.java
- core/src/main/java/google/registry/flows/domain/DomainRestoreRequestFlow.java
- core/src/main/java/google/registry/flows/domain/DomainTransferRequestFlow.java
- core/src/main/java/google/registry/flows/domain/DomainUpdateFlow.java
- core/src/test/java/google/registry/flows/domain/DomainCreateFlowTest.java
- core/src/test/resources/google/registry/flows/domain/domain_create_response_fee.xml
Allow Domain creations to succeed if the fee in the fee extension is equal to or higher than the actual cost of the registration with the default token applied. Still require fees to match if there are no valid default tokens.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/1927)
> Allow incorrect fee extensions on domain creates with default tokens

- core/src/main/java/google/registry/model/EppResource.java
- core/src/main/java/google/registry/model/domain/Domain.java
- core/src/main/java/google/registry/model/domain/DomainBase.java
- core/src/main/java/google/registry/model/host/Host.java
- core/src/main/java/google/registry/model/host/HostBase.java
- core/src/test/java/google/registry/model/domain/DomainTest.java
- core/src/test/java/google/registry/model/history/DomainHistoryTest.java
- db/src/main/resources/sql/schema/db-schema.sql.generated
We have decided to use a separate table (#1940) to track DNS refresh requests
due to performance reasons.
See: go/registry-pull-queue-redesign
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/1943)
> Remove dnsRefreshRequestTime from EppResources

- core/src/main/java/google/registry/env/production/default/WEB-INF/appengine-web.xml
It seems like we're hitting App Engine capacity issues resulting in actual pages now (for whatever reason, but likely one customer), and we obviously don't want that.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/1954)
> Double the number of frontend instances on production from 12 to 24

- core/src/main/java/google/registry/model/domain/token/AllocationToken.java
- core/src/main/java/google/registry/persistence/converter/CommandNameListConverter.java
- core/src/main/java/google/registry/persistence/converter/CommandNameSetConverter.java
- core/src/main/resources/META-INF/persistence.xml
- core/src/test/java/google/registry/model/domain/token/AllocationTokenTest.java
- db/src/main/resources/sql/schema/db-schema.sql.generated
Schema change is in go/r3pr/1957 Original plan was to implement this using varying Token Types, but decided instead to add this field. See discussion in go/r3pr/1952.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/1958)
> Add allowedEppActions to AllocationToken Java classes

- release/stage_beam_pipeline.sh
Fix turned out to be pretty easy, however discovering it and verifying on alpha was a bit complex. 
Anyhow the fix verified on alpha on `expand-billing-2023-03-26t03-00-00z-2023-03-30t17-14-33z` pipeline. It confirmed to be successful with runner v2 disabled.
TODO: b/276340570 to track the status of runner_v2 + autosharding in the future. 
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/1976)
> Add disable_runner_v2 to pipeline options

- core/src/main/java/google/registry/persistence/transaction/JpaTransactionManagerImpl.java
- core/src/test/java/google/registry/persistence/transaction/JpaTransactionManagerImplTest.java
This resolves b/256151008 
The test added shows that without the change outer transaction retries 3 times and inner transaction retries 9 times, with the change inner transaction retries 3 times as well as outer transaction.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/1974)
> Transaction manager to not retry inner transactions

- core/src/main/java/google/registry/env/production/default/WEB-INF/cloud-scheduler-tasks.xml
Makes the next run at the first Monday of December, which should give us
plenty of time to fix the issue with it wiping out PII in the most recent
contact history.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/1982)
> Temporarily disable contact history wipeout

- core/src/main/java/google/registry/model/domain/fee/Credit.java
- core/src/test/java/google/registry/flows/domain/DomainDeleteFlowTest.java
- core/src/test/resources/google/registry/flows/domain/domain_delete_response_fee_free_grace.xml
There can be situations (anchor tenants, test tokens, other ways of getting a domain to cost $0) where we may want to delete a domain during the add grace period but the credit applied is 0. We should not fail on those cases.
See b/277115241 for an example.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/1984)
> Allow a credit of 0 when deleting a domain during a grace period

- core/src/main/java/google/registry/flows/domain/DomainFlowUtils.java
- core/src/main/java/google/registry/model/tld/Registry.java
- core/src/main/java/google/registry/persistence/converter/IdnTableEnumSetConverter.java
- core/src/main/java/google/registry/tldconfig/idn/IdnLabelValidator.java
- core/src/main/java/google/registry/tools/CreateOrUpdateTldCommand.java
- core/src/main/resources/META-INF/persistence.xml
- core/src/test/java/google/registry/tldconfig/idn/IdnLabelValidatorTest.java
- core/src/test/java/google/registry/tools/CreateTldCommandTest.java
- core/src/test/java/google/registry/tools/UpdateTldCommandTest.java
- db/src/main/resources/sql/schema/db-schema.sql.generated
This includes changes to make sure that we use the proper per-TLD IDN tables as well as setting/updating/removing them via the Create/Update TLD commands.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/1977)
> Add Java code for storing and using IDN tables per-TLD

- release/builder/cloudSchedulerDeployer.go
This should resolve failing deployment because of the extra new line or empty space in xml config
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/1988)
> Trim cloud scheduler config url value before submitting

- core/build.gradle
- core/src/main/java/google/registry/batch/BatchModule.java
- core/src/main/java/google/registry/batch/WipeOutContactHistoryPiiAction.java
- core/src/main/java/google/registry/beam/wipeout/WipeOutContactHistoryPiiPipeline.java
- core/src/main/java/google/registry/beam/wipeout/WipeOutContactHistoryPiiPipelineOptions.java
- core/src/main/java/google/registry/config/RegistryConfig.java
- core/src/main/java/google/registry/config/RegistryConfigSettings.java
- core/src/main/java/google/registry/config/files/default-config.yaml
- core/src/main/java/google/registry/env/production/default/WEB-INF/cloud-scheduler-tasks.xml
- core/src/main/resources/google/registry/beam/wipe_out_contact_history_pii_pipeline_metadata.json
- core/src/test/java/google/registry/batch/WipeOutContactHistoryPiiActionTest.java
- core/src/test/java/google/registry/beam/wipeout/WipeOutContactHistoryPiiPipelineTest.java
- release/cloudbuild-nomulus.yaml
Because we need to check if a contact history is the most recent for its
underlying contact resource, the query-wipe out-repeat loop no longer works
ideally due to the added overhead with the query.
Instead, we refactor the logic into a Beam pipeline where the query only
needs to be performed once and history entries eligible for wipe out are
handled individually in their own transforms. Because history entries
are otherwise immutable, we can run the pipeline in relatively relaxed
repeatable read isolation level. We also do not worry about batching for
performance, as we do not anticipate this operation to put a lot of
strains on the particular table.
TESTED=ran the pipeline on alpha and verified the behavior is expected.
- - - …
> Refactor contact history PII wipeout logic into a Beam pipeline

- core/src/main/java/google/registry/dns/DnsUtils.java
- core/src/main/java/google/registry/dns/writer/clouddns/CloudDnsWriter.java
- core/src/main/java/google/registry/dns/writer/dnsupdate/DnsUpdateWriter.java
- core/src/main/java/google/registry/model/tld/Tld.java
- core/src/main/java/google/registry/tools/server/GenerateZoneFilesAction.java
- core/src/test/java/google/registry/dns/writer/clouddns/CloudDnsWriterTest.java
- core/src/test/java/google/registry/dns/writer/dnsupdate/DnsUpdateWriterTest.java
- core/src/test/java/google/registry/tools/CreateTldCommandTest.java
- core/src/test/java/google/registry/tools/UpdateTldCommandTest.java
- core/src/test/java/google/registry/tools/server/GenerateZoneFilesActionTest.java
- core/src/test/java/google/registry/tools/server/tldCustomTtl.zone
This was requested in b/253635762. If the TLD does not have configured TTLs, the defaults from the config file will still be used.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/1992)
> Use a TLD's configured TTLs if they are present

- core/src/main/java/google/registry/tools/CreateOrUpdateRegistrarCommand.java
- core/src/test/java/google/registry/tools/CreateRegistrarCommandTest.java
- core/src/test/java/google/registry/tools/UpdateRegistrarCommandTest.java
When updating a registrar's primary cert, add a flag to activate rotation of previous primary cert to failover.
This functionality is part of the prober ssl cert renewal automation.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/2012)
> Allow rotation when updating registrar cert

- core/src/main/java/google/registry/tools/CreateOrUpdateDomainCommand.java
- core/src/main/java/google/registry/tools/CreateOrUpdateRegistrarCommand.java
- core/src/main/java/google/registry/tools/CreateOrUpdateTldCommand.java
- core/src/main/java/google/registry/tools/RegistrarPocCommand.java
- core/src/main/java/google/registry/tools/UpdateAllocationTokensCommand.java
- core/src/main/java/google/registry/tools/UpdateTldCommand.java
- core/src/main/java/google/registry/tools/params/StringListParameter.java
- core/src/test/java/google/registry/tools/CreateRegistrarCommandTest.java
- core/src/test/java/google/registry/tools/CreateTldCommandTest.java
- core/src/test/java/google/registry/tools/UpdateRegistrarCommandTest.java
- core/src/test/java/google/registry/tools/UpdateTldCommandTest.java
- core/src/test/java/google/registry/tools/params/StringListParameterTest.java
If the user does, e.g. `--allowed_nameservers=` (or contact ids) that shouldn't mean a list consisting solely of the empty string.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/2011)
> Don't allow a list of the empty string in List<String> fields

- core/src/main/java/google/registry/env/crash/default/WEB-INF/cloud-scheduler-tasks.xml
No more production data in crash. This allows us to repopulate crash with test data.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/2017)
> Remove CloudSql wipeout cron job in crash

- core/src/main/java/google/registry/beam/billing/BillingEvent.java
- core/src/test/java/google/registry/beam/billing/BillingEventTest.java
- core/src/test/java/google/registry/beam/billing/InvoicingPipelineTest.java
This column is used by the billing team to create invoices. Registrars
have asked that a single invoice be created for a given registrar,
instead of one per registrar-tld pair. This should have no other effect
on the billing pipeline as the invoice grouping key has a description
field that also contains the TLD, so the granularity as a whole does not
change.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/2024)
> Change usage grouping key in the invoice CSV

- core/src/main/java/google/registry/batch/CloudTasksUtils.java
- core/src/main/java/google/registry/config/RegistryConfig.java
- core/src/main/java/google/registry/config/RegistryConfigSettings.java
- core/src/main/java/google/registry/config/files/default-config.yaml
- core/src/main/java/google/registry/cron/TldFanoutAction.java
- core/src/main/java/google/registry/tools/ServiceConnection.java
- core/src/test/java/google/registry/batch/CloudTasksUtilsTest.java
- core/src/test/java/google/registry/testing/CloudTasksHelper.java
This adds a possible configuration point "defaultServiceAccount" (which in GAE will be the standard GAE service account). If this is configured, CloudTasksUtils can create tasks with standard HTTP requests with an OIDC token corresponding to that service account, as opposed to using the AppEngine-specific request methods.
This also works with IAP, in that if IAP is on and we specify the IAP client ID in the config, CloudTasksUtils will use the IAP client ID as the token audience and the request will successfully be passed through the IAP layer. Unfortunately, unlike other areas (e.g. RequestFactoryModule), we cannot use both IAP and standard authentication; we must choose one. This means that we will need to turn on IAP at roughly the same time that we deploy with the internal …
> Allow usage of standard HTTP requests in CloudTasksUtils

- core/src/main/java/google/registry/beam/rde/RdeIO.java
- core/src/main/java/google/registry/rde/ContactToXjcConverter.java
- core/src/main/java/google/registry/rde/DomainToXjcConverter.java
- core/src/main/java/google/registry/rde/RdeReportAction.java
- core/src/main/java/google/registry/rde/RdeUploadAction.java
- core/src/main/java/google/registry/rde/RdeUtils.java
- core/src/main/java/google/registry/tools/EscrowDepositEncryptor.java
- core/src/test/java/google/registry/rde/RdeReportActionTest.java
- core/src/test/java/google/registry/rde/RdeUploadActionTest.java
When RdeReportAction is invoked without a prefix parameter (as in the
case when it is kicked off by cron jobs for potential catch ups), we
need to used the same heuristics that's employed in RdeUploadAction to
find the most recent prefix for the given watermark, otherwise the job
will not find any deposits to upload.
Also renamed RdeUtil to RdeUtils, to be consistent with our naming
conventions.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/2043)
> Find the most recent prefix for RdeReportAction

- console-webapp/dev-proxy.config.json
- console-webapp/src/app/app-routing.module.ts
- console-webapp/src/app/app.component.html
- console-webapp/src/app/app.module.ts
- console-webapp/src/app/registrar/registrar.component.html
- console-webapp/src/app/registrar/registrar.component.less
- console-webapp/src/app/registrar/registrar.component.spec.ts
- console-webapp/src/app/registrar/registrar.component.ts
- console-webapp/src/app/registrar/registrar.guard.spec.ts
- console-webapp/src/app/registrar/registrar.guard.ts
- console-webapp/src/app/registrar/registrar.service.spec.ts
- console-webapp/src/app/registrar/registrar.service.ts
- console-webapp/src/app/settings/contact/contact-details.component.html
- console-webapp/src/app/settings/contact/contact.component.spec.ts
- console-webapp/src/app/settings/contact/contact.component.ts
- console-webapp/src/app/settings/contact/contact.service.ts
- console-webapp/src/app/settings/registrars/registrars.component.spec.ts
- console-webapp/src/app/settings/users/users.component.spec.ts
- console-webapp/src/app/settings/whois/whois.component.spec.ts
- console-webapp/src/app/shared/services/backend.service.ts
This adds the registrar selection screen which appears as a first step after landing on UI. The implementation was demoed to MB and confirmed as it should be good. 
This also fixes tests for existing components and adds covers added features with tests. 
Mock data removed, back-end integration for /contacts and /registrars endpoints added
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/2054)
> Add registrar selection functionality

- core/src/main/java/google/registry/tools/CurlCommand.java
- core/src/main/java/google/registry/tools/ServiceConnection.java
- core/src/test/java/google/registry/tools/CurlCommandTest.java
- core/src/test/java/google/registry/tools/ServiceConnectionTest.java
Add a --canary option (default to false) to the CurlCommand that allows connection to the canary endpoints.
During canary analysis, only the DEFAULT-canary receives traffic. This new flag allows use to test other canary services manually using the curl command.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/2060)
> Add CurlCommand option to connect to canary

- core/src/main/java/google/registry/tools/server/RefreshDnsForAllDomainsAction.java
- core/src/main/java/google/registry/tools/server/ToolsServerModule.java
- core/src/test/java/google/registry/testing/DatabaseHelper.java
- core/src/test/java/google/registry/tools/server/RefreshDnsForAllDomainsActionTest.java
This PR batches the domains read and processed in the RefreshDnsForAllDomainsAction. The batching is necessary to prevent issues with predicate locking as described in go/dr-psql-index-pitfall.
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/2037)
> Add batching to the RefreshDnsForAllDomainsAction

- core/src/main/java/google/registry/config/RegistryConfig.java
- core/src/main/java/google/registry/config/RegistryConfigSettings.java
- core/src/main/java/google/registry/config/files/default-config.yaml
- core/src/main/java/google/registry/flows/domain/DomainCreateFlow.java
- core/src/main/java/google/registry/flows/domain/DomainFlowUtils.java
- core/src/main/java/google/registry/flows/domain/DomainPricingLogic.java
- core/src/test/java/google/registry/flows/domain/DomainCreateFlowTest.java
- core/src/test/java/google/registry/flows/domain/DomainPricingLogicTest.java
- core/src/test/resources/google/registry/flows/domain/domain_check_fee_reserved_sunrise_response_v06.xml
- core/src/test/resources/google/registry/flows/domain/domain_check_fee_reserved_sunrise_response_v06_with_renewals.xml
- core/src/test/resources/google/registry/flows/domain/domain_check_fee_reserved_sunrise_response_v11_create.xml
- core/src/test/resources/google/registry/flows/domain/domain_check_fee_reserved_sunrise_response_v12.xml
Previously we had a 15% discount applied at invoicing time. We got rid of
that inadvertently in 2022 and we want to add it back, but instead of
being applied at invoicing time we'll just apply it directly to the
creation cost when creating the billing events.
Note: previous behavior didn't care about standard vs premium pricing so
we don't either
https://buganizer.corp.google.com/issues/287070313 is a bug for the
issue, and
https://github.com/google/nomulus/pull/1710/files#diff-5097b0ef57578718444ea6b9d4c6cb32f655686a37e2ca3dd96ad2db86a77f06L151-L170
is the section of the pull request that inadvertently removed it
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/2056)
> Add configurable discount on sunrise domain creates

- core/src/main/java/google/registry/rdap/RdapDataStructures.java
- core/src/main/java/google/registry/rdap/RdapIcannStandardInformation.java
- core/src/main/java/google/registry/rdap/RdapJsonFormatter.java
- core/src/test/java/google/registry/rdap/RdapTestHelper.java
- core/src/test/resources/google/registry/rdap/rdap_domains_four_truncated.json
- core/src/test/resources/google/registry/rdap/rdap_domains_four_with_one_unicode.json
- core/src/test/resources/google/registry/rdap/rdap_domains_four_with_one_unicode_truncated.json
- core/src/test/resources/google/registry/rdap/rdap_domains_two.json
- core/src/test/resources/google/registry/rdap/rdap_incomplete_domain_result_set.json
- core/src/test/resources/google/registry/rdap/rdap_incomplete_domains.json
- core/src/test/resources/google/registry/rdap/rdap_nontruncated_domains.json
- core/src/test/resources/google/registry/rdap/rdapjson_toplevel_domain.json
These wording changes are necessary for compliance with the latest
(2019) RDAP profile found at https://www.icann.org/en/system/files/files/rdap-response-profile-15feb19-en.pdf
The old version (2016), at https://www.icann.org/resources/pages/rdap-operational-profile-2016-07-26-en
included the "www" in the URL for ICANN complaints.
These (among others) were found using the RDAP conformance tool 
https://github.com/icann/rdap-conformance-tool
See https://buganizer.corp.google.com/issues/252317192 for more info,
these are just the low-hanging fruit (removing a www and fixing a typo
in a status)
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/2062)
> Fix minor RDAP typos

- core/src/main/java/google/registry/tools/server/RefreshDnsForAllDomainsAction.java
- core/src/test/java/google/registry/tools/server/RefreshDnsForAllDomainsActionTest.java
This is a follow-on to comments in PR #2037. It makes the main loop cleaner and also removes ambiguities around database handling when the first query is run with the cursor still empty because no results have been found yet.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/2063)
> Add minor refactoring follow-up for RefreshDnsForAllDomainsAction

- core/src/main/java/google/registry/tools/UpdatePremiumListCommand.java
- core/src/test/java/google/registry/tools/UpdatePremiumListCommandTest.java
It was previously calling toString() on an Optional<PremiumList> which was unnecessarily verbose. The existing premium list is required to be present anyway.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/2065)
> Fix the output slightly when running nomulus update_premium_list

- core/src/main/java/google/registry/rdap/RdapIcannStandardInformation.java
- core/src/main/java/google/registry/rdap/RdapJsonFormatter.java
- core/src/test/resources/google/registry/rdap/rdap_associated_contact_no_personal_data.json
- core/src/test/resources/google/registry/rdap/rdap_contact_no_personal_data_with_remark.json
- core/src/test/resources/google/registry/rdap/rdap_domain_no_contacts_with_remark.json
- core/src/test/resources/google/registry/rdap/rdap_domain_unicode_no_contacts_with_remark.json
- core/src/test/resources/google/registry/rdap/rdapjson_domain_logged_out.json
- core/src/test/resources/google/registry/rdap/rdapjson_registrant_logged_out.json
Instead of using REDACTED FOR PRIVACY everywhere we should just include the empty string (this is what the spec says, what other gTLD registrars do, and what the RDAP conformance tool at
https://github.com/icann/rdap-conformance-tool says to do.
In the contact VCards, we omit redacted fields entirely unless the spec requires that they exist (the version number and an empty 'fn' field). This also applies to the "handle" field.
Eventually we will probably want to add the redaction extension but that's not RFCed yet and isn't required for the August RDAP conformance deadline.
Tested on alpha and the conformance tool passes with the exception of one alpha-specific error
- - - …
> Clean up issues with RDAP redaction

- core/src/main/resources/google/registry/reporting/icann/sql/cloud_sql_transaction_counts.sql
- core/src/test/java/google/registry/reporting/icann/ActivityReportingQueryBuilderTest.java
- core/src/test/resources/google/registry/reporting/icann/transaction_counts_test_cloud_sql.sql
See b/290228682, there are edge cases in which the net_renew would be negative when
a domain is cancelled by superusers during renew grace period. The correct thing
to do is attribute the cancellation to the owning registrar, but that would require
changing the owing registrar of the the corresponding cancellation DomainHistory,
which has cascading effects that we don't want to deal with. As such we simply
floor the number here to zero to prevent any negative value from appearing, which
should have negligible impact as the edge cage happens very rarely, more specifically
when a cancellation happens during grace period by a registrar other than the the
owning one. All the numbers here should be positive to pass ICANN validation. …
> Add a floor of zero to transaction report counts

- core/src/main/java/google/registry/tools/RegistryTool.java
- core/src/main/java/google/registry/tools/javascrap/RecreateBillingRecurrencesCommand.java
- core/src/test/java/google/registry/tools/javascrap/RecreateBillingRecurrencesCommandTest.java
This is part of b/247839944 as a followup to the large bug from September 2022. As a result of that, there are domains whose BillingRecurrence objects were closed but the domain wasn't deleted. In order to avoid having these domains stick around forever without being billed, we want to restart billing on them whenever their next billing cycle would have been.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/2077)
> Create a scrap command to re-enable billing recurrences that were closed

- core/src/main/resources/google/registry/reporting/icann/sql/cloud_sql_activity_report_aggregation.sql
- core/src/main/resources/google/registry/reporting/icann/sql/cloud_sql_transaction_counts.sql
- core/src/main/resources/google/registry/reporting/icann/sql/whois_counts.sql
- core/src/test/resources/google/registry/reporting/icann/activity_report_aggregation_test_cloud_sql.sql
- core/src/test/resources/google/registry/reporting/icann/transaction_counts_test_cloud_sql.sql
- core/src/test/resources/google/registry/reporting/icann/whois_counts_test_cloud_sql.sql
This includes two changes, the second necessary for testing the first.
1. We add the rdap-queries field as mandated by the amendment to the registry agreement, https://itp.cdn.icann.org/en/files/registry-agreement/proposed-global-amendment-base-gtld-registry-agreement-12-04-2023-en.pdf. This is fairly similar to the whois-queries field where we just query the logs, but instead of searching for "whois" we search for "rdap".
2. BigQuery doesn't use MAX to refer to the bigger of two fields; MAX accepts an array as an argument. In order to do what we want (and to have the BigQuery statements succeed), we need to use GREATEST. Tested both versions in alpha and production BigQuery instances.
- - - …
> Fix ICANN reporting and add rdap-queries field

- core/src/main/java/google/registry/batch/AsyncTaskEnqueuer.java
- core/src/main/java/google/registry/flows/domain/DomainTransferRequestFlow.java
- core/src/test/java/google/registry/batch/AsyncTaskEnqueuerTest.java
It was only called in one place (in actual production code), and it was just slightly obscuring the fact that re-saves can be scheduled for multiple points in the future in a way that wasn't amazingly helpful to understanding of the system logic at the callsite.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/2083)
> Remove unnecessary overload of AsyncTaskEnqueuer.enqueueAsyncResave()

- core/src/main/java/google/registry/flows/FlowRunner.java
- core/src/main/java/google/registry/flows/session/LoginFlow.java
- core/src/main/java/google/registry/model/eppinput/EppInput.java
- core/src/test/java/google/registry/flows/session/LoginFlowTestCase.java
- core/src/test/resources/google/registry/flows/session/login_set_new_password.xml
- docs/flows.md
This is part of the spec in RFC 5730 that we hadn't implemented until now. Note that this requires changing LoginFlow to be transactional, but I don't think that should cause any issues.
See https://b.corp.google.com/issues/291759824
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/2080)
> Allow EPP password to be changed during login flow

- core/src/main/java/google/registry/batch/CannedScriptExecutionAction.java
- core/src/main/java/google/registry/config/CredentialModule.java
- core/src/main/java/google/registry/config/RegistryConfig.java
- core/src/main/java/google/registry/config/RegistryConfigSettings.java
- core/src/main/java/google/registry/config/files/default-config.yaml
- core/src/main/java/google/registry/groups/GmailClient.java
- core/src/main/java/google/registry/groups/GmailModule.java
- util/src/main/java/google/registry/util/EmailMessage.java
Add placeholder configs for sending emails using Gmail in GSuite.
The names of the new configs are temporary. After migration they will revert to the names currently in use by the AppEngine email API.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/2089)
> Add placeholder configs for Gmail

- db/build.gradle
- db/src/test/java/google/registry/sql/flyway/FlywayDeadlockTest.java
Use a system property to specify whether this check should be executed.
We will update the presubmit test script to run this check only during foss-pr.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/2092)
> Re-enable flyway deadlock check

- core/src/main/java/google/registry/reporting/spec11/Spec11EmailUtils.java
During email migration, alerts should be sent to the address annotated with `newAlertRecipientEmailAddress`.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/2103)
> Fix the alert recipient address for Spec11

- core/src/main/java/google/registry/tools/GetTldCommand.java
- core/src/test/java/google/registry/tools/CommandTestCase.java
- core/src/test/java/google/registry/tools/GetTldCommandTest.java
`System.out` uses the default charset on the platform. Not a big issue since it is only used in tools, but test may break, say on Cloud Build.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/2108)
> Fix unicode issue in GetTldCommand

- release/update_num_instances.sh
This is a fast and easy way to update number of instances for the service deployed to app engine. Works with manual-scaling types services.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/2112)
> Add script to allow quickly update number of instances

- console-webapp/src/app/shared/services/backend.service.ts
- core/src/main/java/google/registry/model/adapters/CurrencyJsonAdapter.java
- core/src/main/java/google/registry/request/RequestModule.java
- core/src/main/java/google/registry/ui/server/registrar/RegistrarConsoleModule.java
- core/src/test/java/google/registry/ui/server/console/RegistrarsActionTest.java
- core/src/test/java/google/registry/ui/server/console/settings/ContactActionTest.java
- core/src/test/java/google/registry/ui/server/console/settings/SecurityActionTest.java
- util/src/main/java/google/registry/util/CidrAddressBlock.java
- util/src/main/java/google/registry/util/DateTimeTypeAdapter.java
- util/src/main/java/google/registry/util/StringBaseTypeAdapter.java
This includes two changes:
1. Creating a base string-type adapter for use parsing to/from JSON classes that are represented as simple strings
2. Changing the object-provider methods so that the POST bodies should contain precisely the expected object(s) and nothing else. This way, it's easier for the frontend and backend to agree that, for instance, one POST endpoint might accept exactly a Registrar object, or a list of Contact objects.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/2113)
> Refactor the way that the console BE parses POST bodies

- core/src/main/java/google/registry/reporting/spec11/GenerateSpec11ReportAction.java
- core/src/test/java/google/registry/reporting/spec11/GenerateSpec11ReportActionTest.java
Increase PublishSpec11Action start delay to avoid the need to retry.
The only other use case is invoice, which typically does not retry: delay is 10 minutes, pipeline finishes within 7 minutes.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/2116)
> Mitigate Cloud task retry problem

- core/src/main/java/google/registry/config/RegistryConfig.java
- core/src/main/java/google/registry/config/RegistryConfigSettings.java
- core/src/main/java/google/registry/config/files/default-config.yaml
- core/src/main/java/google/registry/config/files/nomulus-config-unittest.yaml
- core/src/main/java/google/registry/flows/FlowModule.java
- core/src/main/java/google/registry/flows/FlowRunner.java
- core/src/main/java/google/registry/persistence/IsolationLevel.java
- core/src/main/java/google/registry/persistence/PersistenceModule.java
- core/src/main/java/google/registry/persistence/transaction/JpaTransactionManager.java
- core/src/main/java/google/registry/persistence/transaction/JpaTransactionManagerImpl.java
- core/src/main/java/google/registry/persistence/transaction/TransactionManager.java
- core/src/test/java/google/registry/flows/FlowRunnerTest.java
- core/src/test/java/google/registry/persistence/transaction/JpaTransactionManagerImplTest.java
- core/src/test/java/google/registry/persistence/transaction/ReplicaSimulatingJpaTransactionManager.java
A config file field is added to control if per-transaction isolation
level is actually used. If set to true, nested transactions will throw
a runtime exception as the enclosing transaction may run at a different
isolation level.
In this PR we only add the ability to specify the isolation level,
without enabling it in any environment (including unit tests), or
actually specifying one for any query. This should allow us to set up
the system without impacting anything currently working.
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/2104)
> Add the ability to specify transaction isolation level on a per-transaction basis

- core/src/main/java/google/registry/reporting/billing/PublishInvoicesAction.java
- core/src/main/java/google/registry/reporting/spec11/GenerateSpec11ReportAction.java
- core/src/main/java/google/registry/reporting/spec11/PublishSpec11ReportAction.java
- core/src/test/java/google/registry/reporting/billing/PublishInvoicesActionTest.java
- core/src/test/java/google/registry/reporting/spec11/GenerateSpec11ReportActionTest.java
- core/src/test/java/google/registry/reporting/spec11/PublishSpec11ReportActionTest.java
Replace `SC_NOT_MODIFIED` (304) with `SC_SERVICE_UNAVAILABLE` (503) when data is not available yet. Affected actions are invoice- and spec11-publishing.
It is confirmed that Cloud Tasks currently does not retry with code 304, despite the public documentation stating so. We will use 503 for now, pending the decision by Cloud Tasks whether to change behavior or documentation.
The code `TOO_EARLY` (425) is another alternative. It is not meant for our use case but at least sounds like it is. However, it is not in any javax.servlet jar. We don't want to define our own constant, and we cannot upgrade to jakarta.servlet yet.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/2118)
> Fix Cloud Tasks retry failure

- core/src/main/java/google/registry/tools/RegistryToolComponent.java
Need to add this small fix to get the get_tld command working again
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/2123)
> Inject getTldCommand in RegistryToolComponent

- core/src/main/java/google/registry/beam/rde/RdeIO.java
- core/src/main/java/google/registry/model/registrar/Registrar.java
- core/src/test/java/google/registry/model/registrar/RegistrarTest.java
Also refactors a function to no longer unnecessarily return a low level Iterable type.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/2124)
> Remove a couple unnecessary inner transact() calls

- core/src/main/java/google/registry/dns/RefreshDnsAction.java
- core/src/main/java/google/registry/flows/domain/DomainClaimsCheckFlow.java
- core/src/main/java/google/registry/flows/poll/PollAckFlow.java
- core/src/main/java/google/registry/flows/poll/PollFlowUtils.java
- core/src/main/java/google/registry/flows/poll/PollRequestFlow.java
- core/src/main/java/google/registry/model/EppResourceUtils.java
- core/src/main/java/google/registry/model/tmch/ClaimsList.java
- core/src/main/java/google/registry/persistence/transaction/JpaTransactionManagerImpl.java
- core/src/main/java/google/registry/persistence/transaction/TransactionManager.java
- core/src/test/java/google/registry/model/tmch/ClaimsListDaoTest.java
- core/src/test/java/google/registry/persistence/transaction/ReplicaSimulatingJpaTransactionManager.java
- core/src/test/java/google/registry/tmch/TmchDnlActionTest.java
- core/src/test/java/google/registry/tools/UploadClaimsListCommandTest.java
In the future, reTransact() will be the only way to initiate a transaction that doesn't fail when called inside an outer wrapping transaction (when wrapped, it's a no-op). It should be used sparingly, with a preference towards refactoring the code to move transactions outwards (which this PR also contains).
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/2125)
> Add tm().reTransact() methods and refactor away some inner transactions

- core/src/main/java/google/registry/model/EntityYamlUtils.java
- core/src/test/resources/google/registry/model/tld/tld.yaml
- core/src/test/resources/google/registry/tools/tld.yaml
This makes printing the TLDs prettier and makes it easier to find fields.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/2128)
> Alphabetize YAML output by property name

- core/src/main/java/google/registry/config/RegistryConfig.java
- core/src/main/java/google/registry/config/RegistryConfigSettings.java
- core/src/main/java/google/registry/config/files/default-config.yaml
- core/src/main/java/google/registry/groups/GmailClient.java
- core/src/main/java/google/registry/reporting/billing/BillingEmailUtils.java
- core/src/test/java/google/registry/groups/GmailClientTest.java
- core/src/test/java/google/registry/reporting/billing/BillingEmailUtilsTest.java
- util/src/main/java/google/registry/util/EmailMessage.java
Added support for an optional `reply-to` address for invoicing messages, since these messages are confidential and may not be appropriate for the default address.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/2130)
> Use gmail to send invoices

- core/src/main/java/google/registry/env/common/backend/WEB-INF/logging.properties
- core/src/main/java/google/registry/env/common/default/WEB-INF/logging.properties
- core/src/main/java/google/registry/env/common/pubapi/WEB-INF/logging.properties
- core/src/main/java/google/registry/env/common/tools/WEB-INF/logging.properties
- core/src/main/java/google/registry/persistence/transaction/DatabaseException.java
- core/src/main/java/google/registry/persistence/transaction/JpaTransactionManagerImpl.java
- core/src/test/java/google/registry/persistence/transaction/DatabaseExceptionTest.java
- core/src/test/java/google/registry/persistence/transaction/HibernateLoggingSuppressionTest.java
- core/src/test/java/google/registry/persistence/transaction/JpaTransactionManagerExtensionTest.java
- core/src/test/java/google/registry/persistence/transaction/JpaTransactionManagerImplTest.java
Hibernate logs certain information at the ERROR level, which for the purpose of troubleshooting is misleading, since most affected operations succeed after retry. ERROR-level logging should only be added by Nomulus code.
This PR does two things:
1. Disable all logging in two Hibernate classes: we cannot disable logging at a finer granularity, and we cannot preserve lower-level logging while disabling ERROR.
2. Adds a DatabaseException which captures all error details that may escape the typical loggers' attention: SQLException instances can be chained in a different way from Throwable's `getCause()` method.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/2134)
> Disable Hibernate error logging

- console-webapp/src/app/registrar/registrar-selector.component.html
We set the active registrar ID based on this choice so it needs to be the ID, not the name
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/2138)
> Use registrar ID, not name, in selector

- console-webapp/src/app/registrar/registrar.guard.spec.ts
- console-webapp/src/app/registrar/registrar.guard.ts
Previously this didn't properly deal with nested routings, e.g. "settings/whois". It tried to just pass "whois" as the next url which doesn't work with the router because it's nested under the settings. Using all parts of the URL allows us to handle the nesting.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/2139)
> Pass around the full URL in RegistrarGuard

- core/src/main/java/google/registry/request/auth/OAuthAuthenticationMechanism.java
This token is only ever used for logging. The GAE OAuth service will
parse the header directly when called to retrieve the current user and
user id. Logging it in prod could be a security risk if the logs are
leaked.
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/2148)
> Redact OAuth access token in prod

- console-webapp/src/app/registrar/emptyRegistrar.component.ts
- console-webapp/src/app/registrar/registrar.guard.ts
In this case we should just display the standard page, no need to redirect anywhere since there's nothing to redirect to.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/2149)
> Don't include a nextUrl when accessing the console homepage

- core/src/main/java/google/registry/tools/ConfirmingCommand.java
- core/src/main/java/google/registry/tools/CreateDomainCommand.java
- core/src/main/java/google/registry/tools/CreateOrUpdateTldCommand.java
- core/src/main/java/google/registry/tools/DeleteAllocationTokensCommand.java
- core/src/main/java/google/registry/tools/LoadTestCommand.java
- core/src/main/java/google/registry/tools/LockOrUnlockDomainCommand.java
- core/src/main/java/google/registry/tools/UnrenewDomainCommand.java
- core/src/main/java/google/registry/tools/UpdateAllocationTokensCommand.java
- core/src/main/java/google/registry/tools/javascrap/CreateCancellationsForBillingEventsCommand.java
- core/src/test/java/google/registry/tools/CommandTestCase.java
- core/src/test/java/google/registry/tools/CreateDomainCommandTest.java
- core/src/test/java/google/registry/tools/CreateRegistrarCommandTest.java
- core/src/test/java/google/registry/tools/CreateRegistrarGroupsCommandTest.java
- core/src/test/java/google/registry/tools/CreateTldCommandTest.java
- core/src/test/java/google/registry/tools/DeleteAllocationTokensCommandTest.java
- core/src/test/java/google/registry/tools/LoadTestCommandTest.java
- core/src/test/java/google/registry/tools/LockDomainCommandTest.java
- core/src/test/java/google/registry/tools/UniformRapidSuspensionCommandTest.java
- core/src/test/java/google/registry/tools/UnlockDomainCommandTest.java
- core/src/test/java/google/registry/tools/UnrenewDomainCommandTest.java
- core/src/test/java/google/registry/tools/UpdateTldCommandTest.java
- core/src/test/java/google/registry/tools/javascrap/CreateCancellationsForBillingEventsCommandTest.java
Simply using System.out will use the platform's default charset which can cause issues such as in Cloud Build. Using PrintStream allows us to define the charset.
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/2140)
> Use PrintStream in ConfirmingCommand

- proxy/kubernetes/proxy-service-canary.yaml
- proxy/kubernetes/proxy-service.yaml
The beta API is deprecated.
TESTED=deployed the new manifest to alpha. Without the change, deploying
resulted in an error.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/2153)
> Update proxy k8s manifest

- core/src/main/java/google/registry/tools/ConfigureTldCommand.java
- core/src/test/java/google/registry/tools/ConfigureTldCommandTest.java
The configure_tld command should not be run locally for the Production environment since the regularly running Cloud Build job will quickly overwrite the locally made changes with whatever configurations are stored in source control. 
In situations where a quick fix is needed the command can be used to make TLD changes locally and the breakglass flag can be used to set the TLD to breakglass mode indicating that Cloud Build should not overwrite it. Breakglass mode will be turned off once an automatic Cloud Build run of the command runs with a configuration equal to the the configuration stored in the database, indicating that the internal repo has caught up.
More info can be found in the Breakglass section of go/tldsourcecontrol …
> Add breakglass handling to configureTldCommand

- core/src/main/java/google/registry/model/tld/Tld.java
It will call equalsImmutableObject(), which seems the right thing to do.
We only care if the two Tld objects have the same fields, not if they
are the same object. ErrorProne complained about comparison by identity.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/2158)
> Use equals() method to compare equality

- console-webapp/angular.json
- console-webapp/src/app/app.module.ts
- console-webapp/src/app/registrar/registrar.service.ts
- console-webapp/src/app/settings/whois/whois.component.html
- console-webapp/src/app/settings/whois/whois.component.scss
- console-webapp/src/app/settings/whois/whois.component.ts
- console-webapp/src/app/settings/whois/whois.service.ts
- console-webapp/src/app/shared/services/backend.service.ts
This isn't the prettiest thing, but it replicates the type of view / edit functionality that we had in the original console.
Of note: this doesn't include input field validation, which would probably be a good idea to add at some point.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/2155)
> Add page for WHOIS-editable fields in the console

- release/notifications/README.md
- release/notifications/googlechat.yaml
- release/notifications/update_notifier.sh
- release/notifications/upload_config.sh
Add documentation that describes the current Cloud Build status notification to Google Chat, as well as how to update the configuration and the notifier service.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/2157)
> Add docs for Cloud Build status notification

- console-webapp/src/app/home/widgets/resources-widget.component.html
We want to do this because it takes the user to an external site, which could potentially lead to confusion if they tried to use the back button without a new tab.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/2163)
> Open resources link in new tab

- core/src/main/java/google/registry/tools/RegistryCli.java
- core/src/main/java/google/registry/tools/RegistryToolComponent.java
- core/src/main/java/google/registry/tools/RequestFactoryModule.java
- core/src/test/java/google/registry/tools/RequestFactoryModuleTest.java
Unless an --oauth flag is used, the nomulus tool will only send the OIDC
header. The server still accepts both headers and the user should use
`create_user` command to create an admin User (with the --oauth flag on), which
will then allow one to use the nomulus tool without the --oauth flag.
The --oauth flag and the server's ability to support OAuth-based
authentication will be removed soon. Users are urged to create the User
object in time to avoid service interruption.
TESTED=verified on alpha.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/2160)
> Deprecate the OAuth header in Nomulus tool

- core/src/main/java/google/registry/model/EntityYamlUtils.java
- core/src/main/java/google/registry/model/tld/Tld.java
- core/src/test/java/google/registry/tools/GetTldCommandTest.java
- core/src/test/resources/google/registry/model/tld/tld.yaml
- core/src/test/resources/google/registry/tools/1tld.yaml
- core/src/test/resources/google/registry/tools/badidn.yaml
- core/src/test/resources/google/registry/tools/badunicode.yaml
- core/src/test/resources/google/registry/tools/extrafield.yaml
- core/src/test/resources/google/registry/tools/idns.yaml
- core/src/test/resources/google/registry/tools/missingnullablefields.yaml
- core/src/test/resources/google/registry/tools/nullablefieldsallnull.yaml
- core/src/test/resources/google/registry/tools/outoforderfields.yaml
- core/src/test/resources/google/registry/tools/tld.yaml
- core/src/test/resources/google/registry/tools/wildcard.yaml
This addresses b/301119144. This changes the YAML representation of a TLD to show Duration fields as a String reperesntation using the Java Duration object's toString() format. This eliminates the previous ambiguity over the time unit that is being used for each duration.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/2161)
> Add custom YAML serializer for Duration

- core/src/test/java/google/registry/groups/DirectoryGroupsConnectionTest.java
- core/src/test/java/google/registry/tools/AuthModuleTest.java
JacksonFactory is deprecated and GsonFactory is the recommended
replacement.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/2173)
> Replace JacksonFactory with GsonFactory

- console-webapp/src/app/app.module.ts
- console-webapp/src/app/registrar/registrar.service.ts
- console-webapp/src/app/settings/contact/contact.component.ts
- console-webapp/src/app/settings/security/security.component.ts
- console-webapp/src/app/settings/whois/whois.component.ts
- console-webapp/src/app/shared/services/userData.service.ts
- console-webapp/src/app/snackbar.module.ts
- core/src/main/java/google/registry/request/RequestHandler.java
If we don't explicitly handle random unexpected exceptions, the error that the front end receives includes a big ole stacktrace, which is unhelpful for regular users and possibly bad to expose. Instead, we should provide a vague "something went wrong" message.
Separately, we can create a default SnackBar options and use that (we want it longer than 1.5 seconds because that's pretty short).
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/2177)
> Refine error handling in RequestHandler and the console slightly

- core/src/main/java/google/registry/model/domain/token/AllocationToken.java
- core/src/main/java/google/registry/model/registrar/Registrar.java
- core/src/main/java/google/registry/model/smd/SignedMarkRevocationListDao.java
- core/src/main/java/google/registry/model/tld/Tld.java
- core/src/main/java/google/registry/model/tld/Tlds.java
Cache loads will likely always be inner transactions, if they have a transaction at all. Cache loads do not always call a transaction since they are only necessary if the cache is not fresh at the time it is called. Since the cache itself needs to decide whether or not a DB transaction is necessary, it should use the reTransact method to safely indicate that the isolation level of the outer transaction is what should be used.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/2179)
> Use reTransact when loading the cache for database objects

- core/src/main/java/google/registry/config/files/default-config.yaml
- core/src/main/java/google/registry/tools/server/RefreshDnsForAllDomainsAction.java
This lowers the isolation level to TRANSACTION_REPEATABLE_READ which will hopefully allow the action to run the entire action without timing out on our larger TLDs.
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/2182)
> Lower the isolation level for RefreshDnsForAllDomainsAction

- core/src/main/java/google/registry/batch/BatchModule.java
- core/src/main/java/google/registry/batch/CannedScriptExecutionAction.java
- core/src/main/java/google/registry/module/backend/BackendComponent.java
- core/src/main/java/google/registry/rdap/UpdateRegistrarRdapBaseUrlsAction.java
- core/src/main/java/google/registry/rde/RdeReporter.java
- core/src/main/java/google/registry/reporting/icann/IcannHttpReporter.java
- core/src/main/java/google/registry/request/Modules.java
- core/src/main/java/google/registry/request/UrlConnectionUtils.java
- core/src/main/java/google/registry/tools/RegistryToolComponent.java
- core/src/test/java/google/registry/rdap/UpdateRegistrarRdapBaseUrlsActionTest.java
- core/src/test/java/google/registry/rde/RdeReportActionTest.java
- core/src/test/java/google/registry/reporting/icann/IcannHttpReporterTest.java
- core/src/test/java/google/registry/testing/FakeUrlConnectionService.java
- core/src/test/java/google/registry/tmch/TmchActionTestCase.java
- core/src/test/java/google/registry/tmch/TmchCrlActionTest.java
- core/src/test/java/google/registry/tmch/TmchDnlActionTest.java
- core/src/test/java/google/registry/tmch/TmchSmdrlActionTest.java
- core/src/test/resources/google/registry/module/backend/backend_routing.txt
We previously needed to use URLFetch in some instances where TLS 1.3 is
required (mostly when connecting to ICANN servers),and the JDK-bundled SSL
engine that came with App Engine runtime did not support TLS 1.3.
It appears now that the Java 8 runtime on App Engine supports TLS 1.3
out of the box, which allows us to get rid of URLFetch, which depends on
App Engine APIs.
Also removed some redundant retry and logging logic, now that we know
the HTTP client behaves correctly.
TESTED=modified the CannedScriptExecutionAction and deployed to alpha, used the
new HTTP client to connect to the three URL endpoints that were
problematic before and confirmed that TLS connections can be established. HTTP
sessions were rejected in some cases when authentication failed, but
that was expected.
- - -
This …
> Remove URLFetch

- build.gradle
node.js is already installed as a part of gradle-runner.sh, so I don't think this download is necessary
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/2192)
> Remove node.js download instruction

- core/src/main/java/google/registry/config/files/default-config.yaml
This was already set to true in all environments except prod last week. Now that the release has gone out and we have not seen any issues, we should feel safe turning this on in production as well.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/2196)
> Change the default config for perTransactionIsolation to true

- core/src/main/java/google/registry/model/domain/DomainBase.java
- core/src/main/java/google/registry/module/frontend/FrontendRequestComponent.java
- core/src/main/java/google/registry/ui/server/console/ConsoleDomainListAction.java
- core/src/main/java/google/registry/ui/server/registrar/RegistrarConsoleModule.java
- core/src/test/java/google/registry/ui/server/console/ConsoleDomainGetActionTest.java
- core/src/test/java/google/registry/ui/server/console/ConsoleDomainListActionTest.java
- core/src/test/resources/google/registry/module/frontend/frontend_routing.txt
In the future we'll want to add searching capability but for now we can go with straightforward pagination. 
Note: we will need to add a GSON VKey converter in the future to parse domains, but for now we're not using the domains anywhere
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/2193)
> Add a console action to retrieve a paged list of domains

- core/src/main/java/google/registry/model/adapters/ClassProcessingTypeAdapterFactory.java
- core/src/main/java/google/registry/model/adapters/ClassTypeAdapter.java
- core/src/main/java/google/registry/model/adapters/SerializableJsonTypeAdapter.java
- core/src/main/java/google/registry/model/domain/DomainBase.java
- core/src/main/java/google/registry/persistence/VKey.java
- core/src/main/java/google/registry/tools/GsonUtils.java
- core/src/test/java/google/registry/model/adapters/VKeyAdapterTest.java
- core/src/test/java/google/registry/ui/server/console/ConsoleDomainGetActionTest.java
GSON doesn't allow for clean (de)serialization of Class or Serializable objects which we'll need for converting VKeys to/from JSON.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/2194)
> Add TypeAdapters for VKey objects

- core/src/main/java/google/registry/env/alpha/backend/WEB-INF/appengine-web.xml
- core/src/main/java/google/registry/env/alpha/default/WEB-INF/appengine-web.xml
- core/src/main/java/google/registry/env/alpha/pubapi/WEB-INF/appengine-web.xml
- core/src/main/java/google/registry/env/alpha/tools/WEB-INF/appengine-web.xml
- core/src/main/java/google/registry/env/crash/backend/WEB-INF/appengine-web.xml
- core/src/main/java/google/registry/env/crash/default/WEB-INF/appengine-web.xml
- core/src/main/java/google/registry/env/crash/pubapi/WEB-INF/appengine-web.xml
- core/src/main/java/google/registry/env/crash/tools/WEB-INF/appengine-web.xml
- core/src/main/java/google/registry/env/local/backend/WEB-INF/appengine-web.xml
- core/src/main/java/google/registry/env/local/default/WEB-INF/appengine-web.xml
- core/src/main/java/google/registry/env/local/pubapi/WEB-INF/appengine-web.xml
- core/src/main/java/google/registry/env/local/tools/WEB-INF/appengine-web.xml
- core/src/main/java/google/registry/env/production/backend/WEB-INF/appengine-web.xml
- core/src/main/java/google/registry/env/production/default/WEB-INF/appengine-web.xml
- core/src/main/java/google/registry/env/production/pubapi/WEB-INF/appengine-web.xml
- core/src/main/java/google/registry/env/production/tools/WEB-INF/appengine-web.xml
- core/src/main/java/google/registry/env/qa/backend/WEB-INF/appengine-web.xml
- core/src/main/java/google/registry/env/qa/default/WEB-INF/appengine-web.xml
- core/src/main/java/google/registry/env/qa/pubapi/WEB-INF/appengine-web.xml
- core/src/main/java/google/registry/env/qa/tools/WEB-INF/appengine-web.xml
- core/src/main/java/google/registry/env/sandbox/backend/WEB-INF/appengine-web.xml
- core/src/main/java/google/registry/env/sandbox/default/WEB-INF/appengine-web.xml
- core/src/main/java/google/registry/env/sandbox/pubapi/WEB-INF/appengine-web.xml
- core/src/main/java/google/registry/env/sandbox/tools/WEB-INF/appengine-web.xml
We finally fixed Spinnaker (I hope) to deploy bundled services with Java
17 runtime. Note that the bytecodes are still targeting Java 8. The only
change this PR introduces is to switch the runtime environment to Java
17.
TESTED=Used alpha spinnaker to deploy to crash.
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/2201)
> Upgrade to Java 17 runtime

- release/builder/Dockerfile
- release/builder/build.sh
Updated builder docker base image from Debian10 to Debian11.
Updated node.js installation method. The version it used to install wasn't inline with the version we use everywhere else, now that's fixed.
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/2206)
> Update Debian 10 -> 11, replace node.js installation method

- core/src/main/java/google/registry/flows/domain/DomainCheckFlow.java
- core/src/main/java/google/registry/model/domain/fee/FeeQueryCommandExtensionItem.java
- core/src/test/java/google/registry/flows/domain/DomainCheckFlowTest.java
- core/src/test/resources/google/registry/flows/domain/domain_check_fee_premium_response_v12_renew_only.xml
- core/src/test/resources/google/registry/flows/domain/domain_check_fee_premium_v06_renew_only.xml
- core/src/test/resources/google/registry/flows/domain/domain_check_fee_premium_v06_transfer_only.xml
- core/src/test/resources/google/registry/flows/domain/domain_check_fee_premium_v12_renew_only.xml
- core/src/test/resources/google/registry/flows/domain/domain_check_fee_response_domain_exists_v06_renew_only.xml
- core/src/test/resources/google/registry/flows/domain/domain_check_fee_response_domain_exists_v06_transfer_only.xml
- package-lock.json
The domains (and their associated billing recurrences) were already being loaded to check restores, but they also now need to be loaded for renews and transfers as well, as the billing renewal behavior on the recurrence could be modifying the relevant renew price that should be shown. (The renew price is used for transfers as well.)
See https://buganizer.corp.google.com/issues/306212810
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/2207)
> Also load domains for domain checks of type renew/transfer

- core/src/main/java/google/registry/flows/session/LoginFlow.java
- core/src/main/java/google/registry/model/console/User.java
- core/src/main/java/google/registry/model/registrar/Registrar.java
- core/src/main/java/google/registry/model/registrar/RegistrarPoc.java
- core/src/main/java/google/registry/ui/server/registrar/RegistryLockPostAction.java
- core/src/test/java/google/registry/flows/session/LoginFlowTestCase.java
- core/src/test/java/google/registry/ui/server/registrar/RegistryLockPostActionTest.java
- util/src/main/java/google/registry/util/PasswordUtils.java
- util/src/test/java/google/registry/util/PasswordUtilsTest.java
We have been using SHA256 to hash passwords (for both EPP and registry lock),
which is now considered too weak.
This PR switches to using Scrypt, a memory-hard slow hash function, with
recommended parameters per go/crypto-password-hash.
To ease the transition, when a password is being verified, both Scrypt
and SHA256 are tried. If SHA256 verification is successful, we re-hash
the verified password with Scrypt and replace the stored SHA256 hash
with the new one. This way, as long as a user uses the password once
before the transition period ends (when Scrypt becomes the only valid
algorithm), there would be no need for manual intervention from them.
We will send out notifications to users to remind them of the transition
and urge them to use the password (which should not be a problem with …
> Switch to a stronger algorithm for password hashing

- core/src/main/java/google/registry/beam/common/RegistryJpaIO.java
- core/src/main/java/google/registry/config/RegistryConfig.java
- core/src/main/java/google/registry/config/RegistryConfigSettings.java
- core/src/main/java/google/registry/config/files/default-config.yaml
- core/src/main/java/google/registry/model/server/Lock.java
- core/src/main/java/google/registry/persistence/transaction/DatabaseException.java
- core/src/main/java/google/registry/persistence/transaction/JpaTransactionManager.java
- core/src/main/java/google/registry/persistence/transaction/JpaTransactionManagerImpl.java
- core/src/main/java/google/registry/persistence/transaction/TransactionManager.java
- core/src/test/java/google/registry/flows/FlowRunnerTest.java
- core/src/test/java/google/registry/persistence/transaction/DatabaseExceptionTest.java
- core/src/test/java/google/registry/persistence/transaction/JpaTransactionManagerImplTest.java
- core/src/test/java/google/registry/persistence/transaction/ReplicaSimulatingJpaTransactionManager.java
This PR makes a few changes to make it possible to turn on
per-transaction isolation level with minimal disruption:
1) Changed the signatures of transact() and reTransact() methods to allow
passing in lambdas that throw checked exceptions. Previously one has
always to wrap such lambdas in try-and-retrow blocks, which wasn't a
big issue when one can liberally open nested transactions around small
lambdas and keeps the "throwing" part outside the lambda. This becomes a
much bigger hassle when the goal is to eliminate nested transactions and
put as much code as possible within the top-level lambda. As a result,
the transactNoRetry() method now handles checked exceptions by re-throwing
them as runtime exceptions.
2) Changed the name and meaning of the config file field that used to
indicate …
> Refactor transact() related methods.

- release/builder/build.sh
We can't do the trick we do with `gradle-runner.sh`, which is more like "internal", unlike Cloud Build, which is more of "external", because that'd be confusing for potential open source users. So I'm adding a retry here, which I hope should make it work. 
Node.js group is working on the fix - https://github.com/nodejs/build/issues/1993
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/2210)
> Add retry to cloud build node installation

- core/src/main/java/google/registry/tools/server/RefreshDnsForAllDomainsAction.java
- core/src/main/java/google/registry/tools/server/ToolsServerModule.java
- core/src/test/java/google/registry/tools/server/RefreshDnsForAllDomainsActionTest.java
This also adds a targeted QPS as a parameter in case we need to manually bump it up (or down) for some reason without having to make code changes and re-deploy.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/2212)
> Reduce the QPS of the refresh DNS for all domains action

- core/src/main/java/google/registry/config/RegistryConfig.java
- core/src/main/java/google/registry/config/RegistryConfigSettings.java
- core/src/main/java/google/registry/config/files/default-config.yaml
- core/src/main/java/google/registry/request/auth/AuthModule.java
- core/src/main/java/google/registry/request/auth/OidcTokenAuthenticationMechanism.java
- core/src/test/java/google/registry/request/auth/OidcTokenAuthenticationMechanismTest.java
This allows us to switch the proxy to a different client ID without
disrupting the service. This is a temporary measure and will be removed
once the switch is complete.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/2216)
> Add a fallback token verifier

- core/src/main/java/google/registry/request/Response.java
- core/src/main/java/google/registry/request/ResponseImpl.java
- core/src/main/java/google/registry/security/XsrfTokenManager.java
- core/src/main/java/google/registry/ui/server/console/ConsoleApiAction.java
- core/src/main/java/google/registry/ui/server/console/ConsoleUserDataAction.java
- core/src/main/java/google/registry/ui/server/registrar/ConsoleApiParams.java
- core/src/main/java/google/registry/ui/server/registrar/RegistrarConsoleModule.java
- core/src/test/java/google/registry/testing/FakeConsoleApiParams.java
- core/src/test/java/google/registry/testing/FakeResponse.java
- core/src/test/java/google/registry/ui/server/ActionMembershipTest.java
- core/src/test/java/google/registry/ui/server/console/ConsoleUserDataActionTest.java
While working on XSRF protection I realized that we're lacking a better way to handle API request to new console. For instance I never really liked that we used `JsonGetAction` to handle **POST** and GET requests, as well as the fact that we needed to verify `consoleUser` every time and check if the request is GET or POST, etc. On top of that there's no good place where to actually do the XSRF verification. All that prompted me to create a base class that we can use for Console Api requests - `ConsoleApiAction`. For now I've migrated `ConsoleUserDataAction` to work with the new `ConsoleApiAction` and if you're ok with this approach I will continue updating existing endpoints.
- - - …
> Add handler for Console API requests and XSRF token creation and verification

- core/src/main/java/google/registry/env/production/backend/WEB-INF/appengine-web.xml
- core/src/main/java/google/registry/env/production/default/WEB-INF/appengine-web.xml
- core/src/main/java/google/registry/env/production/pubapi/WEB-INF/appengine-web.xml
- core/src/main/java/google/registry/env/production/tools/WEB-INF/appengine-web.xml
- core/src/main/java/google/registry/env/sandbox/backend/WEB-INF/appengine-web.xml
- core/src/main/java/google/registry/env/sandbox/default/WEB-INF/appengine-web.xml
- core/src/main/java/google/registry/env/sandbox/pubapi/WEB-INF/appengine-web.xml
- core/src/main/java/google/registry/env/sandbox/tools/WEB-INF/appengine-web.xml
Java 17 injects unexpected headers to X-Forwarded-For, which causes
issues with validating incoming IP addresses.
This is a partial reversion of #2201. We are still keeping Java 17 in other environment but sandbox and production needs to be able to parse the header to accept incoming EPP connections from registrars. Once we fix it we will re-enable Java 17 in these environment.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/2218)
> Use Java 8 runtime on sandbox and production

- release/schema-deployer/Dockerfile
Flyway 10+ is not compatible with Java 8.
Rollback this change after we upgrade to Java 11.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/2222)
> Pin Flyway tool jar to 9.22.3

- core/src/main/java/google/registry/groups/GmailClient.java
- core/src/test/java/google/registry/groups/GmailClientTest.java
This may help with the billing-team with attached invoices.
This is a standard header that should do no harm.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/2223)
> Add a disposition header to email attachments

- core/src/main/java/google/registry/bsa/DownloadStage.java
- core/src/main/java/google/registry/bsa/persistence/BsaDownload.java
- core/src/main/java/google/registry/bsa/persistence/DownloadSchedule.java
- core/src/main/java/google/registry/bsa/persistence/DownloadScheduler.java
- core/src/test/java/google/registry/bsa/persistence/BsaDownloadTest.java
- core/src/test/java/google/registry/bsa/persistence/DownloadSchedulerTest.java
Adds a `DownloadScheduler` that generates work for the download action.
The scheduler is called during every run of the download cron job and tells the action what to do,
based on the work state stored in the `BsaDownload` table.
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/2209)
> Download scheduler for BSA

- core/src/main/java/google/registry/flows/EppRequestHandler.java
- core/src/main/java/google/registry/flows/TlsCredentials.java
- core/src/main/java/google/registry/tools/ValidateLoginCredentialsCommand.java
- core/src/test/java/google/registry/flows/EppLoginTlsTest.java
- core/src/test/java/google/registry/flows/EppTestCase.java
- core/src/test/java/google/registry/flows/FlowRunnerTest.java
- core/src/test/java/google/registry/flows/TlsCredentialsTest.java
- core/src/test/java/google/registry/flows/session/LoginFlowViaTlsTest.java
- proxy/src/main/java/google/registry/proxy/handler/EppServiceHandler.java
- proxy/src/test/java/google/registry/proxy/TestUtils.java
- util/src/main/java/google/registry/util/ProxyHttpHeaders.java
For reasons unclear at this point, Java 17's servlet implementation on
GAE injects IP addresses (including unroutable private IPs) into the
standard X-Forwarded-For header, which we currently use to embed
registrar IP addresses to check against the allow list. This results in
the server not properly parsing the header and rejecting legitimate
connections.
This PR sets a custom header that should not be interfered with by any
JVM implementation to store the IP address, while maintaining the old
header as a fallback. The proxy will set both headers to allow the
server to gracefully migrate from Java 8 and Java 17 (and potentially
rollback).
Also removed some headers and logic that are not used.
TESTED=deployed both the proxy and nomulus to crash. Verified that EPP login correctly parsed the …
> Add a dedicated IP header to accommodate Java 17 on GAE

- core/src/main/java/google/registry/flows/domain/DomainPricingLogic.java
- core/src/main/java/google/registry/model/tld/label/ReservedList.java
- core/src/test/java/google/registry/flows/domain/DomainCheckFlowTest.java
- core/src/test/resources/google/registry/flows/domain/domain_check_allocationtoken_fee.xml
- core/src/test/resources/google/registry/flows/domain/domain_check_allocationtoken_fee_anchor_response.xml
- core/src/test/resources/google/registry/flows/domain/domain_check_allocationtoken_fee_response.xml
The code as previously written assumed that creation fees would be the same as renewal fees -- this is not the case for anchor tenants, where the renewal fee is always the standard cost for the TLD (instead of any premium cost). This was already handled properly in the actual billing implementation, but we didn't tell the user the right renewal cost in domain checks.
This also removes some warning logs related to nested transactions
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/2238)
> Return the correct renewal fee for anchor tenants in domain checks

- core/src/main/java/google/registry/tools/UpdateOrDeleteAllocationTokensCommand.java
This doesn't fix any issues with dead/livelocks when deleting or updating allocation tokens, but it at least will significantly reduce the time to load the tokens that we'll want to update/delete.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/2244)
> Filter in SQL when updating/deleting alloc tokens

- core/src/main/java/google/registry/persistence/transaction/JpaTransactionManagerImpl.java
This might be the cause of the SQL performance degradation that we are
observing during the recent launch. The change went in a month ago but
there hasn't been enough increase in mutating traffic to make it
problematic until the launch.
Note that presubmits will still run longer, but I think it is an
acceptable compromise to help us identify nested transactions and
refactor them away. Ultimately we will not log but just throw.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/2251)
> Do not log nested transactions in production

- core/src/main/java/google/registry/tmch/NordnUploadAction.java
Currently, a verify action is enqueued every time the upload method
succeeds. Because the upload job is wrapped in a transaction, the
same task will be enqueued again if the transaction retries.
We cannot move the upload method outside the transaction because the
read-upload-write logic needs to be atomic, and the upload part itself
is idempotent (therefore retri-able). We can, however, move the
enqueuing part outside the transaction as we only need to enqueue the
verify task once the transaction succeeds. This should fix the issue
where multiple verify jobs try to hit the same marksdb endpoints,
resulting in 429 (Too Many Requests) errors.
- - - …
> Do not double-enqueue NordnVerifyAction

- core/src/main/java/google/registry/bsa/persistence/BsaDomainRefresh.java
- core/src/main/resources/META-INF/persistence.xml
- core/src/test/java/google/registry/bsa/persistence/BsaDomainRefreshTest.java
- core/src/test/java/google/registry/schema/integration/SqlIntegrationTestSuite.java
- db/src/main/resources/sql/schema/db-schema.sql.generated
Add the BsaDomainRefresh class which tracks the refresh actions.
The refresh actions checks for changes in the set of registered and reserved domains, which are called unblockables to BSA.
Presubmit tests will pass after this week's deployment.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/2250)
> Add the BsaDomainRefresh entity

- core/src/main/java/google/registry/model/registrar/Registrar.java
- core/src/test/java/google/registry/model/registrar/RegistrarTest.java
- core/src/test/java/google/registry/testing/DatabaseHelper.java
This should resolve b/315349245 and prevent reusing ianaId that's already in the system
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/2257)
> Prevent reusing ianaId for real registrars

- proxy/kubernetes/proxy-service.yaml
From our investigation, the Monday night WHOIS storm does not cause any
strain to the backend system. The backend latency metrics are all well within
the limits. The latency measured from the proxy matches observed latency
by the prober, and we see that the "used" CPU is 1.5x of "requested" CPU
during the time when the latency is above the threshold.
Making this change hopefully removes the proxy as the bottleneck and
ameliorate the pages.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/2259)
> Greatly increase the upper limit of proxy instances in production

- core/src/main/java/google/registry/model/EntityYamlUtils.java
- core/src/test/java/google/registry/tools/ConfigureTldCommandTest.java
- core/src/test/resources/google/registry/tools/jpy.yaml
JPY prices do not have cent values, whereas USD prices do. Therefore the Jackson deserializer reads in the prices from the YAML file as a Double object if it is in USD and as an Integer object if it is in JPY. The `MoneyDeserializer` class already handled this issue cleanly because it parses the object into a `MoneyJson` object which indicates that the amount should be parsed as a BigDecimal object. However, the `TimedTransitionProperty<Money>` deserializer was failing since it was attempting to cast the money value to a double which would fail when the value was an Integer for JPY TLDs. 
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/2258)
> Add type conversion to TimedTransitionProperty<Money> deserializer to handle JPY currency

- core/src/main/java/google/registry/rdap/UpdateRegistrarRdapBaseUrlsAction.java
- core/src/main/java/google/registry/request/UrlConnectionUtils.java
Thanks for the hint with GZIP, I naturally assumed the response was already successfully decoded, since the header was present for a quite some time now. 
Tested in alpha, job succeeded
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/2269)
> Add ICANN csv response GZIP decoding

- core/src/nonprod/java/google/registry/tools/DumpGoldenSchemaCommand.java
- core/src/test/java/google/registry/tools/params/PathParameterTest.java
We've had 3 blockers for kokoro ubuntu update which are now resolved and we can move forward with kokoro os update:
1. missing dependency - fixed separately in kokoro config
2. DumpGoldenSchemaCommandTest failure - this apparently is not new and has been happening in GCP Cloud Build docker where it'd been simply disabled (See https://cs.opensource.google/nomulus/nomulus/+/master:core/build.gradle;l=49) . I've found a way to make it work, which I will later enable in CB as well after this runs well
3. PathParameterTest failures - Pretty much the same story as 2 - it's been failing on GCP Cloud Build docker where the entire test suite has been disabled. My change disables only 2 tests affected test.
- - - …
> Add support for Ubuntu20 on kokoro

- core/src/main/java/google/registry/bsa/UploadBsaUnavailableDomainsAction.java
- core/src/main/java/google/registry/env/alpha/default/WEB-INF/cloud-scheduler-tasks.xml
Also fixes the action taken in the case where zero unavailable domains are found, and temporarily changes over to using the primary DB (because the replica transaction was timing out at 30 seconds on large databases). I'll switch this over to use batching and move it back to replica afterwards, but this should unblock us temporarily.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/2280)
> Add a cron schedule for the BSA upload unavailable domains task

- core/src/main/java/google/registry/bsa/UploadBsaUnavailableDomainsAction.java
- core/src/test/resources/google/registry/module/bsa/bsa_routing.txt
Apparently Google Cloud Scheduler can only do GET, not POST, for some reason.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/2287)
> Make the BSA upload unvailable domains task work with HTTP GET as well

- core/src/main/java/google/registry/bsa/BsaDiffCreator.java
- core/src/main/java/google/registry/bsa/BsaDownloadAction.java
- core/src/test/java/google/registry/bsa/BsaDiffCreatorTest.java
- core/src/test/java/google/registry/bsa/BsaDownloadFunctionalTest.java
- core/src/test/java/google/registry/bsa/persistence/BsaLabelUtilsTest.java
- core/src/test/java/google/registry/bsa/persistence/BsaTestingUtils.java
- core/src/test/java/google/registry/bsa/persistence/DomainRefresherTest.java
- core/src/test/java/google/registry/flows/CheckApiActionTest.java
- core/src/test/java/google/registry/flows/domain/DomainCreateFlowTest.java
- core/src/test/java/google/registry/whois/WhoisActionTest.java
- core/src/test/java/google/registry/whois/WhoisHttpActionTest.java
Fixed the bug that retains deleted BSA labels in the database.
Added a few simple end-to-end tests for BSA download.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/2286)
> Remove deleted BSA labels from database

- core/src/main/java/google/registry/tools/ConfigureTldCommand.java
- core/src/test/java/google/registry/tools/ConfigureTldCommandTest.java
- core/src/test/resources/google/registry/tools/idns.yaml
It is necessary to define these flags in a deployment before merging go/r3pr/2273 in order to prevent breaking the exisitng TLD syncing and entity presubmit testing that has already been enabled.  
The --break_glass flag is now a Boolean parameter instead of a boolean to allow it to be used to also turn off break glass mode when it is set to false.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/2277)
> Define the --build_environment flag and change --break_glass flag to a Boolean type

- core/src/main/java/google/registry/bsa/UploadBsaUnavailableDomainsAction.java
- core/src/test/java/google/registry/bsa/UploadBsaUnavailableDomainsActionTest.java
This also moves it back to the replica transaction manager now that it shouldn't be timing out its queries.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/2282)
> Add batching to BSA unavailable domains list generation

- core/src/main/java/google/registry/env/production/default/WEB-INF/cloud-scheduler-tasks.xml
- core/src/main/java/google/registry/env/sandbox/default/WEB-INF/cloud-scheduler-tasks.xml
This is the job that updates the unblockable domains according to recent changes in domain registration and reservation.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/2290)
> Add bsa-refresh cron job to sandbox and prod

- core/src/main/java/google/registry/env/production/backend/WEB-INF/appengine-web.xml
- core/src/main/java/google/registry/env/production/bsa/WEB-INF/appengine-web.xml
- core/src/main/java/google/registry/env/production/default/WEB-INF/appengine-web.xml
- core/src/main/java/google/registry/env/production/pubapi/WEB-INF/appengine-web.xml
- core/src/main/java/google/registry/env/production/tools/WEB-INF/appengine-web.xml
- core/src/main/java/google/registry/env/sandbox/backend/WEB-INF/appengine-web.xml
- core/src/main/java/google/registry/env/sandbox/bsa/WEB-INF/appengine-web.xml
- core/src/main/java/google/registry/env/sandbox/default/WEB-INF/appengine-web.xml
- core/src/main/java/google/registry/env/sandbox/pubapi/WEB-INF/appengine-web.xml
- core/src/main/java/google/registry/env/sandbox/tools/WEB-INF/appengine-web.xml
The blocking issue is fixed in
https://github.com/google/nomulus/pull/2224.
Java 8 support is being deprecated on 2024-01-31 and no further deployment is
possible afterwards without exception:
https://cloud.google.com/appengine/docs/legacy/standard/java/deprecations
We have been using Java 17 on alpha/crash/qa for several months and have
not oberved any other blocking issue other than possible missing email
attachements, which is being mitigated by including a link to the
attachments saved in GCS.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/2296)
> Use Java 17 runtime on sandbox and production

- core/src/main/java/google/registry/bsa/BsaRefreshAction.java
- core/src/main/java/google/registry/bsa/BsaTransactions.java
The http payload for the report of new unblockable domains s was logged to the wrong file.
This log is for verification and troubleshooting purpose. It does not affect the BSA side.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/2297)
> Fix typo in BsaRefreshAction

- core/src/main/java/google/registry/tools/UpdatePremiumListCommand.java
- core/src/main/java/google/registry/tools/UpdateReservedListCommand.java
- core/src/test/java/google/registry/tools/UpdatePremiumListCommandTest.java
- core/src/test/java/google/registry/tools/UpdateReservedListCommandTest.java
Added a dry-run tag for presubmit tests
Added early exit behavior when there are no new changes to the list
Added a new --build_environment tag to be used to indicate command runs from build tools. This tag was also added to UpdatePremiumListCommand. Once this new tag is deployed, and break glass behavior is added, these commands will be modified to prevent runs on the command line in the production environment unless the --build_environment or --break_glass flag is used.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/2292)
> Add some updates to UpdateReservedListCommand to facilitate internal config presubmits and syncing

- core/src/main/java/google/registry/tools/ConfigureTldCommand.java
- core/src/test/java/google/registry/tools/ConfigureTldCommandTest.java
When running the configureTldCommand in Production, require either a break glass flag or a build-environment flag. The --build_environment flag should not be used on the command line by a human user and should be reserved for use by build tools such as Kokoro and Cloud Build.
This PR cannot be merged until after the changes in go/r3pr/2277 have been deployed.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/2273)
> Require the --break_glass or --build_environment flag in production for configureTldCommand

- build.gradle
We should not assume org.gradle.java.home to exist on kokoro or GCB.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/2305)
> Make the formatting tasks work with Java 17 (take 2)

- core/src/main/java/google/registry/bsa/BsaRefreshAction.java
- core/src/test/java/google/registry/bsa/BsaRefreshFunctionalTest.java
We thought that as a way to verify the refresh job is running, browsing the GCS bucket with empty files is easier than quering the DB or go to GCP logging dashboard, but there are too many of them to be useful.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/2307)
> Stop saving BSA empty refresh changes

- core/src/main/java/google/registry/tools/CreateOrUpdateRegistrarCommand.java
- core/src/test/java/google/registry/tools/UpdateRegistrarCommandTest.java
The fallback should only apply on creates, not on updates, otherwise it can override an existing value for the email address when only the referral email should be what's updated.
This fixes a bug introduced back in commit in 0ead4f8d9d19b938a7f959a70df41cafd9b5c966.
BUG= http://b/322026165
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/2300)
> Don't override existing registrar email address when setting referral email

- core/src/main/java/google/registry/bsa/UploadBsaUnavailableDomainsAction.java
Query size is borderline too-large for the replica.
At 50000, about 2 out of 30 took more than 30 seconds and were aborted. Lower to 40000 and we will keep monitoring the executions.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/2313)
> Reduce query batch size for BSA unavailables

- core/src/main/java/google/registry/flows/domain/DomainCheckFlow.java
- core/src/main/java/google/registry/flows/domain/DomainCreateFlow.java
- core/src/main/java/google/registry/flows/domain/DomainFlowUtils.java
- core/src/main/java/google/registry/flows/domain/DomainRenewFlow.java
- core/src/main/java/google/registry/flows/domain/token/AllocationTokenFlowUtils.java
- core/src/main/java/google/registry/model/domain/token/AllocationToken.java
- core/src/main/java/google/registry/tools/DeleteAllocationTokensCommand.java
- core/src/test/java/google/registry/flows/domain/DomainCheckFlowTest.java
- core/src/test/java/google/registry/flows/domain/DomainCreateFlowTest.java
- core/src/test/java/google/registry/model/domain/token/AllocationTokenTest.java
- core/src/test/java/google/registry/tools/GenerateAllocationTokensCommandTest.java
Add a new type to allow creation of domains blocked by BSA.
Except for the BSA semantics, the new type behaves exactly like SINGLE_USE.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/2319)
> Add REGISTER_BSA allocation type

- core/src/main/java/google/registry/flows/custom/DomainRenewFlowCustomLogic.java
- core/src/main/java/google/registry/model/server/Lock.java
This is the start of a long and low priority migration, but for now I wanted to do a couple of them just to see what it looks like.
This also demonstrates the pattern for use of an @AutoBuilder to replace an @AutoValue.Builder. See https://github.com/google/auto/blob/main/value/userguide/records.md#builders for full details on that.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/2327)
> Convert a couple of @AutoValue classes to Java 15 Records

- core/src/main/java/google/registry/beam/common/RegistryJpaIO.java
- core/src/main/java/google/registry/bsa/BsaTransactions.java
- core/src/main/java/google/registry/bsa/persistence/LabelDiffUpdates.java
- core/src/main/java/google/registry/flows/FlowRunner.java
- core/src/main/java/google/registry/persistence/transaction/JpaTransactionManagerImpl.java
- core/src/main/java/google/registry/persistence/transaction/TransactionManager.java
- core/src/main/java/google/registry/tools/server/RefreshDnsForAllDomainsAction.java
- core/src/test/java/google/registry/persistence/transaction/JpaTransactionManagerImplTest.java
This makes the callsites look neater, as the work to execute itself is often a many line lambda, whereas the transaction isolation level is not more than a couple dozen characters.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/2329)
> Make transaction isolation level the first argument to transact()

- core/src/main/java/google/registry/flows/session/LoginFlow.java
- core/src/main/java/google/registry/model/console/User.java
- core/src/main/java/google/registry/model/registrar/Registrar.java
- core/src/main/java/google/registry/model/registrar/RegistrarPoc.java
- core/src/main/java/google/registry/ui/server/registrar/RegistryLockPostAction.java
- core/src/test/java/google/registry/flows/session/LoginFlowTestCase.java
- core/src/test/java/google/registry/ui/server/registrar/RegistryLockPostActionTest.java
- util/src/main/java/google/registry/util/PasswordUtils.java
- util/src/test/java/google/registry/util/PasswordUtilsTest.java
We introduced Scrypt as the default password hashing algorithm in
November 2023 and have been auto-converting saved hashes whenever a
successful EPP login or registry lock/unlock request is processed.
We will send comms to registrars to inform them the upcoming removal of
SHA256 support and urge them to log in at least once before the change.
Otherwise, they will need to contact support to reset the password out of
band after the change.
This PR will NOT be submitted until comms are out and the effective date
is immediate.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/2310)
> Remove SHA256 as a supported password hashing algorithm

- core/src/main/java/google/registry/tools/RegistryCli.java
This reverts commit 64f59712758941a35b000e81642966dc7e6473ad.
The catch block is too broad and most of the times the errors caught is
because `command.run()` failed and it had nothing to do with getting
the transaction manager. The `runCommand` method is already wrapped in a try
block that checks for `LoginRequiredException` and gives the appropriate
error message.
We need to re-assess the situation when the next time we encounter a
login issue that did not trigger `LoginRequiredException`. A blanket try
catch block is not the solution and only makes the situation more
confusing.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/2342)
> Revert "Include a better error message to debug nomulus tool not working (#2275)"

- core/src/main/java/google/registry/batch/BatchModule.java
- core/src/main/java/google/registry/batch/DeleteLoadTestDataAction.java
- core/src/main/java/google/registry/batch/DeleteProberDataAction.java
- core/src/main/java/google/registry/batch/ExpandBillingRecurrencesAction.java
- core/src/main/java/google/registry/batch/WipeOutContactHistoryPiiAction.java
- core/src/main/java/google/registry/flows/EppToolAction.java
- core/src/main/java/google/registry/module/RegistryComponent.java
- core/src/main/java/google/registry/module/RegistryServlet.java
- core/src/main/java/google/registry/module/RequestComponent.java
- core/src/main/java/google/registry/request/RequestHandler.java
- core/src/main/java/google/registry/request/RequestModule.java
- core/src/main/java/google/registry/request/RequestParameters.java
- core/src/main/java/google/registry/tools/server/ToolsServerModule.java
- core/src/main/java/google/registry/ui/server/console/ConsoleDomainGetAction.java
- core/src/main/java/google/registry/ui/server/registrar/ConsoleOteSetupAction.java
- core/src/main/java/google/registry/ui/server/registrar/ConsoleRegistrarCreatorAction.java
- core/src/main/java/google/registry/ui/server/registrar/ConsoleUiAction.java
- core/src/main/java/google/registry/ui/server/registrar/RegistrarConsoleModule.java
- core/src/main/java/google/registry/ui/server/registrar/RegistryLockGetAction.java
- core/src/test/java/google/registry/request/RequestHandlerTest.java
- jetty/Dockerfile
- jetty/build.gradle
- jetty/src/main/jetty-base/resources/jetty-logging.properties
- jetty/src/main/jetty-base/start.d/ee8-deploy.ini
- jetty/src/main/jetty-base/start.d/http.ini
- jetty/src/main/jetty-base/start.d/server.ini
- jetty/src/main/webapp/WEB-INF/web.xml
- settings.gradle
This PR creates a unified RegistryServlet that will serve all
non-console traffic. It also creates a jetty subproject that allows one
to run Nomulus on top of a standard Jetty 12 runtime.
`./gradlew :jetty:stage` will create a jetty base folder at
`jetty/build/jetty-base` where one is able spin up a local Nomulus server
by running the following command inside the folder:
```bash
java -jar ${JETTY_HOME}/start.jar
```
`JETTY_HOME` is a folder where the [Jetty runtime](https://repo1.maven.org/maven2/org/eclipse/jetty/jetty-home/12.0.6/jetty-home-12.0.6.zip) is located.
This PR also adds a Gradle task to create a Nomulus image based on the
official Jetty image:
```bash
./gradlew :jetty:buildNomulusImage
```
- - - …
> Set up a unified registry servlet for Jetty

- config/presubmits.py
- core/src/main/java/google/registry/model/billing/BillingRecurrence.java
- core/src/test/java/google/registry/batch/CheckBulkComplianceActionTest.java
- core/src/test/java/google/registry/bsa/BsaDownloadFunctionalTest.java
- core/src/test/java/google/registry/bsa/api/JsonSerializationsTest.java
- core/src/test/java/google/registry/flows/EppLoginTlsTest.java
- core/src/test/java/google/registry/groups/GmailClientTest.java
- core/src/test/java/google/registry/model/billing/BillingBaseTest.java
- core/src/test/java/google/registry/model/domain/DomainSqlTest.java
- core/src/test/java/google/registry/model/domain/token/BulkPricingPackageTest.java
- core/src/test/java/google/registry/privileges/secretmanager/FakeSecretManagerClient.java
- core/src/test/java/google/registry/tools/ConfigureTldCommandTest.java
- core/src/test/java/google/registry/tools/CreateBulkPricingPackageCommandTest.java
- core/src/test/java/google/registry/tools/RenewDomainCommandTest.java
- core/src/test/java/google/registry/tools/UpdateBulkPricingPackageCommandTest.java
Also fixed a flaky test where it depends on the current date. On a leap
day, now + 1 year - 1 year results in 2/28 instead of 2/29.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/2343)
> Do not use shaded dependencies from testcontainers

- release/builder/build.sh
Debian 11 repo does not have Java 21. Revert to Java 17 for now so we
can build the builder image, which is needed for release.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/2351)
> Temporarily revert builder to Java 17

- core/src/main/java/google/registry/bsa/BsaValidateAction.java
- core/src/main/java/google/registry/bsa/persistence/DownloadScheduler.java
- core/src/main/java/google/registry/bsa/persistence/Queries.java
- core/src/main/java/google/registry/env/common/bsa/WEB-INF/web.xml
- core/src/main/java/google/registry/env/production/default/WEB-INF/cloud-scheduler-tasks.xml
- core/src/main/java/google/registry/module/RequestComponent.java
- core/src/main/java/google/registry/module/bsa/BsaRequestComponent.java
- core/src/test/java/google/registry/bsa/BsaValidateActionTest.java
- core/src/test/java/google/registry/bsa/persistence/QueriesTest.java
- core/src/test/resources/google/registry/module/bsa/bsa_routing.txt
Add the BsaValidateAction class with a first check (for inconsistency between downloaded and persisted labels).
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/2356)
> Add BSA validation job

- core/src/main/java/google/registry/persistence/PersistenceComponent.java
- core/src/main/java/google/registry/persistence/PersistenceModule.java
- core/src/main/java/google/registry/persistence/transaction/TransactionManagerFactory.java
- jetty/Dockerfile
- jetty/build.gradle
- jetty/src/main/jetty-base/webapps/nomulus.xml
- jetty/start.sh
Chose the default transaction manager based on RegistryEnvironment. This
makes it possible to run nomulus on Jetty locally. Tested with the
following:
```bash
./gradle :jetty:run -Penvironment=alpha
curl http://localhost:8080/beta.app
```
The docker image is also updated to take an argument that specifies the
environment. It runs locally as well but the container doesn't get
access to locally stored credentials, so it fails to initialize the
transaction manager.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/2349)
> Make nomulus work locally

- config/nom_build.py
- core/src/main/java/google/registry/persistence/transaction/TransactionManagerFactory.java
- core/src/main/java/google/registry/tools/RegistryCli.java
Also only caches/resets the original TM when in unit tests (TBT I'm not so sure
that even this is necessary as we don't seem to call the tool from tests
that often. There is only ShellCommandTest that calls the run() function
in RegistryCli and we could just put these tests in fragileTest and make
them run sequentially and fork every time to get around issue with
inference).
The issue with caching is that it tries to first create the to-be-cached
TM, and when the environment given is prod/sandbox/... It will try to
retrieve SQL credentials from prod/sandbox/... secret manager. This
works fine locally as we all have access to prod/sandbox/..., but fails
in Cloud Build jobs such as sync-db-objects where it provides it own
credential that has direct SQL access, but not access to …
> Fix nomulus tool when the environment is localhost

- core/src/main/java/google/registry/bsa/BsaEmailSender.java
- core/src/main/java/google/registry/bsa/BsaRefreshAction.java
- core/src/main/java/google/registry/bsa/BsaValidateAction.java
- core/src/main/java/google/registry/bsa/UploadBsaUnavailableDomainsAction.java
- core/src/main/java/google/registry/module/bsa/BsaComponent.java
- core/src/test/java/google/registry/bsa/BsaRefreshActionTest.java
- core/src/test/java/google/registry/bsa/BsaRefreshFunctionalTest.java
- core/src/test/java/google/registry/bsa/BsaValidateActionTest.java
- core/src/test/java/google/registry/bsa/UploadBsaUnavailableDomainsActionTest.java
- core/src/test/java/google/registry/bsa/persistence/BsaTestingUtils.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/2368)
> Add email notification of BSA job status

- core/src/main/java/google/registry/bsa/BsaTransactions.java
- core/src/main/java/google/registry/bsa/persistence/Queries.java
- core/src/main/java/google/registry/persistence/transaction/JpaTransactionManager.java
- core/src/main/java/google/registry/persistence/transaction/JpaTransactionManagerImpl.java
- core/src/main/java/google/registry/persistence/transaction/TransactionManager.java
Removed the deprecation mark as it is natural to expose methods related
to a transaction like getting the entity manager or checking if one is
in a transaction through the transaction manager interface.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/2366)
> Refactor some code related to the transaction manager

- core/src/main/java/google/registry/model/tld/label/ReservedList.java
- core/src/test/java/google/registry/tools/server/ListReservedListsActionTest.java
- db/src/main/resources/sql/schema/db-schema.sql.generated
- gradle.properties
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/2369)
> Drop should publish field from ReservedList entity

- config/presubmits.py
- core/src/main/java/google/registry/config/DelegatedCredentials.java
- core/src/main/java/google/registry/flows/certs/CertificateChecker.java
- core/src/main/java/google/registry/tmch/TmchCertificateAuthority.java
- core/src/main/java/google/registry/tools/CreateOrUpdateBulkPricingPackageCommand.java
- core/src/test/java/google/registry/module/RequestComponentTest.java
- core/src/test/java/google/registry/testing/CloudTasksHelper.java
- core/src/test/java/google/registry/tools/CreateBulkPricingPackageCommandTest.java
- core/src/test/java/google/registry/tools/UpdateBulkPricingPackageCommandTest.java
- networking/src/test/java/google/registry/networking/handler/SslClientInitializerTest.java
- networking/src/test/java/google/registry/networking/handler/SslInitializerTestUtils.java
- networking/src/test/java/google/registry/networking/handler/SslServerInitializerTest.java
- util/src/main/java/google/registry/util/SelfSignedCaCertificate.java
- util/src/main/java/google/registry/util/X509Utils.java
There is one remaining instance in JpaTransactionManagerImpl that cannot
be removed because DetachingTypedQuery is implementing TypedQuery, which has
a method that expectred java.util.Date.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/2373)
> Remove java.util.Date

- core/src/main/java/google/registry/bsa/BsaValidateAction.java
- core/src/main/java/google/registry/bsa/persistence/Queries.java
- core/src/main/java/google/registry/config/RegistryConfig.java
- core/src/main/java/google/registry/config/RegistryConfigSettings.java
- core/src/main/java/google/registry/config/files/default-config.yaml
- core/src/test/java/google/registry/bsa/BsaValidateActionTest.java
Unblockable domains may become blockable due to deregistration or removal from the reserved list. The BSA refresh job is responsible for removing them from the database. This PR verifies that the refreshes are correct.
Note that recent changes since last refresh are not reflected in the result, and inconsistency due to recent deregistrations are ignored. Changes in reserved status or IDN validity are not timestamped, therefore we cannot ignore recent inconsistencies. However, these changes are rare.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/2381)
> Verify unblockables are truly unblockable

- core/src/main/java/google/registry/bsa/BsaValidateAction.java
- core/src/main/java/google/registry/bsa/persistence/Queries.java
- core/src/test/java/google/registry/bsa/BsaValidateActionTest.java
- core/src/test/java/google/registry/bsa/persistence/QueriesTest.java
All unblockable domains created before the last refresh run should be reported as unblockable (registered).
All reserved domains that are not registered should be reported as unblockable (reserved). Note that transient errors may be reported for newly added reserved domains since we do not maintain update time for when a reserved label is associated with a TLD. However, this scenario is extremely rare in operations.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/2394)
> Check for missing BSA unblockable domains

- core/src/main/java/google/registry/bsa/BsaValidateAction.java
- core/src/main/java/google/registry/env/production/bsa/WEB-INF/appengine-web.xml
- core/src/main/java/google/registry/env/sandbox/bsa/WEB-INF/appengine-web.xml
- core/src/test/java/google/registry/bsa/BsaValidateActionTest.java
As a read-only action that tolerates inconsistency due to recent changes, locking is unnecessary. This should help with the lock contention we are observing.
Also reduces the number of VM instances provisioned for BSA and increase the idle timeout. This should reduce invocation delay. Longer delay may cause Cloud Scheduler to report a cron job as failure on its dashboard even though the job succeeds.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/2399)
> Run BSA Validate without lock

- jetty/build.gradle
- jetty/deploy-nomulus-for-env.sh
- jetty/kubernetes/nomulus-deployment.yaml
- jetty/kubernetes/nomulus-gateway.yaml
- jetty/kubernetes/nomulus-service.yaml
- proxy/build.gradle
- proxy/src/main/java/google/registry/proxy/EppProtocolModule.java
- proxy/src/main/java/google/registry/proxy/HttpsRelayProtocolModule.java
- proxy/src/main/java/google/registry/proxy/Protocol.java
- proxy/src/main/java/google/registry/proxy/ProxyConfig.java
- proxy/src/main/java/google/registry/proxy/ProxyModule.java
- proxy/src/main/java/google/registry/proxy/WhoisProtocolModule.java
- proxy/src/main/java/google/registry/proxy/config/default-config.yaml
- proxy/src/test/java/google/registry/proxy/ProtocolModuleTest.java
This PR makes changes to the proxy so that it is able to relay WHOIS/EPP traffic to localhost via plain HTTP. This allows us to package both the proxy and nomulus image in the same pod and bypass the need to  send the packets across the network.
The functionality is tested on local minikube clusters by forwarding the service to a local port and sending HTTP and WHOIS traffic to the forwarded port. EPP is untested as we don't have a readily available local EPP client, but the same logic follows.
Exposing the service via external load balancer is not yet tested.
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/2389)
> Add nomulus deployment and service manifests

- core/src/main/java/google/registry/export/sheet/SheetSynchronizer.java
- core/src/test/java/google/registry/export/sheet/SheetSynchronizerTest.java
The existing behavior was to ignore bad header names, in a way that was counter-intuitive as a user of the Google Sheet. If a header name was bad (which could just be someone accidentally changing it not realizing it needs to correspond exactly to the name of the field on the Java object), then all of the data in that column was just silently left as-is and never updated. This led to gradually worsening sync and offset shift errors over time.
Now, it will write out an error message into every single cell in the bad column, so it's clear that the column name is wrong and does not correspond to any actual data in the DB.
BUG=http://b/332336068
- - - …
> Handle bad header names in registrar sheet syncing action

- core/src/main/java/google/registry/dns/DnsUtils.java
This table can be small at times, when PSQL may use table scan in queries by keys. At the SERIALIZABLE isolation level, updates to unrelated rows may conflict due to this `optimization`.
Lower the isolation level to repeatable read.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/2428)
> Avoid contention over the RefreshDnsRequest table

- core/src/main/java/google/registry/model/domain/RegistryLock.java
- core/src/main/java/google/registry/module/RequestComponent.java
- core/src/main/java/google/registry/module/frontend/FrontendRequestComponent.java
- core/src/main/java/google/registry/request/RequestParameters.java
- core/src/main/java/google/registry/ui/server/console/ConsoleRegistryLockAction.java
- core/src/main/java/google/registry/ui/server/registrar/RegistryLockPostAction.java
- core/src/test/java/google/registry/ui/server/console/ConsoleRegistryLockActionTest.java
- core/src/test/java/google/registry/ui/server/console/ConsoleUserDataActionTest.java
- core/src/test/resources/google/registry/module/frontend/frontend_routing.txt
- core/src/test/resources/google/registry/module/routing.txt
This handles both GET and POST requests. For POST requests it doesn't actually change anything about the domains because we will need to add a verification action (this will be done in a future PR).
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/2411)
> Add a separate RegistryLock action for the console

- console-webapp/src/app/home/home.component.html
- console-webapp/src/app/resources/resources.component.html
- console-webapp/src/app/settings/security/security.component.html
These probably aren't perfect but they seemed to make sense given the old console. Nothing major.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/2436)
> Change a few wording bits in the console

- appengine_war.gradle
- build.gradle
- console-webapp/.gitignore
- console-webapp/build.gradle
- console-webapp/package-lock.json
- console-webapp/package.json
- console-webapp/src/app/shared/services/backend.service.ts
- console-webapp/staged/app.yaml
- console-webapp/staged/package.json
- console-webapp/staged/server.js
- core/src/main/java/google/registry/env/common/default/WEB-INF/dispatch.xml
- release/build_nomulus_for_env.sh
- release/cloudbuild-nomulus.yaml
This removes the console from being packed with default service war and creates a new node.js service named.
Integrated with local deployment via `./gradlew deploy` as well as spinnaker. Gradlew deployment tested on alpha and qa, spinnaker deployment tested on crash env
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/2433)
> Create node.js console service

- jetty/build.gradle
This is a follow up on a last comment in https://github.com/google/nomulus/pull/2433.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/2439)
> Update jetty's console build path

- core/src/main/java/google/registry/tools/DomainLockUtils.java
- core/src/main/java/google/registry/ui/server/console/ConsoleRegistryLockAction.java
- core/src/main/java/google/registry/ui/server/registrar/RegistryLockPostAction.java
- core/src/main/java/google/registry/ui/server/registrar/RegistryLockVerifyAction.java
- core/src/test/java/google/registry/tools/DomainLockUtilsTest.java
- core/src/test/java/google/registry/tools/UnlockDomainCommandTest.java
- core/src/test/java/google/registry/ui/server/console/ConsoleRegistryLockActionTest.java
- core/src/test/java/google/registry/ui/server/registrar/RegistryLockPostActionTest.java
- core/src/test/java/google/registry/ui/server/registrar/RegistryLockVerifyActionTest.java
The user, on the front end, should not be required to provide whether or not they're trying to verify a lock or an unlock. They should only need the verification code. We can inspect the lock object itself (and the domain in question) to see whether or not we're verifying a lock or an unlock.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/2434)
> Refactor some registry lock verification code

- core/src/main/java/google/registry/ui/server/console/ConsoleApiAction.java
- core/src/main/java/google/registry/ui/server/console/ConsoleDomainListAction.java
- core/src/main/java/google/registry/ui/server/console/ConsoleDumDownloadAction.java
- core/src/main/java/google/registry/ui/server/console/ConsoleEppPasswordAction.java
- core/src/main/java/google/registry/ui/server/console/ConsoleRegistryLockAction.java
- core/src/main/java/google/registry/ui/server/console/RegistrarsAction.java
- core/src/main/java/google/registry/ui/server/console/settings/ContactAction.java
- core/src/main/java/google/registry/ui/server/console/settings/SecurityAction.java
- core/src/main/java/google/registry/ui/server/console/settings/WhoisRegistrarFieldsAction.java
There are a bunch of cases where we want common exception handling and it's annoying to have to deal with the common "set failed response and make sure to return" a bunch of times.
This allows us to break up request methods more easily, since we can now often throw exceptions that will break all the way back up to ConsoleApiAction. Previously, any error handling had to exist in the primary handler method so it could return.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/2443)
> Refactor common exception handling in ConsoleApiAction

- console-webapp/package-lock.json
- console-webapp/src/app/billingInfo/billingInfo.component.ts
- console-webapp/src/app/registrar/registrarsTable.component.scss
- console-webapp/src/app/settings/contact/contact.component.ts
- console-webapp/src/app/settings/whois/whois.component.ts
- console-webapp/src/styles.scss
- core/src/main/java/google/registry/ui/server/console/ConsoleEppPasswordAction.java
- core/src/main/java/google/registry/ui/server/registrar/RegistrarConsoleModule.java
- core/src/test/java/google/registry/ui/server/console/ConsoleEppPasswordActionTest.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/2445)
> Fix console EPP password form, minor adjustments

- core/src/main/java/google/registry/ui/server/console/ConsoleUpdateRegistrarAction.java
- core/src/test/java/google/registry/ui/server/console/ConsoleUpdateRegistrarActionTest.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/2452)
> Add console backend for editing registrar

- config/presubmits.py
- core/src/main/java/google/registry/config/RegistryConfig.java
- core/src/main/java/google/registry/config/RegistryConfigSettings.java
- core/src/main/java/google/registry/config/files/default-config.yaml
- core/src/main/java/google/registry/env/common/tools/WEB-INF/web.xml
- core/src/main/java/google/registry/module/RequestComponent.java
- core/src/main/java/google/registry/module/tools/ToolsRequestComponent.java
- core/src/main/java/google/registry/tools/CreateUserCommand.java
- core/src/main/java/google/registry/tools/DeleteUserCommand.java
- core/src/main/java/google/registry/tools/server/ToolsServerModule.java
- core/src/main/java/google/registry/tools/server/UpdateUserGroupAction.java
- core/src/test/java/google/registry/export/ExportPremiumTermsActionTest.java
- core/src/test/java/google/registry/export/ExportReservedTermsActionTest.java
- core/src/test/java/google/registry/export/SyncGroupMembersActionTest.java
- core/src/test/java/google/registry/tools/CreateUserCommandTest.java
- core/src/test/java/google/registry/tools/DeleteUserCommandTest.java
- core/src/test/java/google/registry/tools/server/CreateGroupsActionTest.java
- core/src/test/java/google/registry/tools/server/UpdateUserGroupActionTest.java
- core/src/test/resources/google/registry/module/routing.txt
- core/src/test/resources/google/registry/module/tools/tools_routing.txt
If a console user group is defined in the config file, we will add/remove the user to/from the group during user creation/deletion, instead of granting/removing the necessary IAP roles to/from the user.
This makes it easy when IAM roles are managed externally (e. g. under latchkey) where individual changes made to IAM will be rolled back, if not also made to latchkey. This way we can simply grant the role to the group via an one-time config change to latchkey, and rely on a user's membership in the group to determine if IAP would all or deny the user's access.
Also forbid mocking of `Response` in tests. We should use the fake implementation instead.
TESTED=tested both individual and group IAP behavior on crash. Verified that email addresses are added/removed to/from the group.
This change …
> Add the ability to add/remove console users from a Google Group

- util/src/main/java/google/registry/util/GcpJsonFormatter.java
- util/src/test/java/google/registry/util/GcpJsonFormatterTest.java
GKE now displays log messages correctly. There is no need for an extra
leading newline, which now results in a useless blank line for each log
entry in Log Explorer.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/2454)
> Removing leading newline from GKE log messages

- console-webapp/src/app/domains/domainList.component.ts
- core/src/test/java/google/registry/server/Fixture.java
When the registrar changes we should reset the page and the total results to 0 (since we haven't loaded them yet)
https://b.corp.google.com/issues/343193698
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/2456)
> Fully reset domain-list page on registrar change

- core/src/main/java/google/registry/flows/domain/DomainPricingLogic.java
- core/src/test/java/google/registry/flows/EppTestCase.java
- core/src/test/java/google/registry/flows/domain/DomainCheckFlowTest.java
- core/src/test/java/google/registry/flows/domain/DomainCreateFlowTest.java
- core/src/test/java/google/registry/flows/domain/DomainInfoFlowTest.java
- core/src/test/java/google/registry/flows/domain/DomainPricingLogicTest.java
- core/src/test/resources/google/registry/flows/domain/domain_check_eap_fee_response_v06.xml
- core/src/test/resources/google/registry/flows/domain/domain_check_fee_response_default_token_v06.xml
- core/src/test/resources/google/registry/flows/domain/domain_check_fee_response_v06.xml
- core/src/test/resources/google/registry/flows/domain/domain_create_eap_fee.xml
- core/src/test/resources/google/registry/flows/domain/domain_create_fee.xml
- core/src/test/resources/google/registry/flows/domain/domain_create_fee_defaults.xml
- core/src/test/resources/google/registry/flows/domain/domain_create_response_eap_fee.xml
- core/src/test/resources/google/registry/flows/domain_create_eap_fee.xml
- core/src/test/resources/google/registry/flows/domain_create_response_eap_fee.xml
- core/src/test/resources/google/registry/flows/domain_delete_response_fee.xml
From the second year on, charge the renewal price.
See b/322833077
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/2446)
> Change billing for multi-year domain creation

- console-webapp/src/app/domains/domainList.component.html
- console-webapp/src/app/domains/domainList.component.scss
- console-webapp/src/app/domains/domainList.component.ts
This means that they'll stick around even while we're loading domains from the server.
This also adds a loading spinner.
https://b.corp.google.com/issues/343213150
https://b.corp.google.com/issues/343211773
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/2457)
> Move domain-list search+download outside of loading bar

- core/src/main/java/google/registry/flows/FlowUtils.java
- core/src/main/java/google/registry/flows/contact/ContactCreateFlow.java
- core/src/main/java/google/registry/flows/domain/DomainCreateFlow.java
- core/src/main/java/google/registry/flows/host/HostCreateFlow.java
- core/src/main/java/google/registry/model/Buildable.java
- core/src/main/java/google/registry/model/annotations/IdAllocation.java
- core/src/main/java/google/registry/model/domain/GracePeriod.java
- core/src/main/java/google/registry/model/domain/secdns/DomainDsDataHistory.java
- core/src/main/java/google/registry/persistence/transaction/IdService.java
- core/src/main/java/google/registry/persistence/transaction/JpaTransactionManagerImpl.java
- core/src/main/java/google/registry/persistence/transaction/ReplicaDbIdService.java
- core/src/main/java/google/registry/persistence/transaction/TransactionManager.java
- core/src/main/java/google/registry/tools/UpdateRecurrenceCommand.java
- core/src/main/java/google/registry/whois/DomainLookupCommand.java
- core/src/main/java/google/registry/whois/NameserverLookupByIpCommand.java
- core/src/test/java/google/registry/testing/DatabaseHelper.java
Added an `allocateId` method to `TransactionManager` and make the application use this method.
Use IdService in the primary DB and an in-memory IdService in the replica.
Switched whois and CheckApi to the replica.
TODO: switch EPP query flows to replica
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/2470)
> Use replica for whois/CheckApi

- console-webapp/src/app/domains/domainList.component.ts
This isn't the worst thing in the world but it does result in a bad request to the server otherwise, and log/error spam. So, only load the domains list if we have a registrar selected.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/2485)
> Wait to load domain list until a registrar is selected

- core/src/main/java/google/registry/flows/domain/DomainPricingLogic.java
- core/src/main/java/google/registry/model/domain/token/AllocationToken.java
- core/src/main/java/google/registry/model/pricing/PremiumPricingEngine.java
- core/src/test/java/google/registry/flows/domain/DomainCreateFlowTest.java
- core/src/test/java/google/registry/flows/domain/DomainPricingLogicTest.java
- core/src/test/java/google/registry/model/domain/token/AllocationTokenTest.java
- core/src/test/resources/google/registry/flows/domain/domain_create_nonpremium_token_response.xml
When using this token (which must be tied to a particular domain), the first year price (and only the first year price, i.e. the creation price) will be the standard price for this TLD. Future years (i.e. renewals) will continue at the normal premium price.
b/332928676, in part
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/2481)
> Add RegistrationBehavior.NONPREMIUM_CREATE

- core/src/main/java/google/registry/env/common/default/WEB-INF/cloud-tasks-queue.xml
- core/src/main/java/google/registry/model/OteAccountBuilder.java
- core/src/main/java/google/registry/model/console/User.java
- core/src/main/java/google/registry/tools/CreateUserCommand.java
- core/src/main/java/google/registry/tools/DeleteUserCommand.java
- core/src/main/java/google/registry/tools/IamClient.java
- core/src/main/java/google/registry/tools/RegistryToolDataflowModule.java
- core/src/main/java/google/registry/tools/SetupOteCommand.java
- core/src/main/java/google/registry/tools/server/UpdateUserGroupAction.java
- core/src/main/java/google/registry/ui/server/registrar/ConsoleOteSetupAction.java
- core/src/main/java/google/registry/ui/server/registrar/ConsoleRegistrarCreatorAction.java
- core/src/main/java/google/registry/ui/server/registrar/RegistrarSettingsAction.java
- core/src/test/java/google/registry/model/OteAccountBuilderTest.java
- core/src/test/java/google/registry/model/OteStatsTestHelper.java
- core/src/test/java/google/registry/model/console/UserTest.java
- core/src/test/java/google/registry/server/RegistryTestServerMain.java
- core/src/test/java/google/registry/server/TestServer.java
- core/src/test/java/google/registry/testing/CloudTasksHelper.java
- core/src/test/java/google/registry/tools/CreateUserCommandTest.java
- core/src/test/java/google/registry/tools/DeleteUserCommandTest.java
- core/src/test/java/google/registry/tools/SetupOteCommandTest.java
- core/src/test/java/google/registry/ui/server/registrar/ConsoleOteSetupActionTest.java
- core/src/test/java/google/registry/ui/server/registrar/ConsoleRegistrarCreatorActionTest.java
- util/src/main/java/google/registry/util/RegistryEnvironment.java
We no longer use `RegistrarPoc` to login to the registrar console (old or new). Therefore, we need to create `User` objects when creating OT&E and production registrars.
Since there are now a couple of places where we need to grant IAP credentials to the newly created `User` objects, it makes sense to put the same logic in an auxiliary function to avoid code duplication.
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/2488)
> Create Users when setting up OT&E and Production registrars

- core/src/main/java/google/registry/beam/rde/RdePipeline.java
- core/src/main/java/google/registry/model/domain/DomainBase.java
- core/src/main/java/google/registry/rdap/RdapJsonFormatter.java
- core/src/test/java/google/registry/flows/domain/DomainInfoFlowTest.java
- core/src/test/java/google/registry/model/domain/DomainTest.java
- core/src/test/java/google/registry/rdap/RdapDomainActionTest.java
- core/src/test/java/google/registry/whois/DomainWhoisResponseTest.java
- core/src/test/resources/google/registry/flows/domain/domain_info_response_no_contacts.xml
- core/src/test/resources/google/registry/rdap/rdap_domain_no_contacts_exist_with_remark.json
- core/src/test/resources/google/registry/whois/whois_domain_no_contacts.txt
This doesn't yet allow them to be absent in EPP flows, but it should make the code not break if they happen to be null in the database. This is a follow-up to PR #2477, which ends up being a bit easier because whereas the registrant is used in more parts of the codebase, the other contact types (admin, technical, billing) are really only used in RDE, WHOIS, and RDAP, and because they were already being used as a collection anyway, the handling for if that collection contains fewer elements or is empty happened to already be mostly correct.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/2490)
> Make all contacts nullable in the data model

- core/src/main/java/google/registry/batch/ResaveEntityAction.java
- core/src/test/java/google/registry/batch/ResaveEntityActionTest.java
Our logs are getting gummed up with an indefinitely failing and retrying task to re-save a prober domain that doesn't exist (likely because it was hard-deleted by delete prober data action), so this makes the re-save action resilient to that failure case so that it stops assuming every enqueued re-save actually corresponds to an entity that exists, thus allowing it to fail permanently if the entity doesn't exist.  Failing permanently is the right thing to do as if the entity doesn't exist now there's no reason to think it will in the future, plus all re-saves are optimistic rather than guaranteed anyway.
This should fix http://b/350530720
- - - …
> Fail permamently in re-save entity action when entity doesn't exist

- core/src/main/java/google/registry/config/RegistryConfig.java
- core/src/main/java/google/registry/config/RegistryConfigSettings.java
- core/src/main/java/google/registry/config/files/default-config.yaml
- core/src/main/java/google/registry/config/files/nomulus-config-unittest.yaml
- core/src/main/java/google/registry/flows/domain/DomainCheckFlow.java
- core/src/main/java/google/registry/model/domain/fee/FeeQueryCommandExtensionItem.java
- core/src/test/java/google/registry/flows/domain/DomainCheckFlowTest.java
- core/src/test/resources/google/registry/flows/domain/domain_check_tiered_promotion_fee_response_v12.xml
As requested, for registrars participaing in these tiered pricing promos that wish to receive this type of response, we make the following changes:
1. The pre-promotional (i.e. base tier) price is returned as the standard domain-create fee when running a domain check.
2. The promotional (i.e. correct) price is returned as a special custom command class with a name of "STANDARD PROMO" when running a domain check.
3. Domain creates will return the non-promotional (i.e. incorrect) price rather than the actual promotional price. This is not implemented in this PR.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/2489)
> Change domain-check fee responses for registrars in tiered promos

- core/src/main/java/google/registry/flows/domain/DomainCreateFlow.java
- core/src/test/java/google/registry/flows/domain/DomainCreateFlowTest.java
As requested, for registrars participating in these tiered pricing promos that wish to receive this type of response, we make the following changes:
1. The non-promotional (i.e. incorrect) price is returned as the standard domain-create fee when running a domain check.
2. The promotional (i.e. correct) price is returned as a special custom command class with a name of "STANDARD PROMO" when running a domain check
3. Domain creates will return the non-promotional (i.e. incorrect) price rather than the actual promotional price.
This PR does only number 3. See PR #2489 for the others.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/2491)
> Change domain-create fee response for tiered promos

- console-webapp/src/app/app.module.ts
- console-webapp/src/app/navigation/navigation.component.html
- console-webapp/src/app/navigation/navigation.component.ts
- console-webapp/src/app/shared/directives/userLevelVisiblity.directive.ts
I'm not exactly sure what else we will need to hide apart from just some DOM elements in the future, so I've tried to come up with what I think is a flexible and easily extensible way so that we can adjust if needed. 
Plus I believe it's not strictly important, because back-end should prevent users from accessing what they are not supposed to anyway, but we certainly want to have something on ui as well.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/2495)
> Add ability to remove elements from console UI per user role

- console-webapp/src/app/registrar/newRegistrar.component.html
I was creating new registrars in sandbox for support team testing and noticed that state field is not marked as required, although being required for submission to succeed.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/2509)
> Mark console state field on new registrar form as required

- core/src/main/java/google/registry/batch/CloudTasksUtils.java
- core/src/main/java/google/registry/model/OteAccountBuilder.java
- core/src/main/java/google/registry/model/console/User.java
- core/src/main/java/google/registry/tools/CreateUserCommand.java
- core/src/main/java/google/registry/tools/DeleteUserCommand.java
- core/src/main/java/google/registry/ui/server/registrar/ConsoleRegistrarCreatorAction.java
- core/src/test/java/google/registry/model/console/UserTest.java
- core/src/test/java/google/registry/tools/CreateUserCommandTest.java
- core/src/test/java/google/registry/tools/DeleteUserCommandTest.java
When creating/deleting users, we need to add/remove the emails in
question to/from the console email group (if it exists). This used to be
done synchronously by calling the Groups API directly from the nomulus
tool. However #2488 made it so that in all cases where group membership
is modified, a Cloud Tasks task is created to execute the change on
the server side asynchronously (because there are multiple places where
this change needs to be done, and it is easier to make it all happen on the
server side).
Alas, as it turns out, Cloud Tasks tasks need to be created with a
service account's credential (which is trivially done on the server side
because the ADC is a service account). Nomulus command runs with a user
credential, and we need to grant the relevant user permission to
masquerade …
> Call Workspace Groups API directly from nomulus tool

- core/src/test/java/google/registry/ui/server/console/settings/ContactActionTest.java
Types are not important for this test suite, so getting rid of one seemed like an easy fix
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/2524)
> Make ContactActionTest deterministic for stop fail under new Hibernate

- core/src/main/java/google/registry/flows/domain/DomainUpdateFlow.java
- core/src/main/java/google/registry/model/domain/DomainBase.java
- core/src/main/java/google/registry/model/eppcommon/AuthInfo.java
- core/src/test/java/google/registry/flows/domain/DomainUpdateFlowTest.java
- core/src/test/java/google/registry/testing/DomainSubject.java
- core/src/test/resources/google/registry/flows/domain/domain_update_no_auth_change.xml
It's valid for the auth data to be null (although it only happens 10 times across our entire registry), so the domain update flow should not fail out with a NullPointerException when the existing state of the data is null and the update isn't adding that data either.
BUG=http://b/359264787
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/2530)
> Make domain update flow handle null auth data

- jetty/deploy-nomulus-for-env.sh
- jetty/kubernetes/nomulus-gateway.yaml
- jetty/kubernetes/nomulus-service.yaml
- jetty/src/main/jetty-base/webapps/healthz/index.html
This will create a multi-cluster external load balancer exposing HTTP
traffic to nomulus running in clusters in the fleet.
Note that this is only an intermediate step. The endpoints need to be split into services that can be independently scaled, and become IAP-protected HTTPS endpoints.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/2527)
> Make Nomulus work on GKE with external load balancer

- core/src/main/java/google/registry/flows/domain/DomainCreateFlow.java
- core/src/test/java/google/registry/flows/domain/DomainCreateFlowTest.java
Previous PRs and token changes (see b/332928676) have made it so that SPECIFIED renewalPriceBehavior tokens must have a renewal price. As such, we can now use that renewalPrice when creating domains with SPECIFIED tokens.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/2502)
> Use token's renewalPrice if renewalBehavior is SPECIFIED

- core/src/main/java/google/registry/model/registrar/RegistrarBase.java
- core/src/main/java/google/registry/module/RequestComponent.java
- core/src/main/java/google/registry/module/frontend/FrontendRequestComponent.java
- core/src/main/java/google/registry/ui/server/console/ConsoleModule.java
- core/src/main/java/google/registry/ui/server/console/ConsoleOteAction.java
- core/src/test/java/google/registry/ui/server/console/ConsoleOteActionTest.java
- core/src/test/resources/google/registry/module/frontend/frontend_routing.txt
- core/src/test/resources/google/registry/module/routing.txt
This change allows us to safely delete the following from the old console:
[ConsoleOteSetupAction](https://cs.opensource.google/nomulus/nomulus/+/master:core/src/main/java/google/registry/ui/server/registrar/ConsoleOteSetupAction.java;bpv=1;bpt=1;l=61?q=ConsoleOte&ss=nomulus%2Fnomulus&gsn=ConsoleOteSetupAction&gs=KYTHE%3A%2F%2Fkythe%3A%2F%2Fgithub.com%2Fgoogle%2Fnomulus%3Flang%3Djava%3Fpath%3Dgoogle.registry.ui.server.registrar.ConsoleOteSetupAction%23ec203b4d693fdd53d26709f78a800106909d6115ada375cf0caffa6a3982692b) and [OteStatusAction](https://cs.opensource.google/nomulus/nomulus/+/master:core/src/main/java/google/registry/ui/server/registrar/OteStatusAction.java;bpv=1;bpt=1;l=49?gsn=OteStatusAction&gs=KYTHE%3A%2F%2Fkythe%3A%2F%2Fgithub.com%2Fgoogle%2Fnomulus%3Flang%3Djava%3Fpath%3Dgoogl …
> Add OT&E create and status to the new console

- core/src/main/java/google/registry/reporting/icann/ActivityReportingQueryBuilder.java
- core/src/main/java/google/registry/reporting/icann/TransactionsReportingQueryBuilder.java
- core/src/main/resources/google/registry/reporting/icann/sql/cloud_sql_attempted_adds.sql
- core/src/main/resources/google/registry/reporting/icann/sql/epp_metrics.sql
- core/src/main/resources/google/registry/reporting/icann/sql/monthly_logs.sql
- core/src/test/resources/google/registry/reporting/icann/attempted_adds_test_cloud_sql.sql
- core/src/test/resources/google/registry/reporting/icann/epp_metrics_test_cloud_sql.sql
- core/src/test/resources/google/registry/reporting/icann/monthly_logs_test_cloud_sql.sql
Instead of having to parse the protoPayload.line from the request logs, we just want to inspect the textPayload from the app logs (stored in a separate table). This applies to the EPP metrics from the activity reporting and the attempted-adds column for the transaction reporting.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/2535)
> Update activity/txn reporting to use new GAE log format

- core/src/main/java/google/registry/reporting/icann/IcannReportingModule.java
- core/src/main/java/google/registry/reporting/icann/IcannReportingStagingAction.java
- core/src/test/java/google/registry/reporting/icann/IcannReportingStagingActionTest.java
This will help us if/when we need to run the report generation multiple times, or for past dates and we don't want to send extra emails or upload any extra reports to ICANN.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/2538)
> Allow skip of emailing/uploading for activity reports

- core/src/main/java/google/registry/model/tld/label/DomainLabelMetrics.java
- core/src/test/java/google/registry/model/tld/label/ReservedListTest.java
- docs/operational-procedures.md
This single metric currently accounts for 22.2% of our total metrics bill, almost double the size of our EPP requests metric, while also simultaneously being much less useful. This change reduces the cardinality by removing two parameters we don't care that much about, which should significantly reduce the size and thus the cost. If after this change the metric is still too large, I'll also then remove the matchCount parameter from this metric. We could possibly even consider deleting the metric in its entirety, as we hardly ever use it.
This PR also removes unused code for premium list metrics that have never actually been written out (and that we won't bother with at this point).
- - - …
> Reduce cardinality of reserved list processing time metric

- core/src/main/java/google/registry/env/common/backend/WEB-INF/logging.properties
- core/src/main/java/google/registry/env/common/bsa/WEB-INF/logging.properties
- core/src/main/java/google/registry/env/common/default/WEB-INF/logging.properties
- core/src/main/java/google/registry/env/common/pubapi/WEB-INF/logging.properties
- core/src/main/java/google/registry/env/common/tools/WEB-INF/logging.properties
Update logging configs after Hibernate 6 migration.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/2546)
> Suppress misleading error-level logs by hibernate

- release/builder/deployCloudSchedulerAndQueue.go
Depending on if a "--gke" parameter (must be the last one) is passed,
the deployer constructs the corresponding URIs for GAE or GKE
accordingly.
TESTED=Used the deployer to deploy tasks to alpha and verified that they
run on GKE.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/2562)
> Make the cloud scheduler deployer GKE-aware

- release/cloudbuild-sync-db-objects.yaml
It looks like /usr/bin/python *may* no longer exists in the latest cloud
builder git image. I ran the latest image and logged into it to verify
that /usr/bin/python3 does exist on 9/25, and again on 9/26 where it
re-appeared.
I think it is generally a good idea to not rely on it being there going
forward.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/2567)
> Make the db object sync job more reliable

- console-webapp/src/app/domains/domainList.component.ts
ACCOUNT_MANAGER users don't have permission to see locks so it'll throw 403s. That's OK, we don't need/want to display that error to the client.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/2574)
> Don't show snackbar on rlock-load failure if 403

- core/src/main/java/google/registry/ui/html/index.html
- core/src/main/java/google/registry/ui/server/registrar/ConsoleUiAction.java
- core/src/test/java/google/registry/ui/server/registrar/ConsoleUiActionTest.java
- core/src/test/java/google/registry/webdriver/RegistrarConsoleScreenshotTest.java
- core/src/test/java/google/registry/webdriver/RegistrarConsoleWebTest.java
The only way to access it now is by adding a non-null URL parameter `noredirect`, for example `https://registry.example/registrar?noredirect=true`.
TESTED=Deployed on alpha, tested both `/registrar` and `/`, and that the `noredirect` override works.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/2575)
> Disable legacy registrar console

- .github/workflows/codeql.yml
This fails for me every day for some reason (starting about a month
ago). The same commit went through the workflow fine when the action was
triggered by a push.
I think there's no reason for us to have a cron run as the changes to the
master branch can only come from commit pushes.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/2581)
> Remove schedule CodeQL run

- core/src/main/java/google/registry/ui/server/console/ConsoleApiAction.java
This fixes b/370927852
Context - Recent change https://github.com/google/nomulus/pull/2540 has made task creation synchronous, which surfaced the fact that method used for enqueuing a SyncRegistrarSheetAction has been incorrect (basically forever), but  it didn't matter much because updated fields are not reflected in the sheet anyway. 
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/2580)
> Set POST method to SyncRegistrarSheetAction invocation

- .github/workflows/codeql.yml
These flags are suggested by GitHub support to disable reusing caches
during Gradle build. They think that could fix the intermittent error
message:
```
Encountered a fatal error while running "/opt/hostedtoolcache/CodeQL/2.19.0/x64/codeql/codeql database finalize --finalize-dataset --threads=4 --ram=14576 --verbosity=progress++ /home/runner/work/_temp/codeql_databases/java". Exit code was 32 and last log line was: CodeQL detected code written in Java/Kotlin but could not process any of it. For more information, review our troubleshooting guide at https://gh.io/troubleshooting-code-scanning/no-source-code-seen-during-build . See the logs for more details.
```
- - - …
> Try to fix CodeQL java actions

- release/cloudbuild-release.yaml
It seems like `/usr/bin/python` is no longer symlinked to the `python3`
binary in the `gcr.io/cloud-builders/git` image.
I've sent out a separate fix to upstream to change the shebang.
https://gerrit-review.git.corp.google.com/c/gcompute-tools/+/439501
But in the meantime, we need this temporary fix for the release to
build.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/2591)
> Fix releases

- core/src/main/java/google/registry/persistence/transaction/BatchedQueries.java
- core/src/main/java/google/registry/persistence/transaction/JpaTransactionManager.java
- core/src/main/java/google/registry/persistence/transaction/JpaTransactionManagerImpl.java
- core/src/main/java/google/registry/tools/server/ListHostsAction.java
- core/src/test/java/google/registry/persistence/transaction/BatchedQueriesTest.java
TransactionManage's `loadAllOf` and `loadAllOfStream` methods are not safe: they may cause PSQL `out of shared memory` errors and also java OOM errors. The key to avoid lockup is to load batches of entities in separate transactions.
This PR added a `BatchedQueries` class, and replaced the unsafe method in one class as a demo.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/2589)
> A batch query utility to replace TransactionManager's `loadAllOf` methods 

- core/src/main/java/google/registry/tools/CurlCommand.java
- core/src/main/java/google/registry/tools/ServiceConnection.java
- core/src/test/java/google/registry/tools/ServiceConnectionTest.java
- jetty/deploy-nomulus-for-env.sh
- jetty/kubernetes/gateway/nomulus-route-backend.yaml
- jetty/kubernetes/gateway/nomulus-route-console.yaml
- jetty/kubernetes/gateway/nomulus-route-frontend.yaml
- jetty/kubernetes/gateway/nomulus-route-pubapi.yaml
- proxy/src/main/java/google/registry/proxy/EppProtocolModule.java
- proxy/src/main/java/google/registry/proxy/ProxyConfig.java
- proxy/src/main/java/google/registry/proxy/ProxyModule.java
- proxy/src/main/java/google/registry/proxy/WhoisProtocolModule.java
- proxy/src/main/java/google/registry/proxy/config/default-config.yaml
- proxy/src/main/java/google/registry/proxy/handler/EppServiceHandler.java
- proxy/src/main/java/google/registry/proxy/handler/HttpsRelayServiceHandler.java
- proxy/src/main/java/google/registry/proxy/handler/WhoisServiceHandler.java
- proxy/src/test/java/google/registry/proxy/ProtocolModuleTest.java
- proxy/src/test/java/google/registry/proxy/TestUtils.java
- proxy/src/test/java/google/registry/proxy/handler/EppServiceHandlerTest.java
- proxy/src/test/java/google/registry/proxy/handler/WhoisServiceHandlerTest.java
This PR adds the ability to deploy canary service in GKE. It includes the following:
1. New deployments and services are added for the canary version of the existing ones.
2. New HTTP routes are created to route requests with `canary: true` header to the canary service.
3. The proxy is configured to add the header when necessary.
4. The Nomulus curl tool now respects the `--canary` flag and will add the header when necessary.
5. Not related: The curl command now displays the content when the response is not OK, as the content may contain error information.
TESTED=1. Deployed to alpha GKE and verified the pubapi service respects the header based routing when using curl to access the endpoint.
2. Verified that Nomulus curl sends the request to canary service when the flag is used.
3. …
> Add canary service to GKE

- core/src/main/java/google/registry/tools/UpdateRecurrenceCommand.java
- core/src/test/java/google/registry/tools/UpdateRecurrenceCommandTest.java
It was failing when any kind of transfer data was present, even completed transfer data. Note that completed transfer data persists on a domain indefinitely until/unless a new transfer is requested.
BUG= http://b/377328244
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/2605)
> Make nomulus update_recurrence command only fail on pending transfers

- core/src/main/java/google/registry/export/ExportDomainListsAction.java
- core/src/main/java/google/registry/model/common/FeatureFlag.java
- core/src/test/java/google/registry/export/ExportDomainListsActionTest.java
- core/src/test/java/google/registry/model/common/FeatureFlagTest.java
- db/src/main/resources/sql/schema/db-schema.sql.generated
We only include the deletion time if the domain is in the 5-day PENDING_DELETE period after the 30 day REDEMPTION period. For all other domains, we just have an empty string as that field.
This is behind a feature flag so that we can control when it is enabled
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/2602)
> Sometimes include deletion times in domain-list exports

- core/src/main/java/google/registry/request/auth/OidcTokenAuthenticationMechanism.java
- core/src/main/java/google/registry/tools/CreateOrUpdateUserCommand.java
- core/src/test/java/google/registry/tools/CreateUserCommandTest.java
- core/src/test/java/google/registry/tools/UpdateUserCommandTest.java
This essentially enables the "forgot password" flow
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/2609)
> Allow for change of registry lock passwords in User objects

- core/src/main/java/google/registry/ui/server/console/ConsoleApiAction.java
- core/src/main/java/google/registry/ui/server/console/ConsoleApiParams.java
- core/src/main/java/google/registry/ui/server/console/ConsoleDomainGetAction.java
- core/src/main/java/google/registry/ui/server/console/ConsoleDomainListAction.java
- core/src/main/java/google/registry/ui/server/console/ConsoleEppPasswordAction.java
- core/src/main/java/google/registry/ui/server/console/ConsoleModule.java
- core/src/main/java/google/registry/ui/server/console/ConsoleOteAction.java
- core/src/main/java/google/registry/ui/server/console/ConsoleRegistryLockAction.java
- core/src/main/java/google/registry/ui/server/console/ConsoleRegistryLockVerifyAction.java
- core/src/main/java/google/registry/ui/server/console/ConsoleUpdateRegistrarAction.java
- core/src/main/java/google/registry/ui/server/console/ConsoleUsersAction.java
- core/src/main/java/google/registry/ui/server/console/RegistrarsAction.java
- core/src/main/java/google/registry/ui/server/console/settings/ContactAction.java
- core/src/main/java/google/registry/ui/server/console/settings/SecurityAction.java
- core/src/main/java/google/registry/ui/server/console/settings/WhoisRegistrarFieldsAction.java
- core/src/test/java/google/registry/testing/ConsoleApiParamsUtils.java
- core/src/test/java/google/registry/testing/DatabaseHelper.java
- core/src/test/java/google/registry/ui/server/console/ConsoleDomainGetActionTest.java
- core/src/test/java/google/registry/ui/server/console/ConsoleDomainListActionTest.java
- core/src/test/java/google/registry/ui/server/console/ConsoleDumDownloadActionTest.java
- core/src/test/java/google/registry/ui/server/console/ConsoleEppPasswordActionTest.java
- core/src/test/java/google/registry/ui/server/console/ConsoleOteActionTest.java
- core/src/test/java/google/registry/ui/server/console/ConsoleRegistryLockActionTest.java
- core/src/test/java/google/registry/ui/server/console/ConsoleRegistryLockVerifyActionTest.java
- core/src/test/java/google/registry/ui/server/console/ConsoleUpdateRegistrarActionTest.java
- core/src/test/java/google/registry/ui/server/console/ConsoleUsersActionTest.java
- core/src/test/java/google/registry/ui/server/console/RegistrarsActionTest.java
- core/src/test/java/google/registry/ui/server/console/settings/ContactActionTest.java
- core/src/test/java/google/registry/ui/server/console/settings/SecurityActionTest.java
- core/src/test/java/google/registry/ui/server/console/settings/WhoisRegistrarFieldsActionTest.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/2585)
> Add RegistrarUpdateHistory objects for console changes

- core/src/main/java/google/registry/flows/poll/PollRequestFlow.java
It doesn't need a higher transaction isolation level as it's only loading a given poll message once, and we want to avoid putting any kind of locks on the PollMessage table as it seems to be having contention issues. Note that the poll message request flow is by far the most frequent code that touches the PollMessage table, as there are many many requests every minute from dozens of registrars, but much fewer poll messages than that to actually ACK.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/2614)
> Downgrade the tx isolation level of poll message request flow

- core/src/main/java/google/registry/flows/poll/PollAckFlow.java
This might help alleviate DB transaction contention on the PollMessage table. A lower transaction isolation level is safe because acking a poll message is idempotent: there are only two things it does, either delete a poll message or take a recurring one from the past and set it to be a year in the future from the date in the past. Both of these operations will always yield the same final result even if executed multiple times simultaneously for some reason.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/2615)
> Downgrade the tx isolation level of poll message ack flow

- core/src/main/java/google/registry/flows/ExtensionManager.java
- core/src/main/java/google/registry/ui/server/console/ConsoleBulkDomainAction.java
- core/src/main/java/google/registry/ui/server/console/ConsoleModule.java
- core/src/test/java/google/registry/flows/ExtensionManagerTest.java
- core/src/test/java/google/registry/ui/server/console/ConsoleBulkDomainActionTest.java
For now it only includes two options (domain deletion and domain suspension). In the future, as necessary, we can add other actions but this seems like a relatively simple starting point (actions like bulk updates are much more conceptually complex).
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/2611)
> Add a bulk-domain-action console endpoint

- core/src/main/java/google/registry/rdap/RdapJsonFormatter.java
- core/src/main/java/google/registry/rdap/RdapObjectClasses.java
- core/src/test/java/google/registry/rdap/RdapActionBaseTestCase.java
- core/src/test/java/google/registry/rdap/RdapDomainActionTest.java
- core/src/test/java/google/registry/testing/DatabaseHelper.java
- core/src/test/java/google/registry/ui/server/console/ConsoleBulkDomainActionTest.java
- core/src/test/resources/google/registry/rdap/rdap_domain_add_grace_period.json
- core/src/test/resources/google/registry/rdap/rdap_domain_auto_renew_grace_period.json
- core/src/test/resources/google/registry/rdap/rdap_domain_explicit_renew_grace_period.json
- core/src/test/resources/google/registry/rdap/rdap_domain_pending_delete_redemption_grace_period.json
- core/src/test/resources/google/registry/rdap/rdap_domain_transfer_grace_period.json
We do this for WHOIS results so we should do it for RDAP results as well (especially since they're mostly already included in the response profile).
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/2606)
> Include GracePeriod statuses in RDAP results

- core/src/main/java/google/registry/config/RegistryConfig.java
- core/src/main/java/google/registry/config/RegistryConfigSettings.java
- core/src/main/java/google/registry/keyring/KeyringModule.java
- core/src/main/java/google/registry/persistence/PersistenceModule.java
Tested: In crash, deployed the nomulus server, and tested the get_sql_credential command.
Note: new SecretManager entries have been added in all environments.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/2625)
> Use sql instance name in SecretManager

- jetty/build.gradle
- jetty/deploy-nomulus-for-env.sh
- jetty/get-endpoints.py
- jetty/kubernetes/nomulus-frontend.yaml
- jetty/kubernetes/nomulus-pubapi.yaml
k8s does not have a way to expose a global load balancer with TCP
endpoints, and setting up node port-based routing is a chore, even with
Terraform (which is what we did with the standalone proxy).
We will use Cloud DNS's geolocation routing policy to ensure that
clients connect to the endpoint closest to them.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/2627)
> Expose EPP and WHOIS endpoints on reginal load balancers

- core/src/main/java/google/registry/persistence/transaction/JpaTransactionManagerImpl.java
Knonw nested transact calls that are not using the `reTransact` method have been refactored away in Sandbox. Enable logging in production to catch any missing cases. Logging is throttled at 1 message per minute per VM.
Once production is cleaned up, we will forbid such transactions in the code, and start factoring away the `reTransact` method.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/2628)
> Enable nested transaction warning in production

- jetty/build.gradle
If we deploy Nomulus, we should do that before queues and the scheduler
tasks are updated.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/2631)
> Explicity specify deployment order for queues and scheduler tasks

- core/src/main/java/google/registry/persistence/PersistenceModule.java
SecretManager based keyring not included in keyring bindings, resulting in runtime failure.
We should simply keyring bindings. There is no use case for multiple implementations. See b/388835696.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/2632)
> Fix keyring in BEAM pipeline

- jetty/kubernetes/nomulus-pubapi.yaml
We are required to respond to HTTP(S) requests on port 80/443 on the
same domain where we serve port 43 WHOIS requests. The proxy already
does this by redirecting to the web WHOIS lookup page on the marketing
website.
This PR makes it so that requests to port 80/443 can be routed to the
proxy for redirect.
TESTED=tested on crash and the redirect works.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/2634)
> Expose Web WHOIS redirects

- core/src/main/java/google/registry/flows/domain/DomainCreateFlow.java
- core/src/main/java/google/registry/flows/domain/DomainPricingLogic.java
- core/src/test/java/google/registry/flows/domain/DomainCreateFlowTest.java
- core/src/test/java/google/registry/flows/domain/DomainPricingLogicTest.java
Instead of using a separate RenewalPriceInfo object, just map the behavior (if it exists) onto the BillingRecurrence with a special carve-out, as always, for anchor tenants (note: this shouldn't matter much since anchor tenants *should* use NONPREMIUM renewal tokens anyway, but just in case, double-check).
This also fixes DomainPricingLogic to treat a multiyear create as a one-year-create + n-minus-1-year-renewal for cases where either the creation or the renewal (or both) are nonpremium.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/2635)
> Map token renewal behavior directly onto BillingRecurrence

- core/src/main/java/google/registry/module/RegistryServlet.java
- core/src/main/java/google/registry/tools/RegistryCli.java
- util/src/main/java/google/registry/util/GcpJsonFormatter.java
- util/src/test/java/google/registry/util/GcpJsonFormatterTest.java
This allows us to search for logs for a given path using a filter like
this:
jsonPayload.httpRequest.requestUrl="/_dr/blah"
TESTED=tested on crash
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/2642)
> Record http request parameters in log metadata

- util/src/main/java/google/registry/util/UrlConnectionException.java
It does not get the error message for 400+ status codes.
It fails to get the status code if the response has neither data nor error.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/2648)
> Fix loss of error info in UrlConnectionException

- core/src/main/java/google/registry/export/ExportPremiumTermsAction.java
- core/src/test/java/google/registry/export/ExportPremiumTermsActionTest.java
https://b.corp.google.com/issues/390053672
This makes it easier to identify what file you're looking at, at a glance
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/2644)
> Add TLD identifier to premium terms filename and header

- core/src/main/java/google/registry/flows/domain/DomainPricingLogic.java
- core/src/test/java/google/registry/flows/domain/DomainPricingLogicTest.java
This is kinda nonsensical because this use case is trying to apply a single use token multiple times in the same domain:check request -- like, trying to use a single-use token for both create, renew, and transfer while having a $0 create price and a premium renewal price.
This change doesn't affect any actual business / costs, since SPECIFIED token renewal prices were already set on the BillingRecurrence
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/2651)
> Handle SPECIFIED renewal price w/token in check flow

- core/src/main/java/google/registry/tools/DomainLockUtils.java
- core/src/main/java/google/registry/tools/LockOrUnlockDomainCommand.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/2658)
> Remove nested transactions from domain (un)locking

- core/src/main/java/google/registry/flows/domain/FeesAndCredits.java
- core/src/test/java/google/registry/flows/domain/DomainCreateFlowTest.java
This isn't a situation we'll encounter often, but if the client has an allocation token that's valid for premium domains that gives a 0 cost, we shouldn't require them to include the fee extension when creating the domain. We already don't require it for standard domains.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/2660)
> Allow for no fee extension with free premium domains

- docs/operational-procedures/brda-deposits.md
- docs/operational-procedures/rde-deposits.md
- docs/proxy-setup.md
- integration/testutils_bashrc
- release/cloudbuild-deploy-gke.yaml
- release/cloudbuild-deploy.yaml
- release/cloudbuild-dev-resource.yaml
- release/cloudbuild-release.yaml
- release/cloudbuild-schema-deploy.yaml
- release/cloudbuild-schema-verify.yaml
- release/cloudbuild-sync-and-tag.yaml
- release/rollback/rollback_test.py
- release/rollback/steps.py
Use of gsutil is discouraged / deprecated, see https://cloud.google.com/storage/docs/gsutil
The only non-trivial changes are
-  previously "stat -q" is used to see if something exists, but "describe" also has a nonzero exit code if the object doesn't exist
- we use the predefined acl https://cloud.google.com/storage/docs/access-control/lists#predefined-acl for world-readable
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/2670)
> Convert gsutil to gcloud storage

- core/src/main/java/google/registry/tools/RegistryCli.java
- jetty/deploy-nomulus-for-env.sh
- jetty/kubernetes/nomulus-backend.yaml
- jetty/kubernetes/nomulus-console.yaml
- jetty/kubernetes/nomulus-frontend.yaml
- jetty/kubernetes/nomulus-pubapi.yaml
Also set the `JETTY_WORKER_INSTANCE` variable so each pod is guaranteed to get a unique session cookie.
Jetty documentation says to use [`JETTY_WORKER_NAME`](https://jetty.org/docs/jetty/12/programming-guide/server/session.html#defaultidmgr), but the source code actually use [`JETTY_WORKER_INSTANCE`](https://sourcegraph.com/github.com/jetty/jetty.project/-/blob/jetty-core/jetty-session/src/main/java/org/eclipse/jetty/session/DefaultSessionIdManager.java?L314). I tested and the latter is indeed used.
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/2674)
> Let nomulus tool connect to sandbox GKE by default

- jetty/deploy-nomulus-for-env.sh
- jetty/kubernetes/nomulus-backend.yaml
- jetty/kubernetes/nomulus-console.yaml
- jetty/kubernetes/nomulus-frontend.yaml
- jetty/kubernetes/nomulus-pubapi.yaml
- release/builder/build.sh
- release/cloudbuild-nomulus.yaml
- release/cloudbuild-release.yaml
- release/cloudbuild-restart-proxies.yaml
Resurrect the EPP load balancer which connects to the sidecar proxy within the same pod as nomulus. This is so that we have the freedom to choose between the standalone proxy and the sidecar one in case one doesn't work as expected.
Also switch to "Performance" nodes with does not have [CPU or memory limits](https://cloud.google.com/kubernetes-engine/docs/concepts/autopilot-compute-classes#when-to-use). I have observed that with the default nodes, after the service ran for a day or so the pods start to crash due to lack of memory from the nodes, which exacerbates the problem with sessions stickness.
Lastly, for the standalone proxies to work properly after a release of Nomulus, a GCB job is added to force restart the proxies (and therefore forcing the clients to reconnect and re-login, to …
> Expose EPP via sidecar proxy

- release/schema-verifier/verify_deployed_sql_schema.sh
Failed pg_dump may not leave a file, failing the subsequent diffing and causing the verifier to return success.
The verifier should abort in this case.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/2681)
> Abort schema verifier when pg_dump fails

- jetty/kubernetes/gateway/nomulus-gateway.yaml
- jetty/kubernetes/nomulus-backend.yaml
- jetty/kubernetes/nomulus-console.yaml
- jetty/kubernetes/nomulus-frontend.yaml
- jetty/kubernetes/nomulus-pubapi.yaml
- release/cloudbuild-release.yaml
This allows us to easily tell which tag was deployed.
Also set the gateway to use named address so they are stable, and so
that we can attach an IPv6 record to it. Auto-provisioned addresses are
IPv4 only.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/2683)
> Add an annotation to the deployment

- common/src/testing/java/google/registry/testing/truth/TextDiffSubject.java
- db/src/test/java/google/registry/sql/flyway/SchemaTest.java
We now pin to postgreSQL v17 when running tests, which means that minor
version might increase without our intervention. This causes (at least)
the comment in the golden schema to change, and failing the test as a
result.
This PR adds the ability to strip lines that we deem as comment from the
comparison, so we don't have to do trivial upgrades to the gold schema
whenever there's minor version upgrade.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/2690)
> Make it possible to ignore comment lines when comparing schemas

- core/src/test/java/google/registry/flows/domain/DomainCreateFlowTest.java
This removes logic from an inner helper method so that it becomes more clear from callsites within each test exactly which behavior is expected from those test conditions.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/2688)
> Refactor logic out of domain create flow tests

- common/src/testing/java/google/registry/testing/truth/TextDiffSubject.java
- db/src/test/java/google/registry/sql/flyway/SchemaTest.java
It still is a list, because we String::startsWith does not benefit from
the target being in a set.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/2691)
> Make ignoreLinesStartingWith varargs

- core/src/main/java/google/registry/request/auth/OidcTokenAuthenticationMechanism.java
This can happen on public endpoints (in pubapi) where the service is
behind IAP but all users (including not-logged-in ones) are allowed. IAP
will add an OIDC token with no email field in the request header.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/2694)
> Reduce log level to info when no email is found from the OIDC token

- proxy/deploy-proxy-for-env.sh
- proxy/src/main/java/google/registry/proxy/handler/WhoisServiceHandler.java
The headers can be used by Cloud Armor to perform IP-based rate
limiting.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/2695)
> Add headers to record WHOIS client IPs

- integration/run_compatibility_tests.sh
Had to temporarily create the files in
gs://domain-registry-dev-deployed-tags but the automated release process will take care of that soon
This is what's causing the ever-present Kokoro CI builds as well as the failures in any change that affects SQL 
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/2702)
> Use nomulus-gke tagging mechanism in sql-int tests

- core/src/main/java/google/registry/persistence/transaction/JpaTransactionManagerImpl.java
There can be delays in releasing predicate locks when we have transactions that are long-lived -- even delays in releasing predicate locks acquired by shorter-lived transactions. Logging the transaction duration will allow us to get a sense as to transaction durations during busy times.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/2682)
> Log transaction durations

- core/src/main/java/google/registry/module/RegistryServlet.java
- util/src/main/java/google/registry/util/GcpJsonFormatter.java
- util/src/test/java/google/registry/util/GcpJsonFormatterTest.java
There are two session cookies, JSESSIONID, which is set by Jetty, and
GCLB, which is set by the Gateway.
In one session, every request other than the first one (the <hello>)
should have the same GCLB value, and every request after a successful
<login> should have the same JSESSIONID.
With these two metadata, we should be able to trace all requests that
*should* belong to the same session and debug issues with session
mismatch (if any).
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/2703)
> Log session cookies in metadata

- core/src/main/java/google/registry/config/files/tasks/cloud-scheduler-tasks-production.xml
- release/builder/deployCloudSchedulerAndQueue.go
For GKE all tasks should be on backend, BSA was on its own service
because of egress IP constraint.
Also made it possible to specify a timeout for the Cloud Scheduler job,
with the default (3m) suitable for most tasks.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/2707)
> Fix a Cloud Scheduler deployment bug

- core/src/main/java/google/registry/model/tld/Tld.java
- core/src/main/java/google/registry/model/tld/label/PremiumList.java
- core/src/main/java/google/registry/persistence/converter/BloomFilterConverter.java
- core/src/main/java/google/registry/rdap/RdapActionBase.java
- core/src/main/java/google/registry/rdap/RdapDataStructures.java
- core/src/main/java/google/registry/rdap/RdapDomainAction.java
- core/src/main/java/google/registry/rdap/RdapIcannStandardInformation.java
- core/src/main/java/google/registry/rdap/RdapObjectClasses.java
- core/src/main/java/google/registry/rdap/RdapResultSet.java
- core/src/main/java/google/registry/rdap/RdapSearchActionBase.java
- core/src/main/java/google/registry/rdap/RdapSearchResults.java
- core/src/main/java/google/registry/request/HttpException.java
- core/src/test/java/google/registry/persistence/converter/BloomFilterConverterTest.java
- core/src/test/java/google/registry/persistence/transaction/JpaTransactionManagerExtension.java
- core/src/test/java/google/registry/rdap/RdapActionBaseTestCase.java
- core/src/test/java/google/registry/rdap/RdapDomainActionTest.java
- core/src/test/java/google/registry/rdap/RdapTestHelper.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/2706)
> Add BSA label to rdap-domain 404 responses for BSA domains

- core/src/main/java/google/registry/ui/server/console/domains/ConsoleBulkDomainDeleteActionType.java
- core/src/main/java/google/registry/ui/server/console/domains/ConsoleBulkDomainSuspendActionType.java
- core/src/main/java/google/registry/ui/server/console/domains/ConsoleBulkDomainUnsuspendActionType.java
- core/src/main/java/google/registry/ui/server/console/domains/ConsoleDomainActionType.java
This makes the action types a bit simpler -- this is possible because
we've reduced the scope of domain actions that we want to natively
support
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/2708)
> Refactor console bulk domain action types

- build.gradle
- console-webapp/build.gradle
- console-webapp/gradle.properties
- release/build_nomulus_for_env.sh
We use the $environment property to set the console config. The default is 'production' as the console screenshot tests depend on it.
TESTED=ran :jetty:copyConsole with
-Penvironment=(sandbox|production|alpha) and checked the resulting js
file.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/2713)
> Fix console build for GKE

- release/cloudbuild-delete-canary.yaml
- release/cloudbuild-release.yaml
We've seen this issue happen more often than not recently, where GAE
canary deployment is stuck for about 10 min and the failed. The reason
is not clear, but delete the canary version prior to a deployment always
fixes the issue.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/2714)
> Add a GCB job to delete GAE canary versions

- release/cloudbuild-monitor-zfa.yaml
This doesn't check for correctness (we have other scripts that do that) but just that the service is available at all (the other scripts do not do that).
This should, and will, be configured with a scheduled trigger in GCB (for us, in the domain-registry-dev project) and configuration to send some sort of pub/sub notification on failure (for us, this is already set up on domain-registry-dev and it sends messages to the "Domain Registry Notifications" chat channel.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/2719)
> Add a GCB script for monitoring ZFA accessibility

- jetty/kubernetes/gateway/nomulus-route-console.yaml
- jetty/src/main/jetty-base/webapps/root/index.html
This reverts commit 2a01c12b14d713158be0209bae95dd090e6eec13.
The `root` folder overrides all routing rules. We need to rethink how to only redirect `/index.html`, Maybe through an action, or some special Jetty config.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/2724)
> Revert "Add a redirect for the console bare domain (#2718)"

- core/src/main/resources/google/registry/reporting/icann/sql/transaction_counts.sql
- core/src/test/java/google/registry/reporting/icann/TransactionsReportingQueryBuilderTest.java
- core/src/test/resources/google/registry/reporting/icann/transaction_counts_test.sql
The SQL statement was incorrectly flooring to zero one layer too deep, which was negating all negative transaction report rows (which occur most frequently when a domain in the autorenew grace period is deleted). I've changed it so that it now only floors to zero at the report level, which still solves the issue reported in http://b/290228682 but whose original fix caused the issue http://b/344645788
This bug was introduced in https://github.com/google/nomulus/pull/2074
I tested this by running the new query against the DB for 2024 Q4 using the registrar that was having issues and confirmed that the total renewal numbers for .app now match with the sum total of what we invoiced for the last three months of 2024.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" …
> Fix handling of negative values in monthly transaction reporting

- core/src/main/java/google/registry/persistence/transaction/JpaTransactionManagerImpl.java
- core/src/test/java/google/registry/persistence/transaction/JpaTransactionManagerImplTest.java
- util/src/main/java/google/registry/util/Retrier.java
This can potentially help even more with serializable transaction failures (optimistic locking exceptions, which are expected to occur somewhat frequently).
With six attempts, we will sleep at most five times, for 100+200+400+800+1600 ms each, for a total of at most 3.1 seconds (much less than the EPP maximum which I believe (?) to be 30 seconds.
In addition, we add a 20% skew in an attempt to spread out possibly-conflicting transaction retries.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/2699)
> Bump the number of retries in transaction failures and add skew

- core/src/main/java/google/registry/export/ExportDomainListsAction.java
- core/src/main/java/google/registry/export/ExportReservedTermsAction.java
- core/src/test/java/google/registry/export/ExportDomainListsActionTest.java
- core/src/test/java/google/registry/export/ExportReservedTermsActionTest.java
We already do this for premium terms, but it's nice to do it for the other list types too
https://b.corp.google.com/issues/390053672
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/2725)
> Include TLD in reserved/registered list filenames too

- jetty/kubernetes/nomulus-backend.yaml
- jetty/kubernetes/nomulus-console.yaml
- jetty/kubernetes/nomulus-frontend.yaml
- jetty/kubernetes/nomulus-pubapi.yaml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/2723)
> Downgrade nodes type for pubapi and console, enable bursting for frontend and backend

- core/src/main/java/google/registry/flows/CookieSessionMetadata.java
- core/src/main/java/google/registry/flows/EppRequestHandler.java
- core/src/main/java/google/registry/flows/EppTlsAction.java
- core/src/main/java/google/registry/flows/HttpSessionMetadata.java
- core/src/main/java/google/registry/flows/SessionMetadata.java
- core/src/main/java/google/registry/flows/StatelessRequestSessionMetadata.java
- core/src/test/java/google/registry/flows/CookieSessionMetadataTest.java
- core/src/test/java/google/registry/flows/EppTlsActionTest.java
- jetty/deploy-nomulus-for-env.sh
- networking/src/test/java/google/registry/networking/handler/SslServerInitializerTest.java
The new `CookieSessionMetadata` makes the Nomulus EPP endpoint stateless. The session data is stored in the cookie, which has the same lifetime as the connection/session itself. This makes the session information global and therefore the release process seamless as no session needs to be re-established via proxy restart, as long as the proxy stays connected to the client, and no period during which stale session information exists on the proxy but not on the newly deployed backend itself exists. It also makes it possible to horizontally scale the frontend deployment like other stateless services.
Also removed a redundant JDK version check in tests as we require at least JDK 21 now. There are some JDK versions which are not all digits (e.g. `21.0.5-ea`) that cause the parsing to fail. …
> Save session data directly in a cookie

- core/src/main/java/google/registry/flows/CookieSessionMetadata.java
- core/src/main/java/google/registry/flows/SessionMetadata.java
- core/src/test/java/google/registry/flows/CookieSessionMetadataTest.java
It turns out period can be used in the URI, such as in
"urn:ietf:params:xml:ns:fee-0.12". I don't think pipe is used, at least
not according to EPP URI namespace naming convention.
Ideally we'd use serialization, but using the default serialization runs
the risk of it being platform/JDK dependent, so a new deployment might
not be able to deserialize existing cookies. A custom serializer that
guarantees stability would have been needed.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/2737)
> Use pipe as extension URI separator

- jetty/kubernetes/nomulus-frontend.yaml
Now that we have effective global sessions thanks to #2734, there is no
longer a need to keep the number of pods on the EPP service static.
We are also no longer vulnerable to random pod restarts. K8s never guarantees
perpetual pod lifetime anyway, and not having to be at its mercy is
certainly a relief.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/2736)
> Make frontend deployment auto scale

- core/src/main/java/google/registry/module/RequestComponent.java
- core/src/main/java/google/registry/module/pubapi/PubApiRequestComponent.java
- core/src/main/java/google/registry/rdap/RdapEmptyAction.java
- core/src/main/java/google/registry/rdap/RdapHelpAction.java
- core/src/test/java/google/registry/rdap/RdapEmptyActionTest.java
- core/src/test/resources/google/registry/module/pubapi/pubapi_routing.txt
- core/src/test/resources/google/registry/module/routing.txt
The behavior when someone hits the plain RDAP base URL isn't specified by the spec. Currently we just return a plain 404 which isn't particularly nice or helpful -- so it would probably be nicer to just redirect to the /help response instead.
tested on alpha,
https://pubapi-dot-domain-registry-alpha.appspot.com/rdap redirects to https://pubapi-dot-domain-registry-alpha.appspot.com/rdap/help
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/2722)
> Redirect an empty RDAP path to the /help response

- core/src/main/java/google/registry/config/files/default-config.yaml
Our connections hover around 20-30% all the time, so this max pool size limitation has been dragging us down. I will double it and monitor for active connections for a week.
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/2742)
> Increase hikari maximum pool size to 20

- core/src/main/java/google/registry/beam/billing/ExpandBillingRecurrencesPipeline.java
- core/src/main/java/google/registry/flows/domain/DomainCheckFlow.java
- core/src/main/java/google/registry/flows/domain/DomainCreateFlow.java
- core/src/main/java/google/registry/flows/domain/DomainFlowUtils.java
- core/src/main/java/google/registry/flows/domain/DomainPricingLogic.java
- core/src/main/java/google/registry/flows/domain/DomainRenewFlow.java
- core/src/main/java/google/registry/flows/domain/DomainTransferApproveFlow.java
- core/src/main/java/google/registry/flows/domain/DomainTransferRequestFlow.java
- core/src/main/java/google/registry/flows/domain/token/AllocationTokenFlowUtils.java
- core/src/test/java/google/registry/flows/domain/DomainCheckFlowTest.java
- core/src/test/java/google/registry/flows/domain/DomainCreateFlowTest.java
- core/src/test/java/google/registry/flows/domain/DomainPricingLogicTest.java
- core/src/test/java/google/registry/flows/domain/DomainRenewFlowTest.java
- core/src/test/java/google/registry/flows/domain/DomainTransferApproveFlowTest.java
- core/src/test/java/google/registry/flows/domain/DomainTransferRequestFlowTest.java
- core/src/test/java/google/registry/flows/domain/token/AllocationTokenFlowUtilsTest.java
- core/src/test/resources/google/registry/flows/domain/domain_check_allocationtoken_fee.xml
- core/src/test/resources/google/registry/flows/domain/domain_check_allocationtoken_fee_anchor_response.xml
- core/src/test/resources/google/registry/flows/domain/domain_check_allocationtoken_fee_response.xml
- core/src/test/resources/google/registry/flows/domain/domain_check_allocationtoken_fee_specificuse_response.xml
- core/src/test/resources/google/registry/flows/domain/domain_check_fee_multiple_commands_allocationtoken_response_v06.xml
- core/src/test/resources/google/registry/flows/domain/domain_check_fee_multiple_commands_allocationtoken_response_v12.xml
We're changing the way that allocation tokens work in suboptimal (i.e. incorrect) situations in the domain check, creation, and renewal process. Currently, if a token is not applicable, in any way, to any of the operations (including when a check has multiple operations requested) we return some variation of "Allocation token not valid" for all of those options. We wish to allow for a more lenient process, where if a token is "not applicable" instead of "invalid", we just pass through that part of the request as if the token were not there.
Types of errors that will remain catastrophic, where we'll basically return a token error immediately in all cases:
- nonexistent or null token
- token is assigned to a particular domain and the request isn't for that domain
- token is not valid for …
> Change AllocationToken behavior in non-catastrophic situations

- core/build.gradle
- core/src/main/java/google/registry/beam/common/RegistryPipelineWorkerInitializer.java
- core/src/test/java/google/registry/beam/common/RegistryPipelineWorkerInitializerTest.java
- util/src/main/java/google/registry/util/RegistryEnvironment.java
This is a tempoary change that should be reverted after GAE is removed.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/2753)
> Hardcode beam pipelines to use GKE for tasks

- console-webapp/src/app/app.component.spec.ts
- console-webapp/src/app/app.component.ts
- console-webapp/src/app/app.module.ts
- console-webapp/src/app/navigation/navigation.component.ts
- console-webapp/src/app/registrar/registrar.service.ts
- console-webapp/src/app/shared/components/pocReminder/pocReminder.component.html
- console-webapp/src/app/shared/components/pocReminder/pocReminder.component.scss
- console-webapp/src/app/shared/components/pocReminder/pocReminder.component.ts
- core/src/main/java/google/registry/ui/server/console/ConsoleUpdateRegistrarAction.java
- core/src/test/java/google/registry/ui/server/console/ConsoleUpdateRegistrarActionTest.java
- core/src/test/java/google/registry/webdriver/ConsoleScreenshotTest.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/2754)
> Add Console POC reminder front-end

- core/src/main/java/google/registry/flows/domain/DomainInfoFlow.java
- core/src/test/java/google/registry/flows/FlowModuleTest.java
- core/src/test/java/google/registry/flows/domain/DomainInfoFlowTest.java
- core/src/test/resources/google/registry/flows/domain_check.xml
This avoids potential replication lag issues when requesting info on domains that were just created.
Only about 9% of EPP requests were domain info requests so this shouldn't have a gigantic impact (roughly 84% are domain check requests, which will remain on the replica) 
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/2750)
> Use the primary DB for DomainInfoFlow

- core/src/main/java/google/registry/tools/CreateCdnsTld.java
- core/src/test/java/google/registry/tools/CreateCdnsTldTest.java
The Cloud DNS rest api is now case-sensitive about enum names (must be lower case, counterintuitively).
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/2760)
> Fix create_cdns_tld command

- core/src/test/java/google/registry/ui/server/console/ConsoleActionBaseTestCase.java
- core/src/test/java/google/registry/ui/server/console/ConsoleDomainGetActionTest.java
- core/src/test/java/google/registry/ui/server/console/ConsoleDomainListActionTest.java
- core/src/test/java/google/registry/ui/server/console/ConsoleDumDownloadActionTest.java
- core/src/test/java/google/registry/ui/server/console/ConsoleEppPasswordActionTest.java
- core/src/test/java/google/registry/ui/server/console/ConsoleOteActionTest.java
- core/src/test/java/google/registry/ui/server/console/ConsoleRegistryLockActionTest.java
- core/src/test/java/google/registry/ui/server/console/ConsoleRegistryLockVerifyActionTest.java
- core/src/test/java/google/registry/ui/server/console/ConsoleUpdateRegistrarActionTest.java
- core/src/test/java/google/registry/ui/server/console/ConsoleUserDataActionTest.java
- core/src/test/java/google/registry/ui/server/console/ConsoleUsersActionTest.java
- core/src/test/java/google/registry/ui/server/console/RegistrarsActionTest.java
- core/src/test/java/google/registry/ui/server/console/domains/ConsoleBulkDomainActionTest.java
- core/src/test/java/google/registry/ui/server/console/settings/ContactActionTest.java
- core/src/test/java/google/registry/ui/server/console/settings/RdapRegistrarFieldsActionTest.java
- core/src/test/java/google/registry/ui/server/console/settings/SecurityActionTest.java
We can probably improve on this in the future if we want, but there's a lot of boilerplate that we don't need to repeat over and over
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/2762)
> Add console action test base case

- core/src/main/java/google/registry/dns/writer/DnsWritersModule.java
- core/src/main/java/google/registry/module/RequestComponent.java
- core/src/main/java/google/registry/module/backend/BackendComponent.java
- core/src/main/java/google/registry/module/backend/BackendRequestComponent.java
- core/src/main/java/google/registry/tools/RegistryToolComponent.java
Add a new DnsWritersModule for use by the component classes.
To override the set of writers installed, we can easily overwrite this file with a private version.
Tested in crash both the server and the tool.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/2769)
> Add an aggregate module for DNS writers

- core/src/main/java/google/registry/tools/UniformRapidSuspensionCommand.java
It was making the undo nomulus command look like this:
)nomulus ...
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/2767)
> Remove spurious parenthesis in URS command output

- release/cloudbuild-nomulus.yaml
- release/cloudbuild-release.yaml
Scripts needed by cron jobs wrongly removed by PR 2661.
TESTED: in crash.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/2776)
> Fix prober cert renewal scripts

- core/src/main/java/google/registry/rdap/RdapJsonFormatter.java
- core/src/test/java/google/registry/rdap/RdapJsonFormatterTest.java
In RDAP, domain queries are the most common by a factor of like 40,000 so we should optimize these as much as possible. We already have an EPP resource / foreign key cache which does improve performance somewhat but looking at some sample logs, it only cuts the RDAP request times by like 40% (looking at requests for the same domain a few seconds apart).
History entries don't change often, so we should cache them to make subsequent queries faster as well. In addition, we're only caching two fields per repo ID (modification time, registrar ID) so we can cache more entries than we can for the EPP resource cache (which stores large objects).
- - - …
> Cache history values for RDAP domain requests

- proxy/src/main/java/google/registry/proxy/ProxyConfig.java
- proxy/src/main/java/google/registry/proxy/ProxyModule.java
- proxy/src/main/java/google/registry/proxy/config/default-config.yaml
- proxy/src/main/java/google/registry/proxy/metric/BackendMetrics.java
- proxy/src/main/java/google/registry/proxy/metric/FrontendMetrics.java
- proxy/src/test/java/google/registry/proxy/ProtocolModuleTest.java
- proxy/src/test/java/google/registry/proxy/metric/BackendMetricsTest.java
- proxy/src/test/java/google/registry/proxy/metric/FrontendMetricsTest.java
This ratio defaults to 1.0 (i.e. all metrics will be recorded), but we will set it much lower in sandbox and production, probably something closer to 0.01. This will reduce recorded metrics volume and thus StackDriver cost, while still retaining enough data for overall performance monitoring.
This is handled stochastically, so as to not require any coordination between Java threads or GKE pods/clusters, as alternative approaches would (i.e. using a counter and recording every Nth, or throttling to a max metrics qps).
BUG = http://b/364907042
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/2772)
> Add the ability to configure a ratio of proxy metrics to be recorded

- proxy/src/main/java/google/registry/proxy/metric/BackendMetrics.java
- proxy/src/test/java/google/registry/proxy/metric/BackendMetricsTest.java
This is necessary so that the total number of requests/responses adds up correctly even though some fraction of them are only being recorded. It uses stochastic rounding so that the totals add up correctly even when the reciprocal of the ratio isn't an integer.
This is a follow-up to PR #2772.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/2780)
> Increment proxy metrics by reciprocal of proxy metrics ratio

- core/src/main/java/google/registry/export/ExportDomainListsAction.java
- core/src/main/java/google/registry/flows/contact/ContactCreateFlow.java
- core/src/main/java/google/registry/flows/contact/ContactUpdateFlow.java
- core/src/main/java/google/registry/flows/domain/DomainCreateFlow.java
- core/src/main/java/google/registry/flows/domain/DomainFlowUtils.java
- core/src/main/java/google/registry/flows/domain/DomainUpdateFlow.java
- core/src/main/java/google/registry/flows/exceptions/ContactsProhibitedException.java
- core/src/main/java/google/registry/model/common/FeatureFlag.java
- core/src/main/java/google/registry/tools/CreateDomainCommand.java
- core/src/test/java/google/registry/flows/contact/ContactCreateFlowTest.java
- core/src/test/java/google/registry/flows/contact/ContactUpdateFlowTest.java
- core/src/test/java/google/registry/flows/domain/DomainCreateFlowTest.java
- core/src/test/java/google/registry/flows/domain/DomainUpdateFlowTest.java
- core/src/test/java/google/registry/model/common/FeatureFlagTest.java
- core/src/test/java/google/registry/tools/CreateDomainCommandTest.java
- core/src/test/resources/google/registry/flows/domain/domain_create_no_contacts.xml
- core/src/test/resources/google/registry/flows/domain/domain_create_response_eap_fee.xml
- core/src/test/resources/google/registry/flows/domain/domain_create_response_premium_eap.xml
- core/src/test/resources/google/registry/flows/domain/domain_update_remove_all_contacts.xml
This prohibits all contact data on create and update EPP flows for both domain and contact flows. It also refactors how default values on FeatureFlags work, as it's safer to specify a single default on the flag itself rather than have to specify it independently at a number of callsites (and potentially end up having an inconsistent value).
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/2781)
> Implement the contacts prohibited feature flag for minimum data set

- core/src/main/java/google/registry/model/console/ConsolePermission.java
- core/src/main/java/google/registry/model/console/ConsoleRoleDefinitions.java
- core/src/main/java/google/registry/model/console/ConsoleUpdateHistory.java
- core/src/main/java/google/registry/module/RequestComponent.java
- core/src/main/java/google/registry/ui/server/console/ConsoleDumDownloadAction.java
- core/src/main/java/google/registry/ui/server/console/ConsoleHistoryDataAction.java
- core/src/main/java/google/registry/ui/server/console/ConsoleRegistryLockVerifyAction.java
- core/src/main/java/google/registry/ui/server/console/ConsoleUsersAction.java
- core/src/main/java/google/registry/ui/server/console/settings/ContactAction.java
- core/src/main/java/google/registry/ui/server/console/settings/RdapRegistrarFieldsAction.java
- core/src/main/java/google/registry/ui/server/console/settings/SecurityAction.java
- core/src/test/java/google/registry/module/RequestComponentTest.java
- core/src/test/java/google/registry/ui/server/console/ConsoleHistoryDataActionTest.java
- core/src/test/java/google/registry/ui/server/console/ConsoleRegistryLockVerifyActionTest.java
- core/src/test/java/google/registry/ui/server/console/settings/RdapRegistrarFieldsActionTest.java
- core/src/test/java/google/registry/ui/server/console/settings/SecurityActionTest.java
- core/src/test/resources/google/registry/module/routing.txt
- db/src/main/resources/sql/schema/db-schema.sql.generated
Frontend is coming in a separate PR. Tested this on Alpha.
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/2782)
> Add console history api

- console-webapp/src/app/shared/services/backend.service.ts
- console-webapp/src/app/users/userDetails.component.html
- console-webapp/src/app/users/userDetails.component.scss
- console-webapp/src/app/users/userEditForm.component.html
- console-webapp/src/app/users/userEditForm.component.scss
- console-webapp/src/app/users/userEditForm.component.ts
- console-webapp/src/app/users/users.service.ts
- core/src/main/java/google/registry/model/console/User.java
- core/src/main/java/google/registry/model/domain/fee12/FeeCheckResponseExtensionItemCommandV12.java
- core/src/main/java/google/registry/model/registrar/Registrar.java
- core/src/main/java/google/registry/model/registrar/RegistrarPoc.java
- core/src/main/java/google/registry/ui/server/console/ConsoleUsersAction.java
- core/src/test/java/google/registry/ui/server/console/ConsoleUsersActionTest.java
This is only enabled for admins, for now at least. It sends an email to the registry lock email address to reset it.
tested on alpha, got the "would have sent email" log line
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/2785)
> Add Registry Lock password reset on front end

- proxy/src/main/java/google/registry/proxy/handler/EppServiceHandler.java
- proxy/src/main/java/google/registry/proxy/handler/HttpsRelayServiceHandler.java
- proxy/src/test/java/google/registry/proxy/handler/EppServiceHandlerTest.java
- util/src/main/java/google/registry/util/ProxyHttpHeaders.java
Tested in crash, works as expected
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/2791)
> Add registrar id header to proxy requests

- core/src/main/java/google/registry/ui/server/console/settings/SecurityAction.java
- core/src/test/java/google/registry/ui/server/console/settings/SecurityActionTest.java
This PR fixes a bug where a generic error was shown for invalid SSL certificates.
1.  Updated `SecurityAction.java` to return the specific error message from the exception.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/2792)
> Provide specific reason for invalid SSL certificate

- core/src/main/java/google/registry/request/RequestModule.java
Load balancer / internal redirections can result in the final request URL lacking "https" when finally getting to the servlet. As a result, even if you use https in the request, the resulting URL can be plain http.
We need to include the actual (HTTPS) URL in the output, so replace it.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/2807)
> Use https in RDAP URLs provided

- release/schema-verifier/allowed_diffs.txt
This is the same problem as the one that broke the Java test:
pg_dump upgrade to 17.6 added new meta command lines.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/2812)
> Fix the schema-verifier in Cloud Build

- core/build.gradle
- core/src/main/java/google/registry/bsa/UploadBsaUnavailableDomainsAction.java
- core/src/test/java/google/registry/bsa/UploadBsaUnavailableDomainsActionTest.java
- core/src/test/java/google/registry/server/TestServer.java
The action was using string concatenation to generate the upload content.
This causes an OOM when string length exceeds 25MB on our current VM.  This means that the VM is having trouble finding up to 50MB of contiguous memory.
This PR witches to streaming upload.
Also added an HTTP upload test.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/2817)
> Fix OOM in UploadBsaUnavailableDomains action

- core/src/main/java/google/registry/tools/CreateCdnsTld.java
- core/src/test/java/google/registry/tools/CreateCdnsTldTest.java
Add a flag to the CreateCdnsTld command to bypass the dns name format check in Sandbox (limiting names to `*.test.`). With this flag, we can create TLDs for RST testing in Sandbox.
Note that if the new flag is wrongly set for a disallowed name, the request to the Cloud DNS API will fail. The format check in the command just provides a user-friendly error message.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/nomulus/2835)
> Allow top level tld creation in Sandbox
